export default {
    "IMF": [
        "What does the abbreviation IMF stand for?",
        "What do you know about the history of the IMF?",
        "What is the difference between the IMF and the World Bank?",
        "Why do many countries protest against the IMF?",
        "What are the aims of the 185-member IMF?",
        "Do you think the IMF should put more pressure on countries that do not have democracy?",
        "Would you like to see the IMF one day become the world’s treasury?",
        "Do you think there is equality among the member states of the IMF?",
        "Would you like to work for the IMF?",
        "What should an international monetary fund do?",
        "What does the IMF do?",
        "Do you think the IMF should get involved with global warming?",
        "What did colonial rule do for Africa?",
        "Who runs the IMF and who should run it?",
        "Where does the IMF get its money from?",
        "What do you think should be the IMF’s obligation to the poor?",
        "Do you think the IMF should be headquartered in Washington DC?",
        "What would you expect to find on the IMF website?",
        "What do you think the IMF will be doing 50 years from now?",
        "What questions would you like to ask the boss of the IMF?"
    ],
    "Identity Cards": [
        "Are identity cards compulsory in your country?",
        "What are the advantages of identity cards?",
        "What kind of information should and shouldn’t be on ID cards?",
        "Do you think ID cards are easy for counterfeiters to make?",
        "Do you think ID cards can solve social problems?",
        "What is your ‘identity’?",
        "Do you worry about identity theft?",
        "What would you do if you lost all your ID cards?",
        "Do you think it would be easy for a hacker to hack into a database containing your personal information?",
        "Do you think fingerprints or retina scans are better than ID cards?",
        "What do you think of the idea of having to carry an ID card?",
        "Where and when do you need to show ID?",
        "How many ID cards do you have?",
        "Do you think governments want too much control with ID cards?",
        "Would you like to see an ID card that is also a passport and credit/debit card?",
        "What are the dangers of ID cards?",
        "What do you think about the idea of a world identity card?",
        "From what age do you think people should carry ID cards?",
        "Would you like to be able to do the design for your ID card?",
        "Why are many people around the world against the idea of ID cards?"
    ],
    "Identity Theft": [
        "What springs to mind when you hear the term ‘identity theft’?",
        "How can someone steal your identity?",
        "Are you sure all of your personal information is secure?",
        "Whose identity would you like to steal for a day and what would you do in those 24 hours?",
        "How can you prevent identity theft?",
        "Is identity theft a minor or major crime?",
        "What danger would your country be in if someone stole your president’s/prime minister’s identity?",
        "Would you consider taking out identity theft insurance?",
        "What would you want to happen to someone who stole your identity?",
        "Have you ever been a victim of identity theft?",
        "What can happen to you if someone steals your identity?",
        "What is actually stolen with identity theft?",
        "How can identity theft be stopped to reduce the chances of illegal immigration?",
        "Do you think someone can steal another person’s identity and live their life?",
        "Do you think someone could steal your identity over the Internet?",
        "Are you always careful about what documents you throw away?",
        "How dangerous do you think it is to put personal information on social networking sites like FaceBook, MySpace and Bebo?",
        "Is identity theft a serious problem in your country?",
        "Have you seen any movies or read any novels about identity theft?",
        "What would happen if everyone’s identity was stolen?"
    ],
    "Immigration": [
        "What comes to mind when you hear the word ‘immigration’?",
        "Is immigration good or bad?",
        "Is immigration an issue in your country?",
        "Do you think immigration has been successful in the USA?",
        "What do you think of the European Union’s idea of its Blue Card (similar to the USA’s Green Card)?",
        "Would you like a blue card or a green card?",
        "When do you think immigration became a social issue?",
        "Would you like to live and work in another country?",
        "Do you think immigrants get a raw deal in the countries they live in?",
        "Is illegal immigration a problem where you live?",
        "Do you have a positive or negative image of immigration?",
        "What rules on immigration would you like your country to have?",
        "What would happen to the world’s population if all immigration laws ended?",
        "Would you report an illegal immigrant to the police?",
        "What are the benefits of immigration?",
        "Do you think immigration helps us all understand each other better?",
        "What world country do you think is most opposed to immigration?",
        "Do you think immigrants should pass a test based on the language and culture of the country they want to live in?",
        "Has immigration around the world been successful?",
        "Does immigration mean creating cosmopolitan societies?"
    ],
    "Immunizations": [
        "What springs to mind when you hear the word ‘immunization’?",
        "Why are immunizations important?",
        "Does your country have a good immunization programme?",
        "Do you have a good immune system?",
        "Do you think it’s possible to immunize all of the world’s children?",
        "What’s the difference between immunization, vaccination and inoculation?",
        "What are the required immunizations when you start school?",
        "Do immunizations and vaccines work?",
        "Do you think there’s a risk of catching the illness from the vaccine?",
        "Would you prefer oral or injection immunization?",
        "Do you think we can get immunized against all diseases one day?",
        "What is the benefit to the world of immunization?",
        "What do you think of the argument than immunization contributes to overpopulation and should be banned?",
        "Do you think there’s still a need for immunization in rich countries?",
        "Do you think immunizations are 100% safe?",
        "Do immunizations stop at childhood?",
        "Do you think new diseases will appear that need immunization?",
        "Would you like to be immunized against old age?",
        "Would you want your government to immunize thousands of children against a killer disease or produce one missile?",
        "How would your country be affected if there was no immunization?"
    ],
    "India": [
        "What images spring to mind when you hear the country India?",
        "What are the good things and bad things about India?",
        "What is India famous for?",
        "What do you know about Indian history?",
        "What images of India do you have that are beautiful and romantic?",
        "What do you think of Indian products and companies?",
        "What has India given to the world?",
        "Would you like to visit India, or live there?",
        "Are Indian languages important languages?",
        "Who are the most famous Indian people you know?",
        "How different is India from other world countries?",
        "Do you think India is one of the world’s most important nations?",
        "Why is India one of the top tourist destinations in the world?",
        "What do you think India will be like 50 years from now?",
        "Does your country have good relations with India?",
        "What do you think about Indian food?",
        "What is your idea of a typical Indian person?",
        "What things about India do you think Indian people are proud of?",
        "What do you know about Indian politics?",
        "What would you like to ask an Indian person about India?"
    ],
    "Indonesia": [
        "What images spring to mind when you hear the country Indonesia?",
        "What are the good things and bad things about Indonesia?",
        "What is Indonesia famous for?",
        "What do you know about Indonesian history?",
        "What do you think Indonesia will be like 50 years from now?",
        "What do you think of Indonesian goods and products?",
        "What has Indonesia given to the world?",
        "Would you like to visit Indonesia, or live there?",
        "Is Bahasa Indonesia an important language?",
        "Who are the most famous Indonesian people you know?",
        "How different is Indonesia from other Asian countries?",
        "Do you think Indonesia is one of the world’s most important nations?",
        "Why is Indonesia one of the top tourist destinations in the world?",
        "What do you know about Indonesia’s record on the environment?",
        "Does your country have good relations with Indonesia?",
        "What do you think about Indonesian food?",
        "What is your idea of a typical Indonesian person?",
        "What things about Indonesia do you think Indonesian people are proud of?",
        "What do you know about Indonesian politics?",
        "What would you like to ask an Indonesian person about Indonesia?"
    ],
    "Inflation": [
        "What springs to mind when you hear the word ‘inflation’?",
        "What is inflation and what causes it?",
        "What is the rate of inflation in your country?",
        "Has your country ever experiences high, hyper or spiraling inflation?",
        "Why is inflation important to economists?",
        "What does inflation mean to you on a daily basis?",
        "What do governments do to control or curb inflation?",
        "What creates runaway inflation like that in Zimbabwe?",
        "How does high inflation affect the economy and the people in it?",
        "What can you do to protect yourself against inflation?",
        "Do you follow the news on different rates of inflation around the world?",
        "How do economies survive even with rates of inflation in the thousands of percent?",
        "Who does inflation hit the hardest?",
        "What is deflation and does this harm the economy?",
        "Does inflation in other countries affect your country’s economy?",
        "Is there an important link between inflation and unemployment?",
        "What is the difference between inflation and real inflation?",
        "What are inflationary pressures?",
        "What are the differences between wage and cost inflation?",
        "What is the “market basket” used in calculating the CPI (Consumer Price Index) to get the figure for inflation?"
    ],
    "Information": [
        "What springs to mind when you hear the word ‘information’?",
        "Are you happy with the amount of information in your head?",
        "How much useless information do you think you’ve learned?",
        "Do you have more information than your grandparents?",
        "Is it important to know a lot of information in today’s world?",
        "What do you think ‘information economics’ is?",
        "What topics would you like to know more information about?",
        "What is the information superhighway and why is it important?",
        "Are you happy to be living in the ‘Information Age’?",
        "How do you gather information?",
        "What’s the difference between information and knowledge?",
        "What information technology do you think is most important?",
        "What kind of information is dangerous in the wrong hands?",
        "Is there freedom of information in your country?",
        "Do you often go to tourist information offices?",
        "What important information are you carrying on you now?",
        "What has the Internet done for information?",
        "What is information overload?",
        "What personal information about you should be confidential information?",
        "What’s the latest information?"
    ],
    "Insects": [
        "What comes to mind when you hear the word ‘insect’?",
        "Do you like insects?",
        "What insects are the most interesting?",
        "What insects are there in your country?",
        "What insect would you most like to be and why?",
        "What’s your scariest insect moment?",
        "How often do you kill insects or use insect spray?",
        "What do you think of people who collect insects or have them as pets?",
        "How would the world change if all insects suddenly became 100 times bigger?",
        "Have your feelings towards insects changed since you were a child?",
        "Do you know a lot about insects?",
        "Why are so many people afraid of insects?",
        "What insects do you get in your house?",
        "What do you do if you get an insect bite?",
        "Would you be able to sleep if there were insects in your bedroom?",
        "Is it wrong to kill insects?",
        "Are there any insects you would not like to touch or pick up?",
        "What do you think insects think about?",
        "What can we learn from insects?",
        "Have you ever seen a scary movie about insects?"
    ],
    "Intelligence": [
        "What is intelligence?",
        "What would you say about your intelligence?",
        "What can you do to increase your intelligence?",
        "Why are some people more intelligent than others?",
        "Does intelligence run in the family?",
        "Does school make a person more intelligent?",
        "Do you think scientists will create Artificial Intelligence that is greater than our intelligence?",
        "Is there a link between intelligence, creativeness and humour?",
        "Does intelligence make people more attractive?",
        "Does speaking English well make you more intelligent than a friend who cannot speak English at all?",
        "Do you worry about your levels of intelligent?",
        "Who is the most intelligent person you know? Why do you think so?",
        "Do you think all world leaders are intelligent?",
        "Are we all born with the same level of intelligence?",
        "Does being very intelligent make you happy?",
        "What insults your intelligence?",
        "What do you think of intelligence tests? Do you think they are accurate",
        "Are intelligent people usually more arrogant?",
        "Do very intelligent and unintelligent people make good partners?",
        "Are dolphins really more intelligent than humans?"
    ],
    "Internet": [
        "What is the Internet?",
        "What would the world be like without the Internet?",
        "Could you live without the Internet?",
        "Is the Internet dangerous?",
        "What kind of technology will replace the Internet?",
        "What annoys you about the Internet?",
        "Are you addicted to the Internet?",
        "What do you think of social networking sites like Facebook, MySpace and Bebo?",
        "Can you remember the first time you used the Internet?",
        "Do you think fingerprints or retina scans are better than ID cards?",
        "How does the Internet work?",
        "How would your life be different without the Internet?",
        "What do you use the Internet for?",
        "How has the Internet changed the world?",
        "What’s the best thing about the Internet?",
        "Could the Internet have a better name?",
        "What does the Internet need more of?",
        "What is your favourite Internet site?",
        "What do you think of the idea of Internet shopping or online dating?",
        "Do you think people will prefer to live their lives on the Internet instead of real life?"
    ],
    "Inventions": [
        "What is the greatest invention ever?",
        "What invention would you like to invent?",
        "What is Mother Nature’s greatest invention?",
        "What does ‘necessity is the mother of invention’ mean? Do you agree with it?",
        "What is the world’s most useless invention?",
        "How was the world different before the wheel was invented?",
        "Do you think the person who invented the atomic bomb was happy with his discovery?",
        "Do new inventions always create new problems?",
        "How do people invent things?",
        "What question would you like to ask an inventor?",
        "What is the greatest invention of the year?",
        "What do you think an inventor’s life is like?",
        "What is the world’s most dangerous invention?",
        "What is the coolest invention ever?",
        "Have you ever thought about inventing anything?",
        "Which invention is better, the Internet or electricity?",
        "What invention is needed to save the world from global warming?",
        "What invention do you think an ant might like?",
        "Do you think new inventions always make people rich?",
        "Who is the world’s greatest ever inventor?"
    ],
    "Investments": [
        "What springs to mind when you hear the word ‘investment’?",
        "How important is it to invest?",
        "Do you think you’ll have a lot of investments when you’re older?",
        "What kind of things can you invest in?",
        "Do you like reading about investments?",
        "Would you like to put money into an investment bank?",
        "Is your country a good place to invest?",
        "What things do you think are risky investments?",
        "If you had just one dollar, what would you invest it in and why?",
        "How is it possible to invest in people? Is this a good idea?",
        "What investment opportunities that you missed do you wish you’d taken advantage of?",
        "What investment advice have you heard recently?",
        "Do you think you are/would be a cautious or risky investor?",
        "What risks are there investing in the stock market?",
        "What rates or return would you want/expect on money you invest?",
        "Is there a history in your family of people making investments?",
        "How far do you trust people with your money?",
        "When should people start investing their money?",
        "How confident are you / would you be with investing your money?",
        "What question would you like to ask an investment expert?"
    ],
    "Iran": [
        "What images spring to mind when you hear the country Iran?",
        "What are the good things and bad things about Iran?",
        "What is Iran famous for?",
        "What do you know about Iranian history?",
        "Do you think Iran should be allowed to have nuclear weapons?",
        "What do you think Iran is right to stand up to the USA?",
        "What kind of country do you think Iran will be in fifty years?",
        "Would you like to visit Iran, or live there?",
        "What was the last story you heard or read about Iran?",
        "Who are the most famous Iranian people you know?",
        "How different is Iran from other world countries?",
        "Do you think Iran is one of the world’s most important nations?",
        "What do you think Iran’s neighbours think of the country?",
        "What do you think of Iran’s president?",
        "Does your country have good relations with Iran?",
        "What role should Iran play in the world today as the birthplace of civilization?",
        "What is your idea of a typical Iranian person?",
        "What things about Iran do you think Iranian people are proud of?",
        "What do you know about Iranian politics?",
        "What would you like to ask an Iranian person about Iran?"
    ],
    "Iraq": [
        "What images spring to mind when you hear the country Iraq?",
        "What are the good things and bad things about Iraq?",
        "What is Iraq famous for?",
        "What do you know about Iraqi history?",
        "What are your thoughts on the recent history of Iraq?",
        "What do you think Iraqi people think of the world?",
        "What has Iraq given to the world?",
        "Would you like to visit Iraq?",
        "What was the last story you heard or read about Iraq?",
        "Who are the most famous Iraqi people you know?",
        "How different is Iraq from other world countries?",
        "Where do you think Iraq fits in the list of the world’s most important countries?",
        "What would the world be like today if the US had never invaded Iraq?",
        "What do you think Iraq will be like 50 years from now?",
        "Does your country have good relations with Iraq?",
        "What do you think is the most tragic thing about Iraq?",
        "What is your idea of a typical Iraqi person?",
        "What things about Iraq do you think Iraqi people are proud of?",
        "What do you know about Iraqi politics?",
        "What would you like to ask an Iraqi person about Iraq?"
    ],
    "Ireland": [
        "What images spring to mind when you hear the country Ireland?",
        "What are the good things and bad things about Ireland?",
        "What is Ireland famous for?",
        "What do you know about Irish history?",
        "What images of Ireland do you have that are beautiful and mysterious?",
        "What do you think about Ireland?",
        "What has Ireland given to the world?",
        "Would you like to visit Ireland, or live there?",
        "What do you know about the economy of Ireland?",
        "Who are the most famous Irish people you know?",
        "How different is Ireland from other European countries?",
        "What do you know about Ireland’s culture?",
        "Do you think Ireland is a good tourist destination?",
        "What do you think Ireland will be like 50 years from now?",
        "Does your country have good relations with Ireland?",
        "What does your country have in common with Ireland?",
        "What is your idea of a typical Irish person?",
        "What things about Ireland do you think Irish people are proud of?",
        "What do you know about Ireland’s geography?",
        "What would you like to ask an Irish person about Ireland?"
    ],
    "Islam": [
        "What springs to mind when you hear the word ‘Islam’?",
        "What is the difference between Islam and other world religions?",
        "Why do you think Islam is the fastest growing religion in the world?",
        "What are the Five Pillars of Islam?",
        "Why do the two main branches of Islam, Sunni and Shi’a, often fight each other?",
        "What things must and mustn’t you do when you enter a mosque?",
        "Would you like to make the pilgrimage to Mecca?",
        "What do you know about and think of the Islamic system of Sharia law?",
        "What do you know about Islamic holidays such as Ramadan and the Eid celebrations?",
        "What questions about Islam would you really like answered?",
        "What is Islam?",
        "What is Jihad and why do people misinterpret it?",
        "How has Islam changed the world throughout history?",
        "What do you know about Islamic art?",
        "How are Muslim countries different to non-Muslim countries?",
        "What is Islamic Fundamentalism?",
        "Does Islam have different rules for men and women?",
        "Do you think Muslims are treated equally by the major world powers?",
        "What do you think of Islamic dress?",
        "What was the last news story you read or heard about Islam?"
    ],
    "Israel": [
        "What images spring to mind when you hear the country ‘Israel’?",
        "What are the good things and bad things about Israel?",
        "What is Israel most famous for?",
        "What do you know about Israel’s history?",
        "What are the differences between Israel and your country?",
        "What do you think about Israeli people?",
        "What has Israel given to the world?",
        "Would you like to visit Israel, or live there?",
        "What do you know about the geography of Israel?",
        "Who are the most famous Israeli people you know?",
        "How different is Israel different from other Middle Eastern countries?",
        "What was the last news story you heard about Israel?",
        "What do you think Israel’s neighbours think of it?",
        "What do you think Israel will be like 50 years from now?",
        "Does your country have good relations with Israel?",
        "What could you do on a holiday in Israel?",
        "What is your idea of a typical Israeli person?",
        "What things about Israel do you think Israelis are proud of?",
        "What do you know about Israeli culture?",
        "What would you like to ask an Israeli about Israel?"
    ],
    "Italy": [
        "What images spring to mind when you hear the country Italy?",
        "What are the good things and bad things about Italy?",
        "What is Italy famous for?",
        "What do you know about Italian history?",
        "What images of Italy do you have that are beautiful and romantic?",
        "What do you think of Italian products and companies?",
        "What has Italy given to the world?",
        "Would you like to visit Italy, or live there?",
        "Is Italian an important language?",
        "Who are the most famous Italian people you know?",
        "How different is Italy from other world countries?",
        "Do you think Italy is one of the world’s most important nations?",
        "Why is Italy one of the top tourist destinations in the world?",
        "What do you think Italy will be like 50 years from now?",
        "Does your country have good relations with Italy?",
        "What do you think about Italian food?",
        "What is your idea of a typical Italian person?",
        "What things about Italy do you think Italian people are proud of?",
        "What countries are better than Italy at football?",
        "What would you like to ask an Italian person about Italy?"
    ]
}
