export default {
    "Animals (idioms)": [
        "Does your teacher ever have to badger you to get your homework?",
        "Who is the black sheep of your family and what is it about them that is so bad?",
        "Did you ever cry wolf when you were young, and then no one believed  your stories?",
        "Who really annoys you and gets your goat? Why do they get your goat?",
        "What do you think of road hogs? How can the police stop their bad manners and dangerous driving?",
        "Have you ever been a guinea pig and let someone test something on you?",
        "Do you always take the bull by the horns and make strong decisions?",
        "Has your government ever wasted money on a white elephant – a project that was a really, really bad idea that no one used?",
        "Did you have a piggy bank as a child? Did you smash it?",
        "Has anyone made a monkey out of you and made you look foolish?",
        "When was the last time you had a whale of a time? What was so great about it",
        "What was the last thing you did in two shakes of a lamb’s tail?",
        "Do you believe that a leopard cannot change its spots? Are you flexible?",
        "Have you ever seen a sporting competition with a strong and weak team – like lambs to the slaughter?",
        "Do you usually manage to get or end up with the lion’s share of something? Is this good or bad?",
        "Are you a lone wolf or do you like being with other people?",
        "Do you agree that the 9-to-5 lifestyle is a rat race?",
        "When was the last time you were so hungry you wolfed your food down in a few seconds?",
        "Are you good at smelling a rat and noticing suspicious things?",
        "Do you always go the whole hog and do, buy, eat… everything possible?"
    ],
    "Back (idioms)": [
        "When was the last time a friend did something behind your back?",
        "Are you careful to cover your back to avoid getting in trouble?",
        "Have you ever broken your back trying to do something very difficult?",
        "Do your parents ever get on your back, asking when you’re going to get married / get a job / move out, etc?",
        "Is there anyone you hate so much you wouldn’t give them the shirt off your back?",
        "When your back is up against the wall, can you be cool and not panic?",
        "What annoying people’s habits really get your back up?",
        "Do you ever scratch someone’s back and then they return the favour ?",
        "Has a friend ever stabbed you in the back, even after you helped them?",
        "Has a friend ever turned his/her back on you when you needed help?",
        "When was the last time you really put your back into doing something?",
        "When was the last time someone gave you a slap on the back for your good work?",
        "Who would you be really glad to see the back of forever?",
        "If people call you bad names, is it like water off a duck’s back?",
        "What do you find so easy that you could do it with one arm tied behind your back?",
        "Do you do bad things the minute your boss’ / teacher’s / parent’s back is turned?",
        "Do you ever have to watch your back to make sure nothing bad happens to you?",
        "Have you ever turned your back on someone / something and simply walked away?",
        "To get you angry, what is the straw that breaks the camel’s back?",
        "Are there any good back idioms in your language?"
    ],
    "Birds (idioms)": [
        "What things do you learn like a duck takes to water?",
        "Do you know anyone who is a bird brain – they never understand anything?",
        "Do you think children should learn about the birds and the bees in sex education classes at high school?",
        "Which came first, the chicken or the egg?",
        "Are you an early bird who always gets up early and arrives early?",
        "At what age do children usually fly the nest and live on their own in your country?",
        "What can people say or do to you that would annoy you and ruffle your feathers?",
        "Have you ever been on a wild goose chase? Perhaps spending hours trying to find something online?",
        "At what age are you no longer a spring chicken? Is this good or bad?",
        "Who rules the roost in your house?",
        "Have you ever chickened out of doing something because you were too afraid or nervous?",
        "Has anyone tried to clip your wings and stopped you from doing something you really wanted to do?",
        "What was the last cock-and-bull story you heard? How silly was it?",
        "Does your teacher have an eagle eye? Can (s)he always spot students when they do things they shouldn’t?",
        "If other people call you names, is it like water off a duck’s back to you?",
        "If someone tells you a secret. Do you ever say a little bird told you?",
        "Are you a night owl who likes to stay up late and study?",
        "Did you ever play chicken at school and do dangerous things your friends dared you to do?",
        "Have you ever been paid chicken feed for a part-time job?",
        "At what age did you feel freedom and start spreading your wings?"
    ],
    "Blood (idioms)": [
        "Is there any bad blood between members of your family?",
        "Do you think family is more important than friends and that blood is thicker than water?",
        "Have you ever been after someone’s blood because they did something bad to you and you were very angry with them?",
        "Do you think you would always look after your own flesh and blood (relatives), no matter what they do to you?",
        "What really scary situations or thoughts make your blood run cold?",
        "Have you ever put a lot of blood, sweat and tears into a big project?",
        "What everyday things or which people make your blood boil so much you get very angry?",
        "Would you like to marry into blue blood and perhaps become a royal?",
        "Have you ever drawn (first) blood in a fist fight?",
        "Are there any interesting blood idioms in your language?",
        "Have you ever burst a blood vessel putting a lot of effort into something?",
        "Is borrowing money from your friends like getting blood from a stone?",
        "Is it in your blood to do voluntary work?",
        "Do you think you could ever do anything really bad, in cold blood?",
        "If someone tells bad lies about you, are you out for their blood?",
        "When you know you can win a game, can you taste blood?",
        "What things disturb you while you are on an airplane?",
        "Do you ever get a sudden rush of blood to the head and do something silly that you regret later?",
        "Do you ever spit blood and speak in a way that shows your anger?",
        "Do you think your government has blood on its hands?"
    ],
    "Body (idioms)": [
        "“They’re always at each other’s throats.” Does this describe you and someone you know who you always fight and argue with?",
        "Have you ever experienced a body blow – a major setback in life?",
        "Does anyone you know always breath down your neck and make sure you do everything correctly and on time?",
        "Are you ever a bundle of nerves? What do you do to control your nervousness?",
        "Is there anyone who you just can’t stomach? Perhaps you have to leave the room if they come in because you hate them so much.",
        "Do you have so much responsibility that you feel you are carrying the weight of the world on your shoulders?",
        "Do you know anyone who is so stupid they are dead from the neck up?",
        "Have you ever said or done anything to shoot yourself in the foot?",
        "What do you do when there’s a frog in your throat?",
        "Do you have any interesting body idioms in your language?",
        "Do you get butterflies in your stomach when you speak in public?",
        "Who irritates and annoys you so much that they get on your nerves, and get under your skin – they are a real pain in the neck?",
        "Do you ever act on your gut feeling? Is it usually right?",
        "Have you ever had to accept a very unfair decision that was hard to stomach?",
        "Have you ever told anyone you hate their guts (in your language)?",
        "Do you know anyone who is so thin (s)he is all skin and bones?",
        "Does anyone ever try to force their views down your throat?",
        "When you need a shoulder to cry on, who do you go to?",
        "Have you ever risked your neck to help a friend?",
        "How do you feel after you’ve got a problem off your chest?"
    ],
    "Business (idioms)": [
        "Why do business people focus on the bottom line so much?",
        "Do you break even at the end of the month, or are you in the red, or even in the black?",
        "Do you like numbers and statistics? Are you a number cruncher?",
        "Does it take you a long time to figure out something? Can you do it in your head or do you need a calculator?",
        "What do you think of the credit squeeze? Are you borrowing less spending less on your credit card because of it?",
        "Have you ever written a cheque / check that bounced? Did it cause you any problems? Did you have to pay bank charges?",
        "Are you into stocks and shares? Have you ever bought a stake in a company?",
        "Have you ever taken a calculated risk? Did you need a calculator?",
        "Why do you think estimating a number uses the language of baseball? People say “C’mon. Gimee a ballpark figure",
        "Why do you think a CEO is sometimes referred to as the big cheese?",
        "Have you cut back on anything recently? Do you like these cutbacks?",
        "How often do you think companies cut corners? How is this?",
        "Have you ever helped draw up a contract?",
        "Do other people’s mobile phones ever make your temper become thin?",
        "What do you need to do to get a company off the ground?",
        "How do you stop a company from going belly up?",
        "Is it only water and drinks companies that have liquid assets?",
        "Have you ever got fed up with red tape?",
        "Why do things that sell quickly sell like hotcakes?",
        "What things can either nosedive or skyrocket?"
    ],
    "Cats (idioms)": [
        "When the cat’s away the mice will play. Who is the cat if you are a mouse? What do you do when the cat’s away?",
        "Do you agree there’s more than one way to skin a cat? When was the last time you found other ways of doing something?",
        "Do you ever put the cat among the pigeons and get someone into trouble?",
        "Why does it rain cats and dogs in England? What animals rain in your country?",
        "Are you a scaredy cat? Do you frighten easily?",
        "Have you ever stayed or lived somewhere where there was not enough room to swing a cat?",
        "Who did you always fight like cats and dogs with as a child?",
        "Do you like copycats? Do you like people copying your fashion?",
        "Has the cat ever got your tongue and you were too shy to speak?",
        "Have you ever told someone’s secret and let the cat out of the bag?",
        "Has anyone ever played cat and mouse with you and teased you?",
        "When you’re exhausted, do you look like something the cat dragged in?",
        "If you’ve just won something, do you look like the cat that swallowed the canary?",
        "Is it true that curiosity killed the cat? Do you have to know everything?",
        "Do you think fat cats should get such high salaries?",
        "Does a cat burglar really steal cats?",
        "How lively and excited is a cat on a hot tin roof? Is this you sometimes?",
        "Is it fair that a cat has nine lives? Would you like that many?",
        "Do you ever feel great and think you are the cat’s whiskers?",
        "Are there any interesting cat idioms in your language?"
    ],
    "Dogs (idioms)": [
        "Do you know anyone whose bark is worse than their bite?",
        "Do you think it’s a real dog-eat-dog world in the 21st Century?",
        "Are you hopeful that every dog has his day, and you’ll have yours one day or some time in the future?",
        "Have the government services in your country gone to the dogs, or are they still very good?",
        "Is the best hangover cure really the hair of the dog that bit you?",
        "Does someone look good if they’re done up like a dog’s dinner?",
        "When was the last time you were totally, totally dog tired?",
        "If you worked like a dog, would you work very hard or not hard at all?",
        "Have you ever thrown someone to the dogs ( a younger brother or sister perhaps) to protect yourself from harm or punishment?",
        "Are there any interesting dog idioms in your language?",
        "Do you family or friends ever put you in the doghouse if you do wrong?",
        "Do you think you’d be happy or sad for leading a dog’s life?",
        "If someone asks to be excused and leaves, telling you they have to see a man about a dog, do you think they’re going to buy a pet?",
        "Do people tell shaggy dog stories in your country (a kind of joke that goes on, and on, and on…)?",
        "If you have your tail between your leg, have you won or lost?",
        "Have you ever worked somewhere where the tail wags the dog?",
        "Who is the top dog in your class or circle of friends?",
        "Can you be too old to study and that it’s right that you can’t teach an old dog new tricks?",
        "To keep the peace, do you always let sleeping dogs lie?",
        "Do you ever bark up the wrong tree and accuse someone innocent of doing something wrong?"
    ],
    "Hand Idioms (1)": [
        "Is it difficult for you to do things with your hands? Are you all thumbs?",
        "When you’re at your desk, what things do you need at your fingertips?",
        "Have you ever burnt your fingers by investing money unwisely?",
        "Does the leader of your country rule with an iron fist? Who do you know who does?",
        "What expensive items have you bought that cost an arm and a leg?",
        "Have you ever dirtied your hands by damaging someone’s reputation?",
        "Are you good at getting people to do what you want and have them eating out of your hand?",
        "Do you mind having second hand things or second hand news?",
        "Have you been in a situation that got out of hand and you could no longer control it?",
        "Would you give your government the thumbs up or the thumbs down?",
        "Have you ever suffered at the hands of nature or at the hands of someone you dislike?",
        "Have you ever been caught red-handed doing something bad?",
        "Have you ever been caught with your hand in the cookie jar – stealing something?",
        "When you go shopping, do you ever come home empty handed?",
        "What personal information would you not want to fall into the wrong hands?",
        "Is it better to learn things from first hand experience?",
        "What in this world do you want so much that you would give your right arm for it?",
        "Is it usual in your country to grease someone’s palm (with money) if you want something done quickly?",
        "Do you have green fingers (a green thumb in the USA) and all your plants and flowers grow very well?",
        "Do you and English go hand in glove? Is English part of you now?"
    ],
    "Hand Idioms (2)": [
        "When was the last time your hands were tied and you couldn’t help a friend?",
        "Are you a safe pair of hands? Can people relax when they leave plans and arrangements in your hands?",
        "When was the last time you needed help and asked a friend to lend you a hand?",
        "Who do you know that is so lazy (s)he never lifts a finger?",
        "Have you ever been so poor you’ve had to live from hand to mouth?",
        "Have you ever been visited by the long arm of the law?",
        "Which of your things would you like to get rid of, to get off your hands?",
        "Do you know an old hand who is very experienced and good at doing something?",
        "Have you ever been somewhere where communication is so bad that the left hand doesn’t know what the right hand is doing?",
        "Would you like to rub shoulders with rich, famous and powerful people?",
        "Have you ever been in a very difficult situation and just managed to hang on by your fingernails?",
        "Do you have a busy life? Do you have your finger in many pies?",
        "What do you have your hands full with at the moment?",
        "Does the heavy hand of the law in your country worry you?",
        "In your culture, do you keep your fingers crossed for good luck?",
        "Which towns do you know like the back of your hand?",
        "Do you think it’s OK for parents to lay a finger on their children and beat them when they do bad things?",
        "Is your teacher always on hand to help you with your work?",
        "Are you quick to point the finger and put the blame on others?",
        "As a rule of thumb, how long should we study English every day?"
    ],
    "Horse (idioms)": [
        "When was the last time you were so hungry that you ate like a horse?",
        "Have you been so hungry you thought you could eat a horse?",
        "Do you ever do things in the wrong order and put the cart before the horse?",
        "Have you ever looked a gift horse in the mouth – you complained because your present was not perfect?",
        "Has anyone told you to hold your horses, and be patient and wait?",
        "Have you ever flogged (beat) a dead horse – the battle was lost but you still kept on trying (perhaps asking your father to borrow his new car)?",
        "Have you ever met someone and then after a few weeks or months, they surprised you with something – they were a dark horse?",
        "How often do you bet on the wrong horse – pick the person who loses?",
        "Is it OK to change horses (leaders) in mid stream (half way through)?",
        "When was the last time you got off your high horse and apologized?",
        "What do you like doing so much that wild horses could not drag you away?",
        "You can lead a horse to water but you can’t make it drink. Have you ever been shown a great opportunity you didn’t take?",
        "Do you always work like a horse (very hard)?",
        "Do you like to hear gossip about someone, or do you prefer the truth – straight from the horse’s mouth?",
        "Do you ever feel you’re flogging a dead horse – you tell someone to do something but they just don’t get it? Does your teacher feel like this?",
        "Do you deal with problems before they arise, or do you lock the barn door the horse has bolted (gone)?",
        "Did you horse around a lot when you were a child?",
        "Do you know anyone who gets on their high horse and thinks they are better than everyone else?",
        "Have you ever been to a one-horse town, with nothing there?",
        "Are there any interesting horse idioms in your language?"
    ]
}
