export default {
    "Jail": [
        "What images spring to mind when you hear the word ‘jail’?",
        "Do you think jails work?",
        "Would you like to work in a jail?",
        "How would you feel if you had to spend a couple of months in jail?",
        "Do you think people leave jail better people or better criminals?",
        "What are the jails like in your country?",
        "What do you think prisoners do in jail every day?",
        "Do you think jails are dangerous places?",
        "In prison escape movies, do you always want the prisoners to escape? Why?",
        "Would you live in a house / apartment that was right next door to a jail?",
        "How did jails start?",
        "Do you think there are better ways of reforming criminals than sending them to jail?",
        "How do you think jails around the world are different?",
        "What’s the best way to escape from jail?",
        "Would you visit me in jail?",
        "If you were in jail, what would you miss most about the outside?",
        "If you were in jail, what would you worry about most?",
        "An American politician once said: “I don't want to send them to jail. I want to send them to school.” What do you think of this?",
        "Do you think life in jail should mean life in jail?",
        "What would you like to ask someone who is in jail for life?"
    ],
    "Jam": [
        "Do you like jam?",
        "Do you know how jam is made?",
        "What’s the difference between jam and marmalade?",
        "What is jam used for in cooking?",
        "How often do you eat jam?",
        "Is jam best on toast, bread or in cakes?",
        "Is jam healthy?",
        "What is the best jam manufacturer?",
        "English people eat jam sandwiches for lunch. What do you think of this?",
        "Do you prefer whole strawberries in strawberry jam or strawberry bits?",
        "What is your favourite kind of jam?",
        "Do you know any books or movies that have famous jam scenes?",
        "Which country makes the best jam?",
        "Americans say ‘jelly’, Brits say ‘jam’. Which is it?",
        "Americans eat peanut butter and jam/jelly sandwiches. Is this acceptable behaviour?",
        "Do you know any good jam recipes?",
        "Do you think there is a link between the jam you eat and the jam in a traffic jam or in a music jam?",
        "What do you think of the idea of spicy jam?",
        "What are the differences between wage and cost inflation?",
        "What is the “market basket” used in calculating the CPI (Consumer Price Index) to get the figure for inflation?"
    ],
    "Jamaica": [
        "What images spring to mind when you hear the country Jamaica?",
        "What are the good things and bad things about Jamaica?",
        "What is Jamaica famous for?",
        "What do you know about Jamaican history?",
        "What images of Jamaica do you have that are beautiful and romantic?",
        "What do you know about Jamaica’s main religion, Rastafarianism?",
        "What has Jamaica given to the world?",
        "Would you like to visit Jamaica, or live there?",
        "What do you know about the geography of Jamaica?",
        "Who are the most famous Jamaican people you know?",
        "How different is Jamaica from other world countries?",
        "Do you think Jamaica is one of the world’s most beautiful nations?",
        "Why is Jamaica one of the top tourist destinations in the world?",
        "What do you think Jamaica will be like 50 years from now?",
        "Does your country have good relations with Jamaica?",
        "What do you think about Jamaican music?",
        "What is your idea of a typical Jamaican person?",
        "What things about Jamaica do you think Jamaican people are proud of?",
        "What do you know about Jamaica food?",
        "What would you like to ask a Jamaican person about Jamaica?"
    ],
    "January": [
        "What springs to mind when you hear the word ‘January'?",
        "What do you think of the month of January?",
        "What good things happen in January?",
        "What things do you usually do in January?",
        "What do you think of the word 'January'?",
        "What are people who are born in January like?",
        "What do you think of January weather?",
        "Where is January on the list of 'the best months'?",
        "Are there any bad things about the month of January?",
        "What plans do you have for next January?",
        "If you made a January festival, what would you it be like?",
        "Is there any delicious food you eat in January?",
        "How should people celebrate in January?",
        "What famous holidays are there in January?",
        "How do you feel when January arrives?",
        "If you made a video about January, what would you put in it?",
        "How do you feel when January is over?",
        "What three adjectives best describe January, and why?",
        "What good thing can you remember happening in January?",
        "What is a good symbol for January, and why?"
    ],
    "Japan": [
        "What images spring to mind when you hear the country Japan?",
        "What are the good things and bad things about Japan?",
        "What is Japan famous for?",
        "What do you know about Japanese history?",
        "What images of Japan do you have that are beautiful and mysterious?",
        "What do you think about Japanese technology?",
        "What has Japan given to the world?",
        "Would you like to visit Japan, or live there?",
        "What do you know about the geography of Japan?",
        "Who are the most famous Japanese people you know?",
        "How different is Japan from other Asian countries?",
        "What do you know about Japanese culture?",
        "Why isn’t Japan one of the top tourist destinations in the world?",
        "What do you think Japan will be like 50 years from now?",
        "Does your country have good relations with Japan?",
        "What do you think about Japanese fashion, music, movies and manga?",
        "What is your idea of a typical Japanese person?",
        "What things about Japan do you think Japanese people are proud of?",
        "What do you know about Japanese food?",
        "What would you like to ask a Japanese person about Japan?"
    ],
    "Jesus": [
        "Is Jesus important in your life?",
        "What goes through your mind when you see images of Jesus?",
        "Do you think Jesus was really white, with light brown hair and blue eyes?",
        "What do you know about Jesus’ birth?",
        "Why is Jesus called ‘Jesus Christ’?",
        "What would Jesus do if he were alive on Earth today?",
        "Why did Jesus have only male disciples?",
        "Do you think it’s OK to name your son Jesus?",
        "Is there such a thing as too much Jesus?",
        "The Bible says little or nothing about Jesus when he was in his teens and early twenties. What happened to him then?",
        "Do you believe Jesus is the son of God?",
        "What do you know about Jesus’ death?",
        "Why is Jesus so important to Christians?",
        "What do you think when people say ‘Jesus’ or ‘Jesus Christ’ when they are angry?",
        "What would the world be like today if Jesus had never existed?",
        "How would the world be different today if God had had a daughter instead of a son?",
        "What were the teachings of Jesus?",
        "Do you think Jesus needs to come back to the world today?",
        "What questions would you like to ask Jesus?",
        "What do you think his answers would be?"
    ],
    "Jewelry": [
        "What springs to mind when you hear the word ‘jewelry’?",
        "Are you a jewelry person?",
        "What kind of jewelry do you like?",
        "Do you like wearing jewelry?",
        "Do you think wearing a lot of jewelry looks good or bad?",
        "What kind of jewelry looks good on men?",
        "Are diamonds really a girl’s best friend?",
        "Why do people wear jewelry?",
        "Do you like traditional jewelry or ethnic jewelry?",
        "What do you think of cheap jewelry?",
        "Do people look better with or without jewelry?",
        "Is there any jewelry that you wear 24/7?",
        "Would you like to wear the jewelry the Queen of England wears?",
        "How often do you go in jewelry shops?",
        "Do you think jewelry should be passed down from one generation to the next?",
        "Is jewelry sexy?",
        "Is a wedding ring considered to be jewelry?",
        "Do you prefer gold or silver jewelry?",
        "What is the best age for boys and girls to start wearing jewelry?",
        "What piece of jewelry would you like to design and then have a jeweler make for you?"
    ],
    "Job Interview Questions": [
        "Why would you be good at this job?",
        "What do you know about this job?",
        "What skills do you have for this job?",
        "What are your strengths and weaknesses?",
        "What qualifications do you have for this job?",
        "How well does your personality fit this job?",
        "Why are you applying for this job?",
        "What do you want to learn from this job?",
        "Are you a good team player?",
        "Do you get on well with other people?",
        "What do you do in stressful situations?",
        "What things about this job are difficult?",
        "Where do you see yourself in five years?",
        "Is there anything you want to ask me?",
        "Have you had problems working with a manager?",
        "What are your goals for the future?",
        "What do you know about this company?",
        "How much do you want this job?",
        "Why did you quit your last job?",
        "What can you contribute to this company?"
    ],
    "Job Interviews": [
        "What do you think of job interviews?",
        "What do you do before a job interview?",
        "What experience do you have of job interviews?",
        "What's the best way to pass a job interview?",
        "What should you wear to a job interview?",
        "Why do people get nervous in job interviews?",
        "What difficult questions have you in an interview?",
        "What are your strong points in job interviews?",
        "What are your weak points in job interviews?",
        "Is it important to ask questions in interviews?",
        "How did your last job interview go?",
        "What was your first job interview like?",
        "How should you sit in a job interview?",
        "How do you sell yourself in an interview?",
        "What questions would a teacher get asked?",
        "Should you make jokes in a job interview?",
        "Should there be an interview for US President?",
        "How can you practice for job interviews?",
        "What is your favourite job interview question?",
        "How do you feel after a job interview?"
    ],
    "Jobs": [
        "What kind of jobs have you had (part-time and full-time)?",
        "Are there many good job vacancies for you in your country?",
        "What is your dream job?",
        "What jobs do you do at home?",
        "Are there jobs that are only for women or only for men?",
        "How many jobs do you think you’ll have in your life?",
        "Are there any jobs you would refuse to do, regardless of the pay?",
        "Is being a rock star or sports star a job?",
        "What do you think the job of being an English teacher is like?",
        "Who has the best job in the world? Why do you think so?",
        "Do you often check the jobs ads in newspapers or on the Internet?",
        "What kinds of jobs interest you most and least?",
        "Is the job market in your country growing?",
        "What are the toughest jobs in the world?",
        "Is being a housewife a job? Should women get paid for this?",
        "Do you like job hunting applying for jobs?",
        "What is the job description of your last job?",
        "Does everyone have equal job opportunities in your country?",
        "What’s the best way to pass job interviews?",
        "What is the best way to quit a job?"
    ],
    "Jokes": [
        "Do you like jokes?",
        "Are you good at telling jokes or do you know anyone who tells good jokes?",
        "Do you always get (understand) the jokes you hear?",
        "Are the jokes you hear always funny?",
        "What makes a joke funny?",
        "Do you understand jokes from other countries or jokes told in English?",
        "What is the funniest joke you know?",
        "Do you ever think your country’s leaders or sports teams are a joke?",
        "Are there times when jokes are bad and should not be told?",
        "This is an English joke: Q. What do you call a fish with no eyes?\n A. fsh. What do you think of this joke?",
        "What kinds of jokes are there in your language?",
        "In English there are sick jokes, private jokes, cruel jokes and dirty jokes. What do you think these are?",
        "What are jokes in your country usually about?",
        "Can you take a joke when someone plays a joke on you?",
        "Have you ever done anything that is beyond a joke?",
        "Do you laugh at children’s jokes?",
        "Do you laugh at your own jokes? Is it OK to do this?",
        "In English, there are ‘mother-in-law’ jokes and ‘blonde’ jokes. Are there groups of people in your country that are commonly joked about?",
        "Are there racist and sexist jokes in your country? What do you think of them?",
        "This is an English joke: Q. What do you call a deer with no eyes?\n A. no idea. What do you think of this joke?"
    ],
    "Journalism": [
        "What is journalism?",
        "What do you know or can guess about the history of journalism?",
        "Would you be interested in studying journalism?",
        "Is journalism a respected profession in your country?",
        "What do you think of the journalism on news stations like the BBC and CNN?",
        "What is the quality of journalism like in your country?",
        "Are there government controls on journalism in your country?",
        "What good does journalism do in the world?",
        "Is journalism always about reporting the truth?",
        "What do you think a career in journalism would be like?",
        "Do you think journalism is different in different countries around the world?",
        "What kind of journalism are you most interested in?",
        "What do you think of journalists who report in war zones?",
        "What kind of people are good at journalism?",
        "Do you think people can make a lot of money from journalism?",
        "Do you think investigative journalism would be interesting?",
        "How important is journalism in today’s world?",
        "What do you think of the paparazzi and gutter press?",
        "Do you think the Internet can make us all journalists?",
        "What do you think world leaders and governments think of journalism?"
    ],
    "Judaism": [
        "What springs to mind when you hear the word ‘Judaism’?",
        "What do you know about Judaism?",
        "What are the differences between Judaism, Christianity and Islam?",
        "Why have Jews been persecuted so much throughout history?",
        "If Jesus was the King of the Jews, why don’t Christians also follow Judaism?",
        "Judaism came first, so why is the number of followers of Judaism much smaller than the numbers for Muslims and Christians?",
        "What would the world be like today if Judaism had not started?",
        "What do you know about customs and rituals in Judaism?",
        "Have you ever been inside a synagogue? What must and mustn’t you do there?",
        "How are Orthodox Jews different from other Jews?",
        "What is anti-Semitism and how can we fight it?",
        "What is Zionism?",
        "Do men and women have different roles in Judaism?",
        "Do you know which holidays are celebrated in Judaism?",
        "Do you think Judaism will thrive as a world religion?",
        "What symbols of Judaism do you know of and what do they mean?",
        "Why is there so much bad feeling between Jews and Arabs?",
        "What do you know about Jewish cuisine?",
        "How important is the nation of Israel in Judaism?",
        "What questions about Judaism would you like the answers to?"
    ],
    "Juice": [
        "What comes to mind when you hear the word ‘juice’?",
        "What is your favourite juice?",
        "How often do you drink freshly squeezed juice?",
        "Do you use a juicer?",
        "Is a lot of juice good for you?",
        "Do you prefer fruit juices or vegetable juices?",
        "Is there anything unhealthy about juice?",
        "What company makes the best juice?",
        "What is better with breakfast, orange juice or coffee?",
        "Why is prune juice sometimes used as a medicine?",
        "Do you prefer ‘smooth’ juice or juice with ‘bits’?",
        "Why do you think orange juice is the most common juice? Does this mean it’s the most delicious?",
        "Do you think drinking juice is better for you than eating fruit?",
        "What is better, carrot juice or banana juice?",
        "What do you use lemon juice for?",
        "Do you think a glass of garlic and onion juice every day would be good for you?",
        "What juices are good with alcohol?",
        "Why is juice good for you?",
        "Why doesn’t juice from bottles taste like freshly squeezed juice?",
        "Wheat grass juice is supposed to be very good for us. What do you know about it?"
    ],
    "July": [
        "What springs to mind when you hear the word ‘July'?",
        "What do you think of the month of July?",
        "What good things happen in July?",
        "What things do you usually do in July?",
        "What do you think of the word 'July'?",
        "What are people who are born in July like?",
        "What do you think of July weather?",
        "Where is July on the list of 'the best months'?",
        "Are there any bad things about the month of July?",
        "What plans do you have for next July?",
        "If you made a July festival, what would you it be like?",
        "Is there any delicious food you eat in July?",
        "How should people celebrate in July?",
        "What famous holidays are there in July?",
        "How do you feel when July arrives?",
        "If you made a video about July, what would you put in it?",
        "How do you feel when July is over?",
        "What three adjectives best describe July, and why?",
        "What good thing can you remember happening in July?",
        "What is a good symbol for July, and why?"
    ],
    "June": [
        "What springs to mind when you hear the word ‘June'?",
        "What do you think of the month of June?",
        "What good things happen in June?",
        "What things do you usually do in June?",
        "What do you think of the word 'June'?",
        "What are people who are born in June like?",
        "What do you think of June weather?",
        "Where is June on the list of 'the best months'?",
        "Are there any bad things about the month of June?",
        "What plans do you have for next June?",
        "If you made a June festival, what would you it be like?",
        "Is there any delicious food you eat in June?",
        "How should people celebrate in June?",
        "What famous holidays are there in June?",
        "How do you feel when June arrives?",
        "If you made a video about June, what would you put in it?",
        "How do you feel when June is over?",
        "What three adjectives best describe June, and why?",
        "What good thing can you remember happening in June?",
        "What is a good symbol for June, and why?"
    ],
    "Jungles": [
        "What springs to mind when you hear the word ‘jungle’?",
        "What is the difference between a jungle and a rainforest?",
        "What was you image of jungles when you were a child?",
        "Would you like to go trekking through a jungle?",
        "Do you think living in the jungle would be better than living in a modern city?",
        "What dangers are there in the jungle?",
        "What should the world do to protect jungle tribes?",
        "Are you a person that would stick to the beaten track in the jungle or cut a totally new track for yourself?",
        "What is the law of the jungle?",
        "What can you do to protect yourself against inflation?",
        "For how long do you think you could live in the jungle?",
        "What would you do every day if you lived in the jungle?",
        "What are the most beautiful features of jungles?",
        "How many and how much of the world’s jungles will still be there in a hundred years from now?",
        "Do you think you could survive in the jungle?",
        "Is it easier to survive in the jungle or the concrete jungle?",
        "What things would you be afraid of in the jungle?",
        "Are jungles healthier, less stressful places to be than cities?",
        "If you spent a year in the jungle, who would you like to take with you?",
        "What three personal belongings would you need if you were to spend a year in the jungle?"
    ],
    "Junk Food": [
        "What springs to mind when you hear the term ‘junk food’?",
        "How often do you eat junk food?",
        "What is it about junk food that is so bad for us?",
        "Do you think there should be a junk food tax to help pay for people who go to hospital with heart and weight problems?",
        "Why is junk food so delicious?",
        "Are parents who feed junk food to their children irresponsible?",
        "Do you think there’ll be more or less junk food in the future?",
        "What junk food do you really, really like?",
        "Is the junk food from your country tastier than the junk food from other countries?",
        "How can you change your lifestyle to eat less junk food?",
        "Do lots of people eat junk food in your country?",
        "Does your government educate people about the dangers of junk food?",
        "Do you think junk food makers are immoral and should think more about people’s health?",
        "What do you think of people who eat mostly junk food?",
        "Does junk food or good quality healthy food make you happier?",
        "If you had to choose between a strict vegetarian diet forever or a junk food diet forever, which would you choose?",
        "Why does junk food cost so much?",
        "What is the definition of junk food?",
        "Is chocolate the most addictive junk food?",
        "Do you think people ate junk food hundreds of years ago?"
    ],
    "Junk Mail": [
        "What is junk mail?",
        "What do you think of junk mail and junk mailers?",
        "What is worse, junk mail in your inbox or junk mail delivered to your house?",
        "How much does junk mail bother, irritate or anger you?",
        "Do you do anything to reduce the amount of junk mail you get?",
        "Why is junk mail also called spam mail?",
        "What are common subjects for the junk mail you receive?",
        "Have you ever replied or responded to junk mail?",
        "Should those who send junk mail go to prison?",
        "Why do people send junk mail?",
        "What do you hate more, junk mail or pop-up ads?",
        "What do you think of the e-mail scammers who say their relative has died leaving them millions of dollars and they need your help?",
        "Should governments, police and software companies work harder to catch spam e-mailers?",
        "Can you always detect spam mail from the subject?",
        "Are you ever fooled by phishing mails – those that look like they’ve been sent from a bank and ask you to confirm your private info?",
        "What would you do or say to someone who kept sending you spam mail?",
        "Have you ever replied to a spam mail asking the sender to stop?",
        "Do you think spam has any negative impact on the Internet?",
        "Have you ever come across junk mail that was useful or interesting?",
        "Do you think junk mail will ever disappear?"
    ],
    "Juvenile Crime": [
        "Is juvenile crime a problem in your country?",
        "What kind of crimes do young people commit?",
        "Are you afraid of young people in your country?",
        "At what age do young people turn to crime?",
        "Why has juvenile crime increased in the past decade?",
        "What is the profile of the average juvenile criminal?",
        "Should young people go to prison if they commit serious crimes?",
        "How much are parents to blame if their children become criminals?",
        "Why do you think so many young people have lost respect for authority?",
        "What part do you think movies, the Internet and video games play in leading young people to crime?",
        "What are the main reasons children become criminals?",
        "Should there be better policing to reduce juvenile crime?",
        "Are schools in your country doing their job to prevent juvenile crime?",
        "What is the relationship between juvenile crime and drugs in your country?",
        "Is society too soft on young people?",
        "What would you do if you discovered your children had committed criminal acts?",
        "What is the impact of gangs on children in your country?",
        "Will there be more or less juvenile crime in the future?",
        "Did you commit any crimes when you were a child?",
        "What questions would you like to ask a juvenile criminal?"
    ]
}
