export default {
    "Valentine's Day": [
        "What do you know about Valentine's Day?",
        "Do you like Valentine's Day?",
        "What are the good things about Valentine's Day?",
        "What would be your perfect Valentine's Day?",
        "What Valentine's Day message would you like someone to write to you?",
        "Tell me about the perfect Valentine's Day meal.",
        "Is Valentine's Day a bad day for people who are single?",
        "Someone once said: “Why was Cupid was to represent Valentine's Day. When I think about romance, the last thing on my mind is a short, chubby toddler coming at me with a weapon.” Do you agree?",
        "What are the most romantic Valentine's Day words in your language?",
        "Should Valentine's Day be a national holiday?",
        "Is Valentine's Day really another way for companies to make money?",
        "What are the best Valentine's Day gifts?",
        "What do you write in a Valentine's Day card?",
        "Who is your perfect Valentine, and why?",
        "What's the most romantic song you know?",
        "Why are roses always associated with Valentine's Day?",
        "Is Valentine's Day a bad day for people who aren't so good-looking?",
        "Is giving chocolates as a Valentine's present a sign of uncreativeness?",
        "Shouldn't every day be Valentine's Day?",
        "How romantic are you?"
    ],
    "Vandalism": [
        "What images spring to mind when you hear the word ‘vandalism’?",
        "Is vandalism a big problem in your country?",
        "Why do vandals like to vandalize things?",
        "Who are the biggest vandals in your country?",
        "Do you think vandalism has always been a problem or is it new?",
        "Did you ever vandalize anything when you were at school?",
        "Is drawing on a school desk vandalism?",
        "What should happen to vandals if the police catch them?",
        "What kinds of things are vandalized in your country?",
        "Would you like to vandalize something?",
        "What is vandalism?",
        "Do you think vandalism leads to more serious crime?",
        "What can people do to keep vandalism out of their neighbourhoods?",
        "What would you do if you saw a group of teenagers vandalizing your car?",
        "Can vandalism turn parts of towns into no-go areas?",
        "Is graffiti art or vandalism?",
        "Are the laws in your country tough enough on vandals?",
        "Is someone who destroys public property while they are drunk a vandal?",
        "What would you do if your 16-year-old child was arrested for vandalism?",
        "Are e-mail spammers Internet vandals?"
    ],
    "Vegetarianism": [
        "What comes to mind when you hear the word ‘vegetarianism’?",
        "Would the world be a better place if everyone was a vegetarian?",
        "Why do people become vegetarians?",
        "Do you think vegetarians lead better lives than non-vegetarians?",
        "Is there anything unhealthy about a vegetarian diet?",
        "What three adjectives would you use to describe vegetarianism?",
        "What would happen to the cow population if we stopped eating them?",
        "Albert Einstein said: \"Nothing will benefit human health and increase chances for survival of life on Earth as much as the evolution to a vegetarian diet.\" Do you agree?",
        "Someone once asked: \"If vegetarians eat vegetables, what do humanitarians eat?\" What do you think?",
        "Margi Clark said: \"I think if you want to eat more meat you should kill it yourself and eat it raw.\" What do you think?",
        "What do you know about vegetarianism?",
        "What are the arguments against vegetarianism?",
        "What do you think vegetarians think of meat eaters?",
        "Would we help save the planet if we were all vegetarian?",
        "Is a vegetarian diet healthier than a meat diet?",
        "What’s a strict vegetarian?",
        "Will we all be vegetarians in the future?",
        "Gandhi said: \"To my mind, the life of a lamb is no less precious than that of a human being.  I should be unwilling to take the life of a lamb for the sake of the human body.\" What do you think?",
        "K.D. Lang asked: \"We all love animals.  Why do we call some \"pets\" and others \"dinner?\" What do you think?",
        "Paul McCartney said: \"If slaughterhouses had glass walls, everyone would be a vegetarian.\" What do you think?"
    ],
    "Video games": [
        "What springs to mind when you hear the term ‘video games’?",
        "Do you learn anything from playing video games?",
        "Do you prefer playing video games alone, against friends or online against the world?",
        "Do you think video games make people violent?",
        "Which company makes the best games?",
        "Would you like to be a game designer? What kinds of games would you design?",
        "Do you prefer watching movies or playing video games?",
        "Does your personality change when you’re gaming?",
        "Are video games good for relieving stress?",
        "Would you but a good book or a good video game for your little sister’s or brother’s birthday?",
        "Do you like video games?",
        "What’s your favourite video game?",
        "PlayStation, X-Box or Nintendo Wii – which is best and why?",
        "Can you remember the first video game you played?",
        "What will video games be like in the future?",
        "Are video games bad for your health?",
        "Which game are you best at?",
        "Are video games good for hand-eye coordination?",
        "Do you like it when Hollywood makes a movie from the video game?",
        "How can you help someone who is addicted to video games?"
    ],
    "Vietnam": [
        "What images spring to mind when you hear the country Vietnam?",
        "What are the good things and bad things about Vietnam?",
        "What is Vietnam most famous for?",
        "What do you know about Vietnam’s history?",
        "What are the differences between Vietnam and your country?",
        "What do you think about Vietnamese people?",
        "What has Vietnam given to the world?",
        "Would you like to visit Vietnam, or live there?",
        "What do you know about the geography of Vietnam?",
        "Who are the most famous Vietnamese people you know?",
        "How different is Vietnam from other Southeast Asian countries?",
        "What was the last news story you heard about Vietnam?",
        "What do you think Vietnam’s neighbours think of it?",
        "What do you think Vietnam will be like 50 years from now?",
        "Does your country have good relations with Vietnam?",
        "What could you do on a holiday in Vietnam?",
        "What is your idea of a typical Vietnamese person?",
        "What things about Vietnam do you think Vietnamese people are proud of?",
        "What do you know about Vietnamese culture?",
        "What would you like to ask a Vietnamese person about Vietnam?"
    ],
    "Violence": [
        "What springs to mind when you hear the word ‘violence’?",
        "How often do you see violence in your country?",
        "What makes people violent?",
        "Is there a cure for violence?",
        "Do you think there’s too much violence on TV and in video games?",
        "Do you think humans will ever be nonviolent?",
        "Do you think men or women like violence more? Why do you think so?",
        "Why are the words ‘sex’ and ‘violence’ so often used together in the phrase ‘sex and violence’?",
        "Sam Peckinpah said: “There is a great streak of violence in every human being. If it is not channeled and understood, it will break out in war or in madness.” Do you agree?",
        "Martin Luther King, Jr. said: “Nonviolence means avoiding not only external physical violence but also internal violence of spirit. You not only refuse to shoot a man, but you refuse to hate him. Do you agree?",
        "Do you enjoy watching violence in real life or in the movies?",
        "How big a problem is domestic violence in your country?",
        "Does violence ever achieve anything?",
        "Have you ever resorted to violence?",
        "Is violent crime on the increase in your countries?",
        "Do people learn to be violent?",
        "Is there much ethnic violence in your country?",
        "Do you think countries can be violent?",
        "Gandhi said: “Victory attained by violence is tantamount to a defeat, for it is momentary.” Do you agree?",
        "Madge Micheels-Cyrus said: “Nonviolence doesn't always work - but violence never does.” Do you agree?"
    ],
    "Vitamins": [
        "What comes to mind when you hear the word ‘vitamin’?",
        "Do you get enough vitamins every day?",
        "How would you know if you didn’t get enough vitamins?",
        "What do you think the most important vitamin is?",
        "Would you like to study vitamins?",
        "What are vitamins?",
        "Do you think it’s important to take vitamin supplements?",
        "Is it dangerous to have too many vitamins?",
        "Have you ever had vitamin deficiency?",
        "Can vitamins change your feelings?",
        "What are vitamins?",
        "Do you worry about not getting enough vitamins?",
        "What vitamins do you know of and what do they do?",
        "Can vitamins improve your intelligence?",
        "Which is better for you – a vitamin C pill or an orange?",
        "Do pharmacies really need so many different bottles of vitamin pills?",
        "What vitamin would you like to invent? What would it do?",
        "What are the differences between vitamins and minerals?",
        "How do people who do not take vitamin pills survive?",
        "Do you think everyone in the world will have enough vitamins in the future?"
    ],
    "Vocabulary": [
        "What images spring to mind when you hear the word ‘vocabulary’?",
        "How important do you think vocabulary is?",
        "Is your teacher good at teaching vocabulary?",
        "What problems do you have with vocabulary?",
        "What advice do you have for students learning vocabulary?",
        "What word makes you proud of your vocabulary?",
        "What’s the best way to broaden your vocabulary?",
        "What’s the best way to study for a vocabulary test?",
        "How important is slang in vocabulary learning?",
        "What book can you recommend to help others learn vocabulary?",
        "What’s more important, grammar or vocabulary?",
        "Do you like studying vocabulary?",
        "Do you have an impressive knowledge of vocabulary in your own language?",
        "What’s the hardest thing about learning English vocabulary?",
        "Are there words in English you still keep forgetting?",
        "Do you separate your vocabulary lists into words, idioms, phrasal verbs, etc?",
        "What do you know about the ‘bad’ words in the English vocabulary?",
        "What do you think of English words becoming part of the vocabulary of your own language?",
        "What’s the best website for learning vocabulary?",
        "Are vocabulary games a good way to remember vocabulary?"
    ],
    "Vocabulary Activities": [
        "What comes to mind when you hear the term ‘vocabulary activity’?",
        "What do you think when your teacher says you’re going to do some vocabulary?",
        "What kind of vocabulary practice do you like most?",
        "Do you like the vocabulary activities your teacher gives you?",
        "Do you have an example of how a vocabulary lesson really improved your vocabulary?",
        "Do you know of any websites that have good vocabulary activities?",
        "Is learning vocabulary in class ever interesting and fun? Should it be?",
        "Do you always understand the reasons why the teacher asks you to do a particular vocabulary activity?",
        "What are your biggest problems with vocabulary?",
        "How important is vocabulary compared with pronunciation, writing, speaking and listening?",
        "Do you like doing vocabulary activities in class?",
        "Do you ever think vocabulary activities are a waste of time?",
        "What vocabulary learning strategies do you use a lot?",
        "Is the topic important when you do a vocabulary activity?",
        "What things are important for a vocabulary activity to be successful?",
        "What advice would you give to a student who says he/she is no good at vocabulary or hates vocabulary?",
        "What do you like most and least about vocabulary in English?",
        "Is there a lot of English vocabulary in your own language? Do you think this could be made into a vocab-learning activity?",
        "Do you think you need vocabulary practice in every class?",
        "What questions would you like to ask your teacher about vocabulary?"
    ],
    "Volunteerism": [
        "What springs to mind when you hear the word ‘volunteer’?",
        "Do you often volunteer to do things?",
        "Have you ever volunteered to do something and then regretted volunteering?",
        "What kind of voluntary work would you like to do?",
        "What would the world be like if no one volunteered to do anything?",
        "Has anyone ever volunteered your services and you didn’t want them to?",
        "Would you like to work as a volunteer overseas?",
        "What was your last volunteer effort?",
        "Does your town have lots of volunteer schemes?",
        "When was the last time someone volunteered to help you?",
        "Do you think we should all volunteer to do something good for others?",
        "December 5th is International Volunteer Day. What do you think happens or should happen on this day?",
        "How do you feel about yourself after you’ve finished a task you volunteered for?",
        "Could all of the world’s problems be solved through volunteerism?",
        "What would you like to see more people volunteer for?",
        "Are volunteers special?",
        "Are you always the first to volunteer?",
        "Would you ever volunteer to help the lion tamer or the fire-eater in a circus?",
        "Do you think doing voluntary work is good for your resume?",
        "Would you join the volunteer army of your country?"
    ],
    "Voting": [
        "What comes to mind when you hear the word ‘voting’?",
        "Do you think voting is over-rated?",
        "Why is being able to vote so important?",
        "Are you happy you’ll get good service from the people you vote for?",
        "Do you like looking at election results on TV?",
        "What do you vote for when you vote?",
        "Is voting in elections for people who are generally not qualified to run a country the best way to run a country?",
        "Are there any problems when it comes to voting in your country?",
        "Do you feel like you are doing something really important when you vote?",
        "Do you think voting and elections make a difference?",
        "How important is it for you to vote?",
        "Do you vote every time you can?",
        "What are the good and bad things about voting?",
        "Does being able to vote mean your country is democratic?",
        "Does having a choice of just two candidates for president mean your country is democratic?",
        "What do you think of the way people vote in other countries?",
        "Have you voted in elections that are not just about politics?",
        "From what age do you think people should be able to vote?",
        "Have you ever voted with your feet?",
        "Joseph Stalin said: \"The people who cast the votes don't decide an election, the people who count the votes do.\" What do you think of this quote?"
    ]
}
