export default {
    "Painting": [
        "What comes to mind when you hear the word ‘painting’?",
        "Do you or did you ever like painting?",
        "Are you good at painting?",
        "Do you think modern artists are good at painting?",
        "What style or period of painting / art do you like?",
        "What do you think of people who are very good at painting?",
        "Do you think painting is an important school subject?",
        "Do you prefer artists from your country or those from others?",
        "What do you think of artists from other continents?",
        "Do you prefer oils, watercolours, sketches or another medium?",
        "What do paintings mean to you?",
        "What kinds of paintings do you have in your house?",
        "Why is painting and art so important to us?",
        "Do you like watching children paint?",
        "Would you like to work with kangaroos – studying them, photographing them, helping protect them etc?",
        "Have you ever been emotionally moved because of a painting?",
        "What do you think artists from centuries ago would think of today’s artists?",
        "What painting that you did was/is your favourite?",
        "Would you consider investing money in a painting? Do you think art is a good investment?",
        "What do people think about when they look at paintings in galleries?"
    ],
    "Palestine": [
        "What images spring to mind when you hear ‘Palestine’?",
        "What are the good things and bad things about Palestine?",
        "What is Palestine most famous for?",
        "What do you know about Palestine’s history?",
        "What are the differences between Palestine and your country?",
        "What do you think about Palestinian people?",
        "What has Palestine given to the world?",
        "Would you like to visit Palestine?",
        "What do you know about the geography of Palestine?",
        "Who are the most famous Palestinian people you know?",
        "How different is Palestine different from other Middle Eastern countries?",
        "What was the last news story you heard about Palestine?",
        "What do you think Palestine’s neighbours think of it?",
        "What do you think Palestine will be like 50 years from now?",
        "Does your country have good relations with Palestine?",
        "What three adjectives would you use to describe Palestine and why?",
        "What is your idea of a typical Palestinian person?",
        "What things about Palestine do you think Palestinians are proud of?",
        "What do you know about Palestinian culture?",
        "What would you like to ask a Palestinian about Palestine?"
    ],
    "Panama": [
        "What images spring to mind when you hear the country name Panama?",
        "What are the good things and bad things about Panama?",
        "What is Panama famous for?",
        "What do you know about Panama’s history?",
        "What do you know about Panama’s famous canal?",
        "What do you think about Panamanians?",
        "What has Panama given to the world?",
        "Would you like to visit Panama, or live there?",
        "What do you know about the geography of Panama?",
        "Who are the most famous Panamanians you know?",
        "How different is Panama from other Latin American countries?",
        "Do you think the name ‘Panama’ is a good name?",
        "Why do you think Ecuador makes more Panama hats than Panama does?",
        "What do you think Panama will be like 50 years from now?",
        "Does your country have good relations with Panama?",
        "What do you know about sport in Panama?",
        "What is your idea of a typical Panamanian person?",
        "What things about Panama do you think Panamanians are proud of?",
        "What do you know about Panamanian politics?",
        "What would you like to ask a Panamanian person about Panama?"
    ],
    "Panic": [
        "What images spring to mind when you hear the word ‘panic’?",
        "How do you usually panic?",
        "Have you ever panicked while using a computer?",
        "Do you keep a cool head while you are panicking?",
        "Have you ever seen panic in the streets?",
        "Have you ever suffered a panic attack?",
        "Why do some people panic in a situation when other people remain calm?",
        "Why do men panic when women cry?",
        "Do you think you’re a good person to have around in times of panic?",
        "Have you ever panicked because of money?",
        "Are you a panic?",
        "What makes you panic?",
        "Do you panic if you oversleep?",
        "When was the last time you hit the panic button?",
        "Who is the biggest panic you know?",
        "What is the medical reason for panic?",
        "What’s the best way for people to overcome panic?",
        "Can you hide your panic from other people or do you rush to the panic stations and totally lose control?",
        "What do you do to calm down someone who is panicking?",
        "Have you ever done something because of panic that you now regret?"
    ],
    "Paper": [
        "What do you know about paper?",
        "Why is paper so useful?",
        "Do you think computers will one day mean we have no use for paper?",
        "Do you use or waste too much paper?",
        "How often do you get a paper cut? Is it painful?",
        "Are you a good paper recycler?",
        "What paper products do you have on you right now that could be replaced by more environmentally friendly things?",
        "Do you prefer blank or lined paper?",
        "Why does it say ‘paper jam’ when there is no paper jam?",
        "What is best for wrapping presents – wrapping paper or newspaper?",
        "What springs to mind when you hear the word ‘paper’?",
        "What do you know about the history of paper?",
        "How can we cut down on the amount of paper we waste?",
        "What happened to the paperless offices and schools that were promised when computers arrived?",
        "Do you think shops should stop using paper bags?",
        "What different things can you use scrap paper for?",
        "Is the production of paper very bad for the environment? Why?",
        "Have you ever spent a long time choosing the correct kind of paper to buy?",
        "What would be a good paper substitute?",
        "Is your desk full of paper?"
    ],
    "Parenting": [
        "What springs to mind when you hear the word ‘parenting’?",
        "What do you think is the most important thing to remember about parenting?",
        "Do you think you’d be / you are a good parent?",
        "What did you learn from your parents about parenting?",
        "Do you think parenting is easy?",
        "Why do things go wrong with some parents?",
        "Did your parents excel in parenting skills?",
        "Do you think parenting has changed throughout the ages?",
        "What would you do differently from your parents?",
        "Would you buy a parenting book and video?",
        "Do you think parenting is the same all over the world?",
        "How long does parenting last?",
        "What do you think of the word ‘parenting’? Is there a better word?",
        "Do you think children should learn parenting skills at school?",
        "What makes a good parent?",
        "Are parenting skills different for women and men?",
        "What do you think children think of their parents’ parenting skills?",
        "Would you tell your friend if you thought s/he was being a bad parent?",
        "Do you think kids should be able to fill in surveys and rank their parents on their parenting skills?",
        "What do you think of the parenting skills of Michael Jackson and Britney Spears?"
    ],
    "Parks": [
        "What comes to mind when you hear the word ‘park’?",
        "What’s your favourite park and why?",
        "What makes a good park good, in your eyes?",
        "Have parks changes since you were a kid?",
        "Do you think parks are different in other countries?",
        "Do you like the sound of children playing in parks?",
        "Are parks in your country now full of kids causing trouble?",
        "Are there enough parks in your neighbourhood?",
        "Do you think dogs should be banned from parks?",
        "Do you like theme parks?",
        "What was your favourite park when you were a child?",
        "If you could design your own park, what would you put in it?",
        "What is the best park in the world?",
        "Are there any parks for adults? Should there be adult-only parks?",
        "Is there anything you dislike about parks?",
        "What are the national parks like in your country?",
        "Do you think children should design the parks in cities?",
        "What will the parks of the future look like?",
        "What’s your favourite thing to do in parks?",
        "What annoys you most about other people’s behaviour in parks?"
    ],
    "Parties": [
        "What images spring to mind when you hear the word ‘party’?",
        "Do you like to party? Do you party hard?",
        "What makes a good party good, for you?",
        "How many parties have you thrown?",
        "What was the worst party you’ve ever been to?",
        "What’s the best birthday party you’ve ever had?",
        "Have you ever been to a fancy dress / costume party?",
        "Have you ever been to a party where lots of things went wrong?",
        "What do you think of children’s birthday parties?",
        "Are parties better in people’s houses or in party halls and hotels etc?",
        "How would you liven up a party?",
        "Are you a party starter, goer or pooper?",
        "Have you ever had or been to a surprise birthday party?",
        "Do you prefer going to dinner parties or giving dinner parties?",
        "What good party games do you know?",
        "Do you get dressed up in your party clothes to go to a party?",
        "Are parties just for kids?",
        "Have you been to a party in another country? Was it different to parties in your country?",
        "Would you let your 16-year-old son organize his own party in your house while you were on vacation?",
        "Do you celebrate the coming of a new year with a party?"
    ],
    "Passports": [
        "What images spring to mind when you hear the word ‘passport’?",
        "Do you like your passport?",
        "Are there many stamps and visas in your passport?",
        "Would you worry if you lost your passport while overseas?",
        "If you could have an additional passport from another country, what would it be?",
        "Is the passport from your country more or less useful than passports from other countries?",
        "Do you like your passport photo?",
        "What do you think passports will be like in the future?",
        "What do you do to keep your passport safe in other countries?",
        "Should we change the name of passports? We rarely travel through ports nowadays.",
        "Is it easy to get a passport in your country?",
        "What are the dangers to passports?",
        "Do you think there is a system that is better than everyone having to carry a passport every time they travel?",
        "Do you ever get nervous going through passport control at airports or border crossings?",
        "How much is a passport in your country? Do you think they should be free?",
        "What do you think about the new biometric passports?",
        "Do you ever get tired of filling out your passport details?",
        "What’s the passport application process like in your country?",
        "Are there any personal documents more important than a passport?",
        "Would you prefer an American or British passport?"
    ],
    "Pasta": [
        "What comes to mind when you hear the word ‘pasta’?",
        "How much do you like pasta?",
        "Do you know how pasta is made?",
        "What are your favourite kinds of pasta?",
        "Pasta or pizza?",
        "How many different types of pasta do you know of?",
        "How often do you eat pasta?",
        "What do you know about the nutritional value of pasta?",
        "What do you think of pasta that comes in tins?",
        "What kind of pasta salad do you make/eat?",
        "What’s the difference between pasta and noodles?",
        "What’s your favourite pasta restaurant and why?",
        "Are you good at cooking pasta dishes?",
        "Why do you think there are so many shapes of pasta?",
        "Do the Italians really cook the best pasta?",
        "Do you think pasta is better than other staple foods like rice, potatoes, bread, etc?",
        "Do you think pasta is good value for money?",
        "What would you say to convince someone who didn’t like pasta that is was really tasty?",
        "How would your life be different if all the world’s pasta ran out?",
        "What’s the difference between pasta and noodles?"
    ],
    "Patience": [
        "What comes to mind when you hear the word ‘patience’?",
        "Is patience important?",
        "What kinds of people do you have little or no patience with?",
        "When during the day is your patience at its lowest and why?",
        "Why do people say ‘patience is a virtue’?",
        "How can you increase your patience?",
        "When was the last time you ran out of patience with someone?",
        "Do you think you’re getting more patient or impatient as you get older?",
        "How long can a company put you on hold before your patience goes?",
        "Are you more patient with the ones you love?",
        "Do you have a lot of patience?",
        "When does your patience wear thin?",
        "Have you ever run out of patience while shopping?",
        "Do you have a lot of patience with children?",
        "Is it possible to have infinite patience?",
        "Do you think a teacher needs a lot of patience? How about our teacher?",
        "Who or what in your life requires the most patience from you?",
        "When was the last time you were rewarded for your patience?",
        "Do you know anyone who would try the patience of a saint?",
        "Of all the people you know, who lacks patience the most?"
    ],
    "Peace": [
        "What comes to mind when you hear the word ‘peace’?",
        "Are you at peace with yourself and the world?",
        "Do you love peace and quiet?",
        "Do you think there’ll ever be peace in the world?",
        "What’s the best way of achieving peace?",
        "What do you think of all the world’s peace processes and peace plans?",
        "Which area of the world do you hope achieves a lasting, permanent peace?",
        "When was the last time you heard of two countries or groups signing a peace deal?",
        "Which is more important, freedom or peace?",
        "What colour is peace?",
        "What does peace mean to you?",
        "How important is peace to you?",
        "What is peace of mind and inner peace?",
        "Do you think all Nobel Peace prize winners deserved their award?",
        "Would you be a good peacemaker? Why do you think this?",
        "Would you consider joining a peace movement?",
        "Do you think everyone who dies rests in peace?",
        "Do you ever have to get the peace pipe out to settle arguments with friends and family?",
        "If religions are all about peace, why do they lead to so much conflict?",
        "Do you do anything to reach a state of peace, like yoga or meditation?"
    ],
    "Penguins": [
        "How would you define a penguin?",
        "Do you like penguins?",
        "What do you think about when you look at penguins?",
        "How would the world be different if there were no penguins?",
        "What do penguins represent in the world?",
        "Do you think penguins have a good life?",
        "Why can’t penguins fly?",
        "Do you think penguin would be good to eat?",
        "Do you spend a little longer in zoos and aquariums looking at the penguins?",
        "What do you think of the word ‘penguin’?",
        "What springs to mind when you hear the word ‘penguin’?",
        "What do you think a penguin would be a good symbol or logo of?",
        "Do you think a penguin would be a good pet?",
        "What do you think of penguin movies?",
        "How are penguins different from other birds?",
        "How do you think global warming affects penguins?",
        "Do you think penguins are dangerous?",
        "What do penguins do for fun?",
        "What questions would you like to ask a penguin?",
        "What do you think its answers would be?"
    ],
    "Pensions": [
        "What springs to mind when you hear the word ‘pension’?",
        "Does your government provide you with a state pension in your old age?",
        "Why are pensions important?",
        "Have you started contributing to a pension scheme?",
        "How much of a pension do you think you’ll need when you retire?",
        "Do you understand how pensions work?",
        "Has anyone ever tried to sell you a pension?",
        "Do you think all companies should contribute to their workers’ pensions?",
        "Should the government tax pensions?",
        "Do you think you’d be good at selling pensions?",
        "How do pension funds operate?",
        "What does it mean when you rollover your pension?",
        "What’s the best age to start your own pension?",
        "How much are you prepared to pay right now in pension contributions?",
        "What do you need to do when you plan a pension?",
        "Do you think pension plans are risky?",
        "What kind of life do you think you will have on a pension?",
        "Who would you go to for advice on pensions?",
        "Why do pension schemes sometimes collapse?",
        "What would you do if the pension scheme you had been paying into for years suddenly collapsed due to mismanagement?"
    ],
    "People": [
        "Are people strange?",
        "What’s the worst thing about people?",
        "What are people best at?",
        "Why do people dislike each other so much?",
        "Do people ever confuse you with other people?",
        "Do guns kill people or do people kill people?",
        "What kind of people do you like best?",
        "What kind of people do you get fed up with?",
        "What different kinds of groups of people can you think of?",
        "When can we use ‘persons’ instead or ‘people’ in English?",
        "What are ordinary people? Do ordinary people vary from country to country?",
        "Are you a morning person?",
        "Do you believe what people tell you?",
        "Does learning always make you motivated to do things?",
        "What can we do to protect indigenous people around the world?",
        "Do you like reading about famous people?",
        "Are you a people person?",
        "What do you think of Internet sites that help you find people?",
        "What do you think of the cry, “People of the world unite”?",
        "Which people are best?"
    ],
    "Perfume": [
        "What comes to mind when you hear the word ‘perfume’?",
        "Do you like perfume?",
        "Is perfume an important part of your culture?",
        "Do you think perfume is good for your skin?",
        "Do you think it’s OK for men to wear perfume?",
        "Do you mind if someone is wearing overpowering perfume on the train or in an elevator?",
        "What do you know about the history of perfume?",
        "Are French perfumes the best?",
        "What are the ingredients of perfume?",
        "From what age do you think it’s OK for people to start wearing perfume?",
        "Do you think perfume needs to be so expensive?",
        "Do you know the difference between a cheap and expensive perfume just by the smell?",
        "Do you like browsing around the perfume departments in stores?",
        "Is perfume only for the rich people of the world?",
        "What makes a great perfume advertisement?",
        "Do you think perfume smells better if it is promoted by a pop star or movie star?",
        "If you could choose a new perfume’s name, what would you choose and why?",
        "What's the biggest reason to wear perfume?",
        "If you could make your own perfume, what smells would you like to include?",
        "Do you think a perfume named after your country or city would sell well?"
    ],
    "Personality": [
        "What images spring to mind when you hear the word ‘personality’?",
        "How would you describe your personality?",
        "Are you happy with your personality?",
        "How has your personality changed over the years?",
        "What or who has helped shape your personality?",
        "What of your personality traits do you like most?",
        "Can a person have no personality?",
        "What is the most attractive personality trait a person can have?",
        "Is your true personality always on show or do you hide parts of it?",
        "What are the personality differences between you and other family members?",
        "Do you think you have a strong personality?",
        "What personality types are you attracted to?",
        "Do you know anyone who has a split personality or multiple personalities?",
        "What word would sum up your personality?",
        "Can you really find out things about someone’s personality from their star sign or blood group?",
        "Do you think you have an outgoing personality?",
        "Do you like taking personality tests? Are they accurate?",
        "What major change would you like to make to your personality?",
        "Whose personality do you like best out of all the people in the world?",
        "What do you think of my personality?"
    ],
    "Peru": [
        "What images spring to mind when you hear the country Peru?",
        "What are the good things and bad things about Peru?",
        "What is Peru most famous for?",
        "What do you know about Peruvian history?",
        "What images of Peru do you have that are beautiful and mysterious?",
        "What do you think about Peruvians?",
        "What has Peru given to the world?",
        "Would you like to visit Peru, or live there?",
        "What do you know about the geography of Peru?",
        "Who are the most famous Peruvian people you know?",
        "How different is Peru from other South American countries?",
        "What do you know about Peruvian cultures?",
        "What would you do if you had limitless amounts of money and just one day in Peru?",
        "What do you think Peru will be like 50 years from now?",
        "Does your country have good relations with Peru?",
        "What do you think about Peru’s leaders?",
        "What is your idea of a typical Peruvian?",
        "What things about Peru do you think Peruvians are proud of?",
        "What do you know about Peruvian politics?",
        "What would you like to ask a Peruvian about Peru?"
    ],
    "Pets": [
        "What springs to mind when you hear the word ‘pet’?",
        "Do you like pets?",
        "How many pets have you had?",
        "Is it important for children to have a pet?",
        "Why do people have pets?",
        "Do you think it’s unfair to keep animals in the home – shouldn’t they be in their natural habitat?",
        "Do you know anyone with an unusual pet?",
        "Is it wrong to spend money on pets and pet food when so many people are starving?",
        "Do you like visiting pet shops?",
        "What animal do you think makes the best pet?",
        "Do pets make good gifts?",
        "Do people usually choose good names for their pets in your country?",
        "What do you think of restaurants and stores aimed at pets?",
        "What problems do pets create for people?",
        "Is a spider or a snake really a pet?",
        "Why do some people prefer pets to children?",
        "What do you think of people who dispose of their pets because they are too much trouble?",
        "Do you think pet owners are often similar to their pets?",
        "What do you think of the idea of virtual pets, like Tamagotchi?",
        "Are pets good value for money?"
    ],
    "Philosophy": [
        "What comes to mind when you hear the word ‘philosophy’?",
        "Do you like philosophy?",
        "Do you think philosophy is important?",
        "What’s your philosophy on life?",
        "Would you like to study philosophy?",
        "What’s the difference between Western philosophy and other philosophies?",
        "What can philosophy teach you?",
        "What’s your philosophy on studying English?",
        "Have you ever read any philosophy books?",
        "What is the most basic philosophy that humans should follow?",
        "What exactly is philosophy?",
        "Is philosophy difficult?",
        "Who’s the greatest philosopher you know of?",
        "What’s your philosophy of education?",
        "Do you think modern philosophy is different from ancient philosophy?",
        "Do you get philosophical if you drink alcohol?",
        "Is there a link between philosophy and religion?",
        "What things do you think you’d study in a philosophy course?",
        "Do only intellectual people talk about philosophy?",
        "Would a person living in a rich part of New York, a jungle dweller, and someone living in a shanty town in an overcrowded developing world city share the same philosophy?"
    ],
    "Phobias": [
        "What images spring to mind when you hear the word ‘phobia’?",
        "Do you have any phobias?",
        "How can someone confront and overcome a phobia?",
        "Are all phobias irrational?",
        "How do phobias develop?",
        "Arachibutyrophobia is the fear of peanut butter sticking to your mouth. Do you know of any other crazy phobias?",
        "Do you know anyone who suffers from vertigo – a fear of heights?",
        "What do you think eremophobia - the fear of oneself – is like?",
        "Are people in your country xenophobic (they fear or hate foreigners)?",
        "Can you guess what these phobias are – hydrophobia, zoophobia, sociophobia and numerophobia? What would life be like with these?\n (Answers: fear of water, animals, society and numbers.)",
        "What is a phobia?",
        "What’s the difference between a phobia and a fear?",
        "Gary Larson, a famous cartoonist, invented Anatidaephobia - the fear that somewhere, somehow, a duck is watching you. Can you understand this phobia? Can you invent your own crazy phobia?",
        "Do you know anyone with haemophobia – a fear of blood?",
        "Do you think people are developing new phobias?",
        "What do you think would be the worst phobia to suffer from?",
        "Charlie Brown said: \"I've developed a new philosophy... I only dread one day at a time.\" Do you also do this?",
        "Do you, or anyone you know, suffer from Anglophobia – a fear of English and English people? How would this affect your studying?",
        "Do you think hypnotherapy can cure phobias?",
        "Someone once said: “Get the facts first. Then panic.” Is this good advice?"
    ],
    "Photography": [
        "What comes to mind when you hear the word ‘photography’?",
        "Do you like taking photographs?",
        "Do you prefer digital photography or film photography?",
        "What’s the best photo you’ve ever taken?",
        "What’s the best photo you’ve ever seen?",
        "Do you think photography is an Art?",
        "What kind of photography do you like looking at?",
        "Do you ever go to photography exhibitions?",
        "What do you think of black and white photography?",
        "Has the Internet changed the way you use photographs?",
        "Are you interested in photography?",
        "Would you like a career in photography?",
        "Do you know a lot about photography?",
        "Would you prefer to be a wildlife photographer or a fashion photographer?",
        "What do you think of paparazzi photographers?",
        "What’s the secret to taking a good photograph?",
        "Have you ever been to a photography studio?",
        "Which do you like taking pictures on, your mobile phone or a digital camera?",
        "Do you think a career in photography would be interesting?",
        "What do you know about the history of photography?"
    ],
    "Physics": [
        "What comes to mind when you hear the word ‘physics’?",
        "Is physics important?",
        "Are you interested in physics?",
        "What did you like most and least about physics?",
        "Do all physics professors need messy hair and a beard?",
        "What do you know about the laws of physics?",
        "What do you know about the different branches of physics; e.g. quantum physics, applied physics, nuclear physics, particle physics, etc?",
        "What use is physics in our world?",
        "Will you become rich if you have a physics degree?",
        "Who was the greatest physicist ever?",
        "What is physics?",
        "How is your country at physics?",
        "Would you like to do physics experiments?",
        "What physics formulae do you know? Do you understand them?",
        "What do you know about physics that you could teach a child?",
        "Why do you think people like physics?",
        "What do you know about Nobel Prize winners in physics?",
        "What question would you like to ask a physicist?",
        "The famous physicist Stephen Hawking said: My goal is simple. It is a complete understanding of the universe, why it is as it is and why it exists at all.” What do you think of this?",
        "What is the greatest ever discovery in physics and what will the next one be?"
    ],
    "Pilots": [
        "What comes to mind when you hear the word ‘pilot’?",
        "Would you like to be a pilot?",
        "What do you think the life of a pilot is like?",
        "Do you think pilots like travelling?",
        "Do you think pilots ever worry about making mistakes?",
        "Why do you think people become fighter pilots?",
        "Do you think pilots ever get bored of flying?",
        "Do you have what it takes to be a pilot?",
        "Do you always listen to what the pilot says in the airplane?",
        "Would you feel safer if the pilot of your airplane was male or female?",
        "What do you think of the job of a pilot?",
        "Would you rather be an airplane pilot or a helicopter pilot?",
        "Would you accept a job as a test pilot if the money was really good?",
        "How do you think pilots feel when they walk through airports in their uniforms?",
        "Do you think a pilot is always excited about flying and going to work?",
        "What do pilots do if they switch careers?",
        "If you were a pilot, which airline would you like to fly for and why?",
        "Are you ever on automatic pilot?",
        "What are the pros and cons of being a pilot?",
        "Will we need pilots in the future?"
    ],
    "Plagiarism": [
        "What exactly is plagiarism?",
        "Have you ever copied someone's words without saying whose words they were?",
        "How bad is plagiarism?",
        "How can we prevent plagiarism?",
        "Teachers can easily Google search sentences they thing were copied. Is it foolish to copy?",
        "Is plagiarism just innocent laziness?",
        "Why do some countries think plagiarism is normal?",
        "How would you feel if someone plagiarised your work?",
        "Have you ever cheated in a test?",
        "Someone once said: \"If you steal from one author it's plagiarism; if you steal from many it's research.\" Do you agree?",
        "Is plagiarism against your ethical values?",
        "Is there any time when plagiarism might be OK (e.g. if you have tons of homework and no time to do it)?",
        "Do you think it's difficult to know what is plagiarism and what isn't?",
        "Do you think schools are universities are too strict when they expel students for plagiarism?",
        "Can you plagiarize yourself?",
        "Has cut and paste decreased creativity and original thought?",
        "How would you feel in front of your teachers or colleagues if you were caught plagiarising?",
        "Do you think plagiarism will be a bigger problem in the future?",
        "Should all teachers put their students' homework, writing, essays, etc. through plagiarism software?",
        "Someone one said: \"Originality is undetected plagiarism.\" What does this mean, and do you agree?"
    ],
    "Planets": [
        "What comes to mind when you hear the word ‘planets’?",
        "Are you interested in the planets?",
        "What do you think of the planet names?",
        "What do you think is the most mysterious planet?",
        "Do you think there’s life on other planets?",
        "Would you like to visit another planet?",
        "Do you think we should look for life on other planets?",
        "How are all the planets different?",
        "What do the names of the planets mean?",
        "Would you like to see our planet from space?",
        "What are planets?",
        "How are planets formed?",
        "Why doesn’t life exist on other planets in our solar system?",
        "What do you think of the idea of moving to another planet after we’re finished with Earth?",
        "Do you know anyone who’s from another planet?",
        "Do you think it will be possible one day to go to planets in other solar systems?",
        "Do you think there’ll ever be a war between planets – Star Wars?",
        "What fictional planets do you know of from books and movies?",
        "Do you think our planet will survive?",
        "Do you think Earth is a good name for our planet? Is it the same in your language?"
    ],
    "Plastic": [
        "What images spring to mind when you hear the word ‘plastic’?",
        "How important is plastic?",
        "Do you know how plastic is made?",
        "What would the world be like without plastic?",
        "What would your home be like without plastic?",
        "What are the downsides to plastic?",
        "Do you thing the word ‘plastic’ is a good or bad word?",
        "Do you think we’ll find an environmentally friendly alternative to plastic?",
        "What is plastic surgery? Would you like to try it?",
        "How useful are plastic containers?",
        "What is plastic?",
        "What do you know about the history of plastic?",
        "What do you think of plastic shopping bags?",
        "What’s your favourite thing made out of plastic?",
        "Is plastic a good word to use to describe our world?",
        "In English, we sometimes describe someone as being ‘plastic’. What do you think this means?",
        "What do you think of the idea of plastic food that tastes like the real think and is nutritious?",
        "Do you prefer to use cash or plastic (credit cards)?",
        "What will be made of plastic in the future that isn’t made of plastic now?",
        "What do you think of plastic knives and forks on airplanes?"
    ],
    "Playtime": [
        "What springs to mind when you hear the term ‘play time’?",
        "What do you learn from playing ?",
        "Do you prefer playing alone, or with / against friends?",
        "What is it about playing that makes people happy?",
        "Do people play enough in your country?",
        "How can play help you relax?",
        "Do you like to watch people playing?",
        "What's the difference between play and fun?",
        "Should schools have more playtime in the schedule?",
        "What would you say if your parents told you to go out and play?",
        "Have you ever played in the rain?",
        "When is playing a waste of time?",
        "Does play time use to much energy?",
        "Can you remember the first games you played?",
        "What will playtime be like in the future?",
        "Is playing good for your health?",
        "“You can discover more about a person in an hour of play than in a year of conversation.”  ― Plato.  What do you think of this?",
        "is climbing a tree playing?",
        "How can you learn English through playing?",
        "Have young people forgotten or don't know how to play?"
    ],
    "Poetry": [
        "What comes to mind when you hear the word ‘poetry’?",
        "Do you like reading and listening to poetry?",
        "How do you think poetry first started?",
        "How is poetry different to other literary styles?",
        "What role does poetry play in your culture?",
        "What did you think of poetry when you studied it at school?",
        "\"Poetry is a mirror which makes beautiful that which is distorted.\" ~ Percy Shelley. What do you think of Shelley’s quote?",
        "Do you think you’re good at writing poetry?",
        "The poet Robert Frost said: \"A poem begins in delight and ends in wisdom.\" Do you agree with him?",
        "Do you have a favourite poem?",
        "What is poetry?",
        "\"Poetry is a deal of joy and pain and wonder, with a dash of the dictionary.\" ~ Kahlil Gibran. What do you think of this quote?",
        "Is poetry important?",
        "Do you think poetry is too much like hard work?",
        "What can poetry teach us about life?",
        "What do you think of the poetry from other countries and cultures?",
        "Would you like someone to write you a poem?",
        "\"Genuine poetry can communicate before it is understood.\" ~ T. S. Eliot. What do you think of Eliot’s words?",
        "If you were to write a poem right now, what would your subject be?",
        "Do you have a favourite poet?"
    ],
    "Poland": [
        "What images spring to mind when you hear the country Poland?",
        "What are the good things and bad things about Poland?",
        "What is Poland most famous for?",
        "What do you know about Polish history?",
        "What do you know about Poland under communism?",
        "What do you think about Poles?",
        "What has Poland given to the world?",
        "Would you like to visit Poland, or live there?",
        "What do you know about the geography of Poland?",
        "Who are the most famous Poles you know?",
        "How different is Poland from other European countries?",
        "What do you know about Polish food?",
        "What would you do if you had limitless amounts of money and just one day in Poland?",
        "What do you think Poland will be like 50 years from now?",
        "Does your country have good relations with Poland?",
        "What do you think about Poland’s leaders?",
        "What is your idea of a typical Polish person?",
        "What things about Poland do you think Poles are proud of?",
        "What do you know about Polish politics?",
        "What would you like to ask a Pole about Poland?"
    ],
    "Police": [
        "What images spring to mind when you hear the word ‘police’?",
        "Do you respect the police?",
        "Are the police in your country good or bad?",
        "What experiences have you had with the police?",
        "Would you ever consider a career with the police?",
        "What would society be like without the police?",
        "Is there a good alternative to a police force?",
        "What changes would you like to make to your country’s police force?",
        "Have you ever called the police?",
        "Do you ever worry about your country becoming a police state?",
        "What should a good police force do?",
        "Would you like your son or daughter to become a police officer?",
        "Do you like the police uniform?",
        "Do you think being in the police would be exciting and interesting?",
        "Do you like TV dramas and documentaries about the police?",
        "What is the most realistic police movie you’ve ever seen?",
        "What do you think a police officer thinks about when he or she is on the beat, walking around town?",
        "Are the police in your country effective at solving crimes and protecting the community?",
        "Do you think your government needs to spend money on employing more police officers?",
        "What questions would you like to ask a police officer?"
    ],
    "Politics": [
        "What comes to mind when you hear the word ‘politics’?",
        "Would you like to work in politics?",
        "Is politics important to you?",
        "Do politics really matter?",
        "Should religion and politics mix?",
        "Is the word ‘politics’ a singular or plural noun?",
        "Do office politics exist where you work?",
        "Is a week a long time in politics?",
        "Do you read about the political issues of your country?",
        "Are there any political hot potatoes in your country?",
        "What do you think of politics?",
        "What is the biggest political issue in your country right now?",
        "What do you think of your country’s political system?",
        "What do you think of your country’s politicians?",
        "Is there a relationship between politics and lies?",
        "At a guess, what percentage of politicians are corrupt?",
        "What local political issues are important in your town?",
        "Do you like talking about and having arguments about politics?",
        "If you were a politician, what political issues would you focus on?",
        "What qualities make a good political leader?"
    ],
    "Pollution": [
        "What comes to mind when you hear the word ‘pollution’?",
        "What different forms of pollution do you know of?",
        "How bad is pollution in your town?",
        "What do you do every day that adds to pollution?",
        "What do you do every day that helps to reduce pollution?",
        "Is there a lot of pollution in your country?",
        "What do you think of people who buy big, gas-guzzling 4WDs when they don’t really need them?",
        "How does pollution affect our health?",
        "Do you think pollution will be a bigger issue in fifty years than it is now?",
        "The former US president Ronald Reagan once said: \"Cars don't cause pollution, trees do.\" Do you think US presidents understand a little more about pollution now?",
        "What is pollution?",
        "What harm does pollution do to the environment?",
        "What do you get most angry about when you think about pollution?",
        "Do you think the Kyoto Protocol and international meetings help reduce pollution?",
        "Which bothers you more, noise pollution from traffic or environmental pollution from traffic?",
        "What do you know about air, marine and river pollution?",
        "What are the worst pollutants and who are the worst polluters?",
        "What simple, everyday thing could help reduce pollution most?",
        "What do you think about noise pollution?",
        "The famous marine biologist Jacques Cousteau said: \"Water and air…have become global garbage cans.\" What do you think of his words?"
    ],
    "Population": [
        "What comes to mind when you hear the word ‘population’?",
        "How would you describe the population of your country?",
        "How has your country’s population changed over the years?",
        "The physicist Stephen Hawking said that if world population continues growing at its current rate, then “by 2600 we would all be standing literally shoulder to shoulder”. Will this happen?",
        "Is population growth a concern in your country?",
        "What would happen in the world if there was a population explosion?",
        "Is the population of your cities growing? How is this affecting the countryside?",
        "Do you like looking at population surveys and statistics?",
        "What do you think rural populations think about the pollution and mess cities are creating?",
        "Is your society moving towards an ageing population? Is this a problem?",
        "Is there any population control in your country?",
        "What kind of ethnic and immigrant populations live in your town?",
        "Ex World Bank President Robert McNamara said: \"Population growth is the gravest issue the world faces. If we do not act, the problem will be solved by famine, riots, insurrection and war.\" Do you agree?",
        "Do you think a diverse population is good for your country?",
        "What is a population crisis?",
        "What factors influence changing population patterns?",
        "Is contraception a good way to reduce population?",
        "What do you think of ‘one child per family’ policies to curb population growth?",
        "What will your country’s population look like in 50 years from now?",
        "What do you think of the idea of an international population tax?"
    ],
    "Pornography": [
        "What comes to mind when you hear the word ‘pornography’?",
        "Who reads and watches pornography and why?",
        "Is pornography more for men or women?",
        "When is a photo of a nude body art and when does it become pornography?",
        "What are your thoughts on pornography?",
        "Have you ever been embarrassed by someone reading a pornographic magazine next to you on the train or bus?",
        "Are the semi-nude photos found in tabloid newspapers considered pornography?",
        "What would you tell your children about pornography if they asked?",
        "What would you think if your partner bought a pornographic magazine or video?",
        "Is there a difference between looking at a pornographic video and looking at a pornographic magazine?",
        "What is pornography?",
        "Should pornography be banned?",
        "Why are pornographic magazines and videos called ‘dirty’ and pornographic movies called ‘blue movies’?",
        "How is pornography viewed in your country? Are there laws on it?",
        "How has the Internet changed pornography?",
        "Would you work in the pornography industry (management, sales, etc) if the money was really good?",
        "If a married person looks at pornography, is it a form of cheating?",
        "Would you date a retired pornography model?",
        "Will pornography ever disappear?",
        "Are people sick if they are addicted to pornography?"
    ],
    "Postal Service": [
        "What do you think of the postal service in your country?",
        "Do you think it’s better for postal services to be in private or government hands?",
        "How has the Internet changed the postal service?",
        "How often do you get real letters – those that are in envelopes and delivered to your door by the postal service?",
        "Do you think sending a letter is cheap or expensive?",
        "Do you send virtual birthday cards or real ones? Why?",
        "Do you think post offices are friendly, efficient places?",
        "What do you think of the job of a postman / mailman / postwoman / mailwoman?",
        "How has the post office survived e-mail?",
        "What postal services do you use most?",
        "Do you think postal services will disappear soon?",
        "Would you like to work for the postal service of your country?",
        "How important is the postal service in your country?",
        "How different was the postal service in your country 20 years ago?",
        "Why is it a zip code in the USA and a post code in other countries?",
        "Do postal workers in your country ever go on strike? Do you think they should?",
        "What are the advantages and disadvantages of opening a savings account with the post office?",
        "Have you ever sent or failed to receive a letter that got lost in the post?",
        "Do you get excited if you see the mail delivery person at your door?",
        "What impresses you most about the postal service?"
    ],
    "Potatoes": [
        "Do you like potatoes?",
        "How important are potatoes?",
        "What do you know about the nutritional value of potatoes?",
        "How do potatoes compare to other staple foods like rice, pasta and bread?",
        "What different ways are there to cook potatoes?",
        "How would fast food chains and British cultural cuisine survive without potatoes?",
        "Do you prefer baked, roast, boiled, mashed or jacket potatoes?",
        "How do you make a potato salad?",
        "What do you know about how potatoes grow?",
        "Are you a meat and potatoes person?",
        "What springs to mind when you hear the word ‘potato’?",
        "What is your favourite potato dish?",
        "How would life be different if potatoes disappeared from the world?",
        "Have you ever eaten instant potatoes?",
        "What else can you use potatoes for besides eating them?",
        "Do potatoes ever get boring?",
        "What’s the strangest potato dish you know of?",
        "Do you think potatoes are good value for money?",
        "What kind of potato chips do you like best?",
        "What part do potatoes play in your culture?"
    ],
    "Poverty": [
        "What is poverty?",
        "Why do so many people live below the poverty line?",
        "What kind of poverty exists in your country?",
        "What do you think living below the poverty line is like?",
        "Is it possible for the world to make poverty disappear?",
        "What do you think of people who buy expensive brands when so much poverty exists in the world?",
        "Aristotle said: \"Poverty is the parent of revolution and crime.\" What do you think?",
        "Why does poverty exist in rich countries like the USA?",
        "What do you think of the “Make Poverty History” campaign?",
        "In 1964, Lyndon B. Johnson announced: \"For the first time in our history it is possible to conquer poverty.\" What went wrong?",
        "What springs to mind when you hear the word ‘poverty’?",
        "Is poverty different in rich countries than in poor ones?",
        "Do you do anything to help reduce poverty?",
        "Bernard Shaw said: \"The greatest of evils and the worst of crimes is poverty.\" Do you agree with this?",
        "How would the world be different if there was no poverty?",
        "What are the causes of poverty?",
        "What do you think a poverty trap is and is it easy for people to escape it?",
        "What is more important to win, the war on terror or the war on poverty? Are governments spending on the right war?",
        "Do you think there’d be no wars if there was no poverty?",
        "Eli Khamarov said: \"Poverty is like punishment for a crime you didn't commit. And one never really forgets either — everything serves as a constant reminder of it.\" How far is this true today?"
    ],
    "Power": [
        "What springs to mind when you hear the word ‘power’?",
        "Do you have power?",
        "Is power a good or bad thing?",
        "Does your country have a lot of power?",
        "Mao Zedong said: \"Political power grows out of the barrel of a gun.\" Do you agree with him?",
        "Lord Acton said: “Power tends to corrupt, absolute power corrupts absolutely.” Do you agree with this?",
        "People in today’s Internet age say knowledge is power. Do you feel more powerful?",
        "If you had lots of power, what would you do with it?",
        "Which is the world’s most dangerous power?",
        "Have you ever played power games with a friend, colleague or family member?",
        "What would you like the power to be able to do?",
        "Do politicians in your country abuse their political power?",
        "When was the last time there was a power struggle in your country?",
        "To what degree do you think money is power?",
        "How much economic power does your country have in your region and in the world?",
        "What do you think of colonial power?",
        "What do corrupt leaders do to hold on to their power?",
        "Do you believe in the power of prayer?",
        "What would the world be like if everyone had the same power?",
        "What do you think of the power of nature?"
    ],
    "Prayer": [
        "What springs to mind when you hear the word ‘prayer’?",
        "What do you pray for?",
        "Are your prayers always answered?",
        "Do you feel different after you pray?",
        "Is it possible to pray for something bad?",
        "Is it selfish to pray for something for yourself?",
        "Do you think prayer time should be a part of school life?",
        "Do you think something has gone wrong if a prayer is unanswered?",
        "Do you believe in the healing power of prayer?",
        "Is it important to say a prayer before and after meals?",
        "How often do you pray?",
        "What’s your favourite prayer?",
        "Where is the best place to pray?",
        "Can you take lessons on how to pray better?",
        "What do you think all people should pray for?",
        "How can you prove to someone who doesn’t believe in prayer that it works?",
        "Do you think people who pray have better lives?",
        "What do you think of prayer groups?",
        "If you could have one prayer answered, what would it be?",
        "Do you think the prayers you make up are better than the prayers found in holy books?"
    ],
    "Pregnancy": [
        "What images spring to mind when you hear the word ‘pregnancy’?",
        "Do you think advances in science will mean men can become pregnant in the future?",
        "What are the dangers of pregnancy?",
        "What’s the first sign of pregnancy?",
        "What’s a phantom pregnancy and why does this phenomena happen?",
        "Would you trust a home pregnancy test?",
        "Should a woman change her lifestyle during her pregnancy?",
        "Is there any kind of pregnancy celebration in your culture?",
        "What should children be taught about conception and pregnancy?",
        "Is unwanted pregnancy a problem in your country?",
        "What do you know about pregnancy?",
        "Are teenage pregnancies a problem in your country?",
        "What do you think of mothers who drink alcohol during their pregnancy?",
        "Why is pregnancy so dangerous in many countries in the world?",
        "What duties and roles does the father have during a mother’s pregnancy?",
        "How scary is pregnancy compared with other events in life?",
        "What complications can occur during pregnancy?",
        "How does a woman’s diet change during pregnancy? Does she eat strange food at midnight in your country",
        "What are the different stages of the baby during pregnancy?",
        "What would you like to know about pregnancy that you don’t know?"
    ],
    "Prejudice": [
        "What images spring to mind when you hear the word ‘prejudice’?",
        "What kinds of prejudice exist in your country?",
        "Why does prejudice occur?",
        "What does your government do to fight prejudice?",
        "Christian Bovee said: “The great obstacle to progress is prejudice.” What do you think of this?",
        "What is the answer to prejudice?",
        "What’s the worst form of prejudice you know of?",
        "Have you ever suffered because of prejudice?",
        "What would you do if prejudice was directed against you?",
        "Would you act if you saw cases of prejudice?",
        "What is prejudice?",
        "What makes someone prejudiced?",
        "Goldini said: “He who never leaves his country is full of prejudices.” Do you agree with this?",
        "Are men or women more likely to be prejudiced?",
        "Do you know any people who have prejudices?",
        "Do you think everyone in the world has prejudices?",
        "Do you think prejudices would exist if sight didn’t?",
        "Should ways to reduce prejudices be taught in schools?",
        "Do you think your county’s leader is prejudiced?",
        "Will the world be free of prejudices one day?"
    ],
    "Presentations": [
        "What do you think when you hear the word ‘presentation’?",
        "Do you like making presentations? Why / Why not?",
        "What’s the best presentation you have ever heard?",
        "How can you stop being nervous about a presentation?",
        "What do you think of PowerPoint? Are you good at using it?",
        "Is it better to give a presentation to five people or thirty? Why?",
        "Do you like listening to presentations?",
        "What kind of slides are best – those with pictures or those with words?",
        "Whose presentation would you like to see (anyone in the world)?  Why?",
        "Do you think giving presentations makes you more confident?",
        "How do you feel one minute before you have to make a presentation?",
        "Will your next presentation be good? Why do you think so?",
        "What is the most difficult thing about making a presentation?",
        "What advice would you give to people making a presentation?",
        "How many slides should a good presentation have? Why?",
        "How scary is making a presentation? Why?",
        "Do you like people looking at you when you make a presentation?",
        "How rude is it to talk during presentations?",
        "What do you think when people talk during your presentation?",
        "How do you feel when your presentation is over? Why?"
    ],
    "Prices": [
        "What comes to mind when you hear the word ‘prices’?",
        "Do you care about prices?",
        "What are prices like in your country?",
        "How do prices compare now to ten years ago?",
        "What prices do you care about most?",
        "Do you understand why oil prices go up and down?",
        "How are prices in your country compared with those in other countries?",
        "Is there a big variety in prices in the different food stores in your town?",
        "Are low prices always good?",
        "What can governments do to stop prices rising?",
        "Do you look at and remember the price of goods when you are shopping?",
        "What do you think of real estate prices?",
        "When did you first start thinking and worrying about prices?",
        "Why do prices vary so much from store to store when you buy things like electronics?",
        "What happens when prices go up at a faster rate than salaries?",
        "Do you think Internet prices of goods should be cheaper than retail prices in stores?",
        "What do you think prices for everyday things will be like twenty years from now?",
        "What prices will decrease over the next few years?",
        "Do you keep an eye on share prices?",
        "What do you think when you see an advert that says “Unbeatable Prices”?"
    ],
    "Pride": [
        "What comes to mind when you hear the word ‘pride’?",
        "Are you a proud person?",
        "What achievement are you most proud of?",
        "Who are you most proud of?",
        "What do you take great pride in doing?",
        "When was the last time you were very proud of yourself?",
        "Do you think you were always a source of great pride for your parents?",
        "Do you think carefully about your actions to maintain your family pride?",
        "What do you do to restore your pride after it has been wounded?",
        "Fulton Sheen said: “Pride is an admission of weakness; it secretly fears all competition and dreads all rivals.” Do you agree?",
        "What is pride?",
        "Are you proud of your country?",
        "Do you feel more pride in yourself or in others?",
        "Are you proud of your heritage?",
        "When can pride be dangerous?",
        "Is pride in yourself a sin?",
        "Which of your characteristics are you most proud of?",
        "Does your pride ever stop you from asking others for help?",
        "Have you ever had to swallow your pride?",
        "John Ruskin said: “Pride is at the bottom of all great mistakes.” Do you agree with him?"
    ],
    "Privacy": [
        "What comes to mind when you hear the word ‘privacy’?",
        "How much do you value your privacy?",
        "How often do people invade your privacy?",
        "What do you know about privacy laws in your country?",
        "Is mental health more important than physical health?",
        "What do you do for some privacy in a crowded place?",
        "Do you feel totally safe and happy in the privacy of your own home?",
        "Do you ever feel that questions asked on websites represent an invasion of privacy?",
        "What’s the longest amount of time you felt you had total privacy somewhere?",
        "Would you like to take karate lessons?",
        "What is privacy?",
        "What do you do to get privacy?",
        "Do you always respect the privacy of others?",
        "Do you think famous people worry about their privacy?",
        "Is it OK for the government or police to ignore your privacy?",
        "Is privacy important when choosing somewhere to go on holiday?",
        "Do newspapers and the paparazzi need to look again at what privacy means?",
        "Do parents invade their kids’ privacy by spying and eavesdropping on them?",
        "Do you think there are issues with privacy and social networking sites like MySpace and Facebook?",
        "What would life be like with no privacy?"
    ],
    "Pronunciation": [
        "What springs to mind when you hear the word ‘pronunciation’?",
        "Are you happy with your pronunciation?",
        "What do you do to improve your pronunciation?",
        "Do you like studying pronunciation in class?",
        "Do you prefer British or American pronunciation?",
        "What problems do you have with pronunciation?",
        "Is pronunciation very important to you?",
        "What’s the biggest communication problem you’ve had because of pronunciation?",
        "What areas of pronunciation are you working on at the moment?",
        "Do you think pronunciation is easy?",
        "What is pronunciation?",
        "What pronunciation problems do learners of your language have?",
        "What are the differences between stress and intonation? Is one more important to you?",
        "Can you easily pronounce all of the sounds in English?",
        "Do you have problems with linking different sounds?",
        "Do you have more problems with hearing English pronunciation or using it in your own speech?",
        "What’s the best pronunciation you’ve ever had?",
        "Do people ever tell you your pronunciation is good?",
        "Do you know any good websites to practice pronunciation?",
        "What advice would you give to other students who want to improve their pronunciation?"
    ],
    "Pronunciation Activities": [
        "What comes to mind when you hear the term ‘pronunciation activity’?",
        "What do you think when your teacher says you’re going to do some pronunciation?",
        "What kind of pronunciation practice do you like most and least?",
        "Do you like the pronunciation activities your teacher gives you?",
        "Do you have an example of how a pronunciation activity really improved your pronunciation?",
        "Do you know of any websites that have good pronunciation activities?",
        "Is learning pronunciation in class ever interesting and fun? Should it be?",
        "Do you always understand the reasons why the teacher asks you to do a particular pronunciation activity?",
        "What are your biggest problems with pronunciation?",
        "How important is pronunciation compared with spelling, vocabulary, punctuation, etc?",
        "Do you like doing pronunciation activities in class?",
        "Do you ever think pronunciation activities are a waste of time?",
        "What pronunciation learning strategies do you use a lot?",
        "Is having charts and diagrams of the mouth important when you do a pronunciation activity?",
        "What things are important for a pronunciation activity to be successful?",
        "What advice would you give to a student who says he/she is no good at pronunciation or hates pronunciation?",
        "What do you like most and least about pronunciation in English?",
        "What are your biggest pronunciation problems in English?",
        "Do you think you need pronunciation practice in every class?",
        "What questions would you like to ask your teacher about pronunciation?"
    ],
    "Property": [
        "What images spring to mind when you hear the word ‘property’?",
        "Are you interested in property?",
        "Do you think property is always a good investment?",
        "Is buying property risky?",
        "Would you prefer to rent or buy your own property?",
        "Would you consider buying property overseas?",
        "Would you like a job selling property?",
        "Where’s the best place to buy property in your country?",
        "What do you know about the property market?",
        "Are property values going up or down in your country? What causes these changes?",
        "Do you think property developers are good for the environment?",
        "Why do poor people always lose out to property developers?",
        "Which do you think offers the best investment, commercial property or residential property?",
        "Who gets the property in a divorce?",
        "What do you think of the property taxes in your country?",
        "What does a property management company do?",
        "What is intellectual property and how important is it?",
        "What things about Mexico do you think Mexican people are proud of?",
        "What do you know about private property laws in your country?",
        "What do you know about property booms and slumps in your country?"
    ],
    "Prostitution": [
        "What springs to mind when you hear the word ‘prostitution’?",
        "What is the status of prostitution in your country?",
        "What’s your attitude towards prostitution?",
        "Do you think prostitution is really the world’s oldest profession? Can it be regarded as a profession?",
        "Should prostitution be legal?",
        "Should there be different laws concerning male prostitution and female prostitution?",
        "What do you think about making prostitution a criminal offence?",
        "What are the dangers to society of prostitution?",
        "What are the dangers to prostitutes of not legalizing prostitution?",
        "Why do people become prostitutes (high class or otherwise)?",
        "What protection or safeguards should governments have in place to protect prostitutes?",
        "If prostitution has been around for thousands of years, how can governments stop it?",
        "What should the world do to stamp out child prostitution?",
        "What should governments do to stop human smuggling and prostitution rings?",
        "Is prostitution a matter of personal choice and not for governments to make decisions on?",
        "Are there any benefits to society of prostitution?",
        "If you were down on your luck, could you turn to prostitution?",
        "Are there areas in your town where prostitutes work?",
        "Why do so many politicians and movie stars get involved in prostitution scandals?",
        "Do you think people will still be asking these same questions about prostitution in 100 years from now?"
    ],
    "Protests": [
        "What do you think about when you hear the word \"protests\"?",
        "Is it good or bad to protest?",
        "What protests are happening around the world right now? Do you agree with them?",
        "How should police deal with protestors?",
        "How have protests changed the history of different countries?",
        "Why do governments protestors?",
        "What things do you need to take on a protest?",
        "How many different things can you do to protest?",
        "Is there a better way than protesting to make your voice heard?",
        "Can a protest by one person be as powerful as a protest by a million?",
        "What would you protest about?",
        "What would your parents think if they saw you on TV news protesting?",
        "Are protestors heroes?",
        "How do things like Twitter and Facebook help protests?",
        "What are the dangers in protesting?",
        "What are the dangers in not protesting?",
        "Do you think governments worry about protests?",
        "What do police officers think about when they are policing a protest?",
        "Is a protest better online or on the streets?",
        "What are the biggest protests in (recent) history?"
    ],
    "Psychology": [
        "What springs to mind when you hear the word ‘psychology’?",
        "What do you know about psychology?",
        "Would you like to study psychology?",
        "What would a psychologist say about you?",
        "Would you like to visit a psychologist?",
        "What do you know about child psychology?",
        "Do you like doing psychology tests?",
        "If you were a scientist, what psychology tests would you like to do?",
        "Would you ever get nervous talking to a psychology expert?",
        "What is reverse psychology?",
        "What is psychology?",
        "What’s the psychology behind addiction?",
        "Which great psychologists do you know of and what did they say?",
        "Would you ever buy a self-help psychology book?",
        "What do you know about forensic psychology?",
        "Do you think you can get a good job with a psychology degree?",
        "Do you think scientists will ever be able to examine the brain and rewrite what we know about psychology?",
        "Who would you really like to understand the psychology of?",
        "What good do you think colour psychology is in this world?",
        "What would you like to know about psychology?"
    ],
    "Public Relations": [
        "What comes to mind when you hear the term ‘public relations’?",
        "What do you think of public relations?",
        "What is the function of public relations?",
        "Would you like to work in public relations?",
        "Do you think public relations is really just modern propaganda?",
        "Why is government public relations called ‘spin’? What do you think of spin?",
        "Do public relations officers get paid to lie?",
        "Have you ever been angry with a company’s (or government’s) attempts at public relations?",
        "Why do companies need a whole public relations department?",
        "What companies do you think have the busiest public relations departments?",
        "What do you know about public relations?",
        "What do you think people study on a public relations course?",
        "Do you think you’d be a good public relations person?",
        "Which world leaders really need a good public relations team?",
        "Is public relations the same as image management?",
        "What do you think of the PR surrounding the war on terror?",
        "A management expert said public relations is relationship management, and is at the core of an organization’s development. What do you think?",
        "Which of these PR techniques are best: press releases, podcasts, Internet ads, televised events, use of celebrities, press conferences?",
        "What’s the difference between public relations and advertising?",
        "How has the Internet changed public relations?"
    ],
    "Pubs, Clubs and Bars": [
        "What comes to mind when you hear the words ‘pubs, clubs and bars’?",
        "Which do you prefer, pubs, clubs or bars?",
        "Are pubs, clubs and bars important to you?",
        "When was the first time you went to a pub, club or bar?",
        "What’s your favourite pun / club / bar and why?",
        "What do you dislike about pubs, clubs and bars?",
        "Do you think there should be more pubs, clubs and bars in your area?",
        "What do you think the opening and closing times of pubs, clubs and bars should be?",
        "Should there be an age limit for pubs, clubs and bars?",
        "What are the alternatives to pubs, clubs and bars?",
        "What’s the difference between a pub, a club and a bar?",
        "What do you think of the names given to pubs, clubs and bars?",
        "What changes would you like to see in pubs, clubs and bars?",
        "What do you think of pub grub (pub food)?",
        "Do you like watching live music in pubs, clubs and bars?",
        "Do you think smoking should be banned in pubs, clubs and bars?",
        "Would you ever go to a pub / club / bar alone to drink?",
        "Are pubs, clubs and bars bad for society?",
        "Are pubs, clubs and bars god places to meet future partners?",
        "If you opened your own pub / club / bar, what would you call it?"
    ],
    "Punishment": [
        "What images spring to mind when you hear the word ‘punishment’?",
        "What were you punished for as a child?",
        "What do you think of capital punishment?",
        "Do you think punishment is a good way to teach people a lesson?",
        "How were you punished as a child?",
        "What is the worse way to punish a child?",
        "Are fines \"soft\" punishments?",
        "How do or would you punish your children?",
        "Which countries to you think have the harshest punishments?",
        "Do people need to be punished? Why?",
        "In what ways is working a form of punishment?",
        "How does you're country punish minors?",
        "Should politicians be punished if they break their promises?",
        "What do you think corporal punishment is? Is it OK?",
        "Is exercise a form of punishment?",
        "Do you ever punish yourself? What for?",
        "Do you like to punish people?",
        "Have you ever threatened your children with punishment?",
        "Do you agree with letting people off from punishment?",
        "What could we do instead of punishing people?"
    ],
    "Pyramids": [
        "What images spring to mind when you hear the word ‘Pyramids’?",
        "How were the Pyramids built?",
        "What do you think of the idea of building a giant pyramid for a king who died?",
        "Do you think the Pyramids were built with alien technology?",
        "Do you think the Pyramids are the most important architectural sites in the world?",
        "Would you rather see the Taj Mahal or the Pyramids?",
        "What would you do if you could spend a whole day at the Pyramids?",
        "How do you think the Pyramids have survived for thousands of years?",
        "What do you think conditions were like for builders building the Pyramids?",
        "What would you think if a McDonalds opened inside one of the Pyramids?",
        "What do you know about the Pyramids in Egypt?",
        "Why were the Pyramids built?",
        "Why do you think the Pyramids were built in the shape of pyramids?",
        "What do you know about other pyramids around the world?",
        "What would you think if Egypt sold the Pyramids to a rich country, which relocated them?",
        "Do you think the Pyramids will be covered in advertising one day?",
        "Would you like to spend a night alone inside one of the Pyramids?",
        "Does a real pyramid have three or four sides?",
        "Would you like to be an archaeologist working at the Pyramids?",
        "What do you think Egyptians feel about their Pyramids?"
    ]
}
