export default {
    "UFOs": [
        "What springs to mind when you hear the abbreviation “UFO’?",
        "What do the letters UFO stand for?",
        "After a UFO has been identified, is it then an IFO?",
        "Do you think UFOs exist, out there, somewhere?",
        "What would you do if a UFO landed in a park near your house?",
        "What do you think UFOs look like? Are they the flying saucers you see in movies?",
        "What would the world do if it knew a UFO would arrive on Earth in the middle of next month?",
        "What’s your favourite movie or book about UFOs?",
        "What do you think is inside a UFO?",
        "Do you hope there are UFOs and they will visit Earth one day?",
        "Have you ever seen a UFO?",
        "What are your early memories of UFOs? Were you scared?",
        "Do you think UFOs would come to Earth to attack us, make friends with us, to get some natural resources, or another reason?",
        "Why are people so fascinated by UFOs?",
        "Do you think governments should spend lots more money looking for signs of UFOs in the universe?",
        "What do you think when people report UFO sightings?",
        "Do you have any good UFO stories?",
        "Do you think it’s possible there are UFOs and the world’s governments are keeping it a secret?",
        "Would you accept an offer from aliens of a ride in their UFO?",
        "How would our world change if we received regular visits from UFOs?"
    ],
    "Uganda": [
        "What images spring to mind when you hear the country Uganda?",
        "What are the good things and bad things about Uganda?",
        "What is Uganda most famous for?",
        "What do you know about Uganda’s history?",
        "What are the differences between Uganda and your country?",
        "What do you think about Ugandan people?",
        "What has Uganda given to the world?",
        "Would you like to visit Uganda, or live there?",
        "What do you know about the geography of Uganda?",
        "Who are the most famous Ugandan people you know?",
        "How different is Uganda from other African countries?",
        "What was the last news story you heard about Uganda?",
        "What do you think Uganda’s neighbours think of it?",
        "What do you think Uganda will be like 50 years from now?",
        "Does your country have good relations with Uganda?",
        "What could you do on a holiday in Uganda?",
        "What is your idea of a typical Ugandan person?",
        "What things about Uganda do you think Ugandans are proud of?",
        "What do you know about Ugandan culture?",
        "What would you like to ask a Ugandan person about Uganda?"
    ],
    "United Arab Emirates": [
        "What images spring to mind when you hear the country UAE?",
        "What are the good things and bad things about the UAE?",
        "What is the UAE most famous for?",
        "What do you know about the UAE’s history?",
        "What are the differences between the UAE and your country?",
        "What do you think about Emirati people?",
        "What has the UAE given to the world?",
        "Would you like to visit the UAE, or live there?",
        "What do you know about the geography of the UAE?",
        "Who are the most famous Emirati people you know?",
        "How different is the UAE from other Middle East countries?",
        "What was the last news story you heard about the UAE?",
        "What do you think the UAE’s neighbours think of it?",
        "What do you think the UAE will be like 50 years from now?",
        "Does your country have good relations with the UAE?",
        "What could you do on a holiday in the UAE?",
        "What is your idea of a typical Emirati person?",
        "What things about the UAE do you think Emiratis are proud of?",
        "What do you know about Emirati culture?",
        "What would you like to ask an Emirati about the UAE?"
    ],
    "United Kingdom": [
        "What do you think of the name \"the United Kingdom\"?",
        "What is the difference between Great Britain, England and the United Kingdom?",
        "What do you know about the food and weather in the UK?",
        "What would you like to do and see in the UK on a three-week holiday?",
        "How do you think people from the UK would describe their kingdom?",
        "Why do the 4 countries compete as Great Britain at the Olympics and not as the United Kingdom",
        "Which UK country is best?",
        "What parts of UK culture are popular in your country?",
        "Does your country have good relations with the United Kingdom?",
        "What do you think of when you see the Union Jack flag?",
        "What do you know about the United Kingdom?",
        "How important is the United Kingdom in the world?",
        "How did the United Kingdom become united?",
        "What has the United Kingdom contributed to the world?",
        "Is the UK still a kingdom, even with a queen? Shouldn't it be a \"queendom\"?",
        "Which part of the UK is most important?",
        "What is the United Kingdom most famous for?",
        "What mistakes has the United Kingdom made?",
        "Would the United Kingdom be better splitting up?",
        "What do you think the UK will be like in 50 years from now?"
    ],
    "United Nations": [
        "What comes to mind when you hear the words ‘United Nations’?",
        "Are the nations united?",
        "Does the United Nations work?",
        "Does your country respect the United Nations and follow all of its decisions and resolutions?",
        "What should happen to countries that ignore UN decisions and resolutions?",
        "What is the alternative to the United Nations?",
        "What are the good things and bad things about the United Nations?",
        "What makes you angry about the United Nations?",
        "How has the United Nations changed the world?",
        "Former General Secretary Kofi Annan said: \"More than ever before in human history, we share a common destiny. We can master it only if we face it together. And that, my friends, is why we have the United Nations.\" Do you think all nations will master this common destiny?",
        "How has the United Nations changed the world?",
        "Do the big nations have too much power in the United Nations?",
        "Would you like to work for the United Nations?",
        "Is the Secretary General of the United Nations the world’s most powerful and important person?",
        "In which countries should the United Nations do more right now?",
        "Do you think the headquarters of the UN should be in New York?",
        "What do you know about the different parts of the UN?",
        "Is the United Nations the world’s most international organization?",
        "Would you like to be the next UN Secretary General?",
        "The 33rd US President Harry Truman said: \"The United Nations is designed to make possible lasting freedom and independence for all its members.\" Do you think these will come one day?"
    ],
    "United States": [
        "What images spring to mind when you hear the country USA?",
        "What are the good things and bad things about the USA?",
        "What is the USA most famous for?",
        "What do you know about the USA’s history?",
        "What are the differences between the USA and your country?",
        "What do you think about American people?",
        "What has the USA given to the world?",
        "Would you like to visit the USA, or live there?",
        "What do you know about the geography of the USA?",
        "Who are the most famous American people you know?",
        "How different is the USA from other countries?",
        "What was the last news story you heard about the USA?",
        "What do you think the USA’s neighbours think of it?",
        "What do you think the USA will be like 50 years from now?",
        "Does your country have good relations with the USA?",
        "What could you do on a holiday in the USA?",
        "What is your idea of a typical American person?",
        "What things about the USA do you think Americans are proud of?",
        "What do you know about American culture?",
        "What would you like to ask an American about the USA?"
    ],
    "Universe": [
        "What images spring to mind when you hear the word ‘universe’?",
        "Are you interested in the universe?",
        "What would you like to know about the universe?",
        "What are the laws of the universe?",
        "Would you like to travel around the universe?",
        "What do you think the edge of the universe looks like?",
        "What is the shape and colour of the universe?",
        "Why do we know more about the universe than the human brain?",
        "Einstein said: \"Two things are infinite: the universe and human stupidity; and I'm not sure about the universe.\" What does he mean? Do you agree?",
        "Stephen Hawking said: \"We are just an advanced breed of monkeys on a minor planet of a very average star. But we can understand the Universe. That makes us something very special.\" Do you agree?",
        "What is the universe?",
        "Who is the centre of your universe?",
        "How did the universe start?",
        "What is a parallel universe? Do you think another you lives in one?",
        "Do you think McDonalds and Starbucks will be in the outer regions of the universe one day?",
        "Why are scientists so interested in finding out about the universe?",
        "What three adjectives would you choose to describe the universe?",
        "Do you think a big bang started our universe?",
        "Aldous Huxley said: \"There is only one corner of the universe you can be certain of improving, and that's your own self.\" Do you agree?",
        "Dyer said: \"Everything is perfect in the universe.\" Do you agree?"
    ],
    "University": [
        "What springs to mind when you hear the word ‘university’?",
        "What are the good and bad things about universities?",
        "Are all of the universities in your country very good?",
        "What would you like to study at university?",
        "Is it important to go to university?",
        "What would happen if all universities closed down?",
        "Are universities the best system of educating people?",
        "Is university life more about studying or having fun?",
        "is university only for very intelligent people?",
        "Camus said: \"The true university of these days is a collection of books.\" Do you agree?",
        "Do you think everyone should go to university?",
        "Should university education be free?",
        "Do you think university today is different from one hundred years ago?",
        "Do you think there are many places that call themselves a university but aren’t good enough to be universities?",
        "How are the universities in your country different from each other?",
        "What’s the difference between college, school and university?",
        "In what ways is life a university?",
        "What university would you really like to study at and why?",
        "Will all universities change over to distance learning one day?",
        "Oscar Wilde said: \"The exquisite art of idleness, one of the most important things that any university can teach.\" Do you agree?"
    ],
    "Uruguay": [
        "What images spring to mind when you hear the country Uruguay?",
        "What are the good things and bad things about Uruguay?",
        "What is Uruguay most famous for?",
        "What do you know about Uruguay’s history?",
        "What are the differences between Uruguay and your country?",
        "What do you think about Uruguayan people?",
        "What has Uruguay given to the world?",
        "Would you like to visit Uruguay, or live there?",
        "What do you know about the geography of Uruguay?",
        "Who are the most famous Uruguayans you know?",
        "How different is Uruguay from other South American countries?",
        "What was the last news story you heard about Uruguay?",
        "What do you think Uruguay’s neighbours think of it?",
        "What do you think Uruguay will be like 50 years from now?",
        "Does your country have good relations with Uruguay?",
        "What could you do on a holiday in Uruguay?",
        "What is your idea of a typical Uruguayan person?",
        "What things about Uruguay do you think Uruguayans are proud of?",
        "What do you know about Uruguayan culture?",
        "What would you like to ask a Uruguayan person about Uruguay?"
    ],
    "Uzbekistan": [
        "What images spring to mind when you hear the country Uzbekistan?",
        "What are the good things and bad things about Uzbekistan?",
        "What is Uzbekistan most famous for?",
        "What do you know about Uzbekistan’s history?",
        "What are the differences between Uzbekistan and your country?",
        "What do you think about Uzbek people?",
        "What has Uzbekistan given to the world?",
        "Would you like to visit Uzbekistan, or live there?",
        "What do you know about the geography of Uzbekistan?",
        "Who are the most famous Uzbek people you know?",
        "How different is Uzbekistan from other European/Asian countries?",
        "What was the last news story you heard about Uzbekistan?",
        "What do you think Uzbekistan’s neighbours think of it?",
        "What do you think Uzbekistan will be like 50 years from now?",
        "Does your country have good relations with Uzbekistan?",
        "What could you do on a holiday in Uzbekistan?",
        "What is your idea of a typical Uzbek person?",
        "What things about Uzbekistan do you think Uzbeks are proud of?",
        "What do you know about Uzbek culture?",
        "What would you like to ask an Uzbek person about Uzbekistan?"
    ]
}
