export default {
    "Years": [
        "What images spring to mind when you hear the word ‘year’?",
        "What has been the best year in your life?",
        "What important events happened in the year of your birth?",
        "Has this year been a good year for you?",
        "Do you make New Year resolutions?",
        "In what year in history would you like to go back to?",
        "What was the best thing to happen to you last year?",
        "What is the best year at school?",
        "Do you think a year is a long time?",
        "Which time of the year do you like best?",
        "What can you get done in a year?",
        "What things do you do every year?",
        "Can you remember what you did each year on your birthday?",
        "How do you feel when a new year arrives?",
        "What do you think life will be like in the year 2100 and the year 3000?",
        "If you could take a year out from studying or work, what would you do?",
        "How long is 'donkey’s years'?",
        "What does it mean to put years on someone or take years off someone?",
        "Does getting on in years mean getting older or doing well in life?",
        "Would a book titled “A year in the life of [your name] be a good book?"
    ],
    "Yemen": [
        "What images spring to mind when you hear the country Yemen?",
        "What are the good things and bad things about Yemen?",
        "What is Yemen most famous for?",
        "What do you know about Yemen’s history?",
        "What are the differences between Yemen and your country?",
        "What do you think about Yemeni people?",
        "What has Yemen given to the world?",
        "Would you like to visit Yemen, or live there?",
        "What do you know about the geography of Yemen?",
        "Who are the most famous Yemeni people you know?",
        "How different is Yemen from other Arab countries?",
        "What was the last news story you heard about Yemen?",
        "What do you think Yemen’s neighbours think of it?",
        "What do you think Yemen will be like 50 years from now?",
        "Does your country have good relations with Yemen?",
        "What could you do on a holiday in Yemen?",
        "What is your idea of a typical Yemeni person?",
        "What things about Yemen do you think Yemenis are proud of?",
        "What do you know about Yemeni culture?",
        "What would you like to ask a Yemeni person about Yemen?"
    ],
    "Yes": [
        "What images spring to mind when you hear the word ‘yes’?",
        "How often do you say yes every day?",
        "Is it sometimes difficult to say yes?",
        "How often do you regret saying yes?",
        "When do you hope the answer is always yes?",
        "How many different ways are there of saying yes?",
        "Has anyone ever got you to say yes against your will?",
        "What words usually follow ‘yes’?",
        "Someone once said: \"Yes and no are very short words to say, but we should think for some length of time before saying them.\" Do you agree?",
        "Tony Blair said: \"The art of leadership is saying no, not saying yes. It is very easy to say yes.\" Do you agree?",
        "Do you like the word yes?",
        "Do you say yes or no more?",
        "How does intonation change the meaning of saying yes?",
        "How would life be different is the word ‘yes’ was taken out of our language?",
        "Do you always say yes when someone asks you for a favour?",
        "What was the happiest yes of your life?",
        "How many languages can you say yes in?",
        "When was the last time you screamed a big “YES!!!!” (even if it was in your head)?",
        "Joseph Campbell said: \"The big question is whether you are going to be able to say a hearty yes to your adventure.\" Do you agree?",
        "Albert Camus said: \"Charm is a way of getting the answer yes without asking a clear question.\" Do you agree?"
    ],
    "Youth": [
        "What images spring to mind when you hear the word ‘youth’?",
        "What are the good things and bad things about today’s youth?",
        "Are today’s youth different from the youth of yesteryear?",
        "How would you describe an average member of today’s youth?",
        "Do today’s youth respect authority?",
        "What is the fountain of youth?",
        "Do you think youths understand how lucky they are?",
        "How are the youth of different continents different to the young people in your country?",
        "Pablo Picasso said: \"Youth has no age.\" What did he mean? Do you agree?",
        "Someone once said: \"Don't waste your youth growing up.\" What did they mean? Do you agree?",
        "What three adjectives would you use to describe today’s youth?",
        "What’s the biggest problem with today’s youth?",
        "What aspects of today’s youth make you hopeful about the future?",
        "Do you have any wild and crazy stories from your youth?",
        "What’s the thing you hated most about your youth?",
        "Do old people understand today’s youth?",
        "What kind of youth were you?",
        "What things about the world do you think youths are angry about?",
        "Herbert Asquith said: \"Youth would be an ideal state if it came a little later in life.\" What did he mean? Do you agree?",
        "George Bernard Shaw said: \"Youth is a wonderful thing. What a crime to waste it on children.\" What did he mean? Do you agree?"
    ]
}
