/*

javascript:(function(){var hi=[];document.querySelectorAll('td[width="93%"]').forEach(lol=>hi.push(lol.innerText));localStorage[document.querySelector('h1 a').innerText.split('\n')[1].trim()] = JSON.stringify(hi);}())

var hi=[];
document.querySelectorAll('td[width="93%"]').forEach(lol=>hi.push(lol.innerText));
localStorage[document.querySelector('h1 a').innerText.split('\n')[1].trim()] = JSON.stringify(hi);



https://raw.githubusercontent.com/lodash/lodash/4.17.11-npm/core.min.js

var topics = {};
_(localStorage).keys().forEach(topicKey => topics[topicKey] = JSON.parse(localStorage[topicKey]));
localStorage.clear();
JSON.stringify(topics, false, 4);

*/

export default {
    "Babies": [
        "What do you think of babies?",
        "Are you good with babies?",
        "What do you think babies like doing most?",
        "What can we as adults learn from babies?",
        "Do you think a baby likes to be with other babies?",
        "What kind of music do you think babies like?",
        "What do babies worry about?",
        "Were you a beautiful baby?",
        "Which do you prefer, baby boys or baby girls?",
        "Do you think men will one day be able to give birth to a baby?",
        "Do you like the word ‘baby’?",
        "What do you think of newborn babies?",
        "Do you think babies have a good time?",
        "Do you like babysitting?",
        "What is the most annoying thing about babies?",
        "What’s the best way to stop a baby from crying?",
        "In what ways are babies stressful?",
        "What are the most amazing things about babies?",
        "What questions would you like to ask a baby?",
        "What do you think the baby would say?"
    ],
    "Backpacking": [
        "Have you ever been backpacking?",
        "What are the advantages of backpacking?",
        "Is backpacking better than taking a package holiday?",
        "What do you think when you see backpackers in your country?",
        "Have you ever stayed at a backpackers' or similar budget accommodation?",
        "Is backpacking generally something for younger people?",
        "Do you think backpacking is done only by those with little money?",
        "How do you think backpacking around the world would change a person?",
        "Is it better to go backpacking alone or with friends?",
        "Do you think backpackers are similar to hippies?",
        "Which is better, a backpack or a suitcase?",
        "What are the negative points or dangers of backpacking?",
        "What are the essential items to put in a backpack?",
        "What is your image of backpackers?",
        "Who would you choose to go backpacking with?",
        "Would you prefer to go on a two-week luxury cruise or go backpacking for six months?",
        "In which countries would you most and least like to go backpacking?",
        "Is it OK for old people to go backpacking?",
        "Would you like to go backpacking around your own country?",
        "Why is it called ‘backpacking’ and not ‘rucksacking’?"
    ],
    "Baldness": [
        "What do you think about baldness?",
        "What causes baldness?",
        "Do you think there’ll ever be a cure for baldness?",
        "How do you think baldness affects people?",
        "Do you think bald men and women are attractive?",
        "Do you think it’s a good idea for a bald person to wear a wig?",
        "Do you feel sorry for teenagers who start receding or thinning on top?",
        "Does hair loss run in the family?",
        "Do you think men from different races look good bald?",
        "Why do we need hair on our heads?",
        "How much time and money do you spend on your hair?",
        "If you were bald, would you consider a hair transplant?",
        "What are the advantages of being bald?",
        "Would you ever shave your head?",
        "What are the nicknames for bald people in your country?",
        "Do you think there should be a World Bald Day – everyone shaves his / her head?",
        "Can you imagine a totally bald world?",
        "What advice would you give to someone worried about going bald?",
        "Do you think combing hair across a bald area of the head to hide the baldness underneath looks good?",
        "Which famous people look good bald?"
    ],
    "Banks": [
        "Do you like banks?",
        "What are the good things about banks?",
        "What are the bad things about banks?",
        "What do you think of bank charges?",
        "Are bank workers always helpful?",
        "Has a bank ever made a mistake with your account / money?",
        "Would you like to work for a bank?",
        "Have you ever taken out a bank loan or overdraft?",
        "What do you think of the Islamic banking concept of forbidding interest rates?",
        "Would you like to use the services of an offshore bank?",
        "Are banks the best place to keep your money?",
        "What makes you angry about banks?",
        "Have you ever met your bank manager?",
        "What banking services do you like most?",
        "Do you ever have to wait a long time in the bank to get served?",
        "What changes would you like to see in the way banks operate?",
        "Are interest rates too high or too low in your country?",
        "What are the differences between commercial, investment and merchant banks?",
        "Do you use Internet banking services?",
        "How often have you used a piggy bank?"
    ],
    "Barbeques": [
        "What springs to mind when you hear the word ‘barbecue'?",
        "How important are barbecues in your country?",
        "What do you think of the word 'barbecue'?",
        "In what ways is eating indoors better than having a barbecue?",
        "Where is the best place to have a barbecue?",
        "What's the best barbecue you've been to?",
        "What's the best food to eat at a barbecue?",
        "How good or bad are barbecues for the environment?",
        "Which are better, charcoal, wood or gas barbecues?",
        "Why do men think they are good cooks at barbecues?",
        "What do you think of barbecues?",
        "In what ways are barbecues better than eating indoors?",
        "What's the worst barbecue you've been to?",
        "Which three guests would you most like to invite to your barbecue?",
        "How healthy (or unhealthy) is barbecued food?",
        "What's the best way to start a barbecue?",
        "What three adjectives best describe barbecues, and why?",
        "What are the dangers of barbecues?",
        "What are the best barbecue games?",
        "What should you do to keep your barbecue safe?"
    ],
    "Baseball": [
        "Why is baseball popular?",
        "Why hasn’t baseball taken off around the world in the way soccer has?",
        "Why has baseball been axed at the 2012 Olympics?",
        "Why is the World Series so named when countries from only two nations participate?",
        "Is baseball interesting without statistics?",
        "Who is the best baseball player ever?",
        "Which is better, baseball or American football?",
        "Do you know the origins of baseball?",
        "What would it take for baseball to be accepted as a popular sport all around the world?",
        "Is there any difference between American, Japanese or Cuban baseball?",
        "How important is baseball in your country?",
        "How can players be allowed to fight and punch the umpires in baseball without being sent off?",
        "Why do baseball players need a giant glove to catch a ball?",
        "Are there any rules in baseball you would like to see changed?",
        "Don’t you think baseball is a boring game of throwing a ball that someone either hits with a bat or misses?",
        "What is the most skillful thing about pitching or striking a ball?",
        "Do baseball players get paid too much money?",
        "How long would it take a baseball beginner to learn the rules and vocabulary?",
        "Would you like to be a famous baseball player?",
        "What is the best baseball team ever?"
    ],
    "Basketball": [
        "Why is basketball so popular?",
        "What are the rules of basketball?",
        "How tall do you have to be to become a basketball player?",
        "What basketball competitions do you know of?",
        "Is basketball interesting without statistics?",
        "Who is the best basketball player ever?",
        "Which is better: basketball, baseball, or American football?",
        "How interested are you in basketball?",
        "What qualities does a good basketball player need?",
        "What do you know about the history of basketball?",
        "How important is basketball in your country?",
        "Do you have a favourite basketball team?",
        "How has basketball changed global fashion?",
        "Are there any rules in basketball you would like to see changed?",
        "Is basketball the coolest game in the world?",
        "What is the most skillful thing about basketball?",
        "Do basketball players get paid too much money?",
        "How long would it take a basketball beginner to learn the rules and vocabulary?",
        "Would you like to be a famous basketball player?",
        "How dangerous is basketball?"
    ],
    "Baths and Bathing": [
        "What springs to mind when you hear the word ‘bath’?",
        "Do you prefer baths or showers?",
        "What do you like least and best about taking a bath / shower?",
        "What’s the worst bathroom you’ve ever taken a bath / shower in?",
        "Do you have a set routine every time you take a bath?",
        "Is it better to take a bath / shower in the morning or evening?",
        "How do you feel if you cannot take a bath?",
        "How do you feel after you take a bath / shower?",
        "Do you keep others waiting while you take a bath / shower?",
        "Pablo Picasso said: “Everything is a miracle. It is a miracle that one does not dissolve in one's bath like a lump of sugar.” Why do you think he said this? Do you agree?",
        "Do you like taking a bath / shower?",
        "Do you read or listen to music in the bath or do anything else to relax?",
        "Is having a gorgeous bathroom important to you?",
        "Have your bathing habits changed over the years?",
        "If you designed your own bathroom, what would it be like?",
        "Have you ever taken a mud bath or bathed in milk?",
        "Do you sing in the bath / shower?",
        "Do you spend a short or long time in the bath / shower?",
        "Do you think it’s important to bathe every day?",
        "The comedian Woody Allen said: “Basically, my wife was immature. I'd be at home in the bath and she'd come in and sink my boats.” Why is this funny?"
    ],
    "Beach": [
        "What springs to mind when you hear the word ‘beach'?",
        "What do you like to do at the beach?",
        "Are you a beach person or a mountain person?",
        "Is a beach holiday the best kind of holiday?",
        "What dangers might you find on the beach?",
        "Who is it best to go to the beach with?",
        "What world beach would you like to go to and why?",
        "What would it be like to live in a house on the beach?",
        "When was the last time you went to the beach?",
        "What kind of things can people do on the beach?",
        "How important are beaches to you?",
        "What are the bad things about beaches?",
        "What is your favourite beach and why?",
        "What beach sports are the best?",
        "What can we do about dirty or polluted beaches?",
        "Should pets be allowed on the beach?",
        "What do you think of the idea of private beaches?",
        "Why do some people not like the beach?",
        "Should there always be lifeguards on the beach?",
        "Why do small children like the beach so much?"
    ],
    "Beauty": [
        "What is beauty?",
        "Who decides who or what is beautiful?",
        "How often do you think about beauty?",
        "Do you think you have the same concept of beauty as your friends?",
        "What are the most important features when determining someone’s beauty?",
        "How would the world be different if we never considered beauty?",
        "Is beauty in design important in your culture?",
        "Do you think we are conditioned by advertising to think what is beautiful and what is not?",
        "What do you think of beauty contests?",
        "What does \"beauty lies in the eye of the beholder\" mean? Do you agree?",
        "Do you think the idea of beauty is changing? How?",
        "Do you think different races have different perceptions of what beauty is?",
        "Is beauty important?",
        "Is there beauty in everything we see and do?",
        "Do you think about your beauty?",
        "Do you think the beauty industry is important?",
        "Do beautiful people have better lives?",
        "Do you think it is important to get your beauty sleep?",
        "What beauty can you see around you now?",
        "Do you see beauty in the English language?"
    ],
    "Beer": [
        "Do you know how beer is made?",
        "What beers are produced in your country?",
        "Do you like beer?",
        "How would you describe the taste of beer?",
        "What do you think of people who drink too much beer?",
        "Would you like to try making your own beer?",
        "What is a good name for a beer?",
        "Do you think there is a difference between beers from different countries?",
        "What do you think of beer bellies and ‘lager louts’?",
        "How many beers would you normally drink a week?",
        "Is beer a very popular drink in your country?",
        "Is there anything healthy about drinking beer?",
        "Is beer an important part of your country’s culture?",
        "From what age can people drink beer in your country?",
        "Why do you think beer is so popular around the world?",
        "Would you like to go to the Munich Beer Festival?",
        "Which country produces the best beer?",
        "Is beer a man’s drink or a woman’s drink?",
        "Do you mix anything with beer?",
        "What’s the best thing to eat with beer?"
    ],
    "Bible": [
        "What is the Bible?",
        "Who is it for?",
        "Why is it important?",
        "What can we learn from the Bible?",
        "How is the Bible different from the holy books of other religions?",
        "Do you think the Bible is interesting?",
        "Have you read all of the Bible?",
        "What is your favorite part of the Bible?",
        "Do you think everything in the Bible is true?",
        "What do you think of the shortened Bible that can be read in 100 minutes?",
        "How often do you read the Bible?",
        "What do you know of the history of the Bible – how all of the books were collected and put together?",
        "What is the main message of the Bible?",
        "Who is the most important person in the Bible?",
        "Do you think the Bible is more interesting than a good novel?",
        "Is there a hidden code in the Bible?",
        "What is the difference between the old and new testaments and which one is more important?",
        "How can religious leaders get more people to read the Bible?",
        "Was the world created the way it is described in the Bible?",
        "If the Bible has all of the answers, why doesn’t everyone read it?"
    ],
    "Bicycles": [
        "Why is a bicycle called a bicycle?",
        "How useful are bicycles?",
        "Do you think bicycles will be used more or less in the future?",
        "What contribution has the bicycle made to the world?",
        "Is your country a bicycle-friendly country?",
        "What are your memories of learning to ride a bicycle?",
        "Have you ever injured yourself falling off of a bicycle?",
        "Have you had any bicycle adventures?",
        "What’s the best bike you’ve ever had?",
        "Have you ever had your bicycle stolen?",
        "Do you need a bicycle?",
        "What are the advantages of a bicycle over a car?",
        "What extra features or functions would be helpful for a bicycle?",
        "Do you think people will ever stop using bicycles?",
        "Have you ever ridden racing bikes, mountain bikes, bmx bikes or other recreational bikes?",
        "Do you think other cyclists are dangerous?",
        "Have you ever used a monocycle?",
        "Do you think governments should require people to pass a cycling proficiency test before being allowed to ride a bicycle on roads?",
        "Should cyclists always wear protective gear?",
        "What are the disadvantages of bicycles?"
    ],
    "Osama Bin Laden": [
        "Who is Osama Bin Laden?",
        "What do you know about him?",
        "When did you first hear about Osama Bin Laden?",
        "What are your feelings towards Bin Laden?",
        "How do you think he managed to evade capture for so long?",
        "Do you think he was really controlling the war on terror?",
        "Why do some Muslims idolize Osama Bin Laden?",
        "What did Osama Bin Laden want from the West?",
        "What do you think will happen to Al Qaeda now?",
        "What do you think of the news coverage of Bin Laden’s death?",
        "If you had met Osama Bin Laden, what would you have said to him?",
        "What motivated Bin Laden to start attacking western targets?",
        "Why did he declare a fatwa against the United States?",
        "What would happen to the war on terror if Bin Laden had been captured earlier?",
        "How did Bin Laden found al-Qaeda?",
        "What do we have to learn from Bin Laden’s life and death?",
        "Why was Bin Laden on America’s side in Afghanistan in the 1980s?",
        "How has Osama Bin Laden changed the world?",
        "How will he be remembered in history by Muslims and by nations attacked by al-Qaeda?",
        "How did you feel when you discovered Bin Laden was dead?"
    ],
    "Birds": [
        "What springs to mind when you hear the word ‘bird’?",
        "Are you interested in birds?",
        "What’s your favourite bird?",
        "Have you ever had a bird as a pet? (Is a bird a good pet?)",
        "Has a bird ever pooped on you? (It is a sign of good luck in some countries.)",
        "Are there any bird superstitions in your country?",
        "What countries have birds as national emblems? Do they reflect that country?",
        "Should trade in feathers be banned like trade in fur?",
        "Are pigeons useful birds or vermin?",
        "What’s the rarest bird you’ve ever seen?",
        "Has your cat ever brought a dead bird into the house?",
        "Has a bird ever crashed into or flown through a window in your home?",
        "Have you ever found a bird’s egg in Spring?",
        "What is your least favourite bird?",
        "What is the most beautiful bird?",
        "Are birds really “free” as the expression “as free as a bird” suggests?",
        "How many species of birds do you think there are in the world?",
        "How many bird species do you think are endangered?",
        "What’s the most common bird in your town / country? Do you like it?",
        "Why do you think humans are so fascinated by birds?"
    ],
    "Birthdays": [
        "Do you like birthdays?",
        "What’s the best and worst birthday you’ve ever had?",
        "Do you know how people celebrate birthdays in other countries?",
        "What’s the best birthday present you’ve ever been given?",
        "What present would you like for your next birthday?",
        "Do you think everyone should have a holiday from school or work on their birthday?",
        "In English people wish those whose birthday it is “many happy returns”. What do you think this means?",
        "What do you do on people’s birthdays in your country that you think doesn’t happen in other countries?",
        "Do you know of any big events that happened on your birthday?",
        "Do you think birthdays have become too commercial?",
        "How do you usually celebrate your birthday?",
        "What did you do on your last birthday?",
        "Do your family and friends always remember your birthday?",
        "What are the milestone birthdays in your country?",
        "Do you think old people like birthdays?",
        "Do you think you were born at a good time of the year?",
        "Do you sing the song “Happy Birthday” in your country?",
        "Would you like to live to celebrate your hundredth birthday?",
        "What happy memories do you have of your birthday parties?",
        "What is a “birthday suit” and why is it called so?"
    ],
    "Black": [
        "Do you like the colour black?",
        "What good things are black?",
        "Do you think black is a positive or negative colour?",
        "In which aspects of your culture does the colour black play an important role?",
        "What is a black box and why is it important?",
        "Are you always in the black or in the red with your bank?",
        "Is there a black sheep in your family?",
        "Is black always fashionable?",
        "How would the world change if all black things were white?",
        "Do you think black is a useful colour?",
        "What do you associate with the colour black?",
        "Do you like wearing black?",
        "How would you assess someone’s personality whose favourite colour was black?",
        "Do you prefer black or white?",
        "What does it mean to be black and blue?",
        "Have you ever had a black eye?",
        "Have you ever bought anything on the black market?",
        "How did you try and remove blackheads on your face?",
        "Why is black commonly the colour of mourning?",
        "Why do you think lawyers, conductors, priests and university graduates wear black?"
    ],
    "Blood": [
        "What is blood?",
        "What does blood do?",
        "Do you like the sight of blood?",
        "Why do you think some people are squeamish at the sight of blood?",
        "Do you believe your blood group reveals anything about your character?",
        "Have you ever donated blood?",
        "What is blood made up of?",
        "Does everybody have the same blood?",
        "When you have a blood test, do you look at the needle go in?",
        "Would you accept blood from someone from another country?",
        "Have you ever seen lots of blood?",
        "Do you think blood is dangerous?",
        "Have you ever had a blood transfusion?",
        "Some religions forbid blood transfusions. What do you think about this?",
        "What’s a blood bank?",
        "What kinds of things are blood curdling?",
        "Do you have low, normal or high blood pressure?",
        "What is usually done ‘in cold blood’?",
        "Do you often cut yourself?",
        "Have you ever lost a lot of blood?"
    ],
    "Blood Diamonds": [
        "Why are blood diamonds called blood diamonds?",
        "Which term do you prefer, ‘blood diamonds’ or ‘conflict diamonds’?",
        "What do you know about blood diamonds?",
        "Why do countries buy these diamonds?",
        "Would you buy a blood diamonds product if it was really cheap?",
        "Does your country insist on “conflict-free” diamond certificates?",
        "How can you be sure you’re not buying a conflict diamond?",
        "Is there a difference between conflict diamonds and conflict oil?",
        "Will warlords still find ways of making money from conflict diamonds even though the international community is trying to stop them?",
        "Will campaigns against conflict diamonds be that effective?",
        "Have you seen the Leonardo DiCaprio movie “Blood Diamond”?",
        "Do you think diamond companies like DeBeers want the trade in conflict diamonds stopped?",
        "Do you think there is enough public awareness of the conflict diamonds issue?",
        "If you found you had a blood diamond, what would you do with it?",
        "How do you think warlords get their money from blood diamonds?",
        "Do you think any other natural resources are used to finance warlords?",
        "Do you think many wars would stop if the trade in blood diamonds ended?",
        "Do you think the trade in conflict diamonds will ever end?",
        "What question would you like to ask a blood diamond seller?",
        "What do you think his/her answer would be?"
    ],
    "Body": [
        "What springs to mind when you hear the word ‘body’?",
        "Do you like your body?",
        "What are the most useful parts of our body?",
        "Are you proud of your body or ashamed of it?",
        "What kind of body language do you use?",
        "How would you describe the human body to an alien?",
        "Would you rather have the perfect body or be super intelligent?",
        "Would you sell your body to science?",
        "How good is our body?",
        "Hermann M. Biggs said: \"The human body is the only machine for which there are no spare parts.\" Is this true? Should there be lots of spare parts?",
        "Do you think our body is perfectly formed?",
        "What do you do to look after your body?",
        "What part of your body would you like to change?",
        "Do you think the naked body is beautiful?",
        "How is your body changing? Do you like these changes?",
        "What will our body look like after another million years of evolution?",
        "What three adjectives would you use to describe the human body?",
        "What’s the best and worst thing ever to happen to your body?",
        "What do you think of bodybuilding and bodybuilders?",
        "Shakespeare said: \"Our bodies are our gardens - our wills are our gardeners.\" What does this mean? Do you agree with him?"
    ],
    "Books": [
        "How important are books to you?",
        "What would life be like without books?",
        "What kinds of books do you like?",
        "Do you prefer paperbacks or hardbacks?",
        "If you wrote a book, what would you write about?",
        "If you could only have one book for the rest of your life, what would it be and why?",
        "Do you think the Internet will make books disappear?",
        "What do you think of the idea of E-books?",
        "What book would you recommend for children?",
        "How many books have you read in English?",
        "Who is your favorite author?",
        "What do you think of Google’s idea to put all the world’s books on the Internet, accessible for free?",
        "Why doesn’t everybody enjoy reading?",
        "Do you prefer to keep the books you read?",
        "What’s the most number of times you have read the same book?",
        "Which is better, the book or the movie?",
        "Do you prefer fiction or non-fiction?",
        "Do you spend a long time browsing in bookshops?",
        "Do you ever read the last page before you start reading a book?",
        "How often do you want the story in a book to never end?"
    ],
    "Boredom": [
        "What do you think of when you hear the word ‘bored’?",
        "Are you bored learning English?",
        "Is school boring? Why or why not?",
        "What’s the most boring thing you have to do?",
        "Do you have boring friends?",
        "Describe a boring movie you watched?",
        "What do you do when you get bored?",
        "Are men or women more boring? (Why)?",
        "Why do we get bored?",
        "What is the most boring book you had to read? Talk about it.",
        "Are you a boring person?",
        "What do you complain about when you are bored?",
        "Is your English teacher boring?",
        "How would you help someone who says they are bored?",
        "Do you think sport is boring? If so, which sport?",
        "What’s the best way to stop being bored?",
        "Is window shopping boring? Why or why not?",
        "Are your politicians boring?",
        "What are the most boring questions you know?",
        "Do you think animals get bored?"
    ],
    "Brain": [
        "What do you think of the brain?",
        "Do you do anything to look after your brain?",
        "How much of your brain do you use?",
        "What do neuroscientists know about the brain?",
        "What do neuroscientists want to know about the brain?",
        "How is the brain structured?",
        "What diseases affect the brain?",
        "Who is the brains of your family?",
        "How often do you tax your brain?",
        "Do people ever pick your brains?",
        "How many different functions does the brain perform?",
        "What would you say about your own brain?",
        "Do you have a quick brain?",
        "Has anyone ever called you a birdbrain (or the equivalent in your language)?",
        "Do you know what Left Brain, Right Brain means?",
        "Why do English speakers say ‘brainstorm’?",
        "What do you think the reptile, mammal and primate parts of the brain control?",
        "Has your country ever experienced or benefited from a brain drain?",
        "What do you think the differences are between male and female brains?",
        "If you had a brain transplant, would you think differently of having a new personality?"
    ],
    "Brazil": [
        "What do you know about Brazil?",
        "What are your impressions of Brazil?",
        "How important is Brazil compared with other nations?",
        "What is Brazil most commonly in the news for?",
        "Why is Brazil so good at football (soccer) and motor racing?",
        "Is Brazil a convenient and safe country in which to live?",
        "Would you like to go to the Rio Carnival?",
        "What do you know of Brazilian politics?",
        "Who is the most famous Brazilian?",
        "How do you think Brazilians would describe their country?",
        "What has Brazil given the world?",
        "What are the first three things that come to mind when you hear the country Brazil?",
        "What role does Brazil play in South America?",
        "What are relations like between your country and Brazil?",
        "Should Brazil have a permanent seat on the United Nations Security Council?",
        "What social problems does Brazil have?",
        "What would you like to do in Brazil on a three-week holiday?",
        "Why is cosmetic surgery so popular in Brazil?",
        "What do you think life is like in Brazil?",
        "What is your image of the typical Brazilian?"
    ],
    "Bread": [
        "What is bread?",
        "How important is bread in your life?",
        "What do you think of the smell of freshly baked bread?",
        "What is the best way to eat bread?",
        "Do you usually buy sliced or unsliced loaves of bread?",
        "Do you prefer white or brown bread?",
        "What kinds of bread from other countries have you tried?",
        "Which country makes the best bread?",
        "Do you ever leave the crusts?",
        "How important is yeast when baking bread?",
        "Do you know how to make bread?",
        "Do you prefer bread or bread rolls?",
        "How do you make bread?",
        "What is your favorite spread to put on bread?",
        "Do you ever buy specialty breads?",
        "How nutritious is bread?",
        "In slang, \"bread\" means money and \"brown bread\" means dead. Can you think of explanations why?",
        "Which is a better staple food, bread or rice?",
        "What is your favorite sandwich?",
        "Do you prefer bread or toast?"
    ],
    "Breakfast": [
        "What did you have for breakfast this morning?",
        "Has what you eat for breakfast changed over the years?",
        "What do you do while having breakfast?",
        "Do you prefer to eat breakfast alone or with other people?",
        "Do you ever eat breakfast in a restaurant or canteen etc.?",
        "What do you think of breakfasts in other countries?",
        "Is the breakfast you usually eat very healthy?",
        "How often do you skip breakfast or have it on the go?",
        "Can you eat “lunch-style food” or “dinner-style food” for breakfast?",
        "What do you think of breakfasts at hotels?",
        "Do you always have time to eat what you want for breakfast?",
        "How important is having breakfast?",
        "Do you watch breakfast television?",
        "Do you make your own breakfast?",
        "What is a traditional breakfast in your country?",
        "Must breakfast be eaten in the morning?",
        "Do you ever eat breakfast at fast food restaurants?",
        "Do you like having breakfast in bed?",
        "What is the origin of the word \"breakfast\"?",
        "Do you prefer a cooked breakfast?"
    ],
    "Great Britain": [
        "Is Britain great?",
        "What is the difference between Great Britain, England and the United Kingdom?",
        "What do you know about British food and weather?",
        "What would you like to do and see in Britain on a three-week holiday?",
        "How do you think British people would describe their country?",
        "Do you think Britain has too much political power in the world?",
        "Would you like to live in Great Britain?",
        "What parts of British culture are popular in your country?",
        "Does your country have good relations with Britain?",
        "What do you think of when you see the Union Jack flag?",
        "What do you know about Great Britain?",
        "How important is Britain in the world?",
        "How did Britain lose its empire?",
        "What has Great Britain contributed to the world?",
        "Would you like to speak with a British accent?",
        "Who is the most famous British person ever?",
        "What is Britain most famous for?",
        "What mistakes has Great Britain made?",
        "Do you like British fashion and music?",
        "What do you think of the British Queen?"
    ],
    "Buddhism": [
        "Is Buddhism a religion?",
        "What do Buddhists believe in?",
        "Are there any gods in Buddhism?",
        "What do you think of when you see the image of Buddha?",
        "What is the difference between Zen Buddhism and others such as Tibetan or Theravada (Thai) Buddhism?",
        "How important is the Dalai Lama?",
        "Are there any Buddhist holy books?",
        "How important is meditation in Buddhism?",
        "What do you know about Buddha?",
        "What is Karma?",
        "Do you believe in reincarnation?",
        "What is Nirvana?",
        "What are the important Buddhist days, ceremonies or festivals?",
        "Do you think Buddhists are less violent than followers of other religions?",
        "Who do Buddhists pray to and what do they pray for?",
        "Why do Buddhists chant?",
        "Why do Buddhists bow?",
        "How has Buddhism affected the world?",
        "Why are most Buddhists vegetarian?",
        "Why is the Buddha fat?"
    ],
    "Bullying": [
        "What springs to mind when you hear the word ‘bullying’?",
        "What different types of bullying are there?",
        "Was bullying a big problem at your school?",
        "Is it worse for children or adults to get bullied?",
        "Why do people bully each other?",
        "Do you think bullying should be made a crime or is it part of growing up?",
        "Is cyber-bullying (online bullying) worse than face-to-face bullying?",
        "What experiences of bullying do you have?",
        "How bad is bullying in your country?",
        "What kind of person is a bully?",
        "Do bullies need help? What kind?",
        "What can people who are bullied do to stop the bullying?",
        "If bullying involves violence, should someone call the police?",
        "What damage does bullying do to people?",
        "Should someone who is bullied make the name of the bully public – put it on the Internet?",
        "Is it always best to stand up to a bully?",
        "Do you think bullying will disappear one day, or is it getting worse?",
        "What message do you have for bullies?",
        "What advice would you give to someone who is bullied (a) online and (b) physically or emotionally?",
        "Are there similarities between bullying and torture?"
    ],
    "Business": [
        "Are you interested in the world of business?",
        "Do you think you have a good head for business?",
        "What kind of business would you like to start?",
        "Do you think anyone can start their own business?",
        "What are the dangers of having your own business?",
        "Would you include your own name in your business name?",
        "Do you read any business magazines?",
        "Do men or women make more successful business people?",
        "Do you think you’d be a tough person to work for?",
        "What advice would you give to people starting in business?",
        "How would you define business?",
        "Would you like to have your own business?",
        "What kind of people are good at business?",
        "Is it easy to start a business in your country?",
        "What business skills do you have?",
        "Would you prefer to start a “bricks ‘n’ mortar” business or an Internet business?",
        "What would be your motto in business?",
        "What kind of office would you like?",
        "Who would be your business hero?",
        "What would be your main business goal?"
    ]
}
