export default {
    "Abbreviations / Acronyms": [
        "Are you interested in learning abbreviations and acronyms in English?",
        "Do you know lots of abbreviations and acronyms?",
        "Do you think abbreviations and acronyms are useful?",
        "Do you have a favorite abbreviation or acronym?",
        "Do you think alphabets that don’t have an English script (Chinese, Russian, Arabic, etc.) use abbreviations and acronyms?",
        "Do you know the punctuation rules for abbreviations and acronyms?",
        "What do you think are the world’s most common abbreviations and acronyms?",
        "Do you ever invent your own acronyms to help you study?",
        "The website www.abbreviationz.com says “RSVP” is one of the most popular queries. Do you know what it means?",
        "What acronym could you create for your name?",
        "What is the difference between an abbreviation and an acronym?",
        "How many United Nations abbreviations and acronyms do you know?",
        "Are there many abbreviations and acronyms in your language?",
        "What do you think about spending a whole English lesson on abbreviations and acronyms?",
        "Can you keep up to date with computer and technology abbreviations and acronyms (WIFI, WAP, ISP, WWW, etc.)?",
        "Do you think abbreviations in e-mail and text messages are adding to or ruining the English (or your) language?",
        "The website www.abbreviationz.com lists 33 different meanings for “BYOB”. Can you think of any?",
        "“Scuba”, “modem”, radar”, “laser” and “NATO” are all acronyms. Do you know what they mean?",
        "Would you like to study for an MA or PhD?",
        "What do ante meridian and post meridian refer to?"
    ],
    "Abortion": [
        "What is abortion?",
        "Do you think abortion should be legal or illegal?",
        "Do you think there are any special cases in which abortion is acceptable?",
        "How does the law regard abortion in your country?",
        "How does your religion or others treat abortion?",
        "Do you think the morning after pill is the same as abortion?",
        "Some people think doctors who carry out abortions are murderers. What do you think?",
        "If your 13-year-old daughter became pregnant, what advice would you give her?",
        "Why allow an unwanted baby to be born?",
        "Does the mother have the right to control her own body?",
        "Is abortion a social problem in your country?",
        "Is abortion dangerous?",
        "Do you sympathize with the pro-life argument?",
        "Do you sympathize with the “right to choose” argument?",
        "If a woman wants an abortion, what rights does the father have?",
        "Is having an abortion a selfish choice?",
        "Do you think abortions should be encouraged for girls of 12, 13 or 14 years old?",
        "When is the fertilized egg a human being?",
        "What do you think of back-street abortionists?",
        "What would you want to tell the unborn child?"
    ],
    "Academy Awards": [
        "What do you know about the Academy Awards?",
        "Do you think the Oscar statue is well-designed?",
        "Do you watch the Academy Awards every year?",
        "Do you usually agree with the judges?",
        "Do you think the Awards are based too much on Hollywood?",
        "Are there similar awards for movies in your country?",
        "Do you know of any other awards for movies?",
        "What do you think of the fashion at the Academy Awards?",
        "How do you think winning an award changes the career of an actor?",
        "Where would you put an Academy Award if you won one?",
        "What is the Academy?",
        "Can you name the winners of the last Academy Awards?",
        "Do you think the Awards are worthwhile?",
        "Would you like to attend the Awards presentations?",
        "Which would you prefer to watch, the Academy Awards or MTV awards?",
        "Do you like the speeches at the Awards?",
        "Why do you think the Academy Awards are also called the Oscars?",
        "Would you like to be a judge at the Academy Awards?",
        "Do you think the judges should be more international?",
        "What is the most important category in the Academy Awards?"
    ],
    "Accidents": [
        "What’s the biggest accident you’ve ever had?",
        "Are you accident prone?",
        "Have you ever been in a car accident?",
        "Have you ever seen a very bad accident?",
        "Have you ever caused an accident?",
        "Do you know what to do or how to treat people in an accident?",
        "Do you know anyone who is “an accident waiting for somewhere to happen”?",
        "Have you ever had any accident prevention training?",
        "How often are there major rail accidents in your country?",
        "Do you worry about having accidents?",
        "Have you ever had any work-related accidents?",
        "Have you ever received compensation for an accident?",
        "Have you ever visited the accidents and emergencies department of a hospital?",
        "What do you think of the expression “he / she was an accident”, meaning his / her parents didn’t plan on having him / her?",
        "Have you ever made an insurance claim for an accident?",
        "Do you think there’ll be another major nuclear accident?",
        "What do you remember about the Space Shuttle accidents?",
        "Have you ever run into an old friend by accident?",
        "What do you think “accidentally on purpose” means?",
        "What was the last tragic accident you read about?"
    ],
    "Actors": [
        "Who is your favorite actor?",
        "Who is your favorite actress?",
        "What do you think about both men and women being called actors nowadays?",
        "Would you like to be an actor?",
        "Do you think men or women are better at acting?",
        "Do you think today’s actors are better than those from 30, 40 or 50 years ago?",
        "Do you think it’s strange that most actors are beautiful or handsome?",
        "Do you think anyone can become an actor?",
        "Are there any actors you really don’t like?",
        "Do you like actors from other countries?",
        "Have you ever acted, either at school or amateur dramatics?",
        "What kind of movies would you like to act in?",
        "Would you prefer to act on the stage, in movies or in TV dramas?",
        "Do you think an actor’s job is difficult?",
        "Do you always agree with the choices for best actor and actress at the Oscars (Academy Awards)?",
        "Do you think actors get paid too much money?",
        "Who are the top actors in your country?",
        "Which actor would you like to change places with and why?",
        "Do you have a favorite acting performance?",
        "What questions would you like to ask your favorite actor?"
    ],
    "Adolescence": [
        "What comes to mind when you hear the word ‘adolescence’?",
        "What is adolescence?",
        "What happens during adolescence?",
        "Is adolescence generally regarded as a good or happy time?",
        "What problems did you have in your adolescence?",
        "Did you worry about whether or not other people liked you?",
        "Did you rebel against your parents or teachers?",
        "When did you begin to feel like you were an adult?",
        "Are there any ceremonies or celebrations in your country to mark the entrance into adulthood?",
        "What worries and fears did you have as an adolescent?",
        "Is there a term for adolescence in your language?",
        "Is adolescence viewed as a difficult time for children / young adults in your country?",
        "Were you an early or late developer?",
        "What physiological and psychological changes take place during adolescence?",
        "Did you suffer from spots and acne?",
        "Were you a problem for your parents during your adolescence?",
        "When did you think you were no longer a child?",
        "Would you like to relive your adolescence?",
        "What advice would you give to today’s adolescents?",
        "Do you think today’s adolescents are more mature than when you were growing up?"
    ],
    "Adoption": [
        "Is adoption common in your country?",
        "What do you think of adoption?",
        "Would you adopt?",
        "What do you think happens to children who are not adopted?",
        "Do you know anyone who was adopted?",
        "What problems do you think there might be with adoption?",
        "Do you think parents who adopt have the same kind of love for their adopted child as natural parents have with their child?",
        "Is it better to adopt a baby or an older child?",
        "Should people adopt children from the same race?",
        "What happens if the biological parents turn up ten years later and ask for their child back?",
        "Should an adopted child have the same legal right as a non-adopted child?",
        "When should you tell a child he / she is adopted?",
        "What checks should adoption agencies conduct on prospective parents?",
        "Should same-sex couples or single people be allowed to adopt?",
        "Would you prefer to adopt a child from your own country or a very poor country?",
        "Do you think international adoption would be a useful solution for under-populated countries?",
        "What questions do you think a child has when he / she finds out he / she is adopted?",
        "Do you think people who adopt have extra-special hearts?",
        "Should brothers and sisters be split apart for adoption?",
        "What happens if the adopted parents decide they don’t like the child after a year or so?"
    ],
    "Adultery": [
        "What is adultery?",
        "How bad is it?",
        "Is it worse for the adulterer to be a man or a woman?",
        "Do the couple have to be married for adultery to take place?",
        "Do you think adultery should be a criminal offence?",
        "What punishment should the adulterer and his / her lover receive?",
        "Could you trust your partner again if they had cheated on you?",
        "How many times would you forgive a cheating partner before filing for a divorce?",
        "Do you think you should be able to sue a cheating partner on the grounds of breach of marriage contract?",
        "What would you do if you discovered your partner had been unfaithful just once – five years ago?",
        "Do you agree with the expression “once an adulterer, always an adulterer”?",
        "Why do people commit adultery?",
        "Are there any telltale signs your partner might veer off the path?",
        "Is adultery a natural part of human relations our jealousies cannot cope with?",
        "Is dating another person adultery or do you have to have sex?",
        "Are extra-marital affairs common in your society?",
        "The Bible says even thinking of having sex with another person is adulterous. What do you think? Is lust really a sin?",
        "Who should get the kids in adultery cases?",
        "Is adultery reasonable grounds for divorce?",
        "Do you have any stories about husbands and wives playing around?"
    ],
    "Adventure": [
        "What springs to mind when you hear the word ‘adventure’?",
        "Do you like adventure?",
        "In what way is learning English an adventure for you?",
        "Who would you like to have a big adventure with?",
        "Do you think your idea of adventure is the same as your parents’ ideas and your grandparents’ ideas?",
        "Does there have to be an element of danger in an adventure?",
        "Do you think animals like adventures?",
        "What adventures would you like to go on in the future?",
        "Do you ever have online adventures?",
        "Do you like adventure movies?",
        "Are you an adventurous person?",
        "Is life a good adventure?",
        "Is adventure important in your life? Why?",
        "What’s the biggest adventure you’ve had in your life?",
        "What was your most unforgettable childhood adventure?",
        "Is your country famous for adventurers?",
        "Which of these things would you like on an adventure: danger, romance, speed, travel, discovery, prizes?",
        "What are your favourite fantasy / adventure video games?",
        "Where would you like to go for an adventure – a jungle, a desert, a small island or a city?",
        "Are men or women more adventurous?"
    ],
    "Advertising": [
        "How would you define advertising?",
        "Would you like to work in advertising?",
        "Do you prefer advertisements on TV, in newspapers, on the radio, on the Internet or in the street?",
        "Do you think advertising is an art?",
        "Would you like there to be no ads on TV?",
        "What do you think of the ads in other countries?",
        "Have you ever placed an ad in the classified section of a newspaper?",
        "Do you think advertising is a clever way of lying about products?",
        "What products depend most on advertising?",
        "What do you think of advertisements for language schools?",
        "Is advertising a good or bad thing?",
        "What factors are essential in making a good advertisement?",
        "Do pop-up ads on the Internet bother you?",
        "What adverts have you seen or heard that you particularly liked?",
        "Do you think you are easily persuaded to buy things after seeing or hearing an ad?",
        "Do you agree with an advertising ban on cigarettes?",
        "What regulations should be applied to adverts to protect consumers?",
        "What would the world be like without advertising?",
        "Have you ever been angry about an advert?",
        "Which companies produce the best ads?"
    ],
    "Advice": [
        "What springs to mind when you hear the word ‘advice'?",
        "What three pieces of advice will you give your children?",
        "How good are you at giving advice?",
        "Have you ever given someone the wrong advice?",
        "Whose advice do you follow more, your parents’ or your friends’?",
        "What advice would you give the leader of your country?",
        "What advice do you have about being successful in love?",
        "What’s the best piece of advice you’ve ever had?",
        "What advice do you wish someone had given you when you were younger?",
        "Would you ever go to a counsellor for advice?",
        "What advice would you give to yourself right now?",
        "Where do you go to get good advice?",
        "Are men or women better at giving advice?",
        "What advice do you have for people who want to study English?",
        "What advice do you have about being successful with money?",
        "Whose advice would you never take (and why)?",
        "Have you ever been given bad advice?",
        "What things do you ask for advice on?",
        "Would you look for advice online?",
        "What’s the best piece of advice you could give anyone?"
    ],
    "Afghanistan": [
        "What do you know about Afghanistan?",
        "Do you remember the Afghan War against the Soviet Union?",
        "Do you feel sorry for Afghanistan?",
        "Do you think peace and prosperity will return to Afghanistan?",
        "What do you remember about the Taliban?",
        "Did you agree with America fighting and ousting the Taliban in 2001?",
        "What do you know about Afghanistan’s economy?",
        "Would you consider working or living in Afghanistan?",
        "Would you like to visit Afghanistan?",
        "Do you think Afghanistan has been a success story in the war on terror?",
        "Do you think Hamid Karzai is a good leader?",
        "Afghanistan supplies 90 percent of the world’s opium. What can be done to prevent this?",
        "What do you think it’s like to live in Kabul?",
        "Do you think there will be another war in Afghanistan?",
        "How many Afghan people have you met?",
        "What do you think the average Afghan thinks of America, Russia, Pakistan, your country…?",
        "Do you think Afghanistan still has human rights problems?",
        "Do you think the different tribes and factions in Afghanistan can live together?",
        "What questions would you like to ask an Afghan?",
        "What do you think his / her answer would be and why?"
    ],
    "Africa": [
        "What images spring to mind when you hear the word ‘Africa’?",
        "Do you have a favorite African country?",
        "What is Africa famous for?",
        "What do you think Africa’s saddest story is?",
        "What images of Africa do you have that are romantic?",
        "What images of Africa do you have that are beautiful?",
        "What has Africa given to the world?",
        "What has the world given to Africa?",
        "What has the world taken from Africa?",
        "Who are Africa’s most famous people?",
        "How different are North Africa, Southern Africa, West and East Africa?",
        "Do you think rich countries will ever give African countries a chance?",
        "What did colonial rule do for Africa?",
        "What does Africa need to do to pull itself out of poverty?",
        "Which African countries would you most like to visit?",
        "What are the biggest challenges facing Africa?",
        "In what areas will Africa achieve prominence in the future?",
        "How interesting is news of Africa compared to news of other continents?",
        "Which of Africa’s problems would you address first?",
        "What do you think of Africa’s present leaders?"
    ],
    "Age": [
        "Do you like being the age at which you now are?",
        "What is the best age to be and why?",
        "What is the worst age to be and why?",
        "Do you worry about getting older?",
        "Do you look your age?",
        "Do you think scientists can slow the ageing process?",
        "Why do some people seem to age faster than others?",
        "Until what age would you like to live?",
        "Are there any age groups you currently don’t like?",
        "What is the best age at which to get married?",
        "Do people respect the aged in your country?",
        "How have you aged in the past ten years?",
        "Do you mind being asked your age?",
        "What do you think your old age will be like (or what is it like)?",
        "Do you agree that you can never be too old to start something new?",
        "What problems are there of an aging population?",
        "What do you least like (like most) about getting older?",
        "Is your society ageist?",
        "Would you like to turn back the clock?",
        "Do you look forward to your birthdays?"
    ],
    "AIDS": [
        "When did you first hear about AIDS?",
        "What do you know about AIDS?",
        "What’s the difference between AIDS and HIV?",
        "What do ‘AIDS’ and ‘HIV’ mean?",
        "What does HIV/AIDS do to the human body?",
        "How serious a problem is AIDS around the world?",
        "Are governments doing enough to combat AIDS?",
        "How badly is your country affected by AIDS?",
        "How do people get HIV / AIDS?",
        "When do you think there’ll be a cure for AIDS?",
        "Have you had or would you ever have an AIDS test?",
        "Are you worried about AIDS?",
        "Do you worry about AIDS and your children?",
        "Do you know anyone or have you met anyone with HIV / AIDS?",
        "Do you trust your partner 100 percent?",
        "Were you taught about AIDS at school?",
        "What’s your government doing to combat AIDS?",
        "What’s the best protection against AIDS?",
        "Is AIDS a taboo subject in your country?",
        "What questions would you ask an AIDS sufferer?"
    ],
    "Airplanes": [
        "What springs to mind when you hear the word ‘airplane'?",
        "How important are airplanes?",
        "What do you know about the history of airplanes?",
        "What different kinds of airplanes are there?",
        "How have airplanes changed over the years?",
        "Would you like your own plane?",
        "What is the best airplane in the world?",
        "Is it better to travel by airplane or by cruise ship? Why?",
        "What do you think when you see an airplane in the sky?",
        "Would you like to work on an airplane?",
        "How do airplanes work?",
        "How dangerous are airplanes?",
        "What will airplanes be like in the future?",
        "Which is better, Boeing or Airbus?",
        "What movies have you seen about airplanes?",
        "Would you like to fly (pilot) an airplane? Why?",
        "What effect do airplanes have on the environment?",
        "How do airplanes get off the ground and fly?",
        "How cool are airplanes?",
        "What three adjectives describe airplanes?"
    ],
    "Alcohol": [
        "What is your favorite alcoholic drink?",
        "How often do you drink?",
        "Do you ever… / How often do you… drink to excess?",
        "Why do you drink alcoholic drinks?",
        "Is alcohol a drug?",
        "Should governments allow people to drink products that make people violent?",
        "Are the drinking and driving laws in your country too strict?",
        "How does alcohol change your behavior, personality and face?",
        "What are the most popular forms of alcohol in your country?",
        "What part does alcohol play in the culture of your country?",
        "When did you start drinking?",
        "What should be the legal age to drink alcohol?",
        "Can bars serve alcohol 24 hours a day in your country?",
        "In the USA, you cannot drink alcohol on the street. What are the laws regarding drinking in public in your country?",
        "What kinds of social problems does alcohol cause in your country?",
        "What do you think of very drunk people?",
        "Alcohol is forbidden in Islam. Is this good?",
        "Do you think people from different countries act differently when drunk?",
        "Have you ever said or done something under the influence of alcohol that you later regretted?",
        "What is the best cure for a hangover?"
    ],
    "Aliens": [
        "Do you think there are aliens somewhere in the universe?",
        "What do you think aliens look like?",
        "Why do you think aliens in movies and comic books generally have a human shape and eyes?",
        "Do you think aliens are likely to be more or less intelligent than us?",
        "Do you think aliens are likely to be friendly or unfriendly?",
        "Where do you think the idea of aliens from outer space came from?",
        "What are the aliens like in your culture’s movies and books?",
        "What do you think of people who say they have met or were kidnapped by aliens?",
        "What’s your favorite movie about aliens?",
        "Do you think aliens would prefer to communicate with us or other species?",
        "Do you think aliens are likely to be friendly or unfriendly?",
        "What would you say to an alien if you met one?",
        "What would you do if you saw a UFO in a field near your house?",
        "Do you think aliens might have lots of viruses that could wipe out the human race?",
        "If the secret service discovered an alien, do you think they would tell the general public?",
        "Do you think aliens would be afraid of humans?",
        "If aliens visited Earth for a week, what do you think they should see to fully understand us and our achievements?",
        "How likely is it we will ever be able to visit a planet that has aliens?",
        "Do you think it’s worthwhile for your government to spend money on alien research or sending signals into space in case aliens are listening?",
        "If an alien visited Earth, what would it say about our planet and people when it returned home?"
    ],
    "Aliens (easier)": [
        "Do you think there are aliens somewhere in space?",
        "What do you think aliens look like?",
        "Why do aliens in movies and comics have a human shape and eyes?",
        "Do you think aliens are more or less intelligent than us?",
        "Do you think aliens are friendly or unfriendly?",
        "Where do you think the idea of aliens came from?",
        "What are the aliens like in your culture’s movies and books?",
        "Would you like to meet an alien? What would you say to it?",
        "What’s your favorite movie about aliens?",
        "What things about Earth would aliens like?",
        "Do you think aliens are dangerous?",
        "What would you do if you knew aliens would attack Earth tomorrow?",
        "What would you do if you saw a UFO near your house?",
        "Do you think you could be friends with an alien?",
        "What jobs could an alien do?",
        "Do you think aliens would be afraid of humans?",
        "What language do aliens speak?",
        "Do you think studying aliens is a good hobby?",
        "What is a good alien name?",
        "What would the world be like if we shared it with aliens?"
    ],
    "Allergies": [
        "Do you have any allergies?",
        "What do you think would be the worst thing to be allergic to?",
        "What things are people allergic to in your country?",
        "Some people are allergic to the twenty-first century. What do you think this means?",
        "What would life be like if you suddenly became allergic to your favorite food?",
        "What do you think… / What is… life like for hay fever sufferers?",
        "What would you do if you suddenly had extreme allergic reactions to your pet / partner / best friend?",
        "What are the most common allergens?",
        "Why are some people allergic to eggs, wheat or peanuts while others are not?",
        "What are the symptoms of allergies?",
        "Can people be cured of allergies?",
        "Some people say children who don’t like taking a bath are allergic to soap. Do you have a similar belief in your country?",
        "Do you think it’s possible that lazy people are allergic to work?",
        "Do you think people with food allergies feel deprived?",
        "Do you know anyone who is allergic to opening his / her wallet?",
        "Do any of your family or friends have allergies?",
        "Which would be worse for you, an allergy to milk, alcohol or animals?",
        "What new allergies might be found in the future?",
        "How can you make children with allergies feel better?",
        "Are you ever allergic to speaking English?"
    ],
    "Alphabet": [
        "Are there twenty six letters in the alphabet of your language?",
        "Does your language have an alphabet?",
        "What are the differences between the English alphabet and your language’s writing system?",
        "What is the most frequently used letter of the alphabet?",
        "Which letters of the alphabet do you not like or have problems with?",
        "Do you think English spelling is confusing?",
        "Are the letters of the alphabet pronounced the same in British, American, Australian, Nigerian … English?",
        "Did you have any problems learning the letters of the alphabet?",
        "What is the difference between consonants and vowels?",
        "What is the International Phonetic Alphabet?",
        "Do you like the English alphabet?",
        "How did you learn the alphabet?",
        "What do you think of other alphabets (Russian, Greek, Arabic, Hebrew, Sanskrit, etc.)?",
        "Who invented the English alphabet?",
        "Why do you think each letter has so many different pronunciations and uses?",
        "How do you think the alphabet could be made easier to use and understand?",
        "Would you like to learn a character-based system like Chinese?",
        "When is the best age to introduce children to the alphabet?",
        "What is alphabet soup?",
        "What does “the ABCs of” mean?"
    ],
    "Alternative Medicine": [
        "What springs to mind when you hear the term ‘alternative medicine’?",
        "What is ‘alternative’ about alternative medicine?",
        "What alternative medicine do you know about?",
        "Have you tried any alternative medicine?",
        "Do you think alternative medicine is just a trend that goes in and out of fashion?",
        "Do you think alternative medicine works?",
        "What kind of people use alternative medicine?",
        "Do you think alternative medicines work better than modern drugs?",
        "Do you trust alternative medicine?",
        "Do you think doctors should study about and be experts in alternative medicine?",
        "Do you think alternative medicines are tried, tested and safe?",
        "Why do you think so little is known about the health benefits of alternative medicine?",
        "Which countries in the world have the best medicines?",
        "Do you think we can find all the medicines we need from the natural world, instead of making drugs?",
        "Would you like to try acupuncture?",
        "What are your thoughts on traditional Chinese medicine?",
        "Do you think the medicine in Western hospitals is alternative medicine in other countries?",
        "What do you think of things like art therapy, music therapy, healing with animals, etc.?",
        "What would you like to know about alternative medicine?",
        "Do you know anyone who uses alternative medicine?"
    ],
    "Amazon": [
        "What images come to mind when you hear the word ‘Amazon’?",
        "What do you know about the Amazon?",
        "How important is the Amazon?",
        "Which is more important, the Amazon River or Amazon rainforests?",
        "What kind of animals are unique to the Amazon?",
        "What environmental problems does the Amazon have?",
        "What’s the difference between a rainforest and a jungle?",
        "What can we do to help protect the Amazon?",
        "Who lives in the Amazon?",
        "Would you like to visit the Amazon?",
        "Would you like to spend a year living in the Amazon jungle?",
        "What can Amazonian Indians teach us about life?",
        "Who has a better life, Amazonian Indians or us?",
        "What do you think Amazonian Indians think of developers cutting down and polluting the rainforests?",
        "Oil giants Chevron and Texaco say they are looking after the rainforest and indigenous peoples. What do you think?",
        "Could you survive a year alone in the Amazon?",
        "Why is it so important to protect the Amazon?",
        "Which is the only river in the world longer than the Amazon?",
        "What is the Amazon Basin?",
        "Why do you think the bookseller Amazon.com chose the word ‘Amazon’ for its name?"
    ],
    "Ambition": [
        "What springs to mind when you hear the word ‘ambition’?",
        "Are you ambitious?",
        "Is it important to have ambitions?",
        "Who is the most ambitious person you know?",
        "What were your ambitions when you were a child?",
        "Can ambitions be dangerous?",
        "What ambitions do you have that you think you’ll realize and what ambitions do you have that you won’t realize?",
        "Do you think animals have ambitions?",
        "Thomas Carlyle said: “I've got a great ambition to die of exhaustion rather than boredom.” What do you think he means by this? Do you agree?",
        "Thomas Jefferson said: “Nothing can stop the man with the right mental attitude from achieving his goal; nothing on earth can help the man with the wrong mental attitude.” Do you agree?",
        "Why do we have ambitions?",
        "What’s the difference between an ambition and a dream?",
        "What ambition have you held the longest?",
        "What happens after you have fulfilled all of your ambitions?",
        "Do you think really old people have ambitions?",
        "Do you like ambitious people?",
        "Do you have any really crazy and wild ambitions?",
        "What do you think it feels like to fulfill a lifelong ambition?",
        "Thomas Merton said: “When ambition ends, happiness begins.” What do you think he means by this? Do you agree?",
        "Marcus Aurelius said: “A man's worth is no greater than the worth of his ambitions.” Do you agree?"
    ],
    "Amnesty International": [
        "What is Amnesty’s primary function?",
        "How important is Amnesty compared to charities such as Save The Children or Help The Aged?",
        "Do you think Amnesty International is a good name?",
        "Who is Amnesty International’s most famous prisoner of conscience?",
        "Why do many governments, including that of the USA, refuse to believe many of Amnesty’s reports?",
        "Do you think Amnesty International is effective?",
        "How do you think Amnesty gets information about “closed” countries and despotic regimes?",
        "How can we help protect and promote human rights?",
        "Do you think there are many countries that do not commit human rights violations?",
        "Do you think working for Amnesty International can be dangerous?",
        "Why is Amnesty International important?",
        "What could Amnesty do to increase its profile?",
        "What do you think of the Amnesty International logo?",
        "What do you know about the history of Amnesty International?",
        "Do you know of any other organizations similar to Amnesty?",
        "How can Amnesty be sure its facts are true?",
        "Have you ever participated in any Amnesty events?",
        "Would you ever write a letter to a government urging them to release a prisoner or stop an execution?",
        "Which countries are the biggest human rights violators?",
        "Why do you think Amnesty refuses funds from governments?"
    ],
    "Amusement Parks": [
        "What springs to mind when you hear the word ‘amusement park'?",
        "What is your experience of amusement parks?",
        "Why do people like amusement parks?",
        "What are the differences between amusement parks and theme parks?",
        "What's the best amusement park in the world?",
        "What do you think of Disneyland?",
        "Is 'amusement park' the right word, or should it be 'excitement park'?",
        "What kind of rides are best?",
        "Are amusement parks good value for money?",
        "Do amusement parks have to be based on cartoon characters?",
        "Would you be a good amusement park designer? Why?",
        "What do you think of jet coasters?",
        "Are there any bad things about amusement parks?",
        "What kind of new amusement park would you like to see built?",
        "How dangerous are the rides at amusement parks?",
        "Who enjoys theme parks more, children or adults?",
        "What is the best job at a theme park?",
        "What do you think of the price of food and merchandise at amusement parks?",
        "What three adjectives best describe amusement parks and why?",
        "What will amusement parks be like in the future?"
    ],
    "Anger": [
        "What springs to mind when you hear the word ‘anger’?",
        "Are you an angry person?",
        "What are you like when you are angry?",
        "What’s the angriest you’ve ever been?",
        "When you get angry, do you stay angry for a long time?",
        "Do you like looking at other people getting angry?",
        "What colour is anger?",
        "What makes you angry about modern life?",
        "Someone once said: “For every minute you are angry, you lose sixty seconds of happiness.” Do you agree?",
        "Someone once said: “Anger is one letter short of danger.” Do you agree?",
        "Why do we have the emotion of anger?",
        "Is there anything positive about getting angry?",
        "Who is the angriest person you know?",
        "Should anger be a sin?",
        "Why do we get angriest with the ones we love?",
        "Who on Earth angers you most?",
        "What happens when you bottle up your anger?",
        "Is it easy for you to control and hide your anger?",
        "Elizabeth Kenny said: “He who angers you conquers you.” What do you think she means by this? Do you agree?",
        "A Chinese Proverb said: “Never write a letter while you are angry.” Do you think this is good advice? Have you regretted writing an angry letter?"
    ],
    "Animal Rights": [
        "What springs to mind when you hear the term ‘animal rights?",
        "What rights do animals have?",
        "Should we all be vegetarian and not kill animals for food?",
        "What rights do humans have that animals should also have?",
        "Is keeping a pet going against animal rights?",
        "What do you think of testing cosmetics on animals?",
        "Would you join an animal rights group?",
        "What animals should have the most rights?",
        "What are blood sports? Should they be banned?",
        "How are animal rights viewed in your country?",
        "In today's world, how are animals suffering?",
        "What do you think of killing animals for fur?",
        "Does animal rights include rights for fish, birds and insects?",
        "Should horse racing be banned?",
        "What can we do to make sure animals' rights are respected?",
        "What do you think of testing medicines on animals?",
        "What bad things might happen to animals in circuses?",
        "How happy do you think animals are in zoos?",
        "Do humans have the right to hunt and kill animals?",
        "How bad is it that many species are becoming extinct?"
    ],
    "Animals": [
        "Do you like animals?",
        "What is your favorite animal?",
        "What animals are there in your country?",
        "What animals have disappeared from your country?",
        "Are there any dangerous animals in your country?",
        "What is the cutest animal in the world?",
        "Do you think animals were put on this planet so we could eat them?",
        "Do you think animals would rather not be kept as pets?",
        "Is it OK to use animals in sport?",
        "What animal would you like to come back to Earth as after you die?",
        "What natural animal ability or talent would you like to have?",
        "What is the most useful animal in the world?",
        "What animal best represents your character?",
        "Do you think it is necessary to experiment on animals to test cosmetics and drugs?",
        "What animals have the best life?",
        "Should animals be kept in zoos?",
        "What are the biggest differences between animals and humans?",
        "If animals could speak, what do you think they would say to humans?",
        "What animal are you most fascinated by?",
        "What animal do you least like?"
    ],
    "Antarctica": [
        "What do you know about Antarctica?",
        "What would you like to know about Antarctica?",
        "Is Antarctica a country?",
        "What happens on Antarctica?",
        "What do you think is interesting about Antarctica?",
        "What do scientists research on Antarctica?",
        "What do you think people do on a two-week holiday on Antarctica?",
        "Do you think a company could make money offering honeymoons on Antarctica?",
        "What are the future threats to Antarctica?",
        "Who should control Antarctica?",
        "Do you know anything of the history of Antarctica?",
        "Do you think Antarctica has any natural resources?",
        "What is the significance of ice shelves on Antarctica melting because of global warming?",
        "Would you like to spend six months working on Antarctica?",
        "What is the yearly climate of Antarctica like?",
        "Are there any indigenous inhabitants on Antarctica?",
        "What would you take photographs of on Antarctica?",
        "Do you like penguins?",
        "Do you think tourism should be allowed on Antarctica?",
        "How could Antarctica hold the key to the question of life on Mars?"
    ],
    "Appearances": [
        "What springs to mind when you hear the word ‘appearances'?",
        "What things do you first notice about someone's appearance?",
        "How do you think you look today?",
        "When is your appearance most important?",
        "What do you think when you look at yourself in the mirror?",
        "Do you think the expression 'Appearances are deceptive' is true? Why?",
        "Do you ever say someone looks good but really they don't?",
        "Has your mother ever complained about your appearance?",
        "What part of the way you look are you happiest with (and why)?",
        "How are people's appearances today different from 100 years ago?",
        "How important is a person's appearance?",
        "What could you do to improve your appearance?",
        "What could I do to improve my appearance?",
        "Has your appearance ever made you feel bad all day?",
        "Is it rude to tell someone that they need to improve their appearance?",
        "How often do you check your appearance in the mirror?",
        "How often do you talk about other people's appearances?",
        "Are people obsessed with appearance today?",
        "Is what's on the inside more important than what's on the outside?",
        "Is appearance more important in politics or show business?"
    ],
    "April": [
        "What springs to mind when you hear the word ‘April'?",
        "What do you think of the month of April?",
        "What good things happen in April?",
        "What things do you usually do in April?",
        "What do you think of the word 'April'?",
        "What are people who are born in April like?",
        "What do you think of April weather?",
        "Where is April on the list of 'the best months'?",
        "Are there any bad things about the month of April?",
        "What plans do you have for next April?",
        "What are the colours of April?",
        "Is there any delicious food you eat in April?",
        "How should people celebrate in April?",
        "What is April Fools' Day? Do you celebrate it?",
        "How do you feel when April arrives?",
        "If you made a video about April, what would you put in it?",
        "How do you feel when April is over?",
        "What three adjectives best describe April, and why?",
        "What good thing can you remember happening in April?",
        "What is a good symbol for April, and why?"
    ],
    "Arabs": [
        "Who are the Arabs?",
        "What makes an Arab an Arab?",
        "What major contributions has Arab civilization made to the world?",
        "What countries have predominantly Arab populations?",
        "What do you know of the past history of the Arabs?",
        "What do you know of the recent history of the Arabs?",
        "Have you been to any Arab countries?",
        "Does the media in your country portray a negative or positive image of Arabs?",
        "What Arab cultural influences affect today’s world?",
        "What do you know about Arabs and Western colonialism?",
        "What do all Arabs have in common?",
        "Is there one Arab country that is more influential than the others?",
        "What is the source of animosities between Arab countries and Israel?",
        "What cultural differences are there among Arabs from different Arab nations?",
        "What are the differences between the words ‘Arab’, ‘Arabic’ and ‘Arabian’?",
        "Who is the greatest Arab leader?",
        "What stereotypes of Arabs exist in your country?",
        "How much political or economic power do Arabs have in the world?",
        "What is the Arab League and how strong and unified is it?",
        "Do you think Arabs will play a greater role in world affairs in the future?"
    ],
    "Architecture": [
        "What springs to mind when you hear the word ‘architecture'?",
        "How important is architecture?",
        "What would you say about the architecture in your country?",
        "What would you learn if you studied architecture?",
        "What do you think of modern architecture?",
        "What is your favourite building in the world (and why)?",
        "What do architects need to be good at?",
        "What architecture do you like from other countries?",
        "Which country has the best architecture?",
        "What is more important – building appearance or comfort for humans?",
        "How interesting is architecture?",
        "What do you think about the architecture of your home?",
        "What would you like to change about the buildings in your town?",
        "How important are architects?",
        "Do you know any famous architects or architect companies?",
        "Which period in history has the best architecture?",
        "What is the relationship between architecture and nature?",
        "What can architects learn from nature?",
        "What is the greatest architectural achievement in history?",
        "What will architecture be like in 100 years from now?"
    ],
    "Argentina": [
        "What images spring to mind when you hear the country Argentina?",
        "What are the good things and bad things about Argentina?",
        "What is Argentina most famous for?",
        "What do you know about Argentina’s history?",
        "What are the differences between Argentina and your country?",
        "What do you think about Argentine people?",
        "What has Argentina given to the world?",
        "Would you like to visit Argentina, or live there?",
        "What do you know about the geography of Argentina?",
        "Who are the most famous Argentine people you know?",
        "How different is Argentina from other South American countries?",
        "What was the last news story you heard about Argentina?",
        "What do you think Argentina’s neighbours think of it?",
        "What do you think Argentina will be like 50 years from now?",
        "Does your country have good relations with Argentina?",
        "What could you do on a holiday in Argentina?",
        "What is your idea of a typical Argentine person?",
        "What things about Argentina do you think Argentines are proud of?",
        "What do you know about Argentine culture?",
        "What would you like to ask an Argentine about Argentina?"
    ],
    "Arguing": [
        "What springs to mind when you hear the word ‘argue'?",
        "How good are you at arguing?",
        "Are there any good things about arguing?",
        "Who is the worst person to argue with? Why?",
        "Who is the most argumentative person you know?",
        "What do people usually argue about?",
        "Is it wrong to argue with your elders?",
        "How often do you feel frustrated in an argument?",
        "What was the last argument you had?",
        "Have you ever lost a friend because of an argument?",
        "What do you like and dislike about arguing?",
        "What's the best way to win an argument?",
        "Is it best to avoid arguments?",
        "What kind of arguments do you dislike?",
        "What do you think of heated arguments?",
        "What do you think of anyone you argue with?",
        "How often do you wish you had never argued?",
        "What topics would you never argue about?",
        "What is the best way to make up after an argument?",
        "Who do you not like to see arguing? Why?"
    ],
    "Armageddon": [
        "What is Armageddon?",
        "Where does the word Armageddon come from?",
        "Armageddon is a battle that takes place at the end of the world. Who do you think the battle is between?",
        "Do you think Armageddon could happen in our lifetime?",
        "What do you think Armageddon will look like?",
        "Do you think people who believe in Armageddon are pessimists?",
        "Would you like to see a movie called “Armageddon”?",
        "What would you do the day before Armageddon?",
        "Do you think soldiers or people witnessing ethnic cleansing experience a form of Armageddon?",
        "In your country, are there people who stand in the street and warn that “the end of the world is nigh”?",
        "Do you think Armageddon, if it comes, will be human-made?",
        "Where would you like to be on the day Armageddon arrives?",
        "What would you eat the night before Armageddon arrives?",
        "Is Armageddon referred to in your religion?",
        "What do you think about Nostradamus and his predictions about Armageddon and the Apocalypse?",
        "Do you think Armageddon will be painful?",
        "What will the Earth look like after Armageddon?",
        "If just ten people could survive Armageddon, would you like to be one of them?",
        "Do you think only people who are religious believe in Armageddon?",
        "Do you think Armageddon will ever happen?"
    ],
    "Army": [
        "What’s your country’s army like?",
        "Does your country have a proud military history?",
        "How strong is your country’s army?",
        "Is your country’s army often involved in conflict?",
        "Are armies necessary?",
        "Which would you choose to join, the army, navy or air force?",
        "What do you think of a career in the army?",
        "What do you think of the US Army?",
        "Is there conscription in your country?",
        "Would you ever fight in a war?",
        "Do you think being a soldier would be interesting?",
        "What would a world with no armies be like?",
        "Is it necessary for governments to spend so much money on armies?",
        "How have armies changed over the centuries?",
        "What do you think the army lifestyle is like?",
        "What do you think of women being in the army?",
        "What do you think the feeling would be like to kill another soldier?",
        "What do you think the feeling would be like to be taken as a prisoner of war?",
        "What do you think is the worst thing about being in the army?",
        "What do you think of army uniforms?"
    ],
    "Aromatherapy": [
        "What springs to mind when you hear the word ‘aromatherapy’?",
        "What do you know about aromatherapy?",
        "Do you think aromatherapy is a good form of medicine?",
        "How does aromatherapy work?",
        "What does someone have to study to become an aromatherapist?",
        "Would you like to try aromatherapy to cure your ills?",
        "Do you think aromatherapy could be dangerous?",
        "Would you like to work as an aromatherapist?",
        "How do you think aromatherapists view people who doubt aromatherapy?",
        "Would you like to learn about aromatherapy and become your own doctor?",
        "Do you know anyone who has tried aromatherapy?",
        "What smells make you feel good?",
        "Why are the oils used in aromatherapy called ‘essential’ oils? What do you think is essential about them?",
        "Do you like the idea that aromatherapy uses natural products like lavender oil and peppermint oil?",
        "Do you think aromatherapy could be effective for reducing stress, helping you sleep, and making you study better?",
        "If aromatherapy works, why do you think it is not used in most of the world’s hospitals?",
        "Do you think aromatherapy can help with things like broken bones? How?",
        "Do you think aromatherapy is just a “hippy thing”?",
        "Do you think there are smells that are bad for our health?",
        "What would you really like to know about aromatherapy?"
    ],
    "Art": [
        "How great is your interest in art?",
        "What’s the best art gallery you’ve been to?",
        "Do you like modern art?",
        "What do you think of installation art?",
        "Do you ever think a lot of art is not really art?",
        "Do you have a favorite artist?",
        "What kind of art do you like – paintings, sculpture, ceramics, etc.?",
        "What is art?",
        "Does art change the way you think or feel?",
        "Do you think anyone can be an artist or do you need a special talent?",
        "Do you think all children should study art at school?",
        "Do you think children should learn the history of art?",
        "Do you think a painting can really be worth a million (or more) dollars?",
        "Do you think today’s artists are as good as those from hundreds of years ago?",
        "What was the last painting / poster / piece of art you bought. Why did you buy it?",
        "Describe the pieces of artwork in your house.",
        "What kind of art is your country famous for?",
        "What kind of life do you think an artist’s is?",
        "Do you have any artistic talents?",
        "How would the world be different without artists?"
    ],
    "Artificial Intelligence": [
        "What springs to mind when you hear the term ‘artificial intelligence'?",
        "What is artificial intelligence?",
        "What are the dangers of artificial intelligence?",
        "Will artificial intelligence ever be more intelligent than humans?",
        "How is artificial intelligence helping us today?",
        "What do you know about the history of artificial intelligence?",
        "What are the good things about artificial intelligence?",
        "How intelligent will artificial intelligence become?",
        "Is there a difference between artificial intelligence and robots?",
        "What would it be like to study about artificial intelligence?",
        "What are the differences between artificial intelligence and human intelligence?",
        "Will robots ever control the world?",
        "How would you like artificial intelligence to help you?",
        "What would our life be like without artificial intelligence?",
        "Will people ever have artificial intelligence as part of their brains?",
        "Will artificial intelligence ever replace the need for humans to work?",
        "How intelligent are you?",
        "What movies have you seen about artificial intelligence?",
        "What three adjectives best describe artificial intelligence?",
        "What will artificial intelligence be like in 100 years from now?"
    ],
    "Astrology": [
        "Do you believe in astrology?",
        "What’s your star sign?",
        "Do you know the characteristics someone with your star sign should have?",
        "Which other star signs are you compatible with?",
        "Do you believe there is any link between the position of the stars when you were born and your fate?",
        "Do you ever read your horoscope?",
        "What would you like the stars to hold for you?",
        "Do you think astrology can be useful?",
        "Do you think anyone can prove that astrology works?",
        "Would you like to learn astrology?",
        "Do you know all the signs of the zodiac in English?",
        "Do you think astrology is an art, a science or something else?",
        "Why do you think many religions frown on astrology?",
        "What’s the difference between astrology and astronomy?",
        "Would you ever go or pay to see an astrologist?",
        "If you had a consultation with an astrologist, what would you want to know?",
        "Would you like to know your future?",
        "Why isn’t astrology a commonly taught university subject?",
        "What would it take to convince you that astrology works?",
        "Do believe in other fortune telling, such as palm reading or determining character by blood type, etc.?"
    ],
    "Astronauts": [
        "Would you like to be an astronaut?",
        "Did you ever want to be an astronaut?",
        "Would you like to go to the moon or travel into space?",
        "What kinds of people become astronauts?",
        "Would you like to experience zero gravity and weightlessness?",
        "What do you think are the biggest challenges of being an astronaut?",
        "What do you think would be the highlights of space travel?",
        "Could you date or marry an astronaut?",
        "What do you think astronauts worry about?",
        "Do you think it would get boring in space?",
        "How important is the job of an astronaut?",
        "If you were offered a job to be an astronaut, would you take it?",
        "What kinds of feelings and emotions do you think you would have on the morning of a journey into space?",
        "What small personal item would you take with you on a journey into space?",
        "Do you have the personality to be an astronaut?",
        "What do you think when you see men walking on the moon or astronauts doing space walks?",
        "Would you rather have a male or female commander on your first trip into space?",
        "If you spent six months in space, what would you do first when you came back to Earth?",
        "What would you say to an alien if you met one in space?",
        "Which country do you think will be the first to send astronauts to Mars?"
    ],
    "August": [
        "What springs to mind when you hear the word ‘August'?",
        "What do you think of the month of August?",
        "What good things happen in August?",
        "What things do you usually do in August?",
        "What do you think of the word 'August'?",
        "What are people who are born in August like?",
        "What do you think of August weather?",
        "Where is August on the list of 'the best months'?",
        "Are there any bad things about the month of August?",
        "What plans do you have for next August?",
        "If you made an August festival, what would it be like?",
        "Is there any delicious food you eat in August?",
        "How should people celebrate in August?",
        "What famous holidays are there in August?",
        "How do you feel when August arrives?",
        "If you made a video about August, what would you put in it?",
        "How do you feel when August is over?",
        "What three adjectives best describe August, and why?",
        "What good thing can you remember happening in August?",
        "What is a good symbol for August, and why?"
    ],
    "Aung San Suu Kyi": [
        "What do you know about Aung San Suu Kyi?",
        "How would you describe Aung San Suu Kyi’s personality?",
        "What are your opinions of Aung San Suu Kyi?",
        "Why did she win the Nobel Peace Prize?",
        "Why doesn’t the world help her?",
        "Why does Burma’s military junta keep her under house arrest?",
        "Do you think Aung San Suu Kyi will see democracy in Burma?",
        "Should we say ‘Myanmar’ or ‘Burma’?",
        "What does Aung San Suu Kyi want to change in her country?",
        "What questions would you like to ask Aung San Suu Kyi?",
        "What is the most recent news you have heard on Aung San Suu Kyi?",
        "What’s the best thing people around the world can do to help her?",
        "How would she change her country if she came to power?",
        "Does Britain have a responsibility as a former colonial power to free her?",
        "Where do you think Aung San Suu Kyi gets her inspiration?",
        "What do you know of the Burmese Junta’s human rights record?",
        "Which living or historical figures would you compare Aung San Suu Kyi to?",
        "“The only real prison is fear, and the only real freedom is freedom from fear.” What do you think about her quote?",
        "What do you think Aung San Suu Kyi’s future is?",
        "What lessons can we learn from Aung San Suu Kyi?"
    ],
    "Australia": [
        "What do you know about Australia?",
        "What is your image of Australian culture?",
        "What do you think of Australian people?",
        "What important roles does Australia play in the world?",
        "What is Australia most famous for?",
        "What have you heard about the famous Aussie lifestyle?",
        "Would you like to live in Australia?",
        "Does your country have good relations with Australia?",
        "Do you like koalas and kangaroos?",
        "Who are the most famous Australian people?",
        "What images spring to mind when you think of Australia?",
        "Why do you think Australians are so crazy about sport?",
        "What do you know about Australia’s natural wonders?",
        "Do you know any Aussie vocabulary?",
        "Why is Australia called the land ‘down under’?",
        "What have Australians contributed to the world?",
        "Do you like Australia’s prime minister?",
        "What do you know about Australia’s Aboriginal peoples?",
        "What questions would you like to ask an Australian?",
        "What do you think his / her answer would be?"
    ],
    "Avian Bird Flu": [
        "How concerned are you about avian bird flu?",
        "What do you know about avian bird flu?",
        "Do you think the world is treating the threat seriously enough?",
        "Influenza killed up to 40 million people in 1918. Do you think avian bird flu could be as deadly?",
        "What is your government doing to protect your country?",
        "What do you think is the best way to avoid the avian bird flu virus?",
        "Do you think world governments and agencies are coordinated enough in fighting avian bird flu?",
        "Has your government provided a lot of information to help you understand avian bird flu?",
        "Does your country import live chickens?",
        "Do you think you might become suspicious of flocks of wild birds?",
        "What would you do if a human-to-human strain found its way into your country?",
        "Do you think your country has enough vaccines to cope with a pandemic?",
        "What would you do if your neighbour had avian bird flu?",
        "Avian bird flu has killed relatively few people. Are people over-reacting to the dangers?",
        "Do you know what the symptoms of avian bird flu are?",
        "Would you travel to countries which have had reported cases of avian bird flu?",
        "Do you think avian bird flu will disappear the way the SARS virus disappeared?",
        "How can a government stop the virus from entering the country?",
        "Will you now think twice about eating chicken?",
        "Would you ever eat raw chicken or raw eggs?"
    ],
    "Azerbaijan": [
        "What images spring to mind when you hear the country Azerbaijan?",
        "What are the good things and bad things about Azerbaijan?",
        "What is Azerbaijan most famous for?",
        "What do you know about Azerbaijan’s history?",
        "What are the differences between Azerbaijan and your country?",
        "What do you think about Azeri people?",
        "What has Azerbaijan given to the world?",
        "Would you like to visit Azerbaijan, or live there?",
        "What do you know about the geography of Azerbaijan?",
        "Who are the most famous Azeri people you know?",
        "How different is Azerbaijan from other Asian/European countries?",
        "What was the last news story you heard about Azerbaijan?",
        "What do you think Azerbaijan’s neighbours think of it?",
        "What do you think Azerbaijan will be like 50 years from now?",
        "Does your country have good relations with Azerbaijan?",
        "What could you do on a holiday in Azerbaijan?",
        "What is your idea of a typical Azeri person?",
        "What things about Azerbaijan do you think Azeris are proud of?",
        "What do you know about Azeri culture?",
        "What would you like to ask an Azeri about Azerbaijan?"
    ]
}
