export default {
    "Hacking": [
        "What do you know about hacking?",
        "Why do you think hackers do what they do?",
        "Do you think hackers add to new technology developments?",
        "What do you think technology companies think about hackers?",
        "Are you worried someone could hack into your computer?",
        "What could you lose if someone hacked into your computer and how upset would you be?",
        "Do you always download security updates to protect your computer from hackers?",
        "Do you think large companies fear hackers?",
        "Who do you think is ahead of the game, the hackers or the software companies?",
        "What kind of damage could terrorist hackers do?",
        "Have you heard of any big hacking cases?",
        "Many companies hide hacking attempts against them because of public relations embarrassment. Do you think hacking is a bigger problem than we hear about?",
        "What punishment should a hacker receive?",
        "What do you think of the schoolchild hackers that get in the news?",
        "Do you think your computer is becoming less or more secure?",
        "Do you think it’s possible for a hacker to steal and take over your whole identity and life?",
        "Do you think a hacker could take over another country?",
        "Do you worry that hackers read your e-mail or credit card details?",
        "What question would you like to ask a hacker?",
        "What do you think his / her answer would be and why?"
    ],
    "Hair": [
        "Are you happy with your hair?",
        "What would the world be like if no one had hair?",
        "How does hair change the way we look?",
        "What kind of hair would you really like?",
        "How has your hairstyle changed over the past few years?",
        "Did you have a hairstyle a long time ago that you think is embarrassing now?",
        "Do you like reading magazines about hair?",
        "Do you worry about hair loss, thinning hair or grey hair?",
        "What do you think of men who are going bald and comb their hair over their head?",
        "Do you dye your hair (or would you dye your hair)?",
        "How important is hair?",
        "Do we need hair?",
        "How much time do you spend in the morning doing your hair?",
        "Do you think being a hair stylist is a good job?",
        "Do you ever have a bad hair day?",
        "What problems do you have with your hair?",
        "How often do you look at and arrange your hair every day?",
        "Do you like having your hair cut?",
        "Would you prefer to have straight, wavy, curly or shaggy hair?",
        "What hair products do you buy on a regular basis?"
    ],
    "Halloween": [
        "Do you celebrate Halloween?",
        "Do you think all countries should celebrate Halloween?",
        "Do you think it’s dangerous for children to go trick-or-treating?",
        "Why don’t Christians celebrate Halloween?",
        "What do you think is the best costume for Halloween?",
        "Do you think Halloween was better a few decades ago or is it better now?",
        "How old is too old to go trick-or-treating?",
        "Do you think Halloween is scary?",
        "What would an alien think of humans if it came to Earth and saw Halloween?",
        "What do you think the black and orange colors of Halloween mean?",
        "What do you think about Halloween?",
        "What do you know about the history of Halloween?",
        "How does Halloween affect American culture?",
        "What do pumpkins have to do with Halloween?",
        "Why do people trick-or-treat on Halloween?",
        "Do you think it’s dangerous these days to open your door to a trick-or-treater?",
        "How did Halloween get its name?",
        "What’s the best Halloween movie you’ve seen?",
        "What are the best Halloween games?",
        "What is the best Halloween food?"
    ],
    "Hands": [
        "Do you like your hands?",
        "How would you describe your hands?",
        "Are you left or right-handed?",
        "Do you do anything to take care of your hands?",
        "Have you ever hurt your hands?",
        "Do you know the names of all the different parts of your hands?",
        "How do you communicate with your hands?",
        "Can you walk on your hands or do handstands?",
        "Who do you like holding hands with?",
        "How often do you wash your hands?",
        "How important are your hands?",
        "Do you like things that are hand painted/made/crafted…?",
        "What hand signals do you use in your language – Are they different from those in English?",
        "Do you have a good handshake?",
        "Do you agree that many hands make light work?",
        "How do you express your feelings by putting your hands on different parts of your body?",
        "What does it mean if someone calls you a safe pair of hands?",
        "Are there times you’d like an extra pair of hands?",
        "What experiences do you have oh hands on learning?",
        "Do people ever ask you to give them a hand?"
    ],
    "Hangovers": [
        "What do you imagine when you hear the word ‘hangover’?",
        "Do you get hangovers?",
        "What is the best cure for a hangover?",
        "Why do some people get worse hangovers than others?",
        "Do you have any sympathy for people with a hangover?",
        "Do you think having a bad hangover is a good excuse to take a day off sick from work?",
        "Why don’t people stop drinking forever after a bad hangover?",
        "What are the symptoms of a hangover?",
        "What do people usually do when they have a hangover?",
        "Do you think scientists will ever produce a cure for hangovers?",
        "How long do hangovers last for?",
        "What do you think when you see someone nursing a hangover?",
        "Do you think hangovers are or can be dangerous?",
        "Has a bad hangover ever stopped you from missing something or doing something important?",
        "What do you eat when you have a hangover?",
        "Some people believe in the “hair of the dog” – having another alcoholic drink – as a hangover cure. Do you think this is good?",
        "What do you think the hangover blues are?",
        "Why do you think a hangover is called a hangover?",
        "What do you know about the science and biology of hangovers?",
        "How many times do you think the average drinker says ‘never again’?"
    ],
    "Harry Potter": [
        "Are you into Harry Potter?",
        "Do you think the Harry Potter series is a literary classic?",
        "Have you read any of the Harry Potter books in English?",
        "Are you surprised that the Harry Potter author J.K. Rowling is the highest-earning novelist in history?",
        "What would you do if you were a witch or wizard?",
        "Religious groups say the Harry Potter books are dangerous as they promote witchcraft among children. What do you think of this?",
        "Do you think J.K. Rowling should write an eighth Potter book?",
        "What impact has Potter made in your country?",
        "The Harry Potter books took 17 years to write. Can you imagine spending so long on a creative project?",
        "What questions would you like to ask J.K. Rowling, the Harry Potter creator?",
        "Why do you think the Harry Potter books are so popular?",
        "What do you know about the author of Harry Potter?",
        "Which is better, the Harry potter books or the movies?",
        "Have you ever been caught up in Pottermania?",
        "Did you buy the Harry Potter books the day they went on sale?",
        "Who is your favourite Harry Potter character?",
        "What is the best book?",
        "Would you like to study at Hogwart’s School of Witchcraft and Wizardry?",
        "Have you ever bought any Potter merchandise?",
        "British Prime Minister Gordon Brown said, \"I think JK Rowling has done more for literacy around the world than any single human being.\" What do you think of this?"
    ],
    "Hate": [
        "Why do people hate?",
        "Do you think animals hate?",
        "Do you think everyone has the same feelings of hate?",
        "Can hate be a positive emotion?",
        "Do you think anyone hates you?",
        "How often do you say you hate this person or you hate that person?",
        "Have you ever said the words “I hate you” and meant it?",
        "Does hatred come from the head or the heart?",
        "What’s the best way to stop feeling hatred towards someone or something?",
        "What do you know about hate crimes. Do they happen in your country?",
        "Do you think the emotion of hate will ever disappear from humans?",
        "What things or people do you hate?",
        "What do you think is the worst kind of hate?",
        "What do you hate most in this world?",
        "What would you do if you got hate mail?",
        "Do you ever hate yourself?",
        "Is it more common for women to hate men or men to hate women? Why?",
        "Who is the biggest figure of hate in your country / the world?",
        "Do you have any pet hates (things you love to hate)?",
        "What food do you really, really hate?"
    ],
    "Having Children": [
        "Do you have or want children? Why?",
        "Have you had much experience with children?",
        "Do you like children of all ages (babies, toddlers, adolescents/teenagers)?",
        "Do you think everyone should have children?",
        "How many children should people have?",
        "What’s your opinion of people who choose not to have children?",
        "What’s your understanding of the terms “childless” and “childfree”?",
        "What do you think of clubs for childless and childfree people ?",
        "Why would people without kids join such clubs?",
        "Is it better to have children or not have them?",
        "What are some good and bad reasons for having children?",
        "What are some good and bad reasons for not having children?",
        "Should people who have hereditary diseases have children?",
        "Should people who can’t afford children have them anyway?",
        "What about people who don’t enjoy the company of children?",
        "How old should a person be before they have children?",
        "Should a single person have children?",
        "What do you think of same-sex couples having children?",
        "How old is too old to have a baby?",
        "If you couldn’t have children, would you adopt?"
    ],
    "Health": [
        "How is your health?",
        "Do you do anything to stay healthy?",
        "Do you worry about the health of those around you?",
        "Do you ever worry about your own mental health?",
        "Have you ever stopped doing something for your health?",
        "Are you always a picture of health when you wake up in the morning?",
        "What are the health risks associated with your lifestyle and environment?",
        "What health problems do you worry about most?",
        "What is the WHO and what does it do?",
        "What can you do to improve your health?",
        "Do you worry about your health?",
        "Are you a health-conscious person?",
        "Do you read magazines or newspaper articles about health?",
        "What things do you do that might damage your health?",
        "How often do you have a health check?",
        "Have you ever been in poor or ill health?",
        "Where do you go to get information on health?",
        "Who are the healthiest people in the world and why are they so healthy?",
        "What are the best and worst jobs for your health?",
        "How is the health of your computer / the economy / the planet?"
    ],
    "Healthcare": [
        "How is the health care in your country?",
        "Is the health care in your country getting better or worse?",
        "Is health care in your country free for some people?",
        "Which country do you think has the best health care?",
        "Which is better, private or public health care?",
        "Are health care workers well paid in your country?",
        "Do you ever think about health care for when you are old?",
        "What is health care like for old and poor people in your country?",
        "What happens to people in poor countries who cannot afford health care?",
        "Is your country’s health care system in need of reform?",
        "Is health care in your country fair to everyone?",
        "What are the most important health care issues in your country?",
        "What are the most important health care issues in the world?",
        "What do you think the health care issues of the future will be?",
        "What do you know about the history of health care in your country?",
        "What are the health care problems in your country?",
        "What do you know about the cost of health care in your country?",
        "Do you think universal health care will ever come to the world?",
        "How big an issue is health care in your national elections?",
        "What questions would you like to ask health care workers?"
    ],
    "Heart": [
        "What comes to mind when you hear the word ‘heart’?",
        "What do you know abut the human heart?",
        "Do you ever think about your heart?",
        "Do you worry about having heart problems?",
        "Is there a history of heart disease in your country?",
        "Do you know the names of the different parts of the heart?",
        "What do you know about heart transplants?",
        "What do you think of transplanting an animal heart into a human?",
        "Does your heart ever miss a beat?",
        "Where do you think the romantic heart shape comes from?",
        "Do you have a lifestyle that looks after your heart?",
        "When and how do you think a human heart first starts beating?",
        "What things are really bad for your heart?",
        "What do you know about heart attacks?",
        "When does your heart pound?",
        "Have you ever had a broken heart?",
        "What can you do to look after your heart?",
        "What do you know about your heart rate?",
        "Do you think governments should do more to reduce heart disease in your country?",
        "Do you think scientists will produce a mechanical heart one day that will be able to work forever?"
    ],
    "Heaven": [
        "What springs to mind when you hear the word ‘heaven’?",
        "Do you think anyone can go to heaven?",
        "Is there just one heaven or a different one for different religions?",
        "What aspects of heaven are here on Earth?",
        "What colours, smells, tastes and sights will be in heaven?",
        "What are the biggest differences between heaven and Earth?",
        "What will you miss most about Earth in heaven?",
        "What do you think a guide book to heaven would contain?",
        "What language do you think is spoken in heaven?",
        "Do you think there’ll be computers and the Internet in heaven?",
        "Do you think you’ll go to heaven?",
        "What do you think heaven looks like?",
        "What do you think you’ll look like in heaven?",
        "Do you think there’ll be anything boring about being in heaven?",
        "What do you think people do every day in heaven?",
        "Do you think we continue relationships in heaven?",
        "What kind of heavenly bodies (angels, gods…) do you think we’ll meet in heaven?",
        "What emotions will we leave behind once we get to heaven and what new emotions will we encounter?",
        "Do you think there are rules in heaven?",
        "Will we remember Earth or be able to look down on Earth once we’re in heaven?"
    ],
    "Heroes": [
        "Who is your hero?",
        "Are most of your heroes male or female?",
        "Are you a hero to anyone?",
        "Who is your country’s biggest national hero and why?",
        "Is there a local hero in your town?",
        "What makes a hero a hero?",
        "Do you think one person’s hero is another person’s villain?",
        "What do you think of hero worship?",
        "Do you think rock stars are really heroes?",
        "Do you think sports stars are bigger heroes than rock stars?",
        "Do you have a sporting hero?",
        "What do you think an accidental hero is and how does he/she become a hero?",
        "What do you think an unsung hero is?",
        "What do you think of this quote: “We can all be heroes in our virtues, in our homes, in our lives”?",
        "And this one: “A hero's greatest act is to lay down his sword”?",
        "Do you think soldiers and police officers are heroes?",
        "What do you know about Guitar Hero and Monkey hero?",
        "Is it important to have heroes?",
        "Who were your heroes when you were a child?",
        "What questions would you ask your hero if you met him/her?"
    ],
    "Hip Hop": [
        "What images come to mind when you hear the word ‘hip hop’?",
        "What do you think of hip hop?",
        "Is American hip hop the best?",
        "What different kinds of hip hop do you know about?",
        "What do you know about the history of hip hop?",
        "Why does hip hop sometimes have a negative image?",
        "How would you define hip hop as a musical style?",
        "What impact has hip hop had on the culture of your country?",
        "Who are the biggest hip hop stars?",
        "What is hip hop fashion?",
        "What do you think of international hip hop?",
        "What are the differences between hip hop and rap?",
        "What do your parents think of hip hop?",
        "What are your favourite hip hop songs?",
        "What makes hip hop so popular?",
        "Do you think hip hop is replacing rock music?",
        "Can you rap?",
        "Do you understand why some people think hip hop isn’t music?",
        "Do you think hip hop music gives a voice to people who follow it?",
        "Who’s best – Eminem or 50 Cent, Beyonce Knowles or Missy Elliot?"
    ],
    "History": [
        "Is history important to you?",
        "Did you like studying history at school?",
        "What period of history interests you most?",
        "What do you think of the recent history of your country – the past fifty years?",
        "What do you know about the early history of your country",
        "What do you think of the overall history of your country?",
        "Do you think history repeats itself?",
        "What period of history would you like to go back and live in?",
        "Napoleon Bonaparte said “History is a set of lies agreed upon”. Do you agree with this?",
        "“Half of writing history is hiding the truth.” What do you think of this quote in relation to what was in your school history books?",
        "Why do people like history?",
        "What do you know about your family history?",
        "Is there a history of illness in your family?",
        "Would you like to be a historian?",
        "In his book 1984, George Orwell says: “He who controls the past, controls the future; and he who controls the present, controls the past.” Do you agree? Does this apply to countries today?",
        "Which people in the world have a troubled history?",
        "Do you think history comes back to haunt us?",
        "Does your country have a proud or violent history?",
        "How would the world change if schools stopped teaching history to children and all history books were destroyed?",
        "Sir Winston Churchill said: “Those that fail to learn from history, are doomed to repeat it.” Do you agree with him?"
    ],
    "Hitch-hiking": [
        "What springs to mind when you hear the word ‘hitchhiking’?",
        "Have you ever hitched a ride?",
        "Is hitchhiking common in your country?",
        "Have you ever picked up or would you ever pick up a hitchhiker?",
        "What country would you like to hitchhike across?",
        "What is the best way to get a ride?",
        "What safety precautions should you take when hitchhiking?",
        "How safe or dangerous is hitchhiking in your country?",
        "Do you think hitchhiking is a fun way to travel around?",
        "Would you hitchhike home late at night if you missed the bus?",
        "Why do you think people like hitchhiking?",
        "Have you read any books or seen any movies about hitchhikers?",
        "Many people have a romantic image about hitchhiking. Why is this?",
        "Do you think you meet interesting people as a hitchhiker / driver who picks up hitchhikers?",
        "Are there different dangers to men picking up female hitchhikers and women picking up male hitchhikers?",
        "What would you talk about if you hitched a ride or picked up a hitchhiker?",
        "What kind of people would you not stop for if you saw them trying to thumb a ride?",
        "What kind of cars would you not get into if you were hitchhiking?",
        "Word partners of the words ‘hitchhiker’ and ‘hitchhiking’ are ‘psychopath,’ ‘puke’ and ‘prostitute’. What do you think this says about hitchhiking?",
        "Do you think hitchhiking should be made illegal?"
    ],
    "Holidays": [
        "Do you like holidays?",
        "What holidays do you celebrate?",
        "What holidays do you really look forward to?",
        "Are there holidays in other countries or religions that you wish were also celebrated in your country?",
        "Are there enough holidays in your country for which workers get the day or days off?",
        "What do you think is the most overrated holiday?",
        "Are there any special occasions or anniversaries you think deserve to be a public holiday but are not?",
        "Do you usually need a holiday after your holiday?",
        "Is it better to stay at home on holidays or go somewhere?",
        "Are holidays where the whole country is travelling stressful?",
        "How would you feel if there weren’t any holidays?",
        "What holiday food do you like?",
        "What are the pros and cons of spending holidays with your family, with your friends, or alone?",
        "Do you think holidays are too commercialized?",
        "Do you put on weight during certain holidays?",
        "Are there holidays in you country that have come from other countries (Valentine’s, Halloween…)?",
        "What’s it like moving around your country during holiday time?",
        "Do you like what’s on TV during holiday times in your country?",
        "What would happen if no one in your country worked during a 3-day holiday?",
        "Do you think there should be a world holiday for everyone on Earth to celebrate together?"
    ],
    "Home Schooling": [
        "Do you think home schooling is a good idea?",
        "What are the advantages of hone schooling?",
        "What kind of children benefit from home schooling?",
        "Would you have preferred home schooling or going to school?",
        "Do you think home schooling hinders a child’s development?",
        "Do children who are home schooled get the social skills they need?",
        "How do parents get all the materials they need for home schooling?",
        "A report found that 58.9% of adults who were home schooled are \"very happy\" with life, compared with 27.6% for the general U.S. population. Is this a good reason to encourage home schooling?",
        "Would you be different today if you’d been home schooled?",
        "Is home schooling gaining popularity in your country?",
        "Would you consider home schooling your children?",
        "Parents home school their children because they think they can educate their children better than schools. Do you think they can?",
        "An American report says home schooled children do much better academically than school children. What do you think about this?",
        "Home schooling avoids many problems such as bullying. Should governments encourage more home schooling?",
        "A U.S. report stated: \"Where possible, children should be withheld from formal schooling until at least ages eight – ten.\" Do you agree?",
        "Would you know how to home school children?",
        "Do you think governments should pay parents for home schooling?",
        "Do you think home schooled children would easily adapt to school?",
        "Do you think kids who go to school would like home schooling?",
        "Do you think children would prefer home schooling or regular schooling?"
    ],
    "Homelessness": [
        "What goes through your mind when you hear the word ‘homeless’?",
        "Do you ever give money to homeless people?",
        "Is homelessness a problem in your country?",
        "What does your government do for the homeless?",
        "What does homelessness say about a society?",
        "Why do you think people become homeless?",
        "What do you think when you walk past homeless people?",
        "How difficult do you think it is for homeless people to get back into employment, get a house, etc?",
        "If you were homeless, where and how would you live?",
        "What do you think it would be like to suddenly become homeless?",
        "Are there homeless children in your country?",
        "Why does the government allow homelessness?",
        "Why do many people look down on the homeless?",
        "What can you do to help the homeless?",
        "If you were homeless, what would you do all day?",
        "Would you give a homeless person a shower and a bed for the night in your home?",
        "Do homeless people lose their civil or human rights in your country?",
        "What do / would you care about more in an election, taxes of the plight of the homeless?",
        "Do you think homelessness will ever disappear, even in rich countries?",
        "What questions would you ask a homeless person?"
    ],
    "Hometown": [
        "What springs to mind when you hear the word ‘hometown’?",
        "What do you think of your hometown?",
        "Would you like to live in your hometown forever?",
        "What is there to do in your hometown?",
        "What are your happiest hometown memories?",
        "How could your hometown be better?",
        "What is the geography of your hometown?",
        "What are the biggest industries or employers in your hometown?",
        "Is your hometown famous for anything?",
        "What would you do if you were mayor of your hometown?",
        "What are the good and bad things about your hometown?",
        "How proud are you of your hometown?",
        "What's the worst experience you've had in your hometown?",
        "What was it like growing up in your hometown?",
        "What things would you take a visitor to see in your hometown?",
        "What are the people like in your hometown?",
        "What is your hometown like for shopping?",
        "What are public services like in your hometown?",
        "How would you describe your hometown in five adjectives?",
        "What do you think your hometown will be like in 50 years from now?"
    ],
    "Homework Activities": [
        "What comes to mind when you hear the word ‘homework’?",
        "What do you think when your teacher says you’re going to have some homework?",
        "What kind of homework do you like most?",
        "Do you like the homework activities your teacher gives you?",
        "What happens when you don’t do your homework?",
        "Would you like your teacher to give you more or less homework?",
        "How important do you think homework is?",
        "Do you always understand the reasons why the teacher asks you to do a particular homework activity?",
        "Do you have a special routine and place to study when you do homework?",
        "Do you have a different attitude to English homework now than you did when you were younger?",
        "Do you ever do homework in class?",
        "Do you ever think homework is a waste of time?",
        "Do you think it’s better if you choose the things to study at home and set your own homework?",
        "Do you think life outside the classroom is like a kind of ongoing homework?",
        "Do you ever do your homework with friends or ask someone to help you?",
        "What advice would you give to a student who says he/she hates homework?",
        "Do you think your teacher spends enough time looking at your homework?",
        "What was the last piece of homework you really loved doing?",
        "Do you think you need a homework after every class?",
        "What questions would you like to ask your teacher about homework?"
    ],
    "Hong Kong": [
        "What images spring to mind when you think of Hong Kong?",
        "What are the good things and bad things about Hong Kong?",
        "What is Hong Kong famous for?",
        "What do you know about Hong Kong history?",
        "What images of Hong Kong do you have that you really like?",
        "What do you think of Hong Kong food?",
        "What has Hong Kong given to the world?",
        "Would you like to visit Hong Kong, or live there?",
        "Is Hong Kong an important part of the world?",
        "Who are the most famous Hong Kong people you know?",
        "How different is Hong Kong from the rest of China?",
        "Do you think Hong Kong is one of the world’s top tourist sites?",
        "Do you think Hong Kong should be a separate country?",
        "What do you know about Hong Kong’s past?",
        "Does your country have good relations with Hong Kong?",
        "What do you know about Hong Kong politics?",
        "What is your idea of a typical Hong Kong person?",
        "What things about Hong Kong do you think Hong Kong people are proud of?",
        "What do you think Hong Kong will be like fifty years from now?",
        "What would you like to ask a Hong Kong person about Hong Kong?"
    ],
    "Horoscopes": [
        "Do you believe in horoscopes?",
        "Do you ever check your horoscope?",
        "Who writes horoscopes and how qualified do you think they are?",
        "Is it possible to predict future events just by someone’s star sign?",
        "Why is it that the things written in horoscopes are always so boring?",
        "If horoscopes are true, we all follow one of twelve future paths. What do you think of this?",
        "What kind of person is someone with your star sign?",
        "What aren’t there horoscopes in serious newspapers?",
        "Do you think it’s strange that in the twenty-first century people get paid to write horoscopes?",
        "Do you know anyone who checks his/her horoscope religiously?",
        "What do you think about what is written in horoscopes?",
        "What kinds of people believe in and follow horoscopes?",
        "Do you think there are horoscopes in every country?",
        "Can you think of a typical horoscope prediction?",
        "Why would anyone think the position of the stars and sun can tell us whether or not you’ll meet the man/woman of your dreams on Tuesday night?",
        "Do you think horoscope writers believe in what they write and predict",
        "What would you like your horoscope to say?",
        "What does your religion say about horoscopes?",
        "Do you think horoscopes could be dangerous?",
        "What questions would you like to ask a horoscope writer?"
    ],
    "Hospitals": [
        "What comes to mind when you hear the word ‘hospital’?",
        "What are your experiences of hospitals?",
        "Would you like to work in a hospital?",
        "Are the hospitals in your country good?",
        "Is the standard of care in your country’s hospitals getting better?",
        "Do you like watching TV programmes about hospitals?",
        "Is it better to be born in hospital or at home?",
        "Why is hospital food so bad?",
        "Do you think hospitals are unhealthy places?",
        "What do you think of a government that's lets its hospitals close down?",
        "Have you ever stayed in hospital?",
        "What do you think hospitals of the future will be like?",
        "Have you ever been to a hospital in another country?",
        "What part of a hospital would you most like a tour of?",
        "Do you think hospitals are happy or sad places?",
        "How could hospitals be made better places to visit and stay in?",
        "What do you think a boutique hospital is?",
        "What do people do if they cannot afford to go to hospital?",
        "Who are the most important people working in hospitals?",
        "What would you do every day if you had to spend six months in hospital?"
    ],
    "House and Home": [
        "Are you a ‘house and home’ person?",
        "What’s your favourite thing about your home?",
        "What is your dream home?",
        "What home improvements would you like to make to your home?",
        "Are you happy with the colour scheme and furniture in your home?",
        "Would you rather live in a house or an apartment?",
        "Do you agree that ‘home is where the heart is’?",
        "Do you like being at home alone?",
        "What are the differences between a house and a home?",
        "Do you like the houses in other countries?",
        "What comes to mind when you hear the word ‘home’?",
        "Are you a stay-at-home person or a going-out person?",
        "Do you do homework and housework?",
        "Do you or would you like to own your own home?",
        "Are you house proud?",
        "Is there anything you hate about your home?",
        "Do you get jealous of other people’s homes?",
        "Would you like to work at home?",
        "Do you like the location of your home?",
        "Would you like to design your own home?"
    ],
    "Housing": [
        "What springs to mind when you hear the word ‘housing’?",
        "Is there a problem with housing in your country?",
        "Does your government provide housing for people on low or no income?",
        "Are you interested in the state of the housing market?",
        "Is it easy to find good quality housing in your town?",
        "What are the housing estates / housing projects like in your area?",
        "Do you think there’ll be housing shortages in your town / country in the future?",
        "Do you think everyone on a low income should get a housing allowance / housing benefit?",
        "If you belonged to your local housing association, what points would you consider raising?",
        "What do you think of the sheltered housing system in which governments provide accommodation for the aged and homeless?",
        "Is there a minister for housing in your government and does he/she do a good job?",
        "How can housing be made affordable for everyone?",
        "Do you think the housing situation in your country is better than that in your neighbouring countries?",
        "Do you know anything about your government’s housing policy?",
        "Have you ever seen very poor quality housing?",
        "What happens in your country when there is a housing boom or a housing slump?",
        "Do you understand how and why poor housing figures in the USA in October 2007 affected the world’s economies?",
        "What issues will arise with housing of the future?",
        "Which countries have major problems with housing?",
        "What would housing on the Moon or Mars look like?"
    ],
    "How tos": [
        "Do you know how to be a good listener?",
        "Do you know how to see in the dark?",
        "Do you know how to train for a marathon?",
        "Do you know how to use Windows and Apple computers?",
        "Do you know how to make people very happy?",
        "Do you know how to lose weight fast?",
        "Do you know how to get the guy / girl of your dreams?",
        "Do you know how to get an upgrade to Business or First Class?",
        "Do you know how to get rich quick?",
        "Do you know how to use English punctuation correctly?",
        "Do you know how to take really good photos?",
        "Do you know how to make bread?",
        "Do you know how to make friends?",
        "Do you know how to look your best?",
        "Do you know how to handle jealousy?",
        "Do you know how to get good grades in your English exams?",
        "Do you know how to look after a baby?",
        "Do you know how to overcome fear?",
        "Do you know how to look ten years younger?",
        "Do you know how to lie?"
    ],
    "Human rights": [
        "What are human rights?",
        "Do you feel you have all the human rights you need?",
        "Do you ever feel your human rights are being violated?",
        "Does your government have a good record on human rights?",
        "Which countries do you think have the worst human rights records and why do you think this is so?",
        "Do you think all people in the world are equal and everyone deserves the same rights?",
        "Which people in your country have ‘more equal rights’ than others?",
        "Do you think each government should have a minister/secretary for human rights?",
        "Are you interested in reading and watching news stories on human rights?",
        "Do you give money to human rights charities?",
        "What human rights do you know about?",
        "What do you know about the Universal Declaration of Human Rights?",
        "What human right is the most important?",
        "Do you think people should visit countries with bad human rights records?",
        "How can the world make sure human rights are protected?",
        "Do unborn children have human rights?",
        "Do you think everyone in the world will one day have the same human rights?",
        "How would the world be different if all human rights were respected?",
        "Do religions respect human rights?",
        "Do you always respect other people’s rights?"
    ],
    "Hunting": [
        "What springs to mind when you hear the word ‘hunting’?",
        "Are you for or against hunting?",
        "Would you like to go hunting?",
        "What kind of hunting is there in your country?",
        "What do you think of trophy hunting?",
        "Do you think it’s OK for people to hunt elephants and whales?",
        "What do you think of people hunting animals for fur?",
        "Do you think hunting is a sport?",
        "Do you think hunting around the world should only be allowed for food?",
        "What are your experiences of job hunting?",
        "What are the differences between hunting and fishing?",
        "Why do you think people get a thrill from hunting and killing animals?",
        "What damage is big game hunting doing in Africa?",
        "Do you think it’s OK to hunt pests?",
        "What hunting methods do you know of that are very cruel?",
        "What do you think of the term ‘blood sports’ to describe hunting?",
        "How has hunting changed over the ages?",
        "Do you think all hunting will be illegal in the future?",
        "Would you like to go on a hunting expedition?",
        "Would you go hunting if you lived in the jungle?"
    ]
}
