export default {
    "Qatar": [
        "What images spring to mind when you hear the country Qatar?",
        "What are the good things and bad things about Qatar?",
        "What is Qatar most famous for?",
        "What do you know about Qatar’s history?",
        "What do you know about Qatar’s plans for its future?",
        "What do you think about Qataris?",
        "What has Qatar given to the Gulf?",
        "Would you like to visit Qatar, or live there?",
        "What do you know about the geography of Qatar?",
        "Who are the most famous Qataris you know?",
        "How different is Qatar from other Gulf or Arab countries?",
        "What do you know about Qatari business?",
        "Do you think investing in Qatar would be a good investment?",
        "What do you think Qatar will be like 50 years from now?",
        "Does your country have good relations with Qatar?",
        "What do you think about Qatar’s leaders?",
        "What is your idea of a typical Qatari?",
        "What things about Qatar do you think Qataris are proud of?",
        "What do you know about Qatari politics?",
        "What would you like to ask a Qatari about Qatar?"
    ],
    "Qualifications": [
        "What comes to mind when you hear the word ‘qualification’?",
        "What do you think of qualifications?",
        "What qualifications do you have?",
        "What qualifications would you like to have?",
        "Which qualifications do you think are best to have?",
        "Do you think everybody needs qualifications?",
        "Do all qualifications need to be recognized by employers?",
        "Do you think some qualifications are a waste of time and money?",
        "What are the minimum qualifications needed to do the job you have / want?",
        "What qualifications would you expect your English teacher to have?",
        "Are qualifications important to you?",
        "Would you rather have a well-qualified teacher with little experience or a very experienced teacher with no qualifications?",
        "Do you think everyone should do a qualification in first aid?",
        "Do you think there should be minimum qualifications for politicians and presidents?",
        "What qualifications does your country’s leader have for his/her job?",
        "Do you think qualifications should be the same in each country so they can be used all over the world?",
        "What do you think of the idea of a parenting qualification that all future parents must study for?",
        "Have you ever lied (would you ever lie) about the qualifications on your resume in order to get a really good job ?",
        "Is it possible to be overqualified for a job (i.e. to have too many qualifications)?",
        "Do all qualifications need to be of the paper variety?"
    ],
    "Quality": [
        "What comes to mind when you hear the word ‘quality’?",
        "Would you rather have quality or quantity?",
        "Do you always believe a company that says its products are of the highest quality?",
        "Do you always have to pay for quality?",
        "How do companies control the quality of their goods and services?",
        "Do you mind paying extra for better quality?",
        "Which countries produce top quality goods?",
        "Do you luxury, brand goods are worth the money? Is the quality so much better than non-brand goods that are half the price?",
        "What was the last thing you bought where you looked at the quality?",
        "Is good quality toilet paper important to you?",
        "Is quality important to you?",
        "When do you want top quality service?",
        "When was the last time something disappointed you because of its poor quality?",
        "How would you rate the quality of your English tuition?",
        "What do you think of the air quality and water quality in your town?",
        "How important to you is the sound quality of your music player?",
        "Which stores or companies offer goods and services at an affordable quality?",
        "What do you think about the quality of the goods and services at McDonalds?",
        "Which makers or products have a reputation for good build quality?",
        "What do you do in life that is top quality?"
    ],
    "Quality of Life": [
        "What comes to mind when you hear the term ‘quality of life’?",
        "How is your quality of life on a scale of one to ten?",
        "What’s the difference between quality of life and standard of living?",
        "What quality of life does a goldfish in a bowl have?",
        "What are the indicators of quality life?",
        "How much does it cost to live a quality, happy life?",
        "How does the environment in your town affect your quality of life?",
        "Would you have a better quality of life if you were more attractive?",
        "Does your country’s leader have a good quality of life?",
        "Does technology change your quality of life?",
        "Do you always try to increase and improve your quality of life?",
        "What single thing could you do to increase the quality of your life?",
        "Can money buy quality of life?",
        "What do you think is more important, quality or longevity of life?",
        "How would you describe your quality of life compared to your parents’?",
        "How does crime and urban decay affect your quality of life?",
        "What does having children do to your quality of life?",
        "Who has a better quality of life, a student or a worker?",
        "Will your quality of life get better or worse over the next few decades?",
        "Does your state of mind affect your quality of life?"
    ],
    "Quarreling": [
        "What images spring to mind when you hear the word ‘quarreling’?",
        "Who do you quarrel with most?",
        "Who is the most quarrelsome person you know?",
        "What things do you quarrel over most?",
        "Do you ever intentionally pick a quarrel with someone?",
        "Does the world quarrel with you or do you quarrel with the world?",
        "Have you ever been caught in the middle of crossfire (i.e. parents quarreling)?",
        "How can you avoid quarreling about money?",
        "Do voices in your head ever quarrel with each other?",
        "What are most of your family quarrels about?",
        "Do men or women quarrel more?",
        "When was the last time you saw a couple quarreling in public?",
        "What do married couples quarrel about most?",
        "Do you think children should have lessons at school on how to avoid quarrels and make up after them?",
        "Is it possible for some couples, best friends, etc to never quarrel?",
        "Is quarreling healthy?",
        "Are there subjects you should never, ever quarrel about?",
        "Do politicians in your country quarrel (and fight) with each other live on television?",
        "Would you like to study on a “How to win every quarrel” course?",
        "What happens when two people quarrel using two different languages?"
    ],
    "Questions": [
        "What questions would you like answered?",
        "What questions do you ask during the course of one day?",
        "What is life’s biggest question?",
        "Where do you go to get your questions answered?",
        "What’s the most stupid questions anyone has ever asked you?",
        "Do you have a favourite question that you like people asking you?",
        "What’s the most common question you ask?",
        "What do you think of the questions young children ask?",
        "What do you think about exam questions?",
        "What questions do you not like to answer?",
        "Are you good at answering questions?",
        "“To be or not to be? That is the question.” Is this a good question?",
        "Have you ever questioned someone for a long time because you didn’t believe what they said?",
        "What do you think of questions on application forms?",
        "Do you like interview questions?",
        "What questions are there about your society?",
        "Do you like answering quiz questions?",
        "What questions do you find difficult to answer?",
        "Are you ever afraid or reluctant to ask someone a question?",
        "What’s the most annoying question people ask you?"
    ],
    "Quizzes": [
        "What comes to mind when you hear the word ‘quiz’?",
        "What is your favourite quiz subject?",
        "Do you like watching quiz shows on TV?",
        "Do you ever take online quizzes?",
        "Have you ever been on a quiz team?",
        "Why are quizzes so popular?",
        "What do you think of personality quizzes and find the perfect partner’ quizzes?",
        "What can you do to study for a general knowledge quiz?",
        "Do you think lots of quiz questions would be a good format for a school exam?",
        "Do you think you’d be quick on the buzzer in a quiz contest?",
        "What do you think of quizzes?",
        "What quiz subject do you think you’d do very well in?",
        "Are young people or old people better at pop quizzes?",
        "What impossible quiz question would you like to add to a quiz?",
        "Are you interested in the trivia that is often found in quizzes?",
        "Do you like doing quizzes in English?",
        "Do you think you’d do well in a quiz about the English language?",
        "Do you think taking quizzes can help your English?",
        "What’s the difference between a test, an exam and a quiz?",
        "Have you ever quizzed anyone whose story you didn’t believe?"
    ],
    "Quotations": [
        "“Where facts are few, experts are many.” (Donald R. Gannon) What do you think?",
        "“It was wonderful to find America, but it would have been more wonderful to miss it.” (Mark Twain) What do you think?",
        "“If all the rich people in the world divided up their money among themselves there wouldn't be enough to go around.” (Christina Stead) What do you think?",
        "“Behind every great fortune there is a crime.” (Honore de Balzac) What do you think?",
        "“Invention is the mother of necessity.” (Thorstein Veblen) What do you think?",
        "“In times like these, it helps to recall that there have always been times like these.” (Paul Harvey) What do you think?",
        "“Politics is supposed to be the second oldest profession. I have come to realize that it bears a very close resemblance to the first.” (Ronald Reagan) What do you think?",
        "“Where is human nature so weak as in the bookstore?” (Henry Ward Beecher) What do you think?",
        "“It is not enough to succeed. Others must fail.” (Gore Vidal) What do you think?",
        "“I believe that banking institutions are more dangerous to our liberties than standing armies.” (Thomas Jefferson) What do you think?",
        "“We are here on Earth to do good to others. What the others are here for, I don't know.” (W. H. Auden) What do you think?",
        "“A fashion is nothing but an induced epidemic.” (George Bernard Shaw) What do you think?",
        "“Some of the worst mistakes of my life have been haircuts.” (Jim Morrison) What do you think?",
        "“I have opinions of my own -- strong opinions -- but I don't always agree with them.” (George W. Bush) What do you think?",
        "“The great thing about a computer notebook is that no matter how much you stuff into it, it doesn't get bigger or heavier.” (Bill Gates) What do you think?",
        "“Every human is an artist. The dream of your life is to make beautiful art.” (Miguel Ruiz) What do you think?",
        "“It is not fair to ask of others what you are unwilling to do yourself.” (Eleanor Roosevelt) What do you think?",
        "“Woe be to him that reads but one book.” (George Herbert) What do you think?",
        "“It is our choices...that show what we truly are, far more than our abilities.” (J. K. Rowling) What do you think?",
        "“To love and be loved is to feel the sun from both sides.” (David Viscott) What do you think?"
    ]
}
