export default {
    "X-rays": [
        "What images spring to mind when you hear the word ‘X-ray’?",
        "What do you know about the history of X-rays?",
        "Do you like having an X-ray?",
        "Do you think X-rays are dangerous?",
        "What are X-rays used for?",
        "When was the last time you had an X-ray?",
        "Do you like looking at the X-ray photographs taken of your body?",
        "What would medicine be like without X-rays?",
        "Would you like your own X-ray machine?",
        "Do you think this service should only be available in business and first class?",
        "What exactly is an X-ray?",
        "Would you like to have X-ray vision?",
        "Would you rather have X-ray vision or lots of money?",
        "Where do you think the term X-ray comes from? What does the ‘x’ mean?",
        "Do X-rays worry you?",
        "What other uses are there for X-rays apart from for medical purposes?",
        "How can X-rays damage the human body?",
        "Do you think new technology will replace X-ray technology?",
        "Why are X-rays so popular in action hero cartoons and movies?",
        "What part of your body would you like to be X-rayed and why?"
    ],
    "Xenophobia": [
        "What images spring to mind when you hear the word ‘xenophobia’?",
        "Where does xenophobia come from?",
        "Do you think there is a xenophobia gene in all of us?",
        "Who is the most xenophobic person you know?",
        "Is someone with xenophobia ill?",
        "How do you cure xenophobia?",
        "If you have any negative feelings, thoughts or images against another culture or race, are you xenophobic?",
        "How much xenophobia exists in your country?",
        "Does patriotism lead to xenophobia?",
        "Have you ever been on the wrong end of xenophobia?",
        "In which countries is xenophobia more common?",
        "Is xenophobia around the world on the rise?",
        "Do multicultural, cosmopolitan countries experience less or more xenophobia?",
        "What’s the difference between xenophobia and racism?",
        "How does xenophobia harm a society and the world?",
        "Do you think xenophobia will disappear one day?",
        "Is xenophobia a mental imbalance?",
        "Do you think people with xenophobia are dangerous?",
        "Do governments create xenophobic feelings among their people?",
        "What would you like to ask someone with xenophobia?"
    ]
}
