export default {
    "Dancing": [
        "Do you like dancing?",
        "How important is dancing in your culture?",
        "How often do you dance?",
        "What kinds of dancing can we see in your country?",
        "Do you like dancing in discos?",
        "Do you have any early memories of dancing?",
        "Why do people like to dance?",
        "Do you ever go to see dance performances?",
        "What dances from other countries do you like?",
        "Are you good at dancing?",
        "Is there a national dance in your country?",
        "Are there any famous dancing groups in your country?",
        "Do you think being a professional dancer would be a good job?",
        "Do you like movies about dancing?",
        "What kind of music do you think is good to dance to?",
        "Do you prefer dancing alone or with other people?",
        "What do you think of ballet?",
        "Do you ever dance in the streets at festivals?",
        "Have you seen or taken part in dances that tell a story?",
        "What is the difference between a good dancer and a bad dancer?"
    ],
    "Danger": [
        "What comes to mind when you hear the word ‘danger’?",
        "Do you like danger?",
        "Have you ever been in danger?",
        "What dangers are there in your house?",
        "Do you do things in your life to avoid danger?",
        "What is the most dangerous thing you’ve done?",
        "Do you know any dangerous people?",
        "What are the dangers of your job?",
        "Which parts of our lives are the most dangerous?",
        "Would you like to join a dangerous sports club?",
        "What is danger?",
        "Why do some people like danger?",
        "What dangers do you see around you every day?",
        "What do you do when you are in danger?",
        "Is the Earth in danger?",
        "What dangerous things were you told to avoid when you were a child?",
        "What countries in the world are too dangerous to visit?",
        "What new dangers are there in society?",
        "What are the dangers of the Internet?",
        "Are there hidden dangers in the food we eat?"
    ],
    "Dark": [
        "What springs to mind when you hear the term ‘the dark’?",
        "Are you afraid of the dark?",
        "Were you afraid of the dark when you were a child?",
        "Why do you think people are afraid of the dark?",
        "Do you ever get worried alone at night in your house in the dark?",
        "How does the dark make you feel?",
        "What kinds of things do you like to do in the dark?",
        "When was the last time you sat alone in the dark?",
        "Do people ever keep you in the dark about their plans?",
        "What would life be like if it was never dark?",
        "Have you ever sat in the dark wondering what it's all about?",
        "What makes children afraid of the dark?",
        "Is watching TV in the dark bad for your eyes?",
        "Have you ever wanted the dark to come and never go away?",
        "What questions would you like to ask the dark?",
        "What three adjectives would you use to describe the dark?",
        "Is it safe to walk around your town in the dark?",
        "Do you find there’s a difference between the dark of summer and the dark of winter?",
        "Do you think the dark in other countries is different to the dark in your own country?",
        "How would you help someone overcome their fear of the dark?"
    ],
    "Dating": [
        "What images spring to mind when you hear the word ‘dating’?",
        "What are the good things and bad things about dating?",
        "What can you remember about your first date?",
        "How do you feel before you go on a first date with someone?",
        "What is your idea of a great first date?",
        "What is the most disastrous date you’ve been on?",
        "If you could go on a date with anyone in the world, who would it be with and why?",
        "Would you ever use a dating service (online or otherwise)?",
        "Would you ever go on a blind date?",
        "Who pays on a first date?",
        "Do you think dating today is any different from dating 50 years ago?",
        "From what age is it OK to start dating?",
        "Isn’t it better to go for an arranged marriage and do away with the hassles of dating?",
        "Is it OK for older men / women to date very young partners?",
        "What do you think parents worry about when their kids start dating?",
        "Is it a better idea to date someone from your own race, religion, social status, etc.?",
        "What are the best ways of making sure a first date leads to a second date?",
        "What should you never do on a first date?",
        "Is dating someone after two years still as exciting as the first date?",
        "Is dating a waste of time?"
    ],
    "Death": [
        "What do you think of death?",
        "Why do some cultures mourn death and others celebrate it?",
        "Are you afraid of death?",
        "How would you like to be remembered?",
        "Would you prefer to be buried, cremated or another kind of ritual?",
        "Would you like to cheat death and live forever?",
        "What happens after you die?",
        "What are the biggest causes of death in your country and how can these be reversed?",
        "Would you prefer to die suddenly or over a few months?",
        "Have you ever felt really bad and looked like death warmed up?",
        "What were you taught about death when you were younger?",
        "Have you ever had an experience in which you nearly died?",
        "Is someone really dead when they are brain dead?",
        "Do you agree with the death penalty?",
        "What do you think of taking one’s own life - suicide?",
        "Do you agree with euthanasia – helping someone else die?",
        "Is there a personification of death in your culture?",
        "In Japan, China and Korea, the number 4 is associated with death – are there any similar associations in your culture?",
        "Do you believe that people can come back from the dead, like a zombie?",
        "Why do you think there is such a fascination in our world with death?"
    ],
    "December": [
        "What springs to mind when you hear the word ‘December'?",
        "What do you think of the month of December?",
        "What good things happen in December?",
        "What things do you usually do in December?",
        "What do you think of the word 'December'?",
        "What are people who are born in December like?",
        "What do you think of December weather?",
        "Where is December on the list of 'the best months'?",
        "Are there any bad things about the month of December?",
        "What plans do you have for next December?",
        "If you made a December festival, what would you want it to be like?",
        "Is there any delicious food you eat in December?",
        "How should people celebrate in December?",
        "What famous holidays are there in December?",
        "How do you feel when December arrives?",
        "If you made a video about December, what would you put in it?",
        "How do you feel when December is over?",
        "What three adjectives best describe December, and why?",
        "What good things can you remember happening in December?",
        "What is a good symbol for December, and why?"
    ],
    "Dentists": [
        "What comes to mind when you hear the word ‘dentist’?",
        "How often do you go to see a dentist?",
        "Do you like visiting the dentist?",
        "What do you think of the smell and sounds at the dentist's?",
        "Do you think trips to the dentist's are reasonably priced?",
        "Do you have good or bad childhood memories of dentists?",
        "Would you like to look inside peoples’ mouths all day as a job?",
        "Talk about a good and bad dentist you’ve had.",
        "Are your teeth in good condition?",
        "Do you think there is a good choice of dentists in your town?",
        "What do you think about as you sit in the dentist’s waiting room?",
        "Do you think dentist’s waiting rooms have to have lots of photos of teeth and toothpaste ads, or would you like to see a different decor?",
        "What do you think a day in the life of a dentist is like?",
        "What do you do to look after your teeth?",
        "What do you think dentists can do to make a visit more pleasurable?",
        "Do you worry about fillings / cavities?",
        "Do you think a dentist always tells the patient if he / she makes a big mistake?",
        "Do you think toothpaste technology will mean there’ll be no need for dentists one day?",
        "Why do you think some people become dentists and some doctors?",
        "Do you think you’d be a good dentist?"
    ],
    "Diana, Princess of Wales": [
        "What do you remember about Diana when she was alive?",
        "Did you feel sorry for her?",
        "Do you think she made a good choice marrying Prince Charles?",
        "Where do you think Diana ranked in a \"World's Most Glamorous Women\" list?",
        "Do you think she was a force for great good in the world?",
        "Can you remember what you felt when you heard the news she had died?",
        "Diana’s brother said she had been hunted by the paparazzi. What do you think of the journalists who followed her everywhere?",
        "Do you think she deserves a sainthood for the causes she worked for?",
        "Do you think Diana was the perfect modern-day princess?",
        "How do you think Diana felt about the British Royal family?",
        "Do you have a favourite image or photo of Diana?",
        "Do you think she really was the people’s princess and the Queen of Hearts?",
        "What do you think Diana is remembered for most?",
        "Do you think Diana’s death was simply a tragic accident?",
        "What do you think she’d be doing today if she hadn’t died?",
        "What do you think of claims that the British Secret Service killed Diana because she was going to marry a Muslim man?",
        "Do you think there is still too much media attention about Diana?",
        "Would you like to live a life like the one she lived?",
        "What questions would you like to have asked Diana and what do you think her answers might have been?",
        "Who would you like to question about Diana and what do you think he/she would say about her?"
    ],
    "Diets": [
        "Can you explain the difference between a diet, diet and to diet?",
        "Tell me about your regular diet.",
        "Have you ever been on a diet?",
        "Do you think people who go on diets get the proper nutrition their body needs?",
        "Do you know anyone with anorexia nervosa or bulimia nervosa?",
        "Do you think the fashion and advertising industries are responsible for encouraging women to be super skinny?",
        "Are you happy with your weight and body shape?",
        "How important is exercising as part of a diet?",
        "Do people in your country eat a well-balanced diet?",
        "How often do you weigh yourself?",
        "Do you worry about your weight?",
        "How much weight would you like to lose or put on?",
        "Are dietary habits in your country changing?",
        "Do you know anyone who is obsessed with their weight and their figure?",
        "What’s your advice for anyone who wants to diet?",
        "Are there any dangers of dieting?",
        "Why are people so worried about the way their body looks?",
        "What do you think of all the fad diets that come on the market?",
        "Do you think it’s possible to lose weight and enjoy eating?",
        "Do you have a balanced diet?"
    ],
    "Digital revolution": [
        "What is the digital revolution?",
        "What is so revolutionary about it?",
        "How does the digital revolution compare with the industrial revolution?",
        "Are we at the beginning, in the middle or at the end of the digital revolution?",
        "Has the digital revolution been good or bad for the world?",
        "How has the digital revolution changed your life?",
        "Are there any aspects of the digital revolution you don’t like?",
        "How would you describe the history of the digital revolution?",
        "Who are or have been the major players in the digital revolution?",
        "What is the most important event so far in the digital revolution?",
        "What digital products do you have?",
        "Do you think it is difficult to keep up to date with technology in the digital revolution? How about your parents or grandparents?",
        "Has the digital revolution reached all four corners of the Earth?",
        "Would you like a job in the digital revolution?",
        "What would our life be like without computers and other digital products?",
        "What do you think of the word \"digital\"?",
        "Do you think people who work in technology are nerds or geeks?",
        "How do you think the digital revolution will change our lives from now?",
        "Do you feel like a revolution is happening around you?",
        "What revolution will come after the digital revolution?"
    ],
    "Dinosaurs": [
        "What comes to mind when you hear the word ‘dinosaur’?",
        "What do you think happened to dinosaurs?",
        "Why are children so interested in dinosaurs from a very young age?",
        "Do you have a favourite dinosaur?",
        "What do you think life was like for men and women when dinosaurs were around?",
        "Do you like looking at dinosaur skeletons and bones at exhibitions?",
        "Would you like to be a paleontologist and look for and study dinosaur bones?",
        "What are your earliest memories of dinosaurs? Did you have dinosaur toys?",
        "Do you like dinosaur movies?",
        "Are there still dinosaurs on Earth today?",
        "Do you think dinosaurs are interesting?",
        "If you were a dinosaur, which one would you be?",
        "Would you like to see dinosaur DNA used to bring dinosaurs back to life?",
        "Why is it important to understand how dinosaurs lived?",
        "What would you say if you had to give a one minute speech on dinosaurs?",
        "What features make a dinosaur a dinosaur?",
        "How do dinosaurs feature strongly in our modern culture?",
        "What would you like to know about dinosaurs that no one knows?",
        "What kind of dinosaurs or dinosaur dishes do you think were tasty?",
        "If someone called you a dinosaur, would you be happy or unhappy?"
    ],
    "Disability": [
        "What comes to mind when you hear the word ‘disability’?",
        "What kinds of disability do you know of?",
        "Some people prefer to use the term ‘physically challenged’ instead of ‘disabled’. What do you think about this?",
        "What problems do people with disabilities face in your country?",
        "Do you think it would be harder to live with a physical disability or an intellectual disability?",
        "Do you always try to help people who are disabled?",
        "Do you tend to think that disabled people always need your help?",
        "What things do you think disability rights groups campaign for?",
        "What do you think of the Paralympic Games (which means ‘alongside the Olympic games’)?",
        "What daily problems do you think wheelchair users have in your town?",
        "What kinds of discrimination do people with disabilities face ?",
        "What message do you think disabled people would like to tell those without a disability?",
        "What role models with a disability do you know of?",
        "How do you think people disabled in accidents come to terms with their new disability?",
        "What should people do on the International Day of Persons with Disabilities?",
        "What misunderstandings do people have about disability?",
        "What problems do disabled people in poorer countries face?",
        "What can disabled people teach those without disabilities?",
        "What tax breaks or financial aid should people with disabilities get?",
        "Do you think science will be able to end disability one day?"
    ],
    "Discrimination": [
        "What is discrimination?",
        "What kinds of discrimination exists in your country?",
        "Do you ever have thoughts that are discriminatory?",
        "Which countries around the world have shocking levels of discrimination?",
        "Are there strong laws in your country to prevent discrimination?",
        "What kinds of sexual discrimination exists in your country?",
        "What do you do when you see discrimination?",
        "Does ageism exist in your country?",
        "Do you think there is religious discrimination in the war on terror?",
        "Is there a class or caste system in your country?",
        "Have you ever been discriminated against?",
        "Have you ever discriminated against people?",
        "What is the worst kind of discrimination?",
        "Do you think discrimination in the world will ever disappear?",
        "What kinds of racial discrimination exists in your country?",
        "Is there discrimination in your school / company?",
        "How do people who are discriminated against react in your country?",
        "Are people in your country discriminated against because of the way they talk?",
        "Where does discrimination come from?",
        "Are you someone who holds zero discriminatory beliefs and attitudes?"
    ],
    "Discussions": [
        "What springs to mind when you hear the word ‘discussion’?",
        "What’s a healthy discussion?",
        "Do you like taking part in discussions in English?",
        "Do you ever get involved in pointless discussions?",
        "Do you ever join discussion boards on the Internet? Are they good for your English?",
        "How often do you take part in political discussions?",
        "What are frank discussions, lively discussions, brief discussions and lengthy discussions? When was the last time you had each of these?",
        "What kinds of discussions do you think are really boring?",
        "Someone once said: \"Discussion is an exchange of knowledge; argument is an exchange of ignorance.\" What does this mean? Do you agree?",
        "A Chinese proverb says: \"A single conversation across the table with a wise person is worth a month's study of books.\" Do you agree?",
        "Are you good at discussing things?",
        "What are the differences between discussions, debates and conversations?",
        "When was the last time you had a heated or animated discussion?",
        "Do you like looking at discussions on TV between a panel of experts?",
        "What are the big discussions in your country at the moment?",
        "Would you like to take a course on how to do well in discussions?",
        "Do you make a point of having the last word in a discussion?",
        "Leon Trotsky said: \"If we'd had more time for discussion, we would probably have made a great many more mistakes.\" Do you agree?",
        "A Kenyan proverb says: \"Having a good discussion is like having riches.\" Do you agree?",
        "Did you like this discussion on discussions?"
    ],
    "Disease": [
        "What springs to mind when you hear the word ‘disease’?",
        "Do you worry about diseases?",
        "What dangerous or deadly diseases are there in your country?",
        "What do you think the deadliest disease in the world is?",
        "Do you think anyone will spread killer diseases as a means of warfare?",
        "What are the most common causes of diseases?",
        "What infectious diseases are there in your country?",
        "Have you ever had any vaccinations against diseases?",
        "What childhood diseases did you get?",
        "Is there a history of disease in your family?",
        "What is disease?",
        "Have you ever had a disease?",
        "Which disease would you most like scientists find a cure for?",
        "What do you think when you read or see news reports on the spread of bird flu, HIV / AIDS and other headline-hitting diseases?",
        "Do you think scientists will one day wipe out / eradicate all diseases?",
        "What do you think the scariest disease is?",
        "Are there ever any outbreaks of diseases in your country?",
        "What is the best way to stop diseases from spreading?",
        "Is there sufficient education and awareness in your country about sexually-transmitted diseases?",
        "What diseases do you worry about getting in your old age?"
    ],
    "Disney": [
        "What comes to mind when you hear the word ‘Disney’?",
        "What do you know about Walt Disney?",
        "What do you think about the whole world of Disney?",
        "Have you ever been (or would you like to go) to a Disney theme park?",
        "Who is your favourite and least favourite Disney character?",
        "Do you think Disney teaches children about anything?",
        "Would you ever wear a Mickey Mouse T-shirt?",
        "Why do you think so many people hate Disney?",
        "What Disney movies have you seen and what did you think of them?",
        "Do you think Disney goods are overpriced?",
        "What Disney character are you most similar to?",
        "Why do you think Disney continues to be so successful?",
        "Do you think adults who are into Disney are strange?",
        "Which company / character do you think is a close rival to Disney?",
        "How American is Disney and the Disney message?",
        "Do you or would you encourage your children to watch Disney shows and movies?",
        "How much money would you need to be paid to dress in a Mickey Mouse costume?",
        "What would Mickey Mouse do if he became President of the USA?",
        "If you could ask Mickey Mouse a question, what would it be?",
        "What do you think his answer would be?"
    ],
    "Distracted Driving": [
        "On a scale of 0 to 10, how important is your cell / mobile phone to you?",
        "How important is your safety and well-being?",
        "Do you ever text, check social media (Facebook, Twitter, etc.) or e-mail while you are walking or driving?",
        "Have you ever seen somebody do something dangerous while texting and walking or driving?",
        "What percentage of traffic accidents do you think are the result of distracted driving?",
        "Is texting while driving as dangerous as drunk driving?",
        "How can society discourage people from letting their phone distract them while walking or driving?",
        "Do you think education alone is enough to eliminate distracted driving?",
        "Are fines a sufficient penalty for distracted driving?",
        "How much should the fine be for distracted driving?",
        "In addition to fines, what other measures can be used to punish distracted drivers?",
        "Can most people multi-task well enough to text and drive safely?",
        "What can a person do to resist being distracted by their phone while walking or driving?",
        "What would you do if the person driving the car or bus you were in starts texting?",
        "Is talking on the phone dangerous while driving?",
        "How long can you wait before checking for messages?",
        "How quickly do you try to respond to messages?",
        "Where do you usually carry your phone? Why?",
        "How do you feel when a friend doesn’t reply to your message immediately?",
        "Do you ever check messages during class? (Be honest!)"
    ],
    "Divorce": [
        "What images spring to mind when you hear the word ‘divorce’?",
        "Do you think that divorce is a sin?",
        "Do people get divorced too easily and quickly today?",
        "What are the main causes for people getting divorced?",
        "Why do you think divorce is higher in some countries than in others?",
        "Who should get the children in a divorce?",
        "Should people sign a divorce agreement before they get married – like Hollywood movie stars do?",
        "Should couples have to take marriage guidance counseling before they file for divorce?",
        "What effect does divorce have on children?",
        "Is being divorced a social stigma in your country?",
        "Is divorce a big problem in your country?",
        "Would you still be friends with someone after you divorced them (or they divorced you)?",
        "Why are divorce rates increasing around the world?",
        "Should divorce settlements be fifty-fifty?",
        "Why do celebrity marriages end in divorce so quickly?",
        "What do you think of quickie divorces?",
        "Do you think divorce would be less common if couples lived together before marriage?",
        "Does divorce mean part of you is a failure?",
        "Would you date someone who had been divorced several times?",
        "Do you think being a divorce lawyer would be a good job?"
    ],
    "Doctors": [
        "What comes to mind when you hear the word ‘doctor’?",
        "How often do you go to the doctor?",
        "Do you always feel better after you’ve visited the doctor?",
        "How do you find a good doctor?",
        "What do you think about the costs of visits to the doctor in your country?",
        "Do you always think you’ve received top treatment from your doctor?",
        "Do you always believe what your doctor says or do you sometimes doubt him / her?",
        "Would you like to be a doctor?",
        "What do you think are the worst aspects of being a doctor?",
        "If you were a doctor, which area would you like to specialize in?",
        "What do you think about when you’re sitting down waiting to see the doctor?",
        "What childhood memories do you have of doctors?",
        "Have you ever changed doctors? If ‘yes’, why?",
        "Do you prefer male or female doctors?",
        "What kind of day do you think a doctor has?",
        "Do you think there are enough doctors in your town?",
        "Are you satisfied you get to spend enough time with your doctor when you visit?",
        "Where do you think the world’s best doctors are?",
        "Do you think doctors talk and gossip about patients?",
        "What kind of person makes an excellent doctor?"
    ],
    "Dogs": [
        "Do you like dogs?",
        "Are dogs really \"a man’s best friend\"?",
        "What kinds of dogs do you like and dislike?",
        "Do you think dogs are the best pets?",
        "Do you think dogs have a good life?",
        "Are you ever afraid of dogs?",
        "What do you think of dogs that bark non-stop?",
        "Do you think people spend too much money on dogs?",
        "In what ways are dogs helpful to humans?",
        "Are there many abandoned dogs in your town?",
        "Do you prefer pedigree or mixed-breed dogs?",
        "Do owners have to clean up after their dogs in your town?",
        "Do you think some owners care too much for their dogs and not enough for other people?",
        "Why are dogs disliked in some cultures?",
        "What do you think of dog hotels, dog cafes and poodle parlors?",
        "Dog is on the menu in many countries. What do you think of this?",
        "What would you do if someone bought you a puppy as a present?",
        "What do you think of people who organize dog fights?",
        "In English, dogs go “woof woof”. How about in your language or other languages you know?",
        "What does a “dog-eat-dog world” mean? Is it true?"
    ],
    "Domestic violence": [
        "What comes to mind when you hear the phrase ‘domestic violence’?",
        "What are the different forms of domestic violence?",
        "In some countries, domestic violence isn’t a crime. What do you think about this?",
        "Which is worse, wife-beating or husband-beating?",
        "Do you think domestic violence exists in all social classes?",
        "Does domestic violence often hit the headlines in your country?",
        "What would you do if you knew there was domestic violence in the house / apartment next to yours?",
        "Is there much education about or awareness of domestic violence in your country?",
        "Do you know of any instances of domestic violence?",
        "Do you think the aggressors of domestic violence grew up in an environment of domestic violence and child abuse?",
        "Is domestic violence a big problem in your country?",
        "What are the main causes of domestic violence?",
        "Are there shelters in your country where victims of domestic violence can stay and seek refuge?",
        "What kinds of people carry out domestic violence?",
        "Why do you think victims of domestic violence stay in the relationship for so long?",
        "Why do many countries see domestic violence as a private, ‘family affair’?",
        "Is domestic violence a subject that is largely swept under the carpet or is a taboo subject in your country?",
        "Have you seen movies or TV shows about domestic violence?",
        "What questions would you ask a violent family member?",
        "Do you think alcohol plays a large part in domestic violence?"
    ],
    "Donuts": [
        "Do you like donuts?",
        "What importance do donuts play in our lives?",
        "What kind of donut would really make your mouth water?",
        "How would you describe the smell of freshly-made donuts?",
        "Do you ever go to donut cafes?",
        "Which is the better spelling of the word – ‘donut’ or ‘doughnut’?",
        "Do you think a ‘healthy donut’ restaurant would catch on?",
        "Does your country have its own unique kinds of donuts?",
        "What do you know about the nutritional value of donuts?",
        "Why do you think donuts are so popular around the world?",
        "What do you think when you hear the word ‘donut’?",
        "What do you think when you see lots of freshly-made donuts?",
        "Where do you think the word ‘doughnut’ came from?",
        "What is your favourite kind of donut?",
        "What do you know about the history of donuts?",
        "Why are donuts round? Do you think other shapes would be popular?",
        "What is your favourite donut shop or chain?",
        "How many donuts could you eat in one go?",
        "Do you think donuts are good value for money?",
        "Which do you prefer, ring donuts or filled donuts?"
    ],
    "Downloading": [
        "How often do you download files?",
        "What would you do if you couldn’t download things?",
        "Does it ever take you too long to download mail?",
        "What do you think of being able to download music?",
        "Do you prefer to download music or have the CD?",
        "Do you pay to download music or do you download it illegally?",
        "Have you ever used the Apple Store, Amazon MP3 or similar download services?",
        "Do you think your government needs to crack down on illegal downloading?",
        "Do you download video files from sites like YouTube?",
        "What other things would you like to be able to download which you can’t at the moment?",
        "Do you think illegal downloading is the same as stealing something from a shop?",
        "Ho do you think musicians feel about their music being downloaded illegally?",
        "How often and what kinds of software do you download?",
        "Have you ever had problems downloading something?",
        "Do you ever download security patches and upgrades to your OS?",
        "What kinds of games do you download?",
        "Have you ever downloaded files and then not been able to find them?",
        "Do you worry about viruses when you download files?",
        "What is the difference between downloading and streaming?",
        "What are the advantages and disadvantages of downloading?"
    ],
    "Dreams": [
        "Do you dream often?",
        "Do you remember your dreams?",
        "Do you dream in colour or in English?",
        "Do you like having dreams?",
        "Do you believe dreams have a special meaning?",
        "Do you have the same dreams again and again?",
        "Has something you’ve dreamt about ever come true?",
        "Have you ever been woken up by a nightmare?",
        "What kinds of people do you meet in your dreams?",
        "Do you tell other people about the dreams you have?",
        "Do you talk in your sleep when you dream?",
        "Have you ever woken up and believed you’re still in your dream?",
        "Do you think animals dream?",
        "Does having a dream affect the way you feel when you wake up?",
        "Do you think dreams can be explained scientifically?",
        "Would you like to stop having dreams or have more dreams?",
        "Do you have the same dreams you had when you were a child?",
        "Do you ever want to live in the world of your dreams?",
        "Do you daydream?",
        "Why do you think some people remember their dreams and others don’t?"
    ],
    "Drink driving": [
        "What do you think about drink driving?",
        "Are the penalties for drinking and driving strict enough in your country?",
        "Do people in your country follow the drink driving laws?",
        "Have you ever been over the limit while driving?",
        "Do passengers have a responsibility to stop drunk people from driving?",
        "Should the passengers of a drunk driver also be punished?",
        "Have you ever been breathalyzed by the police?",
        "Are there scary commercials in your country to stop drunk drivers?",
        "What do you know about statistics for alcohol-related traffic accidents in your country?",
        "Do members of your family or friends drink and drive?",
        "What are the penalties for drink driving in your country?",
        "Do you ever try to stop people from driving under the influence?",
        "Do you think there should be zero tolerance for any alcohol in a driver’s bloodstream?",
        "Do you think the police stop and test enough drivers?",
        "Do you think the police have enough powers to stop and test people?",
        "What penalty would you want for a drunk driver who hit you?",
        "Is alcohol the biggest cause of road accidents in your country?",
        "Do you have a favourite anti-drink-driving slogan, such as \"Arrive Alive\" or \"Think Before You Drink Before You Drive\"?",
        "Do you think drivers should also be tested the night after drinking?",
        "Should drink driving laws also apply to cyclists? How about drunk walking?"
    ],
    "Driving": [
        "Do you like driving / sitting in a car?",
        "What does driving mean to you?",
        "Do you think people change character when they are behind the wheel?",
        "Have you ever been in / had / seen a driving accident?",
        "Do you think driving is dangerous?",
        "What’s the most dangerous piece of driving you’ve ever seen?",
        "Do you (or someone you know well) always follow the rules of the road when you (they) drive?",
        "What do you think about when you drive?",
        "Do you think you are a good or a bad driver?",
        "Do you think there should be more rules for drivers in your country?",
        "When do you think people should be allowed to drive a car?",
        "What do you think of the driving in other countries?",
        "How often do you think people need to renew their driving licence or driving skills?",
        "What should governments do to make driving safer?",
        "Do you prefer to drive or travel by another form of transport?",
        "What do other people think of or say about your driving?",
        "What do you think the punishment for drunk driving should be?",
        "Do you think drivers should be tested frequently to continually improve their driving skills?",
        "Do you think men or women are the best drivers?",
        "If you went on a driving holiday, where would you like to go?"
    ],
    "Drones": [
        "What springs to mind when you hear the word ‘drone'?",
        "What do you think might be fun about flying a drone?",
        "What would you like to do with a drone if you had one?",
        "Do you think drones are here to stay?",
        "Do you think drones are toys?",
        "What videos have you seen of people flying drones?",
        "How useful might drones be in wars?",
        "How safe are drones?",
        "What have you read about drones nearly hitting airplanes?",
        "Do you think people should have a license to fly drones?",
        "What does the word 'drone' mean?",
        "Would you travel in a drone taxi?",
        "How will drones change the delivery of shopping in the future?",
        "Would you like to learn to fly a drone?",
        "Have you seen people flying drones?",
        "If you had a drone, what would you like to film or take pictures of?",
        "What do you think the future holds for drones?",
        "Should drones be banned?",
        "What should the age limit be for people to fly drones?",
        "What do you think of drones replacing cars?"
    ],
    "Drugs": [
        "What comes to mind when you hear the word ‘drugs’?",
        "What do you know about illegal drugs?",
        "Have you ever used illegal drugs?",
        "Many people say marijuana is more dangerous than alcohol. What do you think?",
        "Are there strong laws in your country to prevent the use of drugs?",
        "Some countries execute drug traffickers. What do you think about this?",
        "Do you think alcohol is a dangerous drug?",
        "Many people around the world use ‘designer’ drugs, such as ecstasy, or recreational drugs, such as cannabis. Do you think this is OK?",
        "Is there a drug problem in your school / country?",
        "Why do you think people take drugs?",
        "What comes to mind when you hear the word ‘drug addict’?",
        "What do you think a drug addict does with his / her day?",
        "Many politicians have used cannabis. What do you think about this?",
        "What should governments do to help drug addicts?",
        "Many young children are now using addictive drugs. What do you think about this?",
        "Do you think drugs lead people into crime?",
        "What punishment do you think drug barons should get?",
        "Would you like to work as an anti-narcotics police officer?",
        "Would legalizing soft drugs help reduce crime?",
        "Why do people get into hard drugs like heroin?"
    ],
    "Drugs in sport": [
        "What are your thoughts on athletes using performance-enhancing drugs?",
        "Do you think athletes in all sports take drugs?",
        "Which sport seems to suffer most from participants using drugs?",
        "What is wrong with performance-enhancing drugs?",
        "If there was a vote, do you think athletes would choose to allow performance-enhancing drugs in sport?",
        "How often do you think athletes need to be tested?",
        "What do you think of lifetime bans for those who take performance-enhancing drugs?",
        "How do you think clean athletes feel about those who use drugs?",
        "Have any athletes from your country been discovered or banned?",
        "Do you think sport will ever be totally clean?",
        "Do you think performance-enhancing drugs are OK if they make sport more exciting and athletes break more records?",
        "Is there a difference between performance-enhancing drugs and performance-enhancing sports shoes and other equipment?",
        "Do you think the Tour De France has been badly damaged?",
        "If a World Cup Final winner used drugs to score the winning goal or point for his / her team, should the team be stripped of its trophy?",
        "Which athletes do you think are totally clean, and why?",
        "What do you think of an alternative Olympics in which all athletes take performance-enhancing drugs and steroids?",
        "Do you think an athlete who cheated by using drugs would still think he / she deserved to win his / her medal?",
        "Should a sport or country be banned if it cannot control its athletes?",
        "Have you ever been upset by finding out a sports star cheated?",
        "Would you take steroids if they made you study English better?"
    ]
}
