export default {
    "E-mail": [
        "What springs to mind when you hear the word ‘e-mail’?",
        "How important is e-mail to you?",
        "Do you prefer writing e-mail or real letters with a pen and paper?",
        "Are you always polite in e-mails and start with “Dear” and end with a closing salutation like “Best wishes”, or “Yours sincerely”?",
        "How much time do you spend reading and writing e-mails?",
        "Do you think e-mails are fun?",
        "Do you ever receive spam mail? What do you do with it?",
        "Have you ever pressed ‘send’ and then wish you hadn’t?",
        "Are you good at replying quickly to e-mails?",
        "How many mails are there in your InBox?",
        "How many different e-mail accounts do you have / need?",
        "Which e-mail provider do you use (Hotmail, Gmail, Yahoo..)? Are you happy with the service?",
        "Do you prefer e-mail via your mobile phone or a computer?",
        "Do you think e-mail can be dangerous?",
        "When was the last time an e-mail made you very happy or excited about something?",
        "What new functions would you like to see with e-mail?",
        "Are you worried that governments or criminals can read your mail?",
        "Have you ever waited, and waited, and waited and waited for an e-mail to arrive? How many times did you check?",
        "If you could secretly have access to someone else’s e-mail account, who would it be and why?",
        "What will replace e-mail in the future?"
    ],
    "Ear and Body Piercing": [
        "What do you think of pierced ears?",
        "Do you think there’s any difference between a man or woman having his/her ears pierced?",
        "Do ear-rings / studs make someone look more attractive?",
        "Why do you think people started piercing their ears?",
        "Do you think ear piercing is a strange custom?",
        "Is there any cultural significance of ear piercing in your country?",
        "Should a man have none, one or both ears pierced?",
        "What is the earliest age at which you should get a child’s ears pierced?",
        "Were / Are there any rules in your school about pierced ears?",
        "How many holes do you think is maximum for someone’s ears?",
        "What do you think of body piercing?",
        "Do you think pierced noses, eyebrows, lips, etc look attractive?",
        "Why do you think someone would pierce their tongue and wear a stud inside their mouth?",
        "Why do you think pierced navels and nipples are fashionable?",
        "What would your mother say if you got your face and body pierced?",
        "Do you think the body piercing fashion will continue for generations?",
        "Which cultures do you know of have a long history of piercing?",
        "Do you think there are similarities between body piercing and indigenous tribes who put bones through their nose?",
        "Do you think body piercing can be dangerous?",
        "Do you think every part of the body can be pierced?"
    ],
    "Earth": [
        "What images spring to mind when you hear the word ‘Earth’?",
        "What are your feelings towards the Earth?",
        "How often do you think about the Earth?",
        "How much trouble do you think the Earth is in today?",
        "Would you like to see the Earth from space?",
        "Why is Earth the only place known in the universe that has life?",
        "What do you know about the history of Earth?",
        "Do you think ‘Earth’ is a good name for our planet?",
        "What is Earth made of?",
        "What do you know about the centre of the Earth?",
        "What do you do in your life to care for the Earth?",
        "What do you know about the surface of the Earth?",
        "What do you know about the earth’s rotation?",
        "What natural hazards are there on Earth? Do they affect you?",
        "Does your religion have an explanation for the creation of Earth?",
        "What are the biggest challenges facing Earth?",
        "Do you think it’s possible to save the Earth?",
        "What will happen to the Earth if all humans disappear from it?",
        "Have you ever used the application Google Earth?",
        "What do you think is the most beautiful thing about the Earth?"
    ],
    "Earthquakes": [
        "What comes to mind when you hear the word ‘earthquake’?",
        "Have you ever experienced an earthquake or tremor?",
        "Do you think an earthquake is the world’s scariest natural disaster?",
        "What should you do the second an earthquake hits?",
        "Why do you think people live in areas that have lots earthquakes?",
        "Would you move to a city like Tokyo or San Francisco, where a huge earthquake could strike at any time?",
        "What would you put in your emergency earthquake bag?",
        "What do you think when you see news reports of earthquakes?",
        "Why do earthquakes happen?",
        "What’s the difference between a magnitude 6 and 7 earthquake?",
        "What do you know about earthquakes?",
        "What is your earliest memory of earthquakes (a movie, a story in a book, the real thing…)?",
        "What would happen to your town if a big earthquake struck?",
        "What would you do if an earthquake struck right now?",
        "Do you know where the emergency shelters are in your town (for earthquakes or other natural disasters)?",
        "Scientists say animals know hours before that an earthquake will strike. How do you think this is possible?",
        "Do you think scientists will one day be able to make totally earthquake-proof buildings and cities?",
        "What is the worst earthquake you’ve seen on the news?",
        "Do you like earthquake disaster movies?",
        "Have you ever sent money to earthquake victims (or victims of any other natural disaster)?"
    ],
    "Easter": [
        "What springs to mind when you hear the word ‘Easter?",
        "What is Easter?",
        "According to the Christian religion, Easter is a more important holiday than Christmas. Why to you think this is so?",
        "How do people spend Easter in your country?",
        "What are the traditional Easter dishes in your country?",
        "How do people prepare for Easter?",
        "What more would you like to know about Easter?",
        "Are there any special rituals performed right before or after Easter?",
        "Have you ever spent Easter in another country? Would you like to?",
        "\"Easter tells us that life is to be interpreted not simply in terms of things but in terms of ideals.\" What do you think this quote means?",
        "Should Easter be at the same time / on the same date every year?",
        "What do you like and dislike about Easter?",
        "What's the symbolism of the Easter bunny and Easter eggs?",
        "What is the meaning of Ash Wednesday, Good Friday and Holy Saturday?",
        "What do people in your country do on Easter Monday?",
        "Do you prefer Easter or Christmas?",
        "There would be no Christmas if there was no Easter. Do you agree?",
        "Is Easter less commercial than Christmas? Why (not)?",
        "Someone once said: \"The resurrection gives my life meaning and direction and the opportunity to start over no matter what my circumstances.\" What do you think this means?",
        "Do you think that people will stop celebrating Easter one day?"
    ],
    "Eating": [
        "How much do you enjoy eating?",
        "What time of the day do you most enjoy eating?",
        "Do you have a midnight snack?",
        "Where in your house is your favourite place to eat?",
        "Who do you like eating with most?",
        "Do you like watching TV while you eat?",
        "Are there any rules in your house when you eat?",
        "Are you a slow or fast eater?",
        "Are you a fussy / picky eater?",
        "When was the last time you were so hungry that you felt you could eat a horse?",
        "Do you ever get bored of eating?",
        "How many times do you chew your food?",
        "What do you think of people who eat food on trains or buses?",
        "Are there any rules in your country about eating in public?",
        "Do you think eating should always be a social occasion?",
        "What eating manners do you have in your country that you like and dislike?",
        "Is the issue of healthy eating important to you?",
        "Have you ever suffered from eating disorders?",
        "Have you ever had an eating competition with your family or friends?",
        "Do you ever eat too much?"
    ],
    "Economics": [
        "What is economics?",
        "Are you interested in economics?",
        "How important is economics?",
        "Do you think economics is a good subject to study?",
        "How is the economy in your country?",
        "What are the biggest economic problems in your country?",
        "Do you think economics is a science?",
        "How is economics different under socialist and capitalist systems?",
        "What was the last thing you read or heard about economics?",
        "Do you think economics is the most important thing people think about in an election?",
        "Do you read or watch economics news in newspapers and on the TV?",
        "Do you worry about the world economy?",
        "What are the biggest economic problems in the world?",
        "Do you know what the difference is between macroeconomics and microeconomics?",
        "What do you know about economic growth?",
        "What do you understand by the term ‘environmental economics’?",
        "What is the effect of economics on society?",
        "Do you think economic aid and economic sanctions work?",
        "Which people in this world care most about economics?",
        "What do you think ‘happiness economics’ is?"
    ],
    "Education": [
        "What comes to mind when you hear the word ‘education’?",
        "How important do you think education is?",
        "Do you think you had a good education?",
        "Was there a high standard of education at your schools?",
        "Do you think the quality of education is slipping?",
        "What do you think of the idea of all education being online?",
        "What kind of education did you have in your home?",
        "What would the world be like if everyone had access to a good education?",
        "Does your government really care about education?",
        "In which country do you think you can receive the best education?",
        "What is a good education?",
        "Is the level of education in your country good?",
        "What would you like to change about the education system of your country",
        "Would you like to work in education?",
        "Do you think there’s a lot of money to be made in education?",
        "What kind of experience and qualifications do you think a government’s education minister/secretary needs?",
        "When does education begin?",
        "What do you think Mark Twain meant when he said, “never let school interfere with your education”?",
        "What do you think of single-sex education?",
        "What do you think of the idea of lifelong education?"
    ],
    "Eggs": [
        "Do you like eating eggs?",
        "How often do you eat eggs?",
        "What’s your favorite way of cooking eggs?",
        "Have you ever eaten raw eggs?",
        "What’s the difference between white and brown eggs?",
        "What kind of meals do you cook with eggs?",
        "Do you like to know which poultry farm the eggs you buy come from?",
        "Do you think eggs are good value for money?",
        "What do you know about the nutritional value of eggs?",
        "Are there any interesting customs in your country using eggs?",
        "Do you prefer soft or hard boiled eggs?",
        "Have you had eggs from birds other than chickens?",
        "What does the expression “to have egg on your face” mean? Have you ever had egg on your face?",
        "Do you worry about diseases you can get from eggs?",
        "Do you prefer the egg white or the yolk?",
        "What are you like at breaking eggs when you cook?",
        "Do you usually buy free range eggs or those from battery chickens?",
        "Have you ever wanted to throw an egg at someone?",
        "What have you eaten in the past few days that contained eggs?",
        "What would your life be like without eggs?"
    ],
    "Egypt": [
        "What comes to mind when you hear the word ‘Egypt’?",
        "Do you think Egypt is one of the greatest countries in the world?",
        "What is your opinion of Egypt as a tourist destination?",
        "What do you know about the history of Egypt?",
        "What has Egypt given to the world?",
        "Do you think Egypt is a dangerous or safe country?",
        "Do you know anything about Egyptian politics?",
        "What would you like to do if you had 24 hours in Egypt?",
        "What would you like to do if you had a year in Egypt?",
        "What kind of relations does your country have with Egypt?",
        "What are the differences between Egypt today and Egypt in the past?",
        "What things is Egypt famous for?",
        "What do you know about Egypt’s cities?",
        "What do you know about Egyptian culture?",
        "What is Egypt famous for producing?",
        "Who are the most famous Egyptians you know?",
        "What problems are there in Egypt?",
        "What role does Egypt play in the Middle East? Should it do more",
        "What do you think it would be like to go back in time and live in Ancient Egypt?",
        "Talk for one minute about the future of Egypt."
    ],
    "Electricity": [
        "What is electricity?",
        "What kind of world would we live in without electricity?",
        "Do you worry about your electricity bill?",
        "Can you think of any alternatives to electricity?",
        "Do you ever have power cuts in your town?",
        "Have you ever had an electric shock?",
        "How often do you get a shock from static electricity?",
        "Do you think living near electricity power cables is dangerous?",
        "Do you have enough electrical sockets in your house for all of your electrical appliances?",
        "What do you know about the history of electricity?",
        "Do you think electricity is the greatest invention ever?",
        "What do you tell children about electricity?",
        "What dangers does electricity pose in your house?",
        "Are you satisfied with the safety standards for electricity in your country?",
        "What do you do to save on your electricity bills?",
        "Do you have any problems with electricity when you travel to another country?",
        "What would you like to ask an electricity expert?",
        "Do you think electricity will be wireless one day – just as computer software is wireless today?",
        "Do you think electricity is good value for money?",
        "What do you do to recharge your batteries?"
    ],
    "Elevators": [
        "Do you like elevators?",
        "What do you know (or can guess) about the history of elevators?",
        "How often do you use elevators?",
        "Which do you prefer, elevators or escalators?",
        "What do you do when you ride in an elevator?",
        "Are you thoughts and feelings different when you are in an elevator alone and when there are other people in it?",
        "What things do you look at while the elevator is going up or down?",
        "Why do people keep pressing the button to call the elevator, even though that doesn’t make the elevator come quicker?",
        "Do you have a favorite or least liked elevator?",
        "Do you always try to squeeze in even if the elevator looks full?",
        "Do you ever take the stairs?",
        "Do you ever worry about going into an elevator?",
        "What do you think of the music in elevators?",
        "Do you think all elevators should have a mirror?",
        "Have you ever got out of an elevator on the wrong floor?",
        "Have you ever been unable to control or stop your laughter in an elevator.",
        "What improvements do you think could be made to elevators?",
        "Would you like an elevator in your house?",
        "Have you ever had a bad experience in an elevator?",
        "Do you prefer the word ‘lift’ or ‘elevator’? Why?"
    ],
    "Employment": [
        "Do you have good employment prospects?",
        "What is your employment track record?",
        "Have you ever visited an online employment agency?",
        "Do you ever look at the employment pages in newspapers?",
        "Do you think companies should offer employees lifetime employment?",
        "Have you ever worked somewhere that had bad employment conditions?",
        "Do you always study the terms of employment carefully before you accept a job offer?",
        "Have you ever had your employment terminated?",
        "Are there any conditions of employment you insist on?",
        "Are working conditions in your country better than those in other countries?",
        "What do you understand by the term ‘full employment’?",
        "Is unemployment a problem in your country?",
        "Is there equal opportunities in employment in your country?",
        "Do you ever take any notice of employment statistics?",
        "Would you like to be self-employed?",
        "Do you think young people care enough about their employment prospects?",
        "Have you ever tried to change details on your employment contract?",
        "What rules should there be regarding children and employment?",
        "Which countries and companies do you think offer the best employment opportunities?",
        "What help should a government give those looking for employment?"
    ],
    "Endangered Species": [
        "Do you worry about the world’s endangered species?",
        "Which animals, fish and plants do you think are most endangered?",
        "What do you think the growing list of endangered species says about humankind?",
        "Which endangered species would you least like to see disappear?",
        "Are there endangered species in your country?",
        "Do you do anything to protect endangered species?",
        "Forty percent of all organisms are endangered. What do you think about this?",
        "Why are so many species becoming endangered?",
        "Do you think the list of endangered species can ever get shorter?",
        "Do you like actors from other countries?",
        "Do you think humans will ever be an endangered species?",
        "What should governments do to protect endangered species?",
        "What do you think of the sale of products made from endangered species and how can we stop it?",
        "Do you think endangered species can be bred in zoos or captive breeding programmes and then released into the wild?",
        "Would you like to work for an agency that protects endangered species?",
        "Do you know of any endangered species success stories?",
        "How important is it to teach children about endangered species?",
        "Which countries do you think are most guilty for endangering life?",
        "Do you think honest politicians are an endangered species?",
        "What question would you like to ask an endangered species?"
    ],
    "Energy": [
        "Does your country need a lot of energy?",
        "How can you save the amount of energy you use every day?",
        "Do you think scientists will solve the world’s energy problems?",
        "What happens if we run out of energy?",
        "Does your country use a lot of renewable energy?",
        "What do you think of a future in which we totally rely on nuclear energy?",
        "What are biofuels and what harm do they cause the environment?",
        "Have you started buying energy-efficient appliances for your house?",
        "Do you think its possible to get our future energy from some source we don’t yet know of?",
        "What do you think when multinational energy and oil companies say they care about the environment?",
        "How much energy do you use every day?",
        "Do you try to save energy?",
        "What do you think of the world’s hugely increasing energy needs?",
        "Do you think solar cells, wind farms, tidal power, hydropower and thermal energy will solve our future energy needs?",
        "How would the world be a better place if we used only clean energies?",
        "What have you done today that has used your country’s energy",
        "Do you think it’s possible for there to be energy wars, started by countries who have run out of energy?",
        "What do you think low energy houses of the future will be like?",
        "Does your government have/need an energy conservation policy?",
        "Do you think our energy demands are sustainable?"
    ],
    "Energy Levels": [
        "What is energy?",
        "How important is energy?",
        "Do you always have a lot of energy?",
        "What times of the day do you have most / least energy?",
        "What affects your energy levels?",
        "How can you quickly change your energy level?",
        "Do you know people who have bundles of energy?",
        "Do you ever have too much energy in your body?",
        "Why do you think some people have lots of energy while others have little energy?",
        "Do you always have enough energy to study English?",
        "What things do you do that require a lot of energy?",
        "What do you do when you are running low on energy?",
        "Do you ever have no energy to do something?",
        "Have your energy levels changed as you’ve become older?",
        "What do you do for an energy boost?",
        "Does the place you are in affect your energy levels?",
        "Does thinking require a lot of energy?",
        "How are your energy levels right now?",
        "Do you like being with people who are always full of energy?",
        "What things don’t you have the energy to do right now?"
    ],
    "England": [
        "What images spring to mind when you hear the country 'England'?",
        "What are the good things and bad things about England?",
        "What is England most famous for?",
        "What do you know about England’s history?",
        "What are the differences between England and your country?",
        "What do you think about English people?",
        "What has England given to the world?",
        "What is the difference between Great Britain, England and the United Kingdom?",
        "What do you know about the geography of England?",
        "Who are the most famous English people you know?",
        "How different is England from other European countries?",
        "What was the last news story you read or heard about England?",
        "What do you think it would be like (is like) to live in England?",
        "What do you think England will be like 50 years from now?",
        "Does your country have good relations with England?",
        "What can you do on a holiday in England?",
        "What is your idea of a typical English person?",
        "What things about England do you think the English are proud of?",
        "What do you know about English culture?",
        "What would you like to ask an English person about England?"
    ],
    "English": [
        "What images are in your mind when you hear the word ‘English’?",
        "Why are you studying English?",
        "What adjectives describe your feelings about English?",
        "How much time and money have you spent on English?",
        "How happy are you with your English level?",
        "Has English improved your life?",
        "Do you wish you didn’t have to study English?",
        "What is your best piece of advice to study English?",
        "Have all of your English teachers been good?",
        "How would your life be different without English?",
        "Why is English so important?",
        "What are the things you like most and least about English?",
        "Do you think English is more or less difficult than your language?",
        "What is your favourite word in English, and why?",
        "What's more important: speaking, reading, writing or listening?",
        "How important is English for you in your job or future?",
        "What did you think of English at school?",
        "Do you worry about making mistakes in English?",
        "What do you think of English grammar and spelling?",
        "How would your life change if you were fluent in English?"
    ],
    "Entertainment": [
        "What is entertainment?",
        "What do you do for entertainment?",
        "How often do you do things for entertainment?",
        "What home entertainment equipment do you have?",
        "Do you like entertaining friends at home?",
        "Who is the most entertaining person you know?",
        "Do you spend a lot of money on entertainment?",
        "What is your favourite form of entertainment?",
        "Would you like to work in the entertainment industry?",
        "What kind of person makes a good entertainer?",
        "What kind of TV shows do you watch for entertainment?",
        "Do you think your English classes are entertaining?",
        "What is the best evening of entertainment you’ve had recently?",
        "Do you think your country needs an Entertainment Secretary/Minister?",
        "Do you ever stop and watch street entertainment?",
        "What do you know about corporate entertainment?",
        "What forms of entertainment have been with us for centuries?",
        "What new forms of entertainment have emerged in recent years?",
        "Do you follow entertainment news on the TV or Internet?",
        "Which country do you think has the world’s best entertainment?"
    ],
    "Environment": [
        "Do you worry about the environment?",
        "What stories have you read or heard recently about the environment?",
        "What are the biggest problems facing our environment?",
        "What would you do to save our environment?",
        "What danger does your country pose to the global environment?",
        "Do you think the American government cares more about its economy or the environment?",
        "Which countries are leaders in caring about the environment?",
        "What do you know about the history of how our environment came to be under threat?",
        "Would you give money to or actively campaign for environmental causes?",
        "What do you think of environmental groups like Greenpeace?",
        "What is the quality of the environment in your country?",
        "What kind of environmental policies does your country have/need?",
        "How important is the natural environment to you in your daily life?",
        "Are you environmentally friendly?",
        "Do you think our environment is beyond repair?",
        "Do you think international meetings on the environment are useful?",
        "What do you think our grandkids will think of the way we treated the environment?",
        "What is your image of an environmentalist?",
        "If the environment could speak, what would it tell us?",
        "What is our duty as custodians of the environment?"
    ],
    "Environmental Problems": [
        "What do you think when you hear the words ‘environmental problem’?",
        "Do you add to the environment's problems in your daily life?",
        "What can you do every day to help the environment?",
        "Will the problems get worse or will they slowly disappear?",
        "What is the biggest environmental problem? Why do you think so?",
        "Which do you think is worse, litter in the countryside or coral bleaching?",
        "How eco-friendly is your country?",
        "What causes climate change and how can we reverse it?",
        "What problems do you know of about water?",
        "Will we (humans) kill the Earth one day?",
        "Why is an environmental problem a problem?",
        "What makes environmental problems?",
        "Do you think animals are angry with humans for destroying the Earth?",
        "Which do you think is worse, desertification or noise pollution?",
        "How would you explain to someone who doesn't know what global warming is?",
        "How would you feel if all the pandas died and became extinct?",
        "Who is most responsible for creating environmental problems?",
        "Is it better if we all went back to nature (left the cities and moved to the countryside)?",
        "Is it possible for everyone to change their lifestyle to help the Earth?",
        "Shopping increases environmental problems. Should we stop shopping?"
    ],
    "Equal Rights": [
        "Do you have equal rights?",
        "Do other people in your country have more rights than you?",
        "Is there perfect equality in your country?",
        "Which group of people in your country are least equal?",
        "Which areas of inequality make you angriest?",
        "What do you do when you see inequality in front to you?",
        "Which countries do you think give least regard to equal rights?",
        "What do you know about the history of equal rights?",
        "Which countries have championed equal rights or are good examples of how equality can be achieved?",
        "What do you think of the saying that “all men are born equal but some are born more equal than others”?",
        "What kinds of inequality exist in your country?",
        "What inequalities exist between the sexes?",
        "Is there a lot of racial discrimination in your country?",
        "Do you think one day everyone around the world will have equal rights?",
        "How would you feel if your rights were trampled on?",
        "Why don’t all countries insist on total equality in their societies?",
        "Do you think the USA is the shining example of equality?",
        "What examples can you think of to show that our world is the most unequal place imaginable?",
        "Do politician and the rich and famous have more rights than we do?",
        "How would the world be different if everyone on the planet enjoyed the same rights and no discrimination existed?"
    ],
    "Europe": [
        "What makes Europe so European?",
        "How are Europeans different from each other?",
        "What do you know about the European Union?",
        "What are your favourite European companies and why do you like them?",
        "Do you think Europe has the world’s most interesting history?",
        "Do you think English should be the official language of Europe?",
        "What are the differences between Europe and the USA?",
        "Do you think Europe is a superpower, or has the potential to become one?",
        "What is the most important European country?",
        "Movie producer Quentin Tarantino said the “funniest thing about Europe…is the little differences”. What do you think he means?",
        "Is Europe the greatest continent?",
        "How are Europeans different from people from other continents?",
        "What does it mean to be European?",
        "Is Europe really a continent – it isn’t surrounded by water?",
        "What do you understand by the term ‘Euroscepticism’?",
        "Do you think there is a European culture?",
        "What countries do you think have the fiercest rivalries in Europe?",
        "Former French leader Charles de Gaulle said “it is the whole of Europe that will decide the fate of the world”. What do you think?",
        "What does Europe do better than other continents?",
        "How do you think Europe will do in the next 100 years?"
    ],
    "Euthanasia": [
        "What comes to mind when you hear the word ‘euthanasia’?",
        "What is the legal status of euthanasia in your country?",
        "Do you agree with euthanasia?",
        "Do you understand why people choose euthanasia to end their life?",
        "The Ancient Greek for euthanasia is ‘good death’. What do you think of this meaning?",
        "‘Passive euthanasia’ is where somebody refuses medication knowing they will die without it. Do you think this is OK?",
        "‘Non-aggressive euthanasia’ is where life support systems keeping someone alive are switched off. What do you think of this?",
        "‘Aggressive euthanasia’ is where lethal substances are used to kill someone who wants to die. What do you think of this?",
        "What do you understand by the terms ‘mercy killing’ and ‘assisted suicide’?",
        "Do you know any famous cases of euthanasia?",
        "What is the difference between euthanasia and suicide?",
        "Is there a difference between euthanasia and murder?",
        "Does a family member or a doctor have the right to turn off a life support machine?",
        "How long should doctors keep someone alive who is brain dead?",
        "What does your religion say about euthanasia?",
        "Don’t you think doctors have a duty to keep people alive?",
        "Is euthanasia a compassionate way for the dying to die?",
        "Do governments have the right to keep suffering people alive?",
        "Why not allow euthanasia to save on health care costs?",
        "Do people have a right to die?"
    ],
    "Evolution": [
        "What springs to mind when you hear the word ‘evolution’?",
        "Do you believe the story of evolution as told in religious books?",
        "How do you think the world got here?",
        "How do you think we got here?",
        "What do you think we will look like millions of years from now?",
        "Why have we evolved into different looks and colours?",
        "How was the very first life form created and what did it do/look like?",
        "Why is Darwin’s Theory of Evolution discarded by so many religions?",
        "Many schools in the USA teach creationism – the idea that God put humans on Earth as we are today. What do you think of this?",
        "Do you think God created everything as it is outlined in the book of Genesis?",
        "What do you understand by the term ‘natural selection’?",
        "Do you think Darwin’s theory of evolution is the best?",
        "Do you think we descended from the apes?",
        "Do you think humans are set apart from the animal kingdom?",
        "Many followers of the ‘Intelligent Design’ theory say we were created by an intelligent designer. What do you think?",
        "What do you think of the ‘survival of the fittest’ theory?",
        "Do you think evolution is a random process?",
        "How long ago did human become human and what made us human?",
        "Can you watch evolution happening?",
        "How can we know what happened millions of years ago?"
    ],
    "Excel": [
        "What do you think of Microsoft’s Excel?",
        "Can you remember the first time you used it?",
        "What is your level of expertise at using Excel and why?",
        "How useful is Excel to you?",
        "What do you use Excel for in your personal and work life?",
        "What would your life be like without Excel?",
        "What problems have you had with Excel?",
        "What new features would you like added to Excel?",
        "What is the thing that makes you angriest when using Excel?",
        "Do you use the Visual Basic part of Excel?",
        "How did you learn to use Excel?",
        "Have you read any “for dummies” books or been to any training sessions on Excel?",
        "Do you think all schoolchildren should be taught how to use Excel?",
        "Which do you prefer, MS Word, Powerpoint or Excel?",
        "What would you like to do with Excel that you don’t know how to?",
        "Have you ever made a big mistake when using Excel?",
        "Have you ever lost a lot of work on Excel?",
        "What would life be like if you suddenly lost all your .xls files?",
        "How many times have you wanted to punch the computer while using Excel?",
        "What questions would you like to ask the designers of Excel?"
    ],
    "Exercise": [
        "What springs to mind when you hear the word ‘exercise’?",
        "Why is exercise so important?",
        "What kind of exercise do you think is best?",
        "Do you wish you could exercise more?",
        "Why do many people not exercise?",
        "Do you think it’s easy or difficult to find time to exercise during the day?",
        "Do you think people who exercise are happier than those who don’t?",
        "Do you think there should be a law that requires everyone to exercise?",
        "Is it more fun to exercise alone or with other people?",
        "Do you need advice about how to exercise?",
        "Do you like exercise?",
        "Who do you know who exercises a lot?",
        "What are the bad things about exercise?",
        "Which exercise would you prefer: jogging, swimming or cycling?",
        "Is not exercising a crime against your body?",
        "Do you think the government should do more to ensure everyone exercises?",
        "How can you adapt the everyday things you do to increase your level of exercise?",
        "Do you think exercising makes your brain work better?",
        "What do you think of the idea of having higher hospital charges for those who don’t exercise?",
        "If exercise makes you live a lot longer, why do so many people not bother to do it?"
    ]
}
