export default {
    "-ed / -ing Adjectives (grammar)": [
        "What depressing news have you heard or read about recently?",
        "When was the last time you were very disappointed?",
        "What’s the most disgusting food you’ve ever tasted?",
        "When was the last time you were very embarrassed?",
        "What things are frightening for kids? Were you frightened by them?",
        "Who is the most irritating person you know?",
        "When was the last time you were shocked? What was shocking?",
        "What three things in your life are the most tiring?",
        "Have you seen a really horrifying movie?",
        "What do you get frustrated about?"
    ],
    "Articles (grammar)": [
        "What do you think about the English articles ‘a’, ‘an’ and ‘the’?",
        "Do you have articles in your own language?",
        "What do you think when your teacher says you’ll do a lesson on articles?",
        "What are articles for?",
        "What are your biggest problems with articles?",
        "Would the English language be so different without articles?",
        "What does ‘a’ and ‘an’ mean?",
        "Why do we say ‘the biggest’, ‘the most important’ but not ‘a biggest’ or ‘a most important’?",
        "Would the Philippines, the Maldives, the USA etc be any different without ‘the’?",
        "When do you think articles are absolutely, totally necessary?",
        "What do you know about English articles?",
        "What advice would you give to someone trying to learn articles?",
        "What’s the difference between ‘a’ and ‘an’?",
        "Does your teacher do a good job at explaining articles?",
        "What’s the difference between “I’m a student” and “I’m the student”?",
        "How would you describe what articles are to an alien?",
        "Do you think the terms ‘definite article’ and ‘indefinite article’ help you understand articles better?",
        "Do you care about whether or not you understand articles and use them correctly?",
        "Why is it “Once upon a time” but “The end”? How would “An end” or “Once upon the time” change things?",
        "Did you like this discussion on articles?"
    ],
    "Comparatives (grammar)": [
        "Which is more difficult to learn, English or your language?",
        "What things are you better at than your best friend?",
        "Are people today luckier than they were 50 years ago?",
        "Is it better to study English in class or online?",
        "Are you happier now or were you happier when you were younger?",
        "Are video games better for you than watching TV?",
        "What is worse than failing exams?",
        "Is it better to go on a date with someone who is older or younger than you?",
        "Do you think buying a more expensive brand means it is much better than a cheaper brand?",
        "How much would you pay to have an Internet connection that is 100 times faster than the one you have now?",
        "Does life get more complicated the older you become?",
        "Is the world safer now than it was before 9-11?",
        "Is studying comparatives easier or more difficult than studying superlatives?",
        "Will tomorrow be more interesting than yesterday?",
        "Is there anything more delicious than your mother’s cooking?",
        "What is healthier: eating good food or getting lots of exercise?",
        "Would you like to be more beautiful / more handsome than you are now or more intelligent than now?",
        "Which is worse: a virus attacking your computer or a virus attacking your body?",
        "Are you smarter than your parents? In what way(s)?",
        "What would you like to be better at than anyone else in the world? Why?"
    ],
    "Do You Ever...? (grammar)": [
        "Do you ever wonder what life is all about?",
        "Do you ever type LOL (laugh out loud) when really you aren’t laughing?",
        "Do you ever think you have too many things to finish on time?",
        "Do you ever want to throw all your clothes away and start your wardrobe again?",
        "Do you ever feel jealous of your friends?",
        "Do you ever lie to your parents?",
        "Do you ever get really angry with yourself?",
        "Do you ever regret eating something after eating it?",
        "Do you ever wish you could be someone else?",
        "Do you ever think you have bad luck?",
        "Do you ever think studying English is a waste of time?",
        "Do you ever dream about being really, really rich?",
        "Do you ever buy things and then think it was a mistake?",
        "Do you ever give money to charity?",
        "Do you ever forget the names of people you’ve just met?",
        "Do you ever wish you could be somewhere else?",
        "Do you ever worry about the future of the planet?",
        "Do you ever get confused with all this new technology?",
        "Do you ever think you friends don’t like you?",
        "Do you ever think you’re the happiest person in the world?"
    ],
    "First Conditional (grammar)": [
        "What will you do if you miss your family & friends?",
        "What will you do if you have problems with the English language?",
        "What will you do if you can't stand the heat?",
        "What will you do if you want to move back to your home country?",
        "What will you do if you fall ill?",
        "What will you do if you run out of money?",
        "What will you do if you get bored?",
        "What will you do if you don't like the food in the UK?",
        "What will you do if you split up with your partner?",
        "What will you do if you feel lonely?",
        "What will you do if your neighbours annoy you?",
        "What will you do if someone phones you during the English lesson?",
        "What will you do if you don't enjoy life in the UK?",
        "What will you do if your friend invites you to the cinema tonight?",
        "What will you do if your purse or wallet is stolen?",
        "What will you do if you get a headache?",
        "What will you do if you split up with your partner?",
        "What will you do if your neighbours annoy you?",
        "What will you do if you it rains at the weekend?",
        "What will you do if you run out of food in your house?"
    ],
    "Going To (grammar)": [
        "What are you going to do with your life?",
        "What are you going to do after this class?",
        "Where are you going to go for your next holiday?",
        "Are you going to meet anyone at the weekend?",
        "Are you going to watch television tonight?",
        "What book are you going to read next?",
        "When are you going to give up your bad habits?",
        "What’s the next big decision you’re going to make?",
        "Where in the world are you going to travel?",
        "Are you going to play any video games later today?",
        "What hairstyle are you going to have next?",
        "What are you going to have for lunch / dinner?",
        "What are you going to do on your next birthday?",
        "How are you going to get better at speaking English?",
        "Who are you going to text or send an e-mail to today?",
        "What mobile phone are you going to buy next?",
        "What are you going to do after you finish studying?",
        "Are you going to be rich and famous?",
        "When are you going to stop studying English?",
        "Are you going to live happily ever after?"
    ],
    "Have You Ever...? (grammar)": [
        "Have you ever lost some money?",
        "Have you ever broken a bone?",
        "Have you ever been on a really exciting holiday in another country?",
        "Have you ever felt like giving up studying English?",
        "Have you ever had a fight and lost?",
        "Have you ever told a big, big lie to your parents?",
        "Have you ever done anything illegal?",
        "Have you ever eaten something quite strange?",
        "Have you ever made someone you love very angry?",
        "Have you ever wanted to dance in the streets because you were so happy?",
        "Have you ever cried while watching the news?",
        "Have you ever dreamed about being famous?",
        "Have you ever lost your temper and got really angry in public?",
        "Have you ever raised money for charity?",
        "Have you ever sent someone an e-mail and then regretted sending it?",
        "Have you ever broken something and pretended it wasn’t you who broke it?",
        "Have you ever fallen in love at first sight?",
        "Have you ever won a prize that you thought was a bad prize?",
        "Have you ever met anyone famous?",
        "Have you ever lent someone something and they didn’t give it back?"
    ],
    "How Often...? (grammar)": [
        "How often do you study English? How often should you study?",
        "How often are you in trouble with someone? Who and why?",
        "How often do you feel on top of the world? Is it a good feeling?",
        "How often do you like going shopping?",
        "How often do you think about the world’s future? Are they good thoughts?",
        "How often do you get angry with other people? Who are they?",
        "How often did you get presents when you were a child?",
        "How often do you wish you were somewhere else of someone else? Who and where?",
        "How often should you exercise? How often do you exercise?",
        "How often are you ill? Is this more or less often than your friends?",
        "How often do you do you think ‘how often do I have to do this’? What is it you think about?",
        "How often do you worry about your hair and the way you look? Is it a problem for you?",
        "How often do you check your e-mail?",
        "How often is too often?",
        "How often do you change your mobile phone? Why?",
        "How often do you wish you had special powers? What are these powers?",
        "How often do you spoil yourself?",
        "How often do you think about money? Is this good or bad?",
        "How often will you study English in the future?",
        "How often did you cry when you were younger? What were the main reasons?"
    ],
    "Prefer... (grammar)": [
        "Do you prefer studying English using books or Internet resources?",
        "When do you prefer to study, in the morning, afternoon or evening?",
        "Do your teachers ever ask you what you prefer doing?",
        "Do you prefer to have a choice in class or do what your teacher thinks is best?",
        "Do you prefer doing lessons on reading, writing, speaking or listening?",
        "Would you prefer to have a different teacher?",
        "How do you prefer to study?",
        "Which do you prefer, studying in class with a teacher or studying alone?",
        "What’s the difference between ‘prefer doing something’ and ‘prefer to do something’?",
        "Would you prefer an English teacher from your own country or one from an English-speaking country?",
        "Do you prefer paper dictionaries or online / electronic dictionaries?",
        "What topics do you prefer to talk about in class and which do you prefer to not talk about?",
        "Do you prefer talking with the person next to you in class or moving around and talking to different students?",
        "Do you prefer male or female teachers?",
        "Do you prefer your teacher explaining grammar on the board or working it out for yourself?",
        "Have you ever told your teacher what you prefer doing in class?",
        "What things do you think your teacher might prefer to do differently in class?",
        "What are the differences between ‘prefer’ and ‘would rather’?",
        "Would you prefer to have more, less or no homework?",
        "What would you prefer to do instead of having this discussion?"
    ],
    "Present Perfect (grammar)": [
        "What do you know about the present perfect in English?",
        "What are the different functions of the present perfect?",
        "If a student wanted you to explain the present perfect to them, what would you tell them?",
        "What are your biggest problems with the present perfect?",
        "What’s the difference between ‘Have you ever…’ and ‘Do you ever…’?",
        "Can you think of a more helpful or useful name for the present perfect than ‘the present perfect’?",
        "Does your teacher put a timeline on the board to help explain the present perfect? Is this useful?",
        "What’s the difference between the present perfect and the past simple?",
        "Teachers often talk about ‘unfinished time’ when teaching the present perfect. Do you understand this?",
        "What is your favourite present perfect question?",
        "What do you think when your teacher tells you you’re going to do a lesson on the present perfect?",
        "What does the ‘present’ and the ‘perfect’ mean in the present perfect?",
        "Is there anything similar to the present perfect in your language?",
        "How is the present perfect formed (questions, negatives and statements)?",
        "Can you remember a good or a bad present perfect lesson?",
        "What’s the difference between ‘Have you ever...’  and ‘Have you…’ How does the word ‘ever’ change the question?",
        "Do you think there’s a big difference between ‘gone’ and ‘been’?",
        "What would English be like without the present perfect?",
        "What three adjectives would you use to describe the present perfect? Why these three adjectives?",
        "What’s the difference between the present perfect and the perfect present?"
    ],
    "Present Simple (grammar)": [
        "What do you know about the present simple in English?",
        "What are the different functions of the present simple?",
        "If a student wanted you to explain the present simple to them, what would you tell them?",
        "What are your biggest problems with the present simple?",
        "What difference do you think the ‘third person s’ makes to communication?",
        "Is the present simple really so simple?",
        "What does your teacher do to help you explain the present simple?",
        "How often do you think you make mistakes using the present simple?",
        "How many times have teachers tried to teach you the present simple?",
        "What is your favourite present simple activity?",
        "What do you think when your teacher tells you you’re going to do a lesson on the present simple?",
        "Do you enjoy talking about habits, routines, everyday life, etc. when you study the present simple?",
        "Is there anything similar to the present simple in your language?",
        "How is the present simple formed (questions, negatives and statements)?",
        "Can you remember a good or a bad present simple lesson?",
        "What do you think of the materials and lessons in course books that help you understand the present simple?",
        "Do you think the present simple is just for beginners?",
        "What would English be like without the present simple?",
        "What three adjectives would you use to describe the present simple? Why these three adjectives?",
        "What’s the difference between the present simple and a simple present?"
    ],
    "Put & Take (grammar)": [
        "When was the last time you took something apart? What was it and how old were you?",
        "When did you last have to take back something you had said?",
        "Have you ever taken something back to a shop? What was it and why?",
        "What has been the most difficult thing to take in this term?",
        "Can you tell us a time when you had to take on new responsibilities in your job or family?",
        "What was the last hobby you took up?",
        "When were you last taken out? By who?",
        "Do you take after anyone else in your family?",
        "When did you last have a take away? What did you have?",
        "When you were a child, was anything ever taken away from you? What was it and why?",
        "When was the last time you put away a really big meal? What did you have?",
        "Do you often get told off for not putting things away?",
        "Do you know anyone that has been put away? What did they do?",
        "Have you ever put anyone down or has anyone put you down? Why?",
        "Apart from doing your homework, is there anything else that you sometimes put off?",
        "Who do you have the most difficulty putting up with?",
        "When was the last time you put somebody up? Who was it and for how long?",
        "Do you often put on special clothes to go out?",
        "Have you ever put on a play / show / concert or know anyone who has?",
        "When was the last time you put someone on? Did they find it funny?"
    ],
    "Second Conditional (grammar)": [
        "If you could be anyone in the world, who would you be?",
        "If you were an animal, what animal would you be?",
        "If you went back in time, what year would you go to?",
        "If you had a special power, what would you be able to do?",
        "If you could make one change to the world, what would you do?",
        "If you could change something about your past, what would you change?",
        "What would you like to do if you were a member of the opposite sex for one day?",
        "If you had billions and billions of dollars, how much would you give to charity, and which charities?",
        "If you could go on a date with anyone in the world, who would it be?",
        "If you stopped studying English, would your life change?",
        "If you told me all of your secrets, would I be shocked?",
        "If you changed your name, what name would you choose?",
        "If you could speak three other languages. What would they be?",
        "If you could decide what happens in your life tomorrow, what would you want to happen?",
        "Where would you live if you could live anywhere in the world?",
        "If a natural disaster hit your town, what would you do?",
        "If you became a rock star, what kind of songs would you sing and what image would you have?",
        "If the world was going to end at 3.37 tomorrow afternoon, what would you do up until that time?",
        "If you were the world’s best at something, what would you like to be best at?",
        "If you were a colour, what colour would you be and why?"
    ],
    "Superlatives (grammar)": [
        "Who is the best?",
        "What’s the most disgusting food you’ve ever eaten?",
        "When was the happiest period of your life?",
        "What’s the most difficult thing about studying English?",
        "Who do you think is the most dangerous person in the world?",
        "Who is the nicest person you know?",
        "When is the most relaxing part of the day for you?",
        "What is the hardest thing to understand about superlatives?",
        "What do you think it would be like to be the most beautiful / handsome person in the world?",
        "Is it important for you to have the best quality of everything?",
        "What’s the best country in the world? (and the second best and third best?)",
        "What’s the most exciting video game you know?",
        "What’s the funniest book you’ve ever read and the funniest movie you’ve ever seen?",
        "What is the saddest sight you’ve seen on television recently?",
        "What is your worst nightmare?",
        "Can you remember the most wonderful day of your life?",
        "What’s the most stupid thing you’ve ever done, and the most stupid thing you’ve ever said to someone?",
        "Who’s the craziest person you know?",
        "Do you like having the latest things and knowing the latest news?",
        "What’s the earliest you could get up every morning?"
    ],
    "What's It Like...? (grammar)": [
        "What’s it like being you?",
        "What’s it like in your idea of paradise?",
        "What’s it like being your age?",
        "What’s it like living in the 21st Century?",
        "What’s it like studying English?",
        "What’s it like sitting here and doing this activity with me?",
        "What’s it like outside?",
        "What’s it like to be your best friend?",
        "What’s it like to be a citizen of your country?",
        "What’s it like to be at your level of English?",
        "What’s it like in your secret world inside your head?",
        "What’s it like to be intelligent and talented?",
        "What’s it like having the friends and family you have?",
        "What’s it like in your house for a special occasion?",
        "What’s it like to be lucky?",
        "What’s it like to dream?",
        "What’s it like to be a man/woman today?",
        "What’s it like living on the money you have?",
        "What’s it like in the world you’d like to live in?",
        "What’s it like living in your town?"
    ],
    "What's Your Favourite...? (grammar)": [
        "What’s your favourite time of the day (and why)?",
        "Where’s your favourite place to study (and why)?",
        "Who’s your favourite and least favourite actor (and why)?",
        "What are your favourite sports (and why)?",
        "Where’s your favourite place to go and relax and think about life?",
        "What’s your favourite expression in English?",
        "What was your favourite TV programme when you were a child?",
        "What’s your favourite fast food and fast food restaurant?",
        "What’s your favourite ‘English mistake’ story?",
        "What are your favourite clothes and clothes stores?",
        "What are your favourite pieces of software and computer programmes?",
        "Who are your favourite and least favourite teachers (and why)?",
        "What were your favourite and least favourite subjects at school?",
        "What are your least favourite words (in English and in your own language)?",
        "What’s your favourite and least favourite feature (this could be part of your face and body or your personality)?",
        "What’s your favourite song (and why)?",
        "Who is your favourite and least favourite world leader (and why)?",
        "What’s your favourite joke? Tell it to me.",
        "What’s your favourite and least favourite time of the year (and why)?",
        "Who is your favourite person in the whole wide world?"
    ],
    "When Did You First...? (grammar)": [
        "When did you first use the Internet? How was it?",
        "When did you first go to the cinema? What did you see?",
        "When did you first use a mobile phone? Who did you call?",
        "When did you first think life was great? What happened?",
        "When did you first travel alone? Where did you go?",
        "When did you first have some real money? How did you feel?",
        "When did you first think the world was a dangerous place?",
        "When did you first smoke / drink alcohol?",
        "When did you first fly? What was it like?",
        "When did you first buy someone a present?",
        "When did you first fall in love with someone or something?",
        "When did you first study English? Did you like it?",
        "When did you first buy something expensive? Do you still have it?",
        "When did you first meet your best friend? Was it instant friendship?",
        "When did you first hear your favourite song?",
        "When did you first earn some money? Was it worth it?",
        "When did you first decide on your own hairstyle? Did it look fantastic?",
        "When did you first fail or did poorly in an exam?",
        "When did you first regret doing something? Do you still regret it?",
        "When did you first remember feeling real pain? What happened?"
    ],
    "When Did You Last...? (grammar)": [
        "When did you last you say no?",
        "When did you last you hurt yourself?",
        "When did you last you think to yourself, ‘never again’?",
        "When did you last feel on top of the world?",
        "When did you last tidy your room / your desk?",
        "When did you last shout at somebody?",
        "When did you last have a problem with your computer?",
        "When did you last have a perfect day?",
        "When did you last you say sorry?",
        "When did you last bump into an old friend?",
        "When did you last cry?",
        "When did you last feel really, really angry?",
        "When did you last forget to do something?",
        "When did you last have a fight with someone?",
        "When did you last do something that made you very happy?",
        "When did you last feel positive about Earth’s future?",
        "When did you last get a real letter written by a real person?",
        "When did you last receive some bad news?",
        "When did you last change your plans for your life?",
        "When did you last get lost?"
    ],
    "When Was The First Time...? (grammar)": [
        "When was the first time you used the Internet? How was it?",
        "When was the first time you went to the cinema? What did you see?",
        "When was the first time you used a mobile phone? Who did you call?",
        "When was the first time you thought life was great? What happened?",
        "When was the first time you traveled alone? Where did you go?",
        "When was the first time you had some real money? How did you feel?",
        "When was the first time you thought the world was a dangerous place?",
        "When was the first time you smoked / drank?",
        "When was the first time you flew? What was it like?",
        "When was the first time you bought someone a present?",
        "When was the first time you fell in love with someone or something?",
        "When was the first time you studied English? Did you like it?",
        "When was the first time you bought something expensive? Do you still have it?",
        "When was the first time you met your best friend? Was it instant friendship?",
        "When was the first time you heard your favourite song?",
        "When was the first time you earned some money? Was it worth it?",
        "When was the first time you decided on your own hairstyle? Did it look fantastic?",
        "When was the first time you failed or did poorly in an exam?",
        "When was the first time you regretted doing something? Do you still regret it?",
        "When was the first time you remember feeling real pain? What happened?"
    ],
    "When Was The Last Time...? (grammar)": [
        "When was the last time you said no?",
        "When was the last time you hurt yourself?",
        "When was the last time you thought to yourself, ‘never again’?",
        "When was the last time you felt on top of the world?",
        "When was the last time you tidied your room / your desk?",
        "When was the last time someone shouted at you?",
        "When was the last time you had a problem with your computer?",
        "When was the last time you had a perfect day?",
        "When was the last time you said sorry?",
        "When was the last time you bumped into an old friend?",
        "When was the last time you cried?",
        "When was the last time you felt really, really angry?",
        "When was the last time you forgot to do something?",
        "When was the last time you had a fight with someone?",
        "When was the last time someone did something that made you very happy?",
        "When was the last time you felt positive about Earth’s future?",
        "When was the last time you got a real letter (one in an envelope with a stamp on it) written by a real person?",
        "When was the last time you received some bad news?",
        "When was the last time you changed your plans for your life?",
        "When was the last time you were lost?"
    ],
    "Will You Ever...? (grammar)": [
        "Will you ever be happy with your level of English?",
        "Will you ever earn the amount of money you’d like to?",
        "Will you ever find true happiness?",
        "Will you ever give up your bad habits?",
        "Will men ever understand women?",
        "Will we ever live on the Moon or travel to Mars?",
        "Will we ever live as equals?",
        "Will you ever run out of dreams?",
        "Will you ever be happy with the way you look?",
        "Will teenagers ever listen?",
        "Will we ever find the answer to the meaning of life?",
        "Will you ever stop studying?",
        "Will we ever find life in outer space?",
        "Will you ever truly learn from your mistakes?",
        "Do you think humans will ever be cloned?",
        "Will you ever do all the things you want to do in life?",
        "Will you ever get bored of the Internet?",
        "Will the world ever be at peace?",
        "Will you ever again have the same hair styles you had when you were younger?",
        "Will we ever stop watching rubbish on television?"
    ],
    "Would You Ever...? (grammar)": [
        "Would you ever stop studying English?",
        "Would you ever change your religion or take up a religion?",
        "Would you ever marry for money?",
        "Would you ever leave your country forever?",
        "Would you ever have cosmetic surgery?",
        "Would you ever commit a serious crime?",
        "Would you ever beg in the streets?",
        "Would you ever lie to the police?",
        "Would you ever get a tattoo on your face?",
        "Would you ever stop supporting your favourite sports team?",
        "Would you ever hurt someone you loved?",
        "Would you ever agree to being cloned?",
        "Would you ever consider avoiding computers?",
        "Would you ever say goodbye to your best friend forever?",
        "Would you ever date someone with a criminal record?",
        "Would you ever sell your collection of music or books?",
        "Would you ever consider being a spy for your country?",
        "Would you ever shave off all the hair on your head?",
        "Would you ever give all of your money to charity?",
        "Would you ever change your name?"
    ]
}
