export default {
    "MP3s": [
        "What comes to mind when you hear the word/abbreviation ‘MP3’?",
        "What do you know about MP3s?",
        "Is downloading or copying music in MP3 format better than using CDs, MDs, records and cassettes?",
        "What MP3 players do you know of and which one is best?",
        "Do you visit free MP3 download sites?",
        "What are the good and bad things about MP3 songs?",
        "Is iTunes the best way to store your music library?",
        "Is the iTunes store the best place to buy music on MP3?",
        "What happens when you press ‘delete’ by mistake and wipe out your entire music collection?",
        "What new functions would you like to see on an MP3 player?",
        "What size MP3 player do you need? How many songs do you want to carry around?",
        "What do your grandparents think of MP3 technology?",
        "Have you ever downloaded MP3s illegally?",
        "Have you ever had any problems with MP3 technology?",
        "What do you think will replace MP3 and make it look like old technology?",
        "What do you think of file sharing sites like Napster and Limewire?",
        "Do you have trouble keeping up with new MP3 vocabulary like ‘rip’ and ‘burn’?",
        "Has MP3 technology changed your music habits in any way?",
        "Do you think MP3 will make CDs obsolete?",
        "What questions about MP3s / MP3 technology would you like answered?"
    ],
    "Magazines": [
        "What comes to mind when you hear the word ‘magazines’?",
        "What were the first magazines you started reading?",
        "Do you subscribe to any magazines?",
        "What do you think of the selection of magazines usually found in dental clinics, doctor’s surgeries and hair salons?",
        "What’s your favourite magazine?",
        "Do you think there are magazines for every kind of hobby and interest?",
        "Do you read magazines that are published especially for English learners?",
        "Do you think magazines in English are better than those in your own language?",
        "Do you keep magazines after you’ve read them or do you throw them away?",
        "Do you ever read online magazines? Do you think they are better than paper magazines?",
        "Do you read magazines in English?",
        "What kinds of magazines are there in your country?",
        "Which do you like better, magazines or newspapers?",
        "Do you ever read or look at magazine’s written for members of the opposite sex – men’s magazine and women’s magazines?",
        "How different do you think magazines are in Arab countries, Japan and Sweden?",
        "What kinds of magazines in your country are on the top shelf? Is this where they belong?",
        "Are magazines the best thing to use to kill insects in your house?",
        "Would you prefer to read a fashion, gossip, sports or car magazine?",
        "What magazine would you like to see created that would be perfect for you?",
        "If your face could be on the cover of any magazine in the world, what publication would you choose, and why?"
    ],
    "Magic": [
        "What comes to mind when you hear the word ‘magic’?",
        "Do you like watching magic shows?",
        "What’s your favourite magic trick and why?",
        "Would you like a magic carpet? Where would you go on it?",
        "What role does magic play in your culture?",
        "Do you think magic is something good or dangerous?",
        "What equipment do you need to do magic?",
        "What books and movies about magic do you like?",
        "Do you think a magician is an artist?",
        "What questions would you like to ask a magician?",
        "What is magic?",
        "Do you believe people can do magic?",
        "What do you know about black magic?",
        "What would you do with a magic wand if you had one? Where would you wave it?",
        "What did you think of magic when you were a kid?",
        "Which did you believe in first; love, faith or magic?",
        "Does anyone you know have a magic touch with people / things?",
        "Is there a magic formula to studying English?",
        "What is the most magic moment in your life?",
        "What magic powers would you like to have?"
    ],
    "Malaria": [
        "What images spring to mind when you hear the word ‘malaria’?",
        "What are the symptoms of malaria?",
        "What do you know about malaria?",
        "Do you think it’s possible to rid the world of malaria?",
        "Why are so many African children still dying from malaria?",
        "Have you ever been in a country in which there is malaria?",
        "Will attitudes towards area change if it spreads to Europe and North America with global warming?",
        "How can malaria be prevented?",
        "Would you give money to help fight malaria?",
        "Have you ever had a malaria vaccine or taken malaria tablets?",
        "How do people get malaria? How is it transmitted?",
        "Who is most at risk of getting malaria?",
        "Why do you think Malaria hasn’t been eradicated?",
        "What does malaria do to your body?",
        "Why do you think malaria is so common in Africa?",
        "What parts of the body does malaria usually affect?",
        "What do you think should happen on a World Malaria Day?",
        "Would you avoid going to a country in which there is Malaria?",
        "Do you ever use mosquito repellents?",
        "What questions would you like to ask a researcher into malaria?"
    ],
    "Malaysia": [
        "What images spring to mind when you hear the country Malaysia?",
        "What are the good things and bad things about Malaysia?",
        "What is Malaysia famous for?",
        "What do you know about Malaysian history?",
        "What images of Malaysia do you have that are exotic?",
        "What do you think about Malaysia?",
        "What has Malaysia given to the world?",
        "Would you like to visit Malaysia, or live there?",
        "What do you know about the economy of Malaysia?",
        "Who are the most famous Malaysian people you know?",
        "How different is Malaysia from other Asian countries?",
        "What do you know about Malaysia’s cultures?",
        "Do you think Malaysia is a good tourist destination?",
        "What do you think Malaysia will be like 50 years from now?",
        "Does your country have good relations with Malaysia?",
        "What does your country have in common with Malaysia?",
        "What is your idea of a typical Malaysian person?",
        "What things about Malaysia do you think Malaysian people are proud of?",
        "What do you know about Malaysia’s geography?",
        "What would you like to ask a Malaysian person about Malaysia?"
    ],
    "Management": [
        "What comes to mind when you hear the word ‘management’?",
        "Would you like to work in management?",
        "What do you think of the management of this school?",
        "What kind of people do well working in management?",
        "What is brand management?",
        "What are the good and bad things about working in management?",
        "What are the differences between working in middle and top-level management?",
        "What kind of management do you think it would be good to get into – hotel management, sports, entertainment, tourism, business…?",
        "Do you think management makes people happy?",
        "Do you think it would be interesting to study management?",
        "What do you think of management?",
        "How do you think management styles differ between countries?",
        "Have you ever complained to the management of a company, store, restaurant…?",
        "What good management techniques do you think you have?",
        "Do you think average workers have a better quality of life than those in management?",
        "Do you think working in environmental management would be interesting?",
        "What kind of lifestyle do you think a management consultant has?",
        "When was the last time you heard about a management buyout?",
        "What experiences have you had in management teams or dealing with them?",
        "How do you make the management of a company more effective and productive?"
    ],
    "Maps": [
        "What comes to mind when you hear the word ‘maps’?",
        "Do you like maps?",
        "Are you good at reading maps?",
        "Are men or women better at reading maps?",
        "Are you good at drawing maps?",
        "Have you ever used Google earth to make a map?",
        "What do you think when you look at a map of your country?",
        "Do you need a physical map to find a new place or can you picture the map in your head?",
        "Do you understand all of the symbols on a map?",
        "What do you think of A-Z maps?",
        "Do you prefer foldaway maps or atlas maps?",
        "Do you ever use mind maps to study English vocabulary?",
        "What do you think when you look at a map of the world?",
        "Have you ever got lost using a map?",
        "Have you ever followed a map that was in a language different to your own?",
        "Do you think maps look good hanging on living room walls?",
        "Do you think treasure maps exist? Would you like one?",
        "Do you think maps of museums and art galleries are always easy to understand?",
        "Would you like to work a cartographer (a map maker)?",
        "How long can you spend looking at a map and enjoying it?"
    ],
    "Marathons": [
        "What comes to mind when you hear the word ‘marathon’?",
        "What do you know about marathons?",
        "What do you think of marathon runners?",
        "What do you know about the history of marathons?",
        "What do you need to do to train for and run a marathon?",
        "How do you think a marathon runner’s life is different to your life?",
        "Why do you think marathon runners like doing marathons?",
        "What do people think about while they’re doing a marathon?",
        "Do you think marathon running damages your body?",
        "Why don’t you run in a marathon?",
        "Is running a marathon a big achievement?",
        "Is the marathon gold the best medal to win in an Olympics games?",
        "Do you like going to a city to watch a marathon?",
        "Do you know of any famous marathon runners?",
        "Which nationalities are best at marathons and why?",
        "How would a person’s life change if he/she won a gold medal at the Olympics?",
        "Would you prefer to run in the Great Wall of China Marathon, the Great Tibetan Marathon or the Polar Circle Marathon?",
        "How would life be different if we could skip, hop and bounce as far as kangaroos can?",
        "What questions would you like to ask a marathon runner?",
        "No one has ever run a marathon inside two hours. When do you think this might happen? What time is the absolute fastest for a human?"
    ],
    "March": [
        "What springs to mind when you hear the word ‘March'?",
        "What do you think of the month of March?",
        "What good things happen in March?",
        "What things do you usually do in March?",
        "What do you think of the word 'March'?",
        "What are people who are born in March like?",
        "What do you think of March weather?",
        "Where is March on the list of 'the best months'?",
        "Are there any bad things about the month of March?",
        "What plans do you have for next March?",
        "If you made a March festival, what would you it be like?",
        "Is there any delicious food you eat in March?",
        "How should people celebrate in March?",
        "What famous holidays are there in March?",
        "How do you feel when March arrives?",
        "If you made a video about March, what would you put in it?",
        "How do you feel when March is over?",
        "What three adjectives best describe March, and why?",
        "What good thing can you remember happening in March?",
        "What is a good symbol for March, and why?"
    ],
    "Marijuana": [
        "What comes to mind when you hear the word ‘marijuana’?",
        "Which do you prefer, marijuana, alcohol or caffeine?",
        "If marijuana takes away pain, shouldn’t it be a medicine?",
        "Why do so many countries allow the sale of a damaging drug like alcohol, but ban marijuana?",
        "How would society change if marijuana was legalized?",
        "What word do you like better, marijuana or cannabis?",
        "Why are so many people in favor of legalizing marijuana?",
        "Should politicians who claim to have smoked a little marijuana “at university” resign?",
        "What role does marijuana play in your country’s culture?",
        "What would you think if your country’s leader was photographed with a joint in his/her mouth?",
        "Why do you think marijuana has such a bad image with governments?",
        "If marijuana was legalized in a city 300 kilometres from where you live, would you move?",
        "There are millions of alcohol related deaths and cases of violence but unbelievably few marijuana related cases. Why is alcohol legal?",
        "People say marijuana isn’t addictive. What do you think?",
        "Is the argument that marijuana leads people to harder drugs a valid reason to ban it?",
        "How would you feel if your daughter introduced you to her new boyfriend and he offered you a joint?",
        "How many people do you know who use marijuana?",
        "Would you vote to legalize marijuana or keep it banned?",
        "Do you think marijuana will be legal one day?",
        "If Starbucks sold ready-made joints, would you go there?"
    ],
    "Marketing": [
        "What images spring to mind when you hear the word ‘marketing’?",
        "Would you like to work in marketing?",
        "What marketing tactics do you think are very successful?",
        "What do you think of things like Christmas being marketed?",
        "What do marketing executives do in their jobs?",
        "How has the Internet changed marketing?",
        "Is there too much hype in marketing?",
        "What do you think of McDonalds’ marketing techniques aimed at attracting children?",
        "How would you start marketing a product or idea you had?",
        "What is your opinion of marketing in the era of globalization?",
        "What is marketing?",
        "What’s the best marketing campaign you know of?",
        "What’s the difference between marketing and advertising?",
        "Do you think that McDonald's is a marketing machine for the entertainment industry that is disguised as a restaurant?",
        "Are marketing executives good at selling us exactly what we don’t really need?",
        "What do you think of the marketing strategies used in sports?",
        "Do expensive brands use different types of marketing to cheaper products?",
        "How do marketing techniques differ from country to country?",
        "How much of marketing is lying?",
        "Why are cigarette companies still so successful in their marketing?"
    ],
    "Marriage": [
        "Is marriage over-rated?",
        "What do you think about gay marriage?",
        "What do you think of the concept of no sex before marriage?",
        "What is the secret to a happy marriage?",
        "Why are fewer and fewer people getting married?",
        "Who has the happiest marriage you know? Why do you think this?",
        "How do you think marriage changes people?",
        "Do you believe in arranged marriages?",
        "Should people stay married if they no longer love each other?",
        "Do you think people should agree on a marriage contract before they get married?",
        "What springs to mind when you hear the word ‘marriage’?",
        "Is marriage different today than it was a hundred years ago?",
        "Are there any rules to marriage?",
        "What would the world be like if there was no marriage?",
        "What is important in a marriage?",
        "Is your idea of marriage different now compared to when you were a child?",
        "Is it OK to live together before marriage?",
        "What do you think of bigamy and polygamy?",
        "Do you think there is anything scary about marriage?",
        "Why do so many marriages go wrong?"
    ],
    "Mars": [
        "What do you know about Mars?",
        "Do you think there was/is life on Mars?",
        "Martians are from Mars; do you know what life forms on other planets might be called?",
        "Are you interested in the secrets Mars holds?",
        "Would you like to go to Mars one day?",
        "Why are scientists so interested in Mars?",
        "Do you think it’s possible that one day, many people will live on Mars?",
        "What do you think of the idea often described by scientists that life started on Mars and moved to Earth, which means we are Martians?",
        "What would you like to know about Mars?",
        "Why is Mars red?",
        "What springs to mind when you hear the word ‘Mars’?",
        "Are men really from Mars and women from Venus?",
        "What time of the year do you think would be the best time to visit for a holiday (and why)?",
        "Would you rather live on the Moon or Mars?",
        "What references to Mars do you know of in your country’s popular culture (movies, novels, songs, cartoons…)?",
        "What are the similarities and differences between the Mars chocolate bar and the planet Mars?",
        "What do you think the good and bad things about living on Mars might be?",
        "What name would you give to the first city on Mars?",
        "What do you think you would write on a postcard from Mars?",
        "How would you feel if you read this headline: “Ancient human fossils found on Mars”?"
    ],
    "Mathematics": [
        "What springs to mind when you hear the word ‘mathematics’?",
        "Do you like ‘maths’ – the British English pronunciation and spelling, or ‘math’ the American versions?",
        "Were you good at maths at school?",
        "Did you like maths at school?",
        "Are you good at mental arithmetic now?",
        "What is maths useful for nowadays if we have computers and calculators?",
        "Would you like to study maths again?",
        "Why is maths so important at schools?",
        "Are people who are really good at maths very interesting?",
        "Did you have a favourite or a hated maths teacher?",
        "Are all intelligent people good at maths?",
        "How often do you use maths of some kind in a normal day?",
        "Can you remember what your first real kiss was like?",
        "Do you know your times tables up to 12 times 12?",
        "Are girls or boys better at maths?",
        "How many different branches of mathematics do you know of?",
        "What do you know about the history of maths?",
        "What is the philosophy of mathematics?",
        "What’s most confusing to you: algebra, statistics, probability or chaos theory?",
        "Are there times when two plus two equals five?"
    ],
    "May": [
        "What springs to mind when you hear the word ‘May'?",
        "What do you think of the month of May?",
        "What good things happen in May?",
        "What things do you usually do in May?",
        "What do you think of the word 'May'?",
        "What are people who are born in May like?",
        "What do you think of May weather?",
        "Where is May on the list of 'the best months'?",
        "Are there any bad things about the month of May?",
        "What plans do you have for next May?",
        "If you made a May festival, what would you it be like?",
        "Is there any delicious food you eat in May?",
        "How should people celebrate in May?",
        "What famous holidays are there in May?",
        "How do you feel when May arrives?",
        "If you made a video about May, what would you put in it?",
        "How do you feel when May is over?",
        "What three adjectives best describe May, and why?",
        "What good thing can you remember happening in May?",
        "What is a good symbol for May, and why?"
    ],
    "Meals": [
        "Do you always have three meals a day?",
        "What’s your favourite meal of the day?",
        "Do you prefer meals alone, with one other person or lots of people?",
        "What do you think of the meal times in different countries that are different from your meal times?",
        "Do you ever skip meals?",
        "Do you think it’s OK to eat between meals?",
        "Do you cook your own meals?",
        "Do you think McDonald’s meals are Happy or Unhappy?",
        "Do you always wash your hands and pray before meals?",
        "What do you think of airplane meals?",
        "What’s your favourite meal?",
        "Do you always eat healthy, balanced meals?",
        "Are home-cooked meals the best?",
        "Would you like to have a three-course meal every day?",
        "Is the evening meal the most important meal of the day?",
        "What’s the most delicious meal you can remember eating?",
        "What do you think of frozen meals, microwave meals and other pre-packed meals?",
        "What’s the best thing to do after a lovely meal?",
        "How does meal time now differ from when you were a kid?",
        "What’s the worst possible meal you could imagine?"
    ],
    "Meat": [
        "What images spring to mind when you hear the word ‘meat’?",
        "Do humans need to eat meat?",
        "Is meat healthy or unhealthy?",
        "What’s the strangest meat you’ve eaten?",
        "Do you like raw meat?",
        "Do you think meat eaters are healthier than those who don’t eat meat?",
        "What are the differences between red and white meat?",
        "Raising animals on farms for meat damages the environment. Should people reduce the amount of meat they eat?",
        "What do vegetarians have against eating meat?",
        "Grilled, barbecued, roasted… what’s the best way of cooking meat?",
        "Is meat murder?",
        "How would the world be different if everyone was vegetarian?",
        "What are the differences between meat and fish?",
        "What do you think North and South Korea will be like 50 years from now?",
        "How do different religions view meat?",
        "Some people say eating meat makes people more violent. What do you think of this?",
        "Do babies need meat?",
        "What do you think about eating meat from cloned animals?",
        "Do you think humans are designed to eat meat?",
        "Would you eat meat even if you had to kill the animal yourself?"
    ],
    "Media": [
        "What images spring to mind when you hear the word ‘media’?",
        "What is the media?",
        "Do you think the media have too much power?",
        "What are the good and bad things about the media in your country?",
        "Do you like the fact that today, media coverage of world events in instantaneous and extensive?",
        "What do you think about countries that ban or restrict the media?",
        "Do you always believe the media?",
        "Is the media of your country biased towards the views of your government over the war on terror?",
        "How is today’s media different from that of 30 years ago?",
        "Can you think of any examples of the media being irresponsible?",
        "Would you like to work for the media?",
        "What do you think of the mass media?",
        "What countries do you think have very good media and which have not so good media?",
        "Why do people fear the media?",
        "Should there be any censorship of the media?",
        "Are reporters in today’s media lazy?",
        "Do you think the media tries to manipulate people or change their views?",
        "Is it a good idea for a country’s media to be controlled by the government?",
        "Do you trust the media?",
        "Does the media care more about truth or profits?"
    ],
    "Medicine": [
        "What comes to mind when you hear the word ‘medicine’?",
        "Do you hate taking medicine?",
        "How often do you take medicine?",
        "Should all medicine be free?",
        "Is laughter the best medicine?",
        "Does medicine always work for you?",
        "Do you have any side effects after you take medicine?",
        "What do you think of alternative medicines like homeopathic medicine and aromatherapy?",
        "What medicines are in your medicine cabinet?",
        "Do you think medicine weakens your body’s immune system?",
        "What do you think of herbal and Chinese medicine?",
        "Do you think medicine is too expensive?",
        "Would you ever buy medicine online?",
        "Do you agree with testing on animals to find new medicines?",
        "Do you think that one day, there’ll be medicine to cure all illnesses?",
        "How has medicine changed in the past hundred years?",
        "Do you think medicines are tested enough before they are put on the market?",
        "Have you ever given someone a taste of their own medicine?",
        "How different would the world be without medicine?",
        "What do you think the next revolution in medicine will be?"
    ],
    "Meditation": [
        "What comes to mind when you hear the word ‘meditation’?",
        "Have you ever tried to meditate?",
        "Would you like to go to meditation classes?",
        "Do you feel jealous of people who can find peace through meditation?",
        "Why or how do you think meditation works?",
        "Do you know anyone who meditates?",
        "What benefits do you think meditation brings?",
        "Do you think everyone should try and meditate for twenty minutes each day?",
        "Do you think Asian people are better at meditating than people from other continents?",
        "What do you think of people who meditate?",
        "What is meditation?",
        "Do you think meditation is a part of all religions?",
        "What do you think people think about during meditation?",
        "Do you think meditation helps you live longer?",
        "Do you think people need lessons to be able to meditate?",
        "Is meditation more for men or women?",
        "How is meditation different from other relaxation techniques?",
        "What’s the best time of the day and the best place to meditate?",
        "Do you think there are any dangers to meditation?",
        "How do you think meditation was first discovered?"
    ],
    "Men": [
        "What springs to mind when you hear the word ‘men’?",
        "Do men behave badly?",
        "Can men be beautiful?",
        "Are men really twice as intelligent as women?",
        "Why do men cheat?",
        "Are men more difficult than women?",
        "Are men better drivers than women?",
        "What kind of place would the world be without men?",
        "Is it OK for men to wear make-up?",
        "What’s the worst thing about men?",
        "Do real men cry?",
        "What are the differences between men and gentlemen?",
        "What are man best at and worst at?",
        "Why do men like gambling, drinking, smoking and chasing women?",
        "What three changes would you like to make to (other) men?",
        "Are men getting better or worse?",
        "Is it a man’s world?",
        "Why do men take control of the barbecue but not the kitchen oven?",
        "What is inside a man’s heart and brain?",
        "Will men be different 100 years from now?"
    ],
    "Mental Health": [
        "What comes to mind when you hear the term ‘mental health’?",
        "What do you think your mental health will be like in the future?",
        "What do you do to maintain or improve your mental health?",
        "Are you worried about the mental health of anyone you know?",
        "Is mental health more important than physical health?",
        "Are there many people with mental health problems in your country?",
        "What does your government do for people with mental health diseases and problems?",
        "How can society help people with mental health problems or stop people from developing them?",
        "Do you think modern society increases the likelihood of mental health problems?",
        "What advice would you give to someone with mental health issues?",
        "How is your mental health?",
        "Has your mental health changed over the years?",
        "What affects your mental health on a daily basis?",
        "Are you worried about your mental health?",
        "How does one’s mental health deteriorate?",
        "What is the relationship between sleep and mental health?",
        "What mental health disorders and problems do you know of?",
        "One of the most common mental health problems is depression. How can we help people who suffer from this?",
        "If someone has a mental health disorder, should they be kept in a special mental health institution?",
        "Are murderers with mental health problems really murderers?"
    ],
    "Mexico": [
        "What images spring to mind when you hear the word Mexico?",
        "What are the good things and bad things about Mexico?",
        "What is Mexico famous for?",
        "What do you know about Mexican history?",
        "What images of Mexico do you have that are beautiful and adventurous?",
        "What do you think about Mexico’s different peoples?",
        "What has Mexico given to the world?",
        "Would you like to visit Mexico, or live there?",
        "What do you know about the geography of Mexico?",
        "Who are the most famous Mexican people you know?",
        "How different is Mexico from other Latin American countries?",
        "What do you know about Mexican food?",
        "How much importance or power does Mexico have in the world?",
        "What do you think Mexico will be like 50 years from now?",
        "Does your country have good relations with Mexico?",
        "What do you think about Mexico sights?",
        "What is your idea of a typical Mexican person?",
        "What things about Mexico do you think Mexican people are proud of?",
        "What do you know about Mexican politics?",
        "What would you like to ask a Mexican person about Mexico?"
    ],
    "Michael Jackson": [
        "What springs to mind when you hear the name ‘Michael Jackson’?",
        "What do you think of Michael Jackson?",
        "Would you like to have met Michael Jackson?",
        "What advice would you give to Michael Jackson’s three children?",
        "Do you think Michael Jackson was an inspiration?",
        "What do you think is Michael Jackson’s legacy?",
        "Do you think Michael Jackson is one of the greatest performers ever?",
        "Why do you think millions of people loved Michael Jackson?",
        "Do you think Michael Jackson had a good life?",
        "What do you know about Michael Jackson’s early days?",
        "What’s your favourite Michael Jackson song?",
        "Where were you and what were you doing when you heard the news of Michael Jackson’s death?",
        "What do you think of Michael Jackson’s music?",
        "Do you think you grew up with Michael Jackson?",
        "What do you think of Michael Jackson’s personality?",
        "Would you like to have helped Michael Jackson?",
        "What adjectives would you use to describe Michael Jackson?",
        "What other stars are there in entertainment history like Michael?",
        "What questions would you like to have asked Michael Jackson?",
        "What do you think his answers would have been?"
    ],
    "Microsoft": [
        "What springs to mind when you hear the word ‘Microsoft’?",
        "Do you think Microsoft is a good company?",
        "Do you think Hotmail accounts are better than other e-mail services?",
        "Do you use Messenger? What do you think of it?",
        "Do you think Microsoft is a monopoly and has too much power?",
        "Do you think Microsoft’s products are the best of their type?",
        "What do you think of Microsoft Office?",
        "What do you know or think about Microsoft competitors, such as Apple Computers and Linux?",
        "Do you think Microsoft will always be the top software company?",
        "Do you think Microsoft would be a good company to work for?",
        "What does Microsoft do?",
        "What would the world be like without Microsoft?",
        "Are you happy with the Microsoft products you have?",
        "What is the best thing Microsoft has produced?",
        "What do you think Bill Gates does every day at Microsoft?",
        "What do you know about the history of Microsoft?",
        "Is the Vista OS better than the ones that came before it?",
        "If Microsoft has so many problems, why is it on 95% of the world’s computers?",
        "Which company do you like better, Microsoft or Google?",
        "What questions would you like to ask Bill Gates?"
    ],
    "Middle East": [
        "What comes to mind when you hear the term ‘Middle East’?",
        "What do you know about the Middle East?",
        "Why is the Middle East in the news so often?",
        "Are you interested in reading about the Middle East or watching news on it?",
        "What do you know about conflicts in the Middle East?",
        "When do you think peace and security will arrive in the Middle East?",
        "Who understands the Middle East more – the USA or Europe?",
        "What wonderful things are there about the Middle East?",
        "What countries are part of the Middle East and how are they all different?",
        "Who are the heroes in the Middle East?",
        "How does the Middle East shape world events?",
        "What is your solution to the problems in the Middle East?",
        "What will the Middle East be like 20 years from now?",
        "What does the Middle East have to offer the rest of the world?",
        "What do you know about the Arab-Israeli conflict?",
        "Would you like to live in the Middle East?",
        "Which country in the Middle East would you most like to visit and why?",
        "What do you think people from the Middle East are most proud of about their region?",
        "What do you know about the geography of the Middle East?",
        "What adjectives would you use to describe the Middle East?"
    ],
    "Milk": [
        "What comes to mind when you hear the word ‘milk’?",
        "What do you think of milk?",
        "What would the world be like without milk?",
        "How useful and versatile is milk?",
        "Do you think milk is good value for money?",
        "What do you think of soya milk and coconut milk?",
        "Why is milk so good for your health?",
        "Is cow’s milk best, or do you think goat’s or camel’s milk is better?",
        "How often do you drink milk?",
        "What’s your favourite milk shake and why?",
        "What do you know about milk?",
        "Do you prefer no-fat, low-fat, regular or full-fat milk?",
        "How did people first find out that we could drink cow’s milk?",
        "Would you like to try elephant’s milk or tiger’s milk?",
        "Is taking a bath in milk good for you? Would you like to try?",
        "Why don’t all mothers feed their babies on breast milk? Isn’t it much better for the baby than milk powder / formula?",
        "What do you think of putting milk powder in tea and coffee?",
        "Have you ever had any bad experiences with sour milk?",
        "Do you prefer milk chocolate or dark chocolate?",
        "Hot milk or cold milk – which is best, and why?"
    ],
    "Mining": [
        "What images spring to mind when you hear the word ‘mining’?",
        "Why is mining important?",
        "What do you know about the history of mining?",
        "Is there much mining in your country?",
        "Do you think mining damages the environment?",
        "How long can mining continue before the Earth is destroyed?",
        "Would you like to work in mining?",
        "Do you think miners are paid well?",
        "Why is mining considered to be one of the most stressful jobs?",
        "Do you think we’ll start mining the Moon and Mars one day?",
        "What do you know about mining?",
        "Why are there so many mining accidents in China and Russia?",
        "Do you think mining can ever be environmentally friendly?",
        "Do you think mining companies should be allowed to make billions of dollars from the Earth’s natural resources?",
        "What different types of mining do you know about?",
        "What kinds of headlines and stories might be in a newspaper called “Mining News”?",
        "Would you like to be a miner for a day and see what mining is like?",
        "What dangers are there in mining?",
        "If the decision was yours, would you ban mining around the world?",
        "What questions would you like to ask a mining executive?"
    ],
    "Mobile Telephones": [
        "What comes to mind when you hear the words ‘mobile telephone’?",
        "What was life like before mobile telephones came along?",
        "What would your life be like without your mobile telephone?",
        "Can you remember your first mobile telephone?",
        "Are you happy with the mobile telephone you have now? Why (not)?",
        "What are your favourite functions on mobile telephones?",
        "What new functions would you like to see on mobile telephones?",
        "Do you think mobile telephones are dangerous in any way?",
        "What is the ring tone on your mobile telephone and why did you choose it?",
        "Are other people’s mobile telephones annoying?",
        "How often do you use your mobile?",
        "Do you ever worry about other people listening to your mobile telephone conversations when you are in public?",
        "What interesting conversations have you heard on mobile telephones?",
        "What’s the best brand of mobile phone?",
        "What do you think of the Apple iPhone?",
        "What do you think of people who use their mobile telephone while driving?",
        "What would you do if your date spent more time on his/her mobile telephone than he/she spent talking to you?",
        "Do young people use mobile telephones too much?",
        "Do you think schools should ban mobile phones?",
        "From what age do you think children should have a mobile phone?"
    ],
    "Models": [
        "What comes to mind when you hear the word ‘models’?",
        "What do you think of models and modeling?",
        "Would you like to be a model?",
        "What do you think a model’s life is like?",
        "Are models good role models to other men and women?",
        "Do you think female models need to be so thin?",
        "Do you think you’d be a good model?",
        "Why do models walk down the catwalk in such an abnormal way?",
        "Do you think models get paid too much?",
        "Why are most of the world’s highest paid models white?",
        "Do you have a favourite supermodel?",
        "Would you encourage your child if he/she wanted to be a model?",
        "Is it wrong for children to be models?",
        "Do you think nude models should be paid more than fashion models?",
        "What are the bad things about modeling?",
        "Do men need to be muscular to succeed in modeling or can they be short with a big tummy?",
        "Would the clothes that models wear look good on you?",
        "What do you think supermodels talk to each other about on their lunch break?",
        "Is nude modeling art or pornography?",
        "What questions would you like to ask a top model?"
    ],
    "Monarchy": [
        "What comes to mind when you hear the word ‘monarchy’?",
        "What do you think of the idea of monarchy?",
        "What monarchies do you know of around the world?",
        "Are monarchies good or bad for a country?",
        "Why do many countries still maintain their monarchies?",
        "Do members of a monarchy need to work hard for their country?",
        "Is it unfair that people are born into a monarchy and automatically lead a privileged life, never having to lift a finger?",
        "What differences are there in society of the world’s monarchies?",
        "Which of the world’s monarchies do you think is best?",
        "Would you prefer your country to be a monarchy or republic?",
        "How did monarchies start?",
        "Why do people in some monarchies respect their monarchs so much?",
        "Would you like to be a monarch?",
        "What do you think the average king, queen, emperor, empress, sheikh, sheikha, sultan, sultana does in an average day?",
        "Do you think monarchs should have the power to change governments and constitutions?",
        "What do you think monarchs think about their people?",
        "What would a monarch do if one day their monarchy ended and their money was taken away?",
        "What would you do if you were monarch for a day?",
        "Who is the best monarch ever – living or dead?",
        "What questions would you like to ask a monarch?"
    ],
    "Money": [
        "What comes into your head when you hear the word \"money\"?",
        "How important is money?",
        "How attractive are people with lots of money?",
        "What would life be like without money?",
        "How often do you think about money?",
        "What does the expression, \"money doesn't grow on trees\" mean? What would life be like if money grew on trees?",
        "Who and why might someone ask, \"Do you think I’m made of money?\" Have you ever asked this?",
        "How would the world be different if all the money was shared out equally among all people?",
        "What's the best way of making a lot of money?",
        "Have you ever raised money for charity?",
        "How important is money to you?",
        "Is money really the root of all evil?",
        "Can money buy happiness?",
        "How often do you worry about money?",
        "What’s the largest amount of money you've ever had in your wallet/purse?",
        "Does having a lot of money make someone more attractive?",
        "Have you ever lost a lot of money?",
        "How much pocket money should a 13-year-old get?",
        "Do you ever run out of money?",
        "Do you agree with the idiom that, \"a fool and his money are easily parted\"?"
    ],
    "Moon": [
        "What images spring to mind when you hear the word ‘moon’?",
        "What do you know about the Moon?",
        "Is the Moon important in your culture?",
        "Do you like looking at the Moon?",
        "What do you think about when you look at the Moon?",
        "Would you like to visit the Moon?",
        "Do you think there’ll be cities on the Moon in the future with McDonalds and Starbucks?",
        "What would happen to the Earth if the Moon disappeared?",
        "What are the different phases of the Moon?",
        "What would you do if you spent a day on the Moon?",
        "Is our Moon better than other moons?",
        "Do you think countries will fight each other day for territory on the Moon?",
        "Why do some cultures say the Moon is made of cheese?",
        "Why is it important to study the Moon?",
        "Why can you sometimes see the Moon during the day?",
        "What do you like doing by moonlight?",
        "Why do you think people say the Moon landing didn’t really happen, that it was just a hoax?",
        "Someone once said, “Moonlight is sculpture; Sunlight is painting.” What do you think?",
        "Do you think you’ll ever go to the Moon?",
        "What movies have you seen about the Moon?"
    ],
    "Morning": [
        "What is your usual morning routine?",
        "What were mornings like in your house when you were a kid?",
        "How are weekend mornings different from weekday mornings?",
        "Would you prefer the morning shift or evening shift?",
        "Do animals prefer mornings?",
        "Which is worse, the morning or evening rush hour?",
        "Do you ever say, “It’s been a bad morning”?",
        "Is morning the best time to study and get things done?",
        "What happens in your town early in the morning? How does it wake up?",
        "What do you do early morning, mid morning and late morning?",
        "What springs to mind when you hear the word ‘morning’?",
        "Are you a morning person?",
        "What do you like doing in the morning?",
        "Are you grumpy in the morning?",
        "Do you like watching morning TV shows or listening to morning radio shows?",
        "If you have morning sickness do you think you should take a morning after pill?",
        "How do people usually feel ‘the morning after the night before’?",
        "Do you always mean it when you say ‘Good morning’?",
        "When does morning start and end?",
        "What things about morning would you like to change?"
    ],
    "Morocco": [
        "What images spring to mind when you hear the country Morocco?",
        "What are the good things and bad things about Morocco?",
        "What is Morocco famous for?",
        "What do you know about Moroccan history?",
        "What images of Morocco do you have that are beautiful and adventurous?",
        "What do you think about Morocco’s culture and peoples?",
        "What has Morocco given to the world?",
        "Would you like to visit Morocco, or live there?",
        "What do you know about the geography of Morocco?",
        "Who are the most famous Moroccan people you know?",
        "How different is Morocco from other Arab or African countries?",
        "What do you know about Moroccan food?",
        "What is Morocco usually in the news for?",
        "What do you think Morocco will be like 50 years from now?",
        "Does your country have good relations with Morocco?",
        "What do you think about Morocco’s sights?",
        "What is your idea of a typical Moroccan person?",
        "What things about Morocco do you think Moroccan people are proud of?",
        "What would you like to do during a two-week holiday in Morocco?",
        "What would you like to ask a Moroccan person about Morocco?"
    ],
    "Mosquitoes": [
        "What comes to mind when you hear the word ‘mosquito’?",
        "What do you think of mosquitoes?",
        "A brown bat eats 1200 mosquitoes an hour. Do you think having a brown bat as a pet would be a good idea?",
        "Why are mosquitoes dangerous?",
        "What purpose do mosquitoes serve?",
        "Where do mosquitoes go during the day and what do they do?",
        "What are more annoying, mosquitoes or flies?",
        "What do you do when a mosquito buzzes around you in bed?",
        "What adjectives would you use to describe mosquitoes?",
        "Can you stop yourself from scratching a mosquito bite?",
        "What do you think of mosquitoes?",
        "How would the world be different without mosquitoes?",
        "Is there anything useful about mosquitoes?",
        "What’s the best way of killing mosquitoes?",
        "What do you do when you get a mosquito bite?",
        "Do you ever look at a mosquito sucking your blood or do you swipe it instantly?",
        "Do you think mosquitoes prefer men or women?",
        "How can you protect yourself against mosquitoes?",
        "What would life be like if mosquitoes were as big as birds?",
        "What do you think of people who study mosquitoes for a living?"
    ],
    "Mothers": [
        "What images spring to mind when you hear the word ‘mother’?",
        "Can you describe your mother in one word? Why that word?",
        "Have you ever thought that mothers might have ESP?",
        "Do you always buy your mother a present on Mother’s Day?",
        "What are the differences between a mother and a mother-in-law?",
        "In what ways do you take after your mother?",
        "What is your mother’s biggest fault?",
        "Is your mother more like a mother or a best friend?",
        "What do/did your mother and you argue about?",
        "What do you think of Mother’s Day? Is it necessary?",
        "What are the biggest differences between mothers and fathers?",
        "Why and how did your father fall in love with your mother?",
        "Are you happy with the way your mother raised you?",
        "Should mothers stay at home and look after the kids?",
        "What’s the best piece of advice your mother has given you?",
        "Do you think mothers are the same all around the world?",
        "How are mothers and grandmothers different?",
        "What do you think is the hardest thing about being a mother?",
        "What’s the biggest lie you’ve ever told your mother?",
        "What do you talk to your mother about on the phone?"
    ],
    "Motorcycles": [
        "What images spring to mind when you hear the word ‘motorcycle’?",
        "What are the good things and bad things about motorcycles?",
        "Do you like motorcycles?",
        "In what ways are motorcycles better than cars?",
        "Would cities and towns be better places if you could only ride motorcycles in them?",
        "Do you think all motorcycle gangs are dangerous?",
        "What do you think of Harley Davidson motorcycles?",
        "Would you prefer a motorcycle or a horse?",
        "Would you like to go touring on a motorcycle holiday?",
        "What’s more exciting, Formula 1 or motorcycle racing?",
        "Would you worry if your children got a motorbike?",
        "What do you know about Kenyan cultures?",
        "What’s the big attraction of motorcycles for young people?",
        "Do you need leathers to ride a motorcycle?",
        "At what age do you think it’s OK to start riding a motorcycle?",
        "Do you think big, powerful motorbikes are glamorous?",
        "What are the best motorcycles to buy?",
        "What movies have you seen that have lots of motorcycles?",
        "Would you prefer to ride a motorcycle or be a passenger?",
        "What’s the biggest cause of motorcycle accidents?"
    ],
    "Mountains": [
        "What images spring to mind when you hear the word ‘mountain’?",
        "Do you like mountains?",
        "How often do you go to the mountains?",
        "What kind of mountains do you like?",
        "Do you like holidays in the mountains?",
        "Are there any beautiful mountains in your country?",
        "Are mountains important?",
        "Do you prefer the mountains or the beach?",
        "Do you like mountain climbing?",
        "Which mountain would you really like to climb?",
        "Would you like to have a mountain named after you?",
        "Would you like to live in the mountains for a year?",
        "Do you ever feel in life that you have a real mountain to climb?",
        "What mountains look the most beautiful (e.g. snow capped, rocky, etc)?",
        "How would the world be different if there were no mountains?",
        "What things can you do on top of a mountain?",
        "Do you think climbing Mount Everest would change your life?",
        "Do you think you could survive better in the mountains or jungle?",
        "Have you ever made a mountain out of a mole hill?",
        "What do you think of mountain scenery?"
    ],
    "Movies": [
        "What do you think of when you hear the word ‘movie’?",
        "Would you like to work in the movie industry?",
        "Why are movies called movies?",
        "Which movie would you like to live in?",
        "What’s the best movie you’ve ever seen?",
        "Do you prefer watching movies at the cinema or on TV?",
        "Who is the biggest movie hero ever and the biggest ever bad guy?",
        "Which country makes the best movies?",
        "Who are your favourite movie stars (and why)?",
        "What’s the worst movie you’ve ever seen?",
        "Are movies good for us?",
        "Do you think movies make people more violent?",
        "What movie genre do you like best?",
        "Which actor would you want to play you in a movie about you? Why?",
        "Would you like a job as a movie critic?",
        "What things make a great movie a great movie?",
        "Tell me about the first time you went to the movie theater?",
        "If you could make a movie, what would it be about?",
        "Do you prefer to watch a good movie, a good documentary or a good game of sport?",
        "Who do you like watching movies with best?"
    ],
    "Multiculturalism": [
        "What springs to mind when you hear the word ‘multiculturalism’?",
        "What are the good things about multiculturalism?",
        "Is it possible for a country to avoid multiculturalism today?",
        "How would the world be different if there was no multiculturalism in any country?",
        "Do you think multiculturalism will eventually lead to a single world mixed race?",
        "Why are many people afraid of multiculturalism?",
        "Where in the world do you think multiculturalism works best?",
        "Do you think multiculturalism can ever be reversed?",
        "Do you think the original culture of a society that has become multicultural like the change?",
        "Is multiculturalism good for world peace and understanding?",
        "What is multiculturalism?",
        "What problems does multiculturalism bring to a country?",
        "Do you think elementary school children in multicultural classes give a lot of thought to multiculturalism?",
        "Would you prefer your country to be multicultural or of just one culture?",
        "Is multiculturalism something that only white societies think about?",
        "Can multiculturalism result in a country losing its identity?",
        "Is multiculturalism really another form of racism?",
        "In a multicultural society, should newcomers do what they can to assimilate into the culture of their new country?",
        "Is multiculturalism a dirty word?",
        "Is multiculturalism a threat to some countries / your country?"
    ],
    "Murder": [
        "Why do humans murder?",
        "Is the death penalty murder?",
        "Is it ever OK to kill someone?",
        "Is killing someone in self-defence murder?",
        "In your wildest rage, anger, jealousy, etc, are you capable of murder?",
        "Is abortion murder?",
        "What is the difference between assassination, murder and manslaughter?",
        "If you saw someone very close to you murder someone, would you turn them in to the police?",
        "What’s the difference between ‘kill’ someone and ‘murder’ someone?",
        "If a person kills their clone, is it murder or suicide?",
        "What springs to mind when you hear the word ‘murder’?",
        "Is killing animals for meat and fur murder?",
        "“It was murder on the roads getting home tonight.” Is the rush hour in your town also murder?",
        "In English, people say “I’ll murder him/her” when they are angry with someone. What do you think of this?",
        "What high profile murder has happened in your town?",
        "Do you think there’s too much murder on TV?",
        "If you saw a murder at close hand, how would you deal with the murderer?",
        "What would you do if you discovered your new partner, neighbour or flatmate had just been released from prison for mass murder?",
        "Is it murder to take someone’s life in a war?",
        "How would the world be different today if leaders such as Ghandi, Martin Luther King, JFK and Malcom X had not been murdered?"
    ],
    "Muscles": [
        "What springs to mind when you hear the word ‘muscles’?",
        "Are you happy with your muscles?",
        "Have you ever trained to increase the size of your muscles?",
        "Are muscular men/women more attractive than normal men/women?",
        "What do you think of bodybuilding?",
        "How would your life be different if you had a very muscular physique?",
        "Would you rather be very muscley but have little stamina, or be very lean with lots of stamina?",
        "Have you ever worried about the size of your muscles?",
        "When was the last time you had muscle pain?",
        "What muscle(s) would you really like to work on?",
        "What do you know about muscles?",
        "What’s the best way to get big muscles?",
        "What would life be like if your muscles started wasting away?",
        "Why do people think muscles are so attractive?",
        "What general, everyday exercises are good for building up your muscles?",
        "What can you eat to help make your muscles bigger?",
        "What happens to muscles when you stop working out and start getting old(ish)?",
        "Male models are usually muscular, whereas female models are usually thin and not that muscular. Why is this?",
        "Have you torn or damaged a muscle?",
        "How often do you get muscle cramp?"
    ],
    "Museums": [
        "What comes to mind when you hear the word ‘museum’?",
        "What’s the best museum you’ve ever been to?",
        "What do you like most and least about museums?",
        "Do you think museums should be free to enter?",
        "What is the first museum you can remember going to?",
        "Do you prefer going to museums alone or with others?",
        "What do you think is the best museum in the world?",
        "What kinds of museums are there in your town?",
        "Would a museum dedicated to your life and times be interesting?",
        "What exhibitions are on at the moment that you’d really like to see?",
        "Are all museums important?",
        "Do you think museums in other countries are more or less interesting than those in your own country?",
        "If you could have one exhibit from any museum in the world, what would it be, and why?",
        "Would you like to work in a museum?",
        "Would you become really intelligent if you spent a year wandering through museums?",
        "What’s the strangest museum you’ve heard of?",
        "Are all museums good for children?",
        "If you had lots of money to start your own museum, what would you exhibit in it and what would you call it?",
        "Which country has the best museums in the world?",
        "Do you prefer museums with interactive exhibits or those you just look at?"
    ],
    "Music": [
        "What images spring to mind when you hear the word ‘music’?",
        "What does music mean to you?",
        "What would life be like without music?",
        "Which is more important to you, music or TV?",
        "What kind of music do you like?",
        "How have your musical tastes changed since when you were a kid?",
        "What music can change the way you feel?",
        "What’s the best time and place to listen to music?",
        "Where does the best music come from, the USA, UK or other?",
        "What decade has produced the best music?",
        "How varied are your musical tastes?",
        "What artists/band do you want to see at a music festival?",
        "What musical genres do you really hate?",
        "Do you think most music (say 90%) is rubbish?",
        "Is the Internet helping or hindering musicians?",
        "Do you agree with Shakespeare that music is the food of love?",
        "What new music have you bought or listened to recently?",
        "What do you think of the music your parents listen to?",
        "Why do humans like music so much?",
        "What do you think of the music they play in supermarkets and elevators?"
    ],
    "Musical Instruments": [
        "What’s your favourite musical instrument?",
        "Have you ever learnt to play a musical instrument?",
        "What musical instrument do you not like the sound of?",
        "Do you think everyone should learn to play a musical instrument when they are at school?",
        "Why is it good to learn a musical instrument?",
        "What musical instrument will your children learn to play?",
        "What is the most unusual musical instrument you know of?",
        "If you were a musical instrument, what would you be and why?",
        "How would your life be different if you could play a musical instrument very well?",
        "What is the most useful musical instrument to know how to play?",
        "Have you ever been jealous of someone who can play a musical instrument really well?",
        "What musical instrument looks the most beautiful?",
        "Do you prefer electric musical instruments or acoustic?",
        "What musical instruments are unique to your country or culture?",
        "Do you think a record turntable is a musical instrument when it’s used in hip-hop?",
        "Can any object be a musical instrument if it’s used to make music?",
        "What musical instruments from other countries do you love the sound of?",
        "Do you think a synthesizer can reproduce the sounds of musical instruments?",
        "Do you think jazz musicians and classical musicians view their musical instruments differently?",
        "What musical instrument sounds best when played solo?"
    ],
    "Mysteries": [
        "What comes to mind when you hear the word ‘mystery’?",
        "What are the mysteries of the world?",
        "Is English ever a mystery to you?",
        "Do you like reading mysteries or watching mystery movies?",
        "What mystery would you really like to be solved?",
        "Are the people you know sometimes a mystery to you?",
        "Is mystery in our lives good?",
        "Would you be a good detective in solving mysteries?",
        "Is the opposite sex a mystery to you?",
        "Do you like TV shows that are about unsolved mysteries?",
        "What is the best mystery movie ever?",
        "How often do you solve a mystery?",
        "Are you mysterious?",
        "Why is life such a mystery?",
        "Do you think people in relationships should keep some mystery between them?",
        "What is the biggest mystery in the universe?",
        "What do you think of the mystery surrounding the Loch Ness Monster and the Yeti?",
        "Do you think love is an unsolved mystery?",
        "If you wrote a mystery book, what would you call it?",
        "Is it sometimes a mystery where you left your keys or where you saved that document to?"
    ]
}
