export default {
    "Language": [
        "What do you think about language?",
        "How do you think language first started?",
        "How much of a barrier do you think language is?",
        "How is our language different from animal language?",
        "Do you think that one day there will be just one language in the world? Would the world be a better place?",
        "Have you ever had a language exchange?",
        "Does language make the personalities of each nationality different?",
        "Do you think body language is universal?",
        "Would you like to learn sign language?",
        "What languages do you like or dislike the sound of?",
        "What are your feelings towards your own language?",
        "How would you compare your own language with English?",
        "How do you think the world would be different if there was only one language?",
        "What are the good and bad things about your language?",
        "Is there a lot of bad / foul language in your mother tongue?",
        "Why do you think there are so many different languages in the world?",
        "What do you think of languages that are dying? Do you think they should be preserved?",
        "What three languages would you really like to speak, and why?",
        "What is the most confusing language in the world?",
        "Do you think English should become an official language in your country?"
    ],
    "Latin America": [
        "How did Latin America get its name?",
        "What springs to mind when you hear the term ‘Latin America’?",
        "Do you think people from Latin America like the term ‘Latin America’?",
        "Why isn’t Latin America as rich and as advanced as North America?",
        "What do you think Latin America will be like 50 years from now?",
        "What has Latin America given to the world?",
        "What do people from Latin America have in common?",
        "How are the peoples of Latin America different to each other?",
        "What things about Latin America do you think Latin American people are proud of?",
        "What do you know about Latin American politics and political leaders?",
        "What are the differences between Latin America and North America?",
        "What are the good things and bad things about Latin America?",
        "Do you think there is a Latin American culture?",
        "What do you think the rest of the world thinks about Latin America?",
        "What images of Latin America do you have that are beautiful?",
        "What do you know about Latin America’s history?",
        "What has Latin America given to the world?",
        "Which Latin American country would you most like to live in?",
        "What do you know about the geography of Latin America?",
        "Who are the most famous Latin American people you know?"
    ],
    "Laughter": [
        "What definition would you give for laughter?",
        "Do you laugh a lot?",
        "How important is laughter?",
        "Is laughter infectious / catching?",
        "Do you often burst into laughter?",
        "When is laughter wrong or ill-advised?",
        "What do you think when you hear the sound of laughter?",
        "How does laughter happen?",
        "People can ‘roar’ or ‘howl’ with laughter, and ‘burst into’ or ‘break into’ laughter. What are the differences between these?",
        "How does laughter sound as we move from being a baby to our old age?",
        "Is laughter ‘the best medicine’?",
        "What do you know about laughter yoga and laughter clubs?",
        "Have you ever laughed at something you shouldn’t have – something very serious?",
        "Can you always contain your laughter?",
        "Do you ever have uncontrollable fits of laughter?",
        "What do you think of canned laughter on the television?",
        "Why do you think some people laugh more than others?",
        "What social functions does laughter have?",
        "Do men and women laugh about different things?",
        "What would you like to know about laughter?"
    ],
    "Law": [
        "What comes to mind when you hear the word ‘law’?",
        "Why do we have laws?",
        "What laws in your country do you hate?",
        "Are there any laws in your country that you think should be made tighter?",
        "Have you ever broken any laws?",
        "Do you think the laws in your country are similar to those in other countries?",
        "Do you think there are laws for the rich and different laws for the poor?",
        "Where, when and why do you think laws first started?",
        "What laws do you tend to ignore?",
        "What are gun laws like in your country?",
        "Do you think all laws are good?",
        "Would you like to be a lawmaker?",
        "What would your country be like if there were no laws?",
        "What’s the craziest law you know of?",
        "What do you think of the idea of international laws that would replace all national laws?",
        "What new laws would you like your country to introduce?",
        "Do you think laws are evenly applied to everyone in your society?",
        "What new laws do you think we’ll have fifty years from now?",
        "Have you ever been to see a lawyer?",
        "What law would you like to make for your English class?"
    ],
    "Leadership": [
        "What springs to mind when you hear the word ‘leadership’?",
        "Do people automatically have leadership or must they learn it?",
        "Why is good leadership important?",
        "What do you think of the leadership of your country?",
        "What is the most important thing a leader must remember about leadership?",
        "Have you ever been in positions of leadership?",
        "What leadership quality do you most value/admire?",
        "Who in the world do you think possesses the greatest leadership skills?",
        "Would you like to take a course in leadership?",
        "What do you think of the leadership of the US President and your country’s leader?",
        "What leadership qualities do you have?",
        "What leadership qualities do you want or need in the future?",
        "Are people who have leadership qualities more physically attractive than people with no leadership skills?",
        "Is there always stress with leadership?",
        "Does leadership exist in a romantic partnership?",
        "Is leadership an art or a science?",
        "Do you think people with no leadership skills have a more or les happy life?",
        "Does good leadership require bullying?",
        "What different kinds of leadership styles are there?",
        "How often are there leadership battles in your country? Do they interest you?"
    ],
    "Learning": [
        "What comes to mind when you hear the word ‘learning’?",
        "What do you know about learning?",
        "When do you think we first start learning?",
        "What kinds or methods of learning do you like best?",
        "Why are some people better at learning than others?",
        "Do you have any learning difficulties?",
        "What is the best learning experience you’ve had?",
        "How can you make sure learning is always fun?",
        "Do you think you’ll always be involved in lifelong learning?",
        "Do you think learning by doing or learning by listening is best?",
        "Are you good at learning new things?",
        "When you learn new things, is there always a steep learning curve?",
        "What’s the difference between teaching and learning? Does teaching always lead to learning?",
        "Does learning always make you motivated to do things?",
        "What tips on learning would you give to other people?",
        "Do you think we ever stop learning? Are we ever too old to start learning something new?",
        "What’s the unhappiest you’ve been while learning something?",
        "What good and bad experiences have you had learning English?",
        "Confucius said: ‘Thought without learning is perilous.’ Do you agree?",
        "Is learning something new ever a total waste of time?"
    ],
    "Leather": [
        "What comes to mind when you hear the word ‘leather’?",
        "What do you know about leather?",
        "Do you like leather products?",
        "The production of leather is bad for the environment. Why do you think this is?",
        "What kind of shoes would you buy if there were no more leather shoes?",
        "Would you ever wear a leather jacket and trousers?",
        "Why do you think leather is used for so many products?",
        "Do you think leather is always fashionable?",
        "What colour leather clothes do you think looks best?",
        "Do you like leather furniture?",
        "What’s the difference between leather and suede?",
        "Would you be happy to buy artificial leather products instead of real leather goods?",
        "Would you buy products that use other animal skins, like crocodile, snake, rabbit, etc?",
        "How important has leather been in technology in our history?",
        "What do you think of fashion companies like Louis Vuitton and Gucci using ostrich leather?",
        "Leather has a place in modern culture, e.g. cowboys, heavy metal music, etc. Does it play a role in your country’s culture?",
        "Some religions and cultures avoid leather. Do you know what they are and why they do so?",
        "Do you do anything to care for your leather goods?",
        "Would you like to take up leather-working as a hobby?",
        "What new uses do you think there are for leather?"
    ],
    "Lebanon": [
        "What images spring to mind when you hear the country Lebanon?",
        "What are the good things and bad things about Lebanon?",
        "What is Lebanon famous for?",
        "What do you know about Lebanese history?",
        "What images of Lebanon do you have that are beautiful or sad?",
        "What do you think about Lebanese people?",
        "What has Lebanon given to the world?",
        "Would you like to visit Lebanon, or live there?",
        "What do you know about the geography of Lebanon?",
        "Who are the most famous Lebanese people you know?",
        "How different is Lebanon from other Middle Eastern countries?",
        "What do you know about Lebanese food?",
        "Why isn’t Lebanon one of the richest countries in the Middle East?",
        "What do you think Lebanon will be like 50 years from now?",
        "Does your country have good relations with Lebanon?",
        "Do you think Lebanon will ever have peace and security?",
        "What do you know about the religious make up of Lebanon?",
        "What things about Lebanon do you think Lebanese people are proud of?",
        "What do you know about Lebanese politics?",
        "What would you like to ask a Lebanese person about Lebanon?"
    ],
    "Legs": [
        "Do you like your legs?",
        "Is two the best number of legs to have for a human?",
        "Do you need to stretch your legs (take a break and go for a walk)?",
        "How often, when and where do you cross your legs?",
        "Have you ever broken or injured a leg?",
        "Do you think legs are attractive?",
        "How would you describe your legs?",
        "Do you think men with hairy legs should shave them?",
        "What’s the best way to get shapely legs?",
        "What do you do when you get cramp in your legs?",
        "What springs to mind when you hear the word ‘legs’?",
        "Can you name all the different parts of the leg?",
        "Do you ever get wobbly legs or go weak at the knees?",
        "Which are more useful, legs or arms?",
        "Why are long legs considered attractive? Would you like longer legs?",
        "Do people ever pull your leg (play a trick or joke on you) or do you ever pull other people’s legs?",
        "Have your legs ever been very, very tired?",
        "What health and medical problems do you know of that affect only our legs?",
        "What different things can you do with your legs?",
        "What would you like to know about legs?"
    ],
    "Liberty": [
        "What springs to mind when you hear the word ‘liberty’?",
        "What is the difference between freedom and liberty?",
        "What do you value most – life, liberty or the pursuit of happiness?",
        "Do you feel you have a lack of liberty?",
        "Which world country do you think most values liberty?",
        "Which world country do you think least values liberty?",
        "What are civil liberties and how important are they to you?",
        "Would you fight or riot to protect your liberty?",
        "Is there religious liberty in your country?",
        "Have you been to countries where there is very little liberty for the people? What did you think?",
        "What does liberty mean in your country?",
        "What do you think of New York’s Statue of Liberty?",
        "How would you feel if your liberty was taken away?",
        "Do children have the same liberties as adults?",
        "What extra liberties would you like?",
        "Do people ever take liberties with you?",
        "How would you define liberty?",
        "What do you know about the Liberty Bell?",
        "Do you think you’ll enjoy more or fewer liberties in the future?",
        "What questions about liberty would you like answers to?"
    ],
    "Libraries": [
        "What comes to mind when you hear the word ‘library’?",
        "How often do you go to the library?",
        "Can you remember your earliest visits to libraries?",
        "Do you think libraries have changed over the years?",
        "Would you like to work in a library?",
        "Do you like the atmosphere of libraries?",
        "Are there enough libraries where you live?",
        "What’s the best library you’ve ever been to?",
        "What would happen if libraries suddenly disappeared?",
        "Would society be better if there were ten times more libraries?",
        "What do you think libraries will be like 50 years from now?",
        "Have you ever borrowed a book from a library and not returned it?",
        "How can your government encourage people to use libraries more often?",
        "How will the Internet change the function of libraries?",
        "What things about libraries don’t you like?",
        "Do you think people are using libraries more or less than they did 20 years ago?",
        "What do you think libraries need that they don’t have now?",
        "What is correct library etiquette? Do you always stick to it?",
        "What is your country’s national library like?",
        "Have you ever used a library full of English books?"
    ],
    "Libya": [
        "What images spring to mind when you hear the country Libya?",
        "What are the good things and bad things about Libya?",
        "What is Libya famous for?",
        "What do you know about Libya’s history?",
        "What do you think of Libya?",
        "What has Libya given to the world?",
        "What do you know about the economy of Libya?",
        "Who are the most famous Libya people you know?",
        "Would you like to visit Libya, or live there?",
        "What do you know about the geography of Libya?",
        "How different is Libya from other African and Arab countries?",
        "Do you think Libya is a positive force for world peace?",
        "What do you think Libya will be like 50 years from now?",
        "Does your country have good relations with Libya?",
        "What do you think about Libya’s leader Colonel Gadaffi?",
        "What is your idea of a typical Libyan person?",
        "What things about Libya do you think Libyan people are proud of?",
        "What do you know about Libyan politics?",
        "What would you like to ask a Libyan person about Libya?",
        "What do you know about Libya’s culture?"
    ],
    "Lies": [
        "Why do people lie?",
        "Is it OK to tell lies?",
        "How often do you lie?",
        "What’s the biggest lie you’ve ever told?",
        "Children who are good liars often grow up to be very intelligent. Were you a good liar when you were a child?",
        "Have you ever lied in a job interview?",
        "Have you told any lies today?",
        "Who lies more, men or women?",
        "Has a lie someone told you ever hurt you?",
        "What do you think of liars?",
        "People often say: “It’s easy to tell when politicians lie – they move their lips.” Do you agree with this?",
        "Do you think white lies are OK?",
        "Would you ever lie in a court of law?",
        "Do you think you could lie and beat a lie detection test?",
        "Someone once said there are ‘lies, damned lies and statistics.’ What do you think of this?",
        "How many lies are there in a pack of lies?",
        "What would you do if someone spread lies about you?",
        "Have you ever cheated on or lied to a partner?",
        "Do you feel guilty when you tell a lie?",
        "Have you ever been found out when telling a lie?"
    ],
    "Life": [
        "What comes to mind when you hear the word ‘life’?",
        "Do you enjoy life?",
        "What life-changing moments have you had in your life?",
        "Have you led an easy or difficult life?",
        "Do you think there’s life after death?",
        "Do you think there’s life on Mars (or on other planets)?",
        "Do you ever feel you have wasted your life?",
        "Would you like to live your same life all over again?",
        "What’s your love life like?",
        "Is life more similar to a pizza or a box of chocolates?",
        "What is the meaning of life?",
        "What’s your biggest goal in life?",
        "Is life complicated?",
        "What word would you use to sum up your life?",
        "Do you have a good quality of life?",
        "If life came with an instruction manual, what would it say?",
        "Who has been your biggest influence in life?",
        "What will life be like fifty years from now?",
        "What does life taste, smell, feel, look and sound like?",
        "If you could live someone else’s life, whose would it be and why?"
    ],
    "Listening Activities": [
        "What comes to mind when you hear the term ‘listening activities’?",
        "What do you think when your teacher says you’re going to do a listening activity?",
        "What kind of listening activities do you like best?",
        "Do you like the listening activities your teacher gives you?",
        "Do you have an example of how a listening activity improved your listening?",
        "Do you know of any listening websites that have good listening activities?",
        "Which is best – listening activities in the classroom or real-life listening?",
        "Do you always understand the reasons why the teacher asks you to do a particular listening activity?",
        "What are your biggest problems with listening?",
        "How important are listening activities compared with reading, speaking and writing activities?",
        "Do you like doing listening activities in class?",
        "Do you ever think listening activities are a waste of time?",
        "Do you prefer any particular accent when doing a listening activity?",
        "Is the topic important when you do a listening activity?",
        "What things are important for a listening activity to be successful?",
        "What advice would you give to a student who panics when he or she cannot follow a listening?",
        "How often should you listen to English podcasts, news, songs, etc?",
        "How long do you think listening activities should be?",
        "Do you think you need a listening activity in every class?",
        "What questions would you like to ask your teacher about listening activities?"
    ],
    "Literacy": [
        "What do you think about literacy?",
        "How are literacy rates in your country?",
        "Is literacy linked to one’s intelligence?",
        "How does literacy affect your life?",
        "Are you computer literate?",
        "How do high levels of literacy help a country?",
        "How do literacy levels in your country compare with other countries?",
        "What can governments do to improve literacy rates?",
        "What do you think ‘Family Literacy’ is?",
        "Elizabeth Hardwick said: “The greatest gift is a passion for reading.” Do you agree?",
        "What is literacy?",
        "How would your life be different if you were illiterate?",
        "Do you think there should be an International Literacy Day?",
        "How do illiterate people in your country get by?",
        "What would you do to improve your children’s literacy?",
        "What is the biggest barrier to literacy and how can we overcome it?",
        "What do you think the Internet has done to improve literacy around the world?",
        "A writer said that in the future, \"the new illiterate will be the person who has not learned how to learn.\" What do you think of this quote?",
        "How literate are you in English?",
        "What would the world be like if books and reading had never been invented?"
    ],
    "Literature": [
        "What comes to mind when you hear the word ‘literature’?",
        "What kind of literature do you read?",
        "Who is your favourite character from literature?",
        "Do you think today’s literature is up to the same standard of the literature from a hundred years ago?",
        "Have you read any books by winners of the Nobel Prize for Literature?",
        "Would you like to study English literature?",
        "Has the literature of your country influenced the world?",
        "Do you think songwriters should be eligible for the Nobel Prize for Literature?",
        "Would you like to study the history of world literature?",
        "Do you like classical literature?",
        "What do you think of modern literature?",
        "Did you enjoy studying literature at school?",
        "What image do you have of people who study literature at university?",
        "In 1857, Gustave Flaubert said: \"Read in order to live.\" What do you think of this?",
        "Do you like classical literature?",
        "What do you think of children’s literature?",
        "Are you proud of your country’s literature?",
        "Are you more interested in world literature or just the literature of your country?",
        "Do you think we’ll all be reading or listening to e-Books in the future?",
        "What different kinds of literature exist? Is literature only novels?"
    ],
    "London": [
        "What comes to mind when you hear the word ‘London’?",
        "Do you think London is the greatest city in the world?",
        "What are your favourite images of London?",
        "What do you know about life in London?",
        "What is your image of Londoners?",
        "Would you like to live in London?",
        "What things can tourists do in London?",
        "What do you think of the different London accents?",
        "Do you think the 2012 London Olympics will be good?",
        "Is London the best place to live in the UK?",
        "What do you know about the London Underground?",
        "Do you think London is a good place for shopping?",
        "How tolerant and cosmopolitan do you think London is?",
        "What do you think of London weather?",
        "Do you think London is a cheap or expensive city?",
        "Is London a dangerous place to visit?",
        "What do you know about the history of London?",
        "What do you think London will be like fifty years from now?",
        "Do you think London is a good place to eat?",
        "Did London Bridge really fall down?"
    ],
    "Love": [
        "What images spring to mind when you hear the word ‘love’?",
        "How important is love?",
        "Do you think it is possible to love everyone?",
        "How do people fall in love?",
        "How and why do people fall out of love?",
        "What is your favourite love song and why?",
        "How does love make you feel?",
        "Does love last forever?",
        "What does love look like?",
        "Has love changed over the past 10,000 years?",
        "What is love?",
        "What would your life be like without love?",
        "What does it feel like to say, “I love you”?",
        "Do you love to live or live to love?",
        "Are there any rules to love?",
        "What kind of love is the best love?",
        "Is there a thin line between love and hate?",
        "Do you love yourself? Should you do so?",
        "What is the difference between love and being in love?",
        "Is it more important to love or be loved?"
    ]
}
