export default {
    "Waiting": [
        "What comes to mind when you hear the word ‘waiting’?",
        "Do you like waiting for things?",
        "Is waiting good for us?",
        "What does waiting teach us?",
        "What's the most important thing you've waited for?",
        "What do you think of people who cannot wait?",
        "What do you do or think about while waiting at the dentist?",
        "What do we call people who cannot wait?",
        "Do you ever give up waiting for people who are late? How long can you wait?",
        "Paulo Coelho said: \"Life was always a matter of waiting for the right moment to act.\" How true is this?",
        "What do you think of people who cannot wait in line?",
        "What are you waiting for now?",
        "Where is a really bad place to wait?",
        "Are people who are waiting for things to happen wishing their life away?",
        "Are you waiting for answers?",
        "Do you like waiting in the rain?",
        "What do you do and think about when you wait for an airplane / aeroplane?",
        "Does your country often have to wait for rain?",
        "Is it easier to wait for things as we get older?",
        "Someone once said: \"All god things are worth waiting for.\" How true is this?"
    ],
    "Wales": [
        "What images spring to mind when you hear the country Wales?",
        "What are the good things and bad things about Wales?",
        "What is Wales most famous for?",
        "What do you know about Welsh history?",
        "What are the differences between Wales and your country?",
        "What do you think about Welsh people?",
        "What has Wales given to the world?",
        "Would you like to visit Wales, or live there?",
        "What do you know about the geography of Wales?",
        "Who are the most famous Welsh people you know?",
        "How different is Wales from the other the British countries?",
        "What was the last news story you heard about Wales?",
        "What do you think Wales’s neighbours think of it?",
        "What do you think Wales will be like 50 years from now?",
        "Does your country have good relations with Wales?",
        "What could you do on a holiday in Wales?",
        "What is your idea of a typical Welsh person?",
        "What things about Wales do you think Welsh people are proud of?",
        "What do you know about Wales culture?",
        "What would you like to ask a Welsh person about Wales?"
    ],
    "Walking": [
        "What comes to mind when you hear the word ‘walking’?",
        "Do you like walking around your town?",
        "Is walking very good for your health?",
        "How much walking do you do every day?",
        "What useful things could you do while you are walking?",
        "What do you think of your walking style?",
        "Do you prefer walking on the beach, in the mountains, in the desert or in the countryside?",
        "Would you like to go on a walking holiday?",
        "Raymond Inmon said: \"If you are seeking creative ideas, go out walking.  Angels whisper to a man when he goes for a walk.\" What does this quote mean? Do you agree?",
        "Carrie Latet wrote: \"Walking: the most ancient exercise and still the best modern exercise.\" Do you agree?",
        "What do you think of walking?",
        "Are you glad we walk on two legs instead of four?",
        "What’s the longest distance you’ve ever walked in a day?",
        "What do you think of tightrope walking?",
        "Do you like walking around barefoot?",
        "What should happen on International Walking Day?",
        "Who do you like to go for a walk with?",
        "How would your town change if the centre was walking only – no cars?",
        "Steven Wright said: \"Everywhere is walking distance if you have the time.\" What does this quote mean? Do you agree?",
        "St. Jerome said: \"To solve a problem, walk around.\" Do you agree?"
    ],
    "War": [
        "Why war?",
        "Does war ever do any good?",
        "Have you ever experienced a war?",
        "Do you think we'll ever stop starting wars?",
        "Why are some countries so eager to wage war, while others aren’t?",
        "What wars has your country fought in the recent past?",
        "Would you fight in a war to save your country?",
        "Would you like to work as a war correspondent?",
        "Aeschylus said: \"In war, truth is the first casualty.\" Do you agree with this?",
        "Someone once said: \"Join the Army, see the world, meet interesting people - and kill them.\" What do you think of this quote?",
        "What comes to mind when you hear the word ‘war’?",
        "What is a war dance and who does (used to do) them?",
        "What do you think of the system of charging people with war crimes?",
        "The Geneva Convention issued a list of the rules of war? What do you think these are? Does it seem strange to have rules for war?",
        "How do you think current wars could be stopped?",
        "What do you think future wars will be fought over?",
        "Do you think there’d be fewer wars if all countries were ruled by women?",
        "What would you do today if a war broke out in your country tomorrow?",
        "José Narosky said: \"In war, there are no unwounded soldiers.\" Do you agree with this?",
        "Bertrand Russell said: \"War does not determine who is right - only who is left.\" What do you think of this quote?"
    ],
    "War Crimes": [
        "What springs to mind when you hear the term ‘war crimes’?",
        "Do you think war is a crime?",
        "Do people in a war worry about war crimes?",
        "Do countries that chase war criminals also commit war crimes?",
        "What punishments should war criminals get?",
        "What is the worst war crime anyone / any country can commit?",
        "Who decides the rules about war crimes?",
        "What do you think of countries do not join the International Criminal Court and say its citizens cannot be tried for war crimes?",
        "Where are war crimes happening at the moment?",
        "Is the use of child soldiers a war crime?",
        "What are war crimes?",
        "Which countries do you think have committed the biggest war crimes?",
        "Is accidentally killing a civilian in a war zone a war crime?",
        "Has your country ever committed a war crime?",
        "What’s the difference between a war criminal and a terrorist?",
        "Who is the biggest war criminal in all of history?",
        "What’s the difference between a war crime and committing the same crime during peacetime?",
        "Is it only the winners who decide what war crimes are?",
        "Do you think war crimes will ever stop?",
        "Can war crimes be committed via the Internet?"
    ],
    "Water": [
        "What comes to mind when you hear the word ‘water’?",
        "What does water taste like?",
        "When do you like drinking water?",
        "Do you think water should be free?",
        "Do you buy mineral water or drink tap water?",
        "Do you drink enough water every day?",
        "Do you ever think about how precious water is?",
        "What three adjectives would you use to describe water?",
        "Isak Dinesen said: \"The cure for anything is salt water - sweat, tears, or the sea.\" What do you think of this quote?",
        "In 1732, Thomas Fuller said: \"We never know the worth of water till the well is dry.\" What do you think of this quote?",
        "Do you like water?",
        "Do you worry about the future availability of water?",
        "What do you think it would be like to have no fresh drinking water?",
        "What do you think of the fact that most of the world’s population is without clean water, yet rich countries spend billions on oil, brand goods, tourism, etc?",
        "What are the best and worst things about tap water and bottled water?",
        "How does water form?",
        "What different things can you do with water?",
        "What do you know about water?",
        "Henry David Thoreau said: \"I believe that water is the only drink for a wise man.\" What do you think of this quote?",
        "Jacques Cousteau said: \"Water and air, the two essential fluids on which all life depends, have become global garbage cans.\" What do you think of this quote?"
    ],
    "Wealth": [
        "What comes to mind when you hear the word ‘wealth’?",
        "How do you get wealth?",
        "Does wealth make people happy?",
        "Do you think it’s fair that so much of the world’s wealth is in the hands of so few people?",
        "What would you do if you had incredible wealth?",
        "Do you think it’s fair that individuals can amass great wealth by selling or exploiting their country’s natural resources?",
        "Do you think people should be forced to distribute their wealth to create a fairer society?",
        "Do you think the world’s wealthiest nations do enough to help the poorer nations?",
        "Henry David Thoreau said: \"Wealth is the ability to fully experience life.\" What do you think of this quote?",
        "Margaret Bonnano said: \"Being rich is having money; being wealthy is having time.\" What do you think of this quote?",
        "Are you wealthy?",
        "What would a wealthy person do if (s)he suddenly lost all his/her wealth?",
        "What are the best and worst things about being wealthy?",
        "Why would you like to be wealthy?",
        "Do you think your personality would change if you had great wealth?",
        "Is it better to pursue wealth or happiness?",
        "What questions would you like to ask a wealthy person?",
        "Are you jealous of people with great wealth?",
        "A. J. Reb Materi said: \"So many people spend their health gaining wealth, and then have to spend their wealth to regain their health.\" What do you think of this quote?",
        "Benjamin Franklin said: \"Early to bed, early to rise, makes a man healthy, wealthy and wise\" What do you think of this quote?"
    ],
    "Weapons": [
        "What images spring to mind when you hear the word ‘weapon’?",
        "Do you think everyone has the right to carry a weapon?",
        "Are there a lot of weapons in your country?",
        "Do you agree with the amount of money your government spends on weapons?",
        "What’s your opinion on countries with nuclear weapons and those who want weapons?",
        "Do you think terrorists will ever use nuclear, chemical or biological weapons?",
        "Would you ever carry or use a weapon?",
        "What do you think of the weapons trade?",
        "Seneca said: \"A sword is never a killer, it is a tool in the killer's hands.\" Do you agree?",
        "Joseph Stalin said: \"Ideas are more powerful than guns. We would not let our enemies have guns, why should we let them have ideas.\" What do you think of this quote?",
        "Do you think weapons are interesting?",
        "Do you think the world will ever be free from weapons of mass destruction?",
        "What are the laws in your country regarding deadly and lethal weapons?",
        "Would you like to work in the weapons industry?",
        "What do you think the personality of a weapons designer is like?",
        "What do you think the weapons of the future will be like?",
        "“The tongue is mightier than the sword;” Is free speech a weapon?",
        "What weapons can you buy in stores in your country?",
        "Albert Einstein said: \"I know not with what weapons World War III will be fought, but World War IV will be fought with sticks and stones.\" What does this quote mean? Do you agree?",
        "Hermione Gingold said: \"Fighting is essentially a masculine idea; a woman's weapon is her tongue.\" Do you agree?"
    ],
    "Weather": [
        "What comes to mind when you hear the word ‘weather’?",
        "What is your favourite weather?",
        "What do you think of today’s weather?",
        "Do you worry about the world’s changing weather?",
        "Why do different countries have different weather?",
        "Has the weather in your country changed over the past decades?",
        "Have you ever experienced extreme weather?",
        "Do you always try and look at or read the weather forecast?",
        "John Ruskin said: \"There is really no such thing as bad weather, only different kinds of good weather.\" What do you think of this quote?",
        "Anthony J. D'Angelo said: \"Wherever you go, no matter what the weather, always bring your own sunshine.\" What do you think of this quote?",
        "What are your favourite weather words?",
        "Do you understand all the symbols on the weather map?",
        "How does the weather change you feelings?",
        "When was the last time the weather destroyed one of your plans?",
        "Have you ever had to weather a storm?",
        "Would you like to work as a weather forecaster?",
        "What do you think the weather will be like in your country 100 years from now?",
        "What new weather would you like to invent?",
        "Kin Hubbard said: \"Don't knock the weather; nine-tenths of the people couldn't start a conversation if it didn't change once in a while.\" What do you think of this quote?",
        "Someone once said: \"If you don't like the weather, wait a minute.\" What do you think of this quote?"
    ],
    "Websites": [
        "What springs to mind when you hear the word ‘website’?",
        "Do you think websites are interesting?",
        "Can you remember the very first website you looked at?",
        "What’s your favourite website?",
        "What would websites would you recommend other students to learn English?",
        "Would you like to have your own website?",
        "What things really annoy you about websites?",
        "How many websites do you look at in an average day / week?",
        "How long do you spend looking at one website?",
        "Have you ever got angry with a website?",
        "What do you think makes a good website?",
        "Can you think of a website you use (and like) that needs to better designed?",
        "If you started your own website, what would you call it?",
        "Do you think there are websites that are dangerous?",
        "From what age do you think children should be allowed to look at websites?",
        "Do you think your government should be able to censor websites?",
        "What’s the most useful website for you?",
        "What do you think of websites that have pop-up music and ads?",
        "Do you think all websites should follow the same rules?",
        "What do you think websites will be like in the future?"
    ],
    "Weddings": [
        "What springs to mind when you hear the word ‘weddings’?",
        "Are weddings important?",
        "What kind of weddings do you think are best?",
        "Do you wish you could go to more weddings?",
        "Why do many people not like weddings?",
        "Do you think it’s easy or difficult to plan your own wedding?",
        "What’s the best and worst wedding you’ve ever been to?",
        "What are the best and worst things about weddings?",
        "Do you think weddings in other countries are better than those in your country?",
        "Do you think your wedding is the happiest day of your life?",
        "Do you like weddings?",
        "What kind of wedding would you like (have liked)?",
        "Which celebrity wedding would you really like to go to?",
        "What do you think of royal weddings?",
        "What do people getting married in your culture promise each other in a wedding?",
        "In your country, do people have to invite people they don’t like to their wedding?",
        "What is the best part of a wedding: the ceremony, the vows, or the reception?",
        "Do you think that one day, weddings will become a thing of the past?",
        "What do you think of alternative weddings such as underwater weddings or weddings on the wing of a flying airplane?",
        "What three adjectives would you use to describe weddings?"
    ],
    "Weekends": [
        "What comes to mind when you hear the word ‘weekends’?",
        "Are you happy with a two-day weekend or should it be three days?",
        "Weekends in some countries are Fridays and Saturdays, in other countries it’s Saturdays and Sundays. Which days are best?",
        "Why do we have weekends?",
        "What do you usually do on your weekends?",
        "What’s the most memorable weekend have you had in the past years?",
        "What would life be like without weekends?",
        "How do you feel the evening before the weekend starts?",
        "Novelist Chuck Palahniuk said: \"The only reason why we ask other people how their weekend was is so we can tell them about our own weekend.\" Do you agree?",
        "Bill Watterson said: \"Weekends don't count unless you spend them doing something completely pointless.\" Do you agree?",
        "Do you think we’re lucky to have weekends?",
        "How would the world change if weekends were three days long?",
        "What are you doing this weekend?",
        "How do you feel the evening the weekend is over?",
        "Do you believe in working on the weekends?",
        "Is there anything you dislike about weekends?",
        "Which are better – weekends now or weekends as a child?",
        "Do you do everything you want to do at the weekends?",
        "John Shirley said: \"Weekends are a bit like rainbows; they look good from a distance but disappear when you get up close to them.\" Do you agree?",
        "Loesje asked: \"Why wait for the weekend to have fun?\" Do you agree?"
    ],
    "Weight": [
        "What images spring to mind when you hear the word ‘weight’?",
        "Do you worry about your weight?",
        "Does your weight go up and down easily or is it usually stable?",
        "How often do you weigh yourself?",
        "What’s your ideal weight?",
        "Have you ever tried to lose or gain weight?",
        "What do you think overweight people think of people who are anorexic (and vice versa)?",
        "Should we learn about how to control our weight at school?",
        "Do you know what your birth weight was?",
        "An English proverb says: \"Don't dig your grave with your own knife and fork.\" What does this mean? Do you agree?",
        "Are you happy with your current weight?",
        "What’s the best way to lose or put on weight?",
        "Do you think people worry too much about their weight?",
        "Is your partner’s weight important to you?",
        "Why is almost everyone's new years resolution to lose weight?",
        "Are you worth your weight in gold?",
        "Do men or women worry more about their weight?",
        "What problems do overweight and underweight people have?",
        "Why do you think people are secretive about their weight?",
        "Someone once said: \"The best way to lose weight is to eat all you want of everything you don't like.\" Do you agree?"
    ],
    "Welfare": [
        "What is social welfare?",
        "How do you feel about people who get government welfare benefits?",
        "Should people have the right to free housing if they can’t afford it?",
        "How did welfare programs start?",
        "How do people abuse the welfare system in your country?",
        "Do you like your country’s welfare system?",
        "How would you change the welfare system in your country?",
        "What more can governments do to help homeless people?",
        "Should companies do more to help people stay off welfare?",
        "Should those on welfare do community work and learn new skills?",
        "Have you ever had to apply for welfare?",
        "Has a government failed if people are homeless or hungry?",
        "Which country has the best welfare system?",
        "Should wealthy people pay more taxes to help the poor?",
        "Should homelessness be made a crime against humanity?",
        "Who should be responsible to help the poor, charities or government?",
        "Why don't billionaires do more to help the poor?",
        "Would you pay more taxes if you knew the money was for social welfare programs?",
        "Does welfare encourage people not to work?",
        "Should there be time limits to getting welfare?"
    ],
    "Whales": [
        "What comes to mind when you hear the word ‘whale'?",
        "What are the arguments for and against whaling?",
        "What do you think of countries that kill whales?",
        "What do you think of people who eat whale meat?",
        "How endangered are whales and what can we do to help?",
        "What would it be like to swim with whales?",
        "How important whales to the food chain?",
        "What three adjectives would you use to describe whales?",
        "What does having a \"whale of a time\" mean?",
        "Have you read the story \" Moby Dick\"?",
        "What part do whales have to play in your culture?",
        "Do you worry about the future of whales?",
        "How dangerous are whales to humans?",
        "What do you know about killer whales?",
        "What movies about whales have you seen? Which one is best",
        "What would you do if you saw a whale when you were swimming?",
        "How would you protect whales?",
        "How is pollution killing whales?",
        "Do you or would you support Greenpeace?",
        "What do you think of the \"Save the whales\" campaign?"
    ],
    "Women": [
        "What comes to mind when you hear the word ‘women’?",
        "What are women best at?",
        "What is the most annoying thing about women?",
        "How would the world be different if all leaders were women?",
        "Who are the greatest women in your country’s history?",
        "What do women like and dislike about being women?",
        "Which country has the world’s most beautiful women?",
        "Do you think women should be allowed to fight in wars?",
        "Joseph Conrad said: \"Being a woman is a terribly difficult task, since it consists principally in dealing with men.\" What does this mean? Do you agree?",
        "Harriet Beecher Stowe said: \"Women are the real architects of society.\" Do you agree?",
        "Are women equal to men?",
        "Who’s the greatest woman you know?",
        "Why do women like fashion so much?",
        "Are photos of women in advertising demeaning to women?",
        "Are women from your culture luckier than women from other cultures?",
        "What common characteristics do all women share?",
        "Are women cleverer than men?",
        "How will women be different 100 years from now?",
        "Someone once said: \"Women get the last word in every argument. Anything a man says after that is the beginning of a new argument.\" Do you agree?",
        "Someone once said: \"God created man before woman. But then you always make a rough draft before the final masterpiece.\" What does this mean? Do you agree?"
    ],
    "Words": [
        "What comes to mind when you hear the word ‘words’?",
        "What are your favourite English words?",
        "Are you good with words?",
        "How often do you look in the dictionary for the meaning of a word?",
        "What words of wisdom do you have for students learning English?",
        "Parents tell their children, “Sticks and stones may break your bones but words can never hurt you.” Is this true?",
        "How would you describe yourself in three words?",
        "How many wpm can you type?",
        "Someone once said: \"Love is just a word until someone comes along and gives it meaning.\" Do you agree?",
        "James Earl Jones said: \"One of the hardest things in life is having words in your heart that you can't utter.\" What does this mean? Do you agree?",
        "What are your favourite words in your own language?",
        "Have words ever hurt you?",
        "Are there any bad words and swear words in your language you don’t like using?",
        "Have words ever failed you and you’ve been left speechless?",
        "How often is a word on the tip of your tongue?",
        "What do you do if you read something and don’t understand the words?",
        "What would you like your last words to be?",
        "Is it true that actions speak louder than words?",
        "Someone once said: \"One picture is worth ten thousand words.\" What does this mean? Do you agree?",
        "Harriet Beecher Stowe said: \"The bitterest tears shed over graves are for words left unsaid.\" What does this mean? Do you agree?"
    ],
    "Work": [
        "What images spring to mind when you hear the word ‘work’?",
        "Are you interested in working?",
        "Someone said work is for horses and idiots, do you agree?",
        "What would life be like if we did not have to work?",
        "Would you like to work in your own business?",
        "Would you like to work in another country?",
        "What are working conditions like in your country?",
        "What is the best job in your country?",
        "What do you want to do for work?",
        "What did your parents do for work?",
        "Why do we have to work?",
        "What is a workaholic?",
        "Would you like to work the night shift, day shift or afternoon shift?",
        "Do people work long hours in your country?",
        "Is work a  dirty word?",
        "Will you ever become a millionaire by working?",
        "Is housework really work?",
        "Is raising a family hard work?",
        "Is looking after a pet hard work?",
        "What is it like to be out of work?"
    ],
    "Wrinkles": [
        "What do you think when you hear the word \"wrinkles\"?",
        "Do you worry about wrinkles?",
        "Do you think wrinkles are good or bad?",
        "What causes wrinkles?",
        "Can we do anything to prevent wrinkles?",
        "Do some wrinkles make some people look better?",
        "How would very old people look without wrinkles?",
        "What do you think of anti-wrinkle creams? Do they work?",
        "Do men or women worry more about wrinkles?",
        "Will scientists invent something to totally prevent wrinkles one day?",
        "Which word is better – \"wrinkles\" or \"age lines\"?",
        "Do people worry too much about wrinkles?",
        "Do cosmetics companies lie about how their creams stop wrinkles?",
        "Would you consider botox or cosmetic surgery to remove wrinkles?",
        "What do you think of laughter lines and crow's feet?",
        "Some people say wrinkles add character to someone's face. True?",
        "The writer Mark Twain said wrinkles show where smiles have been. What do you think of this?",
        "Where on the face is it worst to have wrinkles?",
        "Are wrinkles worse for women or men? Why?",
        "What do you like and dislike about wrinkles?"
    ],
    "Writing": [
        "What springs to mind when you hear the word ‘writing’?",
        "Do you prefer writing or typing?",
        "How is your writing in English?",
        "Is writing in your language different from writing in English?",
        "What are your biggest problems with writing?",
        "How important is writing to you?",
        "Do/Did you enjoy your writing classes?",
        "When do you need to write in your everyday life?",
        "Novelist James Michener said: \"I'm not a very good writer, but I'm an excellent rewriter.\" Is this the same as you?",
        "Gene Fowler said: \"Writing is easy:  All you do is sit staring at a blank sheet of paper until drops of blood form on your forehead.\" What does he mean? Do you think writing is like this?",
        "Do you like writing?",
        "Do you worry about writing exams?",
        "Do you prefer reading, listening, speaking or writing lessons?",
        "Do you think creative writing is good for you?",
        "What writing skills do you need to be able to write well?",
        "Do you think writing will disappear in the future, once computers can recognize and write down everything you say?",
        "Are you a good writer in your own language?",
        "Do you like your handwriting? How would you describe it",
        "Poet William Wordsworth said: \"Fill your paper with the breathings of your heart.\" Do/Can you do this?",
        "E. L. Doctorow said: \"Writing is an exploration. You start from nothing and learn as you go.\" Do you agree?"
    ],
    "Writing Activities": [
        "What comes to mind when you hear the term ‘writing activity’?",
        "What do you think when your teacher says you’re going to do some writing?",
        "What kind of writing practice do you need most? Which writing skills do you need to improve?",
        "Do you like the writing activities your teacher gives you?",
        "Do you have an example of how a writing lesson really improved your writing?",
        "Do you know of any websites that have good writing activities?",
        "How different is writing in English to writing in your own language?",
        "Do you always understand the reasons why the teacher asks you to do a particular writing activity?",
        "What are your biggest problems with writing?",
        "How important are writing activities compared with reading, speaking and listening activities?",
        "Do you like doing writing activities in class?",
        "Do you ever think writing activities are a waste of time?",
        "Do you prefer writing with a pen or a keyboard?",
        "Is the topic important when you do a writing activity?",
        "What things are important for a writing activity to be successful?",
        "What advice would you give to a student who says he/she is no good at writing?",
        "How important is it to plan what you write?",
        "How important do you think writing in English is in today’s world?",
        "Do you think you need writing practice in every class?",
        "What questions would you like to ask your teacher about writing?"
    ]
}
