export default {
    "NASA": [
        "What comes to mind when you hear the word ‘NASA’?",
        "What does the acronym NASA mean?",
        "Would you like to work for NASA?",
        "What do you think is NASA’s greatest ever triumph?",
        "What projects is NASA working on at the moment?",
        "Why is the work NASA does important?",
        "Why is NASA so interested in Mars?",
        "Do you think NASA’s $15 billion annual budget is enough or should the money be spent on other things?",
        "What do you think NASA’s astronaut training is like?",
        "Why isn’t NASA interested in more manned trips to the Moon?",
        "What do you know about NASA?",
        "What do you know about NASA’s competitors?",
        "What do you know about the early days of NASA?",
        "If NASA found an alien, do you think they’d tell us about it?",
        "Do you think NASA has secrets it doesn’t tell the world about the things it has found?",
        "What is the point of NASA? What’s its mission?",
        "If you could decide on a project for NASA, what would it be?",
        "What do NASA workers talk about in their lunch break?",
        "What would be the best job to have in NASA?",
        "What questions would you like to ask a NASA astronaut?"
    ],
    "NATURAL DISASTERS": [
        "What comes to mind when you hear the term ‘natural disasters’?",
        "What are natural disasters?",
        "Have you ever experienced a natural disaster?",
        "What was the last natural disaster you saw on TV?",
        "Have you ever prepared for a natural disaster?",
        "Are there often natural disasters in your country?",
        "Do you think natural disasters are happening more frequently in the world today?",
        "What’s the worst natural disaster in your opinion?",
        "Do you think the world should be more concerned about natural disasters or terrorism?",
        "What’s the best natural disaster movie you’ve ever seen?",
        "What’s worse, natural disasters or manmade disasters?",
        "Would you move if you lived in a country where natural disasters were common?",
        "Why are so many natural disaster movies set in New York City?",
        "Do you know anyone who could be called a natural disaster?",
        "What are the worst natural disasters you can remember?",
        "Are natural disasters acts of God?",
        "Do you think world governments do enough to help people after natural disasters?",
        "What would happen if a giant comet hit the Earth?",
        "If a natural disaster hit your town, what would you do?",
        "Why do you think natural disasters always seem to affect poor people most?"
    ],
    "Nails": [
        "What do you think about your nails?",
        "What are fingernails and toe nails useful for?",
        "Do you ever think nails could have been better designed?",
        "What do you think of people who bite their nails?",
        "Do you think nail polish makes nails look attractive? What colour is best?",
        "What do you think of nail art and spending $100 to have glitter stuck on your nails?",
        "What does it say about a person if he/she always has long and dirty fingernails?",
        "Why do women like manicures and pedicures so much?",
        "Is cutting your nails too much trouble at times?",
        "What do you think of long, false nails?",
        "Why do women spend so much time and energy on nail care?",
        "What do you think when you see someone with a really long nail on his/her big toe?",
        "Have you ever ripped off part of a nail?",
        "How can you stop children biting their nails?",
        "How important are the other person’s fingernails when you are thinking about dating them?",
        "Does the scratching of a chalk board with fingernails make you shiver?",
        "Do you do things to look after your nails and make them stronger?",
        "How would life be different without fingernails?",
        "What do you think of people who bite their toenails?",
        "Should you cut your nails after dark?"
    ],
    "Names": [
        "Do you like your name(s)?",
        "What does your name mean?",
        "Why did your parents choose that name for you?",
        "What is the coolest name in the world?",
        "If you could change your name, what would you change it to?",
        "What names do you really dislike?",
        "Are boys names better than girls names or is it the other way round?",
        "What are good names to give to pets?",
        "Can you guess the social status of someone in your country from his or her name?",
        "What do you think of old people’s names?",
        "Do you prefer people to call you by your given name of your family name (with Mr, Ms, Miss, Mrs, etc)?",
        "What is the most ridiculous name you’ve ever heard?",
        "Do you have a nickname and do you like it?",
        "What do you think of the idea of naming babies after their parents?",
        "Hyphenated (double-barreled) names are common in English speaking countries. If Mr Pilkington-Smythe married Ms Montague-Smith, the child could be called (Jane/John) Pilkington-Smythe-Montague-Smith. What do you think of this?",
        "What thing in the world you like to be named after you?",
        "What do you think of people naming their children after actors and pop stars?",
        "How many middle names does a person really need?",
        "Do you have problems with your name and legal documents?",
        "Do you think children’s names should be from their culture?"
    ],
    "National Anthems": [
        "What comes to mind when you hear the term ‘national anthem’?",
        "Do you like your national anthem?",
        "What feelings do you have when you hear your national anthem?",
        "Do you know all the words to your national anthem?",
        "Do you think your national anthem is the right one or would you like a different one?",
        "Have your eyes ever filled with tears at the sound of your national anthem?",
        "Do you think your national anthem should be played regularly in schools?",
        "What is the most meaningful line in your national anthem?",
        "Some countries play the national anthem in movie theatres before a film begins. What do you think of this?",
        "Do you think you should stand when you hear another country’s national anthem?",
        "Are national anthems useful, necessary, important?",
        "What  national anthems from other countries do you like?",
        "Are there any national anthems you hate?",
        "Do you always stand and put your hand on your heart when you hear your national anthem?",
        "What would you feel if people booed your national anthem?",
        "Would you like to sing your national anthem to thousands of people at a special occasion in your country?",
        "If you could choose a pop or rock song to be your country’s national anthem, what would you choose?",
        "Do you think a world anthem would be better than national anthems?",
        "Do the words of your national anthem reflect your country’s culture today?",
        "What new words would you like to add to your national anthem?"
    ],
    "Nationality": [
        "What comes to mind when you hear the word ‘nationality’?",
        "Are you happy with your nationality?",
        "If you could change nationality, which other nationality would you choose?",
        "Is nationality a problem in today’s world?",
        "What’s the difference between nationality and race?",
        "Is nationality important?",
        "Would you like dual nationality? What are the benefits?",
        "Is your nationality or religion more important to you?",
        "What difficulties do you think there are in marrying someone from a different nationality to you?",
        "What nationality are people with no countries (Kurds, Palestinians, etc)?",
        "What should schools teach children about nationality?",
        "Will nationality become more or less important in the future?",
        "What are the good points about your nationality?",
        "What are the bad points about your nationality?",
        "What other nationalities does your country have a problem with?",
        "When are you most proud of your nationality?",
        "If you changed your nationality, would you love your new country more than your original country?",
        "Do you look like your nationality?",
        "What things are common among people with your nationality?",
        "Do you think your nationality is pure?"
    ],
    "Nature": [
        "What things do you think about when you hear the word ‘nature'?",
        "How important is nature to you? Why?",
        "How much nature is there where you live?",
        "What is the most beautiful thing in nature? Why?",
        "How does being in nature make you feel? Why?",
        "Why do people live in cities, where there is almost no nature?",
        "What does \"the power of nature\" mean? How powerful is nature?",
        "What bad things are people doing to nature?",
        "What would the trees say to humans (if they could talk)?",
        "Where is the best place in your country to see or experience nature?",
        "What is nature?",
        "What would life be like without nature?",
        "In 100 years from now, how different do you think the natural world will be?",
        "How important is nature in your culture?",
        "Are there any bad things about nature?",
        "How can we add more nature to cities?",
        "Where is nature at its most beautiful – the mountains, oceans, deserts, beaches, space, or forests? Why do you think so?",
        "What three things can you do today to help nature?",
        "How good would you be at living in nature? Why do you think so?",
        "How would the world be a better place if we all went back to nature?"
    ],
    "Neighbours": [
        "What comes to mind when you hear the word ‘neighbour’?",
        "Are you neighbourly?",
        "What kind of neighbors don’t you like?",
        "Do you trust your neighbours?",
        "Do you have nosy neighbors?",
        "Do you have any terrible neighbours stories?",
        "“Love thy neighbor as thyself.” Do you believe this?",
        "Do high fences make good neighbors?",
        "What are the biggest problems among neighbours?",
        "Would you like to live next door to your boss?",
        "Do you have good neighbours?",
        "Who would you love to move next door to you?",
        "Have you ever argued with your neighbors?",
        "What would you do if you had really noisy neighbours?",
        "Would you like to have your parents or parents-in-law as neighbors?",
        "Would you like your current neighbours to move?",
        "Have you ever had a “dog problem” with neighbors?",
        "What’s your neighborhood like?",
        "Do you know any secrets or gossip about your neighbours?",
        "What would you really like to know about your neighbors?"
    ],
    "Nepal": [
        "What images spring to mind when you hear the country Nepal?",
        "What are the good things and bad things about Nepal?",
        "What is Nepal famous for?",
        "What do you know about Nepalese history?",
        "What images of Nepal do you have that are beautiful and adventurous?",
        "What do you think about Nepal’s peoples?",
        "What has Nepal given to the world?",
        "Would you like to visit Nepal, or live there?",
        "What do you know about the geography of Nepal?",
        "Who are the most famous Nepalese people you know?",
        "How different is Nepal from other Asian countries?",
        "What do you know about Nepalese culture?",
        "What do you think Nepalis think about Mount Everest?",
        "What do you think Nepal will be like 50 years from now?",
        "Does your country have good relations with Nepal?",
        "What do you think about Nepal’s leaders?",
        "What is your idea of a typical Nepalese person?",
        "What things about Nepal do you think Nepalese people are proud of?",
        "What do you know about Nepalese politics?",
        "What would you like to ask a Nepali person about Nepal?"
    ],
    "New York": [
        "What images spring to mind when you hear ‘New York’?",
        "What are the good things and bad things about New York?",
        "What is New York famous for?",
        "What do you know about New York’s history?",
        "What images of New York do you have that are exciting?",
        "What do you think about New York?",
        "Why is New York described as a world city?",
        "Would you like to visit New York, or live there?",
        "What do you think of New Yorkers?",
        "What adjectives would you use to describe New York and why?",
        "How different is New York from other American cities?",
        "What would you do if you could spend one day in New York?",
        "What movies do you know that are set in New York?",
        "What do you think New York will be like 50 years from now?",
        "What do you know or remember about 9/11?",
        "What do you think about New York’s nickname, the ‘Big Apple’?",
        "What is your idea of a typical New Yorker?",
        "What things about New York do you think New Yorkers are proud of?",
        "What news stories do you know of that are about New York?",
        "What would you like to ask a New Yorker about New York?"
    ],
    "New Zealand": [
        "What images spring to mind when you hear the country New Zealand?",
        "What are the good things and bad things about New Zealand?",
        "What is New Zealand famous for?",
        "What do you know about New Zealand’s history?",
        "What images of New Zealand do you have that are beautiful?",
        "What do you think about New Zealand?",
        "What do you know about the different people who live in New Zealand?",
        "Would you like to visit New Zealand, or live there?",
        "What do you think of New Zealanders?",
        "What adjectives would you use to describe New Zealand and why?",
        "How different is New Zealand from other countries?",
        "What would you do if you could spend one week in New Zealand?",
        "Why are New Zealanders called ‘Kiwis’? What do you think of Kiwis?",
        "What do you think New Zealand will be like 50 years from now?",
        "What do you know about sport in New Zealand?",
        "Do you know any famous New Zealanders?",
        "What is your idea of a typical New Zealander?",
        "What things about New Zealand do you think New Zealanders are proud of?",
        "What do you know about New Zealand’s stand on environmental issues?",
        "What would you like to ask a New Zealander about New Zealand?"
    ],
    "News": [
        "What images spring to mind when you hear the word ‘news’?",
        "Do you think news is usually happy or sad?",
        "How important is keeping up to date with the news to you?",
        "Do you prefer to watch, listen to or read about news?",
        "What areas of the world are you most interested in?",
        "What kinds of stories hit the headlines in your local newspaper?",
        "What are your favourite sections of the newspaper?",
        "What was the last piece of good news you heard?",
        "What news story are you following at the moment?",
        "Do you trust everything you read, see or hear on the news?",
        "What is news? What makes something news?",
        "What do you understand by the phrase, “No news is good news”?",
        "Would you like to work as a newscaster or a news reporter?",
        "What is your favourite news programme?",
        "What’s the best satellite news station, BBC, CNN, other?",
        "What do you think of news stations being under state control?",
        "What’s the most tragic news you’ve seen on TV?",
        "Is news and propaganda the same thing in some countries?",
        "Do you think news programmes should include Hollywood/celebrity stories and gossip?",
        "Do you think news reporting in your country is fair and balanced? How about in other countries?"
    ],
    "Nigeria": [
        "What images spring to mind when you hear the country Nigeria?",
        "What are the good things and bad things about Nigeria?",
        "What is Nigeria famous for?",
        "What do you know about Nigerian history?",
        "What images of Nigeria do you have that are beautiful and adventurous?",
        "What do you think about Nigeria’s peoples?",
        "What has Nigeria given to the world?",
        "Would you like to visit Nigeria, or live there?",
        "What do you know about the geography of Nigeria?",
        "Who are the most famous Nigerian people you know?",
        "How different is Nigeria from other African countries?",
        "What do you know about Nigerian cultures?",
        "Nigeria has lots of oil. Why isn’t it one of the richest countries in Africa?",
        "What do you think Nigeria will be like 50 years from now?",
        "Does your country have good relations with Nigeria?",
        "What do you think about Nigeria’s leaders?",
        "What is your idea of a typical Nigerian person?",
        "What things about Nigeria do you think Nigerians are proud of?",
        "What do you know about Nigerian politics?",
        "What would you like to ask a Nigerian person about Nigeria?"
    ],
    "Night": [
        "What comes to mind when you hear the word ‘night’?",
        "What do you know about night?",
        "Are you a night person or a day person?",
        "What do you do at night that is different from during the day?",
        "Do you feel different at night than you do during the day?",
        "Do you have a favourite night of the week?",
        "What did you do last night?",
        "Do you ever have nightmares?",
        "Do ‘things go bump in the night’ in your house?",
        "What’s the best night out you’ve ever had?",
        "Do you like the night?",
        "Would you prefer to work a night shift or day shift?",
        "Is it safe to walk the streets at night in your town?",
        "How does nature change when days turns to night?",
        "Do you like going to nightclubs?",
        "Have you ever stayed awake all night?",
        "Are you afraid of anything when night time comes?",
        "What would life and the world be like if humans were nocturnal – we slept during the day and were active at night?",
        "What are your plans for tonight?",
        "What do you think in English it’s ‘yesterday’ but not ‘yesternight’?"
    ],
    "No": [
        "What comes to mind when you hear the word ‘no’?",
        "Which do you say more, ‘no’ or ‘yes’?",
        "Is it sometimes difficult for you to say ‘no’?",
        "What did you think when your parents said ‘no’ when you were a child?",
        "What is a no-no?",
        "When was the last time you had to shout ‘no’?",
        "Are there any no-go areas in your town? Is your room a no-go area?",
        "Do you prefer no-frills, no-nonsense stores or do you like expensive department stores?",
        "Have you ever been in a no-win situation?",
        "Do you think ‘no’ always means ‘no’?",
        "What do you think of the word ‘no’?",
        "When was the last time you said ‘no’?",
        "Have you ever said ‘no’ when you really wanted to say ‘yes’?",
        "What would the world be like if everyone said ‘no’?",
        "What do you think are common questions to which people reply ‘no’?",
        "Why do you think people might say ‘no, no, no, no, no’?",
        "Which question would you always say ‘no’ to?",
        "What words do you know that commonly follow ‘no’?",
        "What times in your life has your head said ‘yes’ but your heart said ‘no’ – or vice versa?",
        "Why might your government start a “Say No” campaign?"
    ],
    "Nobel Prize": [
        "What images spring to mind when you hear the phrase “Nobel Prize”?",
        "What do you think of the Nobel Prize?",
        "What do you know about the different Nobel prizes?",
        "What do you know about the different Nobel Prize winners?",
        "What do you know about the life of Alfred Nobel?",
        "Does your country have many Nobel Prize winners?",
        "Would you prefer to win a Nobel Prize for peace, literature, medicine, physics or economics?",
        "Ghandi never won the Nobel Prize for Peace. Do you think he should have?",
        "Do you know any Nobel Prize winners who should not have received the award?",
        "What do Nobel Prize winners have in common?",
        "Would you rather win a Nobel Prize, an Oscar, an Olympic gold medal or a World Cup winner’s medal?",
        "Men usually win Nobel Prizes. Does this make the Nobel selection committee sexist?",
        "If you could make a new Nobel Prize category, what would it be and who would win it?",
        "Do you think there should be a Nobel Prize for the environment?",
        "Are there any better prizes in the world than the Nobel Peace prize?",
        "What do you think you should win a Nobel Prize for?",
        "How does winning a Nobel Prize change the winner’s life?",
        "Should a Nobel Prize winner try to change the world?",
        "Would you rather attend the Oscars or the Nobel Prize ceremony?",
        "What would you like to ask a Nobel Prize winner?"
    ],
    "Noise": [
        "When do you make a lot of noise?",
        "What noises do you like and dislike?",
        "What do you think of noise pollution?",
        "Do you worry about strange noises when you’re in bed?",
        "Can you enter your house and sneak to your room without making a noise?",
        "What’s the most terrifying noise you know of?",
        "What noises does your computer make?",
        "Do animals in your language make the same noises as they do in English?",
        "Does anyone you know have a bad habit of making noises?",
        "Where do you hear background noise and what do you think of it?",
        "What springs to mind when you hear the word ‘noise’?",
        "What’s the most annoying noise for you?",
        "Do you worry about strange noises when you’re in an airplane?",
        "Are you easily awoken by noises?",
        "What bodily noises are there and what do you think of them?",
        "Are noise levels like in your town?",
        "Can you sleep if there’s a lot of noise going on?",
        "Do you ever think that some music is just noise?",
        "What is white noise and why is it white?",
        "Have you ever complained to anyone about noise?"
    ],
    "Northern Ireland": [
        "What images spring to mind when you hear 'Northern Ireland'?",
        "What are the good things and bad things about Northern Ireland?",
        "What is Northern Ireland most famous for?",
        "What do you know about Northern Ireland’s history?",
        "What are the differences between Northern Ireland and your country?",
        "What do you think about Northern Ireland people?",
        "What has Northern Ireland given to the world?",
        "What is the difference between Great Britain, England and the United Kingdom?",
        "What do you know about the geography of Northern Ireland?",
        "Who are the most famous Northern Ireland people you know?",
        "How different is Northern Ireland from other European countries?",
        "What was the last news story you read or heard about Northern Ireland?",
        "What do you think it would be like (is like) to live in Northern Ireland?",
        "What do you think Northern Ireland will be like 50 years from now?",
        "Does your country have good relations with Northern Ireland?",
        "What can you do on a holiday in Northern Ireland?",
        "What is your idea of a typical Northern Ireland person?",
        "What things about Northern Ireland do you think the Northern Ireland are proud of?",
        "What do you know about Northern Ireland culture?",
        "What would you like to ask a Northern Ireland person about Northern Ireland?"
    ],
    "Norway": [
        "What images spring to mind when you hear the country name Norway?",
        "What are the good things and bad things about Norway?",
        "What is Norway famous for?",
        "What do you know about Norway’s history?",
        "What images of Norway do you have that are beautiful?",
        "What do you think about Norway?",
        "What do you know about the geography of Norway?",
        "Would you like to visit Norway, or live there?",
        "What do you think of Norwegians?",
        "What adjectives would you use to describe Norway and why?",
        "How different is Norway from other Scandinavian countries?",
        "What would you do if you could spend one week in Norway?",
        "What do you know about Norwegian culture?",
        "What do you think Norway will be like 50 years from now?",
        "What do you know about sport in Norway?",
        "Do you know any famous Norwegians?",
        "What is your idea of a typical Norwegian?",
        "What things about Norway do you think Norwegians are proud of?",
        "What do you know about Norway’s government and society?",
        "What would you like to ask a Norwegian about Norway?"
    ],
    "Nose": [
        "What comes to mind when you hear the word ‘nose’?",
        "How important is the nose?",
        "Do you think noses could have been a different shape?",
        "What are the functions of our nose?",
        "What do you think of nose piercing?",
        "Who has the best looking nose?",
        "What kind of noses do you find attractive?",
        "Do you think everyone picks their nose?",
        "Do you ever look down your nose at other people?",
        "If you were Pinocchio, how long would your nose be by now?",
        "Do you like your nose?",
        "Is there a correct way to blow your nose in your country?",
        "Have you ever ‘cut off your nose to spite your face’?",
        "What’s the best way to stop a nose bleed?",
        "If a cosmetic surgeon offered you a free nose job, would you take it?",
        "How often does your nose run / do you get a runny nose?",
        "Can you name all the different parts of the nose?",
        "Have you ever broken or hurt your nose?",
        "When you’re really busy, do you put your nose to the grindstone?",
        "What do you do if you have a congested (blocked) nose?"
    ],
    "November": [
        "What springs to mind when you hear the word ‘November'?",
        "What do you think of the month of November?",
        "What good things happen in November?",
        "What things do you usually do in November?",
        "What do you think of the word 'November'?",
        "What are people who are born in November like?",
        "What do you think of November weather?",
        "Where is November on the list of 'the best months'?",
        "Are there any bad things about the month of November?",
        "What plans do you have for next November?",
        "If you made a November festival, what would you it be like?",
        "Is there any delicious food you eat in November?",
        "How should people celebrate in November?",
        "What famous holidays are there in November?",
        "How do you feel when November arrives?",
        "If you made a video about November, what would you put in it?",
        "How do you feel when November is over?",
        "What three adjectives best describe November, and why?",
        "What good thing can you remember happening in November?",
        "What is a good symbol for November, and why?"
    ],
    "Nuclear Energy": [
        "What images spring to mind when you hear the term ‘nuclear energy’?",
        "What are the good things and bad things about nuclear energy?",
        "Would you live near a nuclear power plant if it meant your power bills were halved?",
        "What you encourage your government to adopt a nuclear energy programme if it reduced carbon emissions?",
        "Do you think people will ever see nuclear energy as safe?",
        "If there is another disaster on the scale of Chernobyl, do you think governments should stop their nuclear energy programmes?",
        "Should only democratic countries be “allowed” to have nuclear energy programmes?",
        "What are the best alternatives to nuclear energy?",
        "If the money was good, would you work at a nuclear power plant?",
        "What happens to nuclear energy when all the plutonium runs out?",
        "How does nuclear energy work?",
        "Are you at all worried about nuclear energy?",
        "What nuclear energy programmes exist in your country?",
        "Do you think nuclear energy now has a good image?",
        "Do you think the oil industry is happy about nuclear energy?",
        "Would you like to see nuclear powered cars?",
        "Would you buy your own “household” nuclear reactor if one was available?",
        "Why do politicians go on and on about nuclear energy for “peaceful purposes”?",
        "What do environmentalists think about nuclear energy?",
        "If nuclear energy is so clean, why isn’t it in every country?"
    ],
    "Nuclear Weapons": [
        "What images spring to mind when you hear the term ‘nuclear weapons’?",
        "What do you think about nuclear weapons?",
        "How often do you worry about nuclear weapons?",
        "Which country in the world do you think will use nuclear weapons next?",
        "How would the world be different if nuclear weapons were small enough and easy enough to make to be sold on the black market?",
        "Do you think terrorists will ever get nuclear weapons?",
        "Would the world be a safer place without nuclear weapons?",
        "Will most countries have nuclear weapons one day?",
        "Do you want your country to have nuclear weapons?",
        "Are nuclear weapons really a big deterrent?",
        "Would you allow your government to use nuclear weapons if it was the only way to stop your country from being invaded?",
        "Do you think a nuclear war is inevitable or do you believe world leaders have sense?",
        "If you knew a nuclear weapon would be fired at your country next week, what would you do in the next few days?",
        "Which country that has nuclear weapons is the most dangerous?",
        "Should the UN try and stop countries like Brazil, Indonesia and Australia from getting nuclear weapons if they want them?",
        "Do countries with nuclear weapons have the right to stop other countries developing them?",
        "What do you think it feels like to press the “launch” button?",
        "Would you work for a company that made nuclear weapons?",
        "What would the world be like after a nuclear war?",
        "What are the chances of a World War IV?"
    ],
    "Numbers": [
        "What comes to mind when you hear the word ‘number’?",
        "Why do we have numbers?",
        "Are you a number?",
        "What are the important numbers in your life?",
        "Can you easily remember telephone and license plate (car registration) numbers?",
        "Do you have a lucky and unlucky number?",
        "What numbers do you look at every day?",
        "Would you like a job in which you had to work with numbers?",
        "What are the happy numbers in your life?",
        "Have you ever been, or are you now, number one?",
        "Are you good with numbers?",
        "Why is the number of your cash card called a PIN number – it becomes a ‘Personal Identification Number number’?",
        "What do you think of the number 100?",
        "What do you think of the number 1,000,000?",
        "Would you live in house number 13 (or number 4 in China/Japan)?",
        "Would you be interested in studying numerology?",
        "What’s the difference between a number and numeral?",
        "What is the number of the beast? Are you worried about this number",
        "What does the verb ‘number’ mean? Do you ever number things?",
        "What does it mean if “your days are numbered”?"
    ],
    "Nursing": [
        "What do you think about nursing?",
        "What adjectives would you use to describe nurses?",
        "Do you think nursing is a good career?",
        "What do you think would be the best and worst things about nursing?",
        "What kind of personality do you need to be a good nurse?",
        "Do you think nursing is dangerous?",
        "Do you think nurses get paid enough?",
        "Are male or female nurses better?",
        "What do you think is a typical nurses day?",
        "Do you think nurses or doctors work harder?",
        "Would you rather have a male or female nurse if you were in hospital?",
        "Do you think you would be a good nurse?",
        "Do you think nurses get used to the sight of blood?",
        "What do you think about violence against nurses?",
        "If you were a nurse, in what medical would you like to work?",
        "Do you think nurses need training to deal with death?",
        "What do you think of governments that make nurses unemployed? Shouldn’t nurses have a job for life?",
        "How can governments encourage more people to take up nursing?",
        "If you were rich, would you have your own private nurse?",
        "What’s the youngest you think someone can become a nurse?"
    ],
    "Nuts": [
        "What comes to mind when you hear the word ‘nut’?",
        "What do you know about nuts?",
        "Do you have a favourite nut?",
        "What dishes do you like that have nuts in them?",
        "What’s the best thing to eat or drink with nuts?",
        "Do you eat nuts any time during the year or only on special occasions?",
        "What do you know about the nutritional value of nuts?",
        "Why do we say crazy people are ‘nuts’?",
        "What drives you nuts?",
        "What do you think of coconuts?",
        "Do you like salted, chillied, dry roasted or plain nuts?",
        "Do you know anyone who is allergic to nuts?",
        "How would your life be different without nuts?",
        "How would nature be different without nuts?",
        "Do you like fruit and nut? What other things go well with nuts?",
        "Do you think there should be other nutty spreads besides peanut butter and Nutella?",
        "What do you think of the idea of nut juice?",
        "Which are better, nuts or potato chips?",
        "What is a “tough nut that is hard to crack”? Do you know anyone like this",
        "Which is better, a nut roast or beef roast?"
    ]
}
