export default {
    "Zambia": [
        "What images spring to mind when you hear the country ‘Zambia’?",
        "What are the good things and bad things about Zambia?",
        "What is Zambia most famous for?",
        "What do you know about Zambia’s history?",
        "What are the differences between Zambia and your country?",
        "What do you think about Zambian people?",
        "What has Zambia given to the world?",
        "Would you like to visit Zambia, or live there?",
        "What do you know about the geography of Zambia?",
        "Who are the most famous Zambian people you know?",
        "How different is Zambia from other African countries?",
        "What was the last news story you heard about Zambia?",
        "What do you think Zambia’s neighbours think of it?",
        "What do you think Zambia will be like 50 years from now?",
        "Does your country have good relations with Zambia?",
        "What could you do on a holiday in Zambia?",
        "What is your idea of a typical Zambian person?",
        "What things about Zambia do you think Zambians are proud of?",
        "What do you know about Zambian culture?",
        "What would you like to ask a Zambian person about Zambia?"
    ],
    "Zimbabwe": [
        "What images spring to mind when you hear the country Zimbabwe?",
        "What are the good things and bad things about Zimbabwe?",
        "What is Zimbabwe most famous for?",
        "What do you know about Zimbabwe’s history?",
        "What are the differences between Zimbabwe and your country?",
        "What do you think about Zimbabwean people?",
        "What has Zimbabwe given to the world?",
        "Would you like to visit Zimbabwe, or live there?",
        "What do you know about the geography of Zimbabwe?",
        "Who are the most famous Zimbabwean people you know?",
        "How different is Zimbabwe from other African countries?",
        "What was the last news story you heard about Zimbabwe?",
        "What do you think Zimbabwe’s neighbours think of it?",
        "What do you think Zimbabwe will be like 50 years from now?",
        "Does your country have good relations with Zimbabwe?",
        "What could you do on a holiday in Zimbabwe?",
        "What is your idea of a typical Zimbabwean person?",
        "What things about Zimbabwe do you think Zimbabweans are proud of?",
        "What do you know about Zimbabwean culture?",
        "What would you like to ask a Zimbabwean person about Zimbabwe?"
    ],
    "Zombies": [
        "What images spring to mind when you hear the word ‘zombie’?",
        "What do you know about zombies?",
        "Is there a time of the day or week you feel like a zombie?",
        "What would you do if you woke up one morning and all of the people in your town were zombies?",
        "What three adjectives would you use to describe a zombie?",
        "Are there zombies (of any kind) in your culture?",
        "If you were a zombie, what would you do with your life (death)?",
        "Are you a walking zombie if you have next to no sleep?",
        "What name would you give to a zombie movie?",
        "What do you think zombies chat about when they get together?",
        "What is a zombie?",
        "Do you have a favourite zombie movie?",
        "Do you think zombies are real?",
        "Why do horror movies like zombies?",
        "What’s the best way to re-kill a zombie?",
        "What do you think zombies do all day?",
        "Have you ever had a dream or a nightmare about zombies?",
        "Which would you be more afraid of - a zombie, a vampire or a werewolf?",
        "What do you think of the word ‘zombie’?",
        "How do you stop a small child from being afraid of zombies?"
    ],
    "Zoos": [
        "What images spring to mind when you hear the word ‘zoo’?",
        "What are the good things and bad things about zoos?",
        "What is the most famous zoo in the world?",
        "Do you think animals know they are in zoos?",
        "What are your earliest memories of a zoo?",
        "What purpose do zoos serve?",
        "Would you like to work in a zoo?",
        "Do you think their should be human exhibits in zoos, living in caged houses?",
        "What happens in a zoo at night and the early hours of the morning?",
        "Would you like to study zoology?",
        "Do you like zoos?",
        "What was the last news story you heard about a zoo?",
        "What would happen if all the zoo animals escaped into the town?",
        "Do you feel sorry for the animals in zoos?",
        "Have you ever felt like you were in a zoo?",
        "Which is better - a zoo or an aquarium?",
        "What happens to the animals that die in zoos?",
        "Why do you think kids love zoos so much?",
        "What’s the best thing to buy from the zoo gift shop?",
        "Are zoos morally wrong?"
    ]
}
