export default {
    "FAQs": [
        "What does ‘FAQ’ stand for?",
        "How often do you click the ‘FAQ’ link on a website?",
        "Do you always find answers in the FAQs?",
        "Do you think the FAQs are really asked by lots of people?",
        "What is the question you ask most frequently?",
        "What do you do if you cannot find an answer in the FAQs?",
        "Do you ever think your question is more common than the ones on the FAQ list?",
        "Do you ever skip the FAQs and go straight to the ‘Contact Us’ link?",
        "Do you think some companies put their own list of FAQs online simply to promote their product?",
        "Would you like a job answering FAQs for companies?",
        "How do you pronounce FAQ?",
        "Most sites have no more than ten FAQs. Do you think this is helpful?",
        "Do you think a FAQ page is an excuse to cut back on customer service costs?",
        "What do you think are the most frequently asked questions to Google, YAHOO! Or Microsoft?",
        "What do you think are the most frequently asked questions to your country’s leader?",
        "What do you think is the world’s most frequently asked question?",
        "Have you seen the FAQ acronym offline?",
        "What do you think are the most common FAQs on English language sites?",
        "Would you like to know how many people asked a FAQ?",
        "Do you think there is a better system than a FAQ page?"
    ],
    "Facebook": [
        "What springs to mind when you hear the word ‘Facebook’?",
        "Do you like the Facebook logo?",
        "Facebook or Twitter?",
        "What are the best things about Facebook?",
        "Do you think it’s dangerous putting information on Facebook?",
        "What are your favourite Facebook applications or games?",
        "How would you sell someone to Facebook who didn’t want to open an account?",
        "What is the purpose of Facebook?",
        "Would you ever pay to use Facebook?",
        "Have you ever put anything on Facebook that you regretted?",
        "Can you remember when you first heard of Facebook?",
        "What do you think of the name ‘Facebook’?",
        "What do you think Facebook will be like a decade from now?",
        "What would you like Facebook to do differently?",
        "Is Facebook a good place to meet new people?",
        "Would you let your 14-year-old child open a Facebook account?",
        "Is Facebook here to stay or will something else come along and make it history?",
        "What do you think of people who are addicted to Facebook?",
        "What questions would you like to ask Facebook’s owner?",
        "Did you like this discussion?"
    ],
    "Factories": [
        "What kind of factories are there in your town?",
        "What factories were in your town 50 years ago?",
        "Do you think factories are the same all over the world?",
        "Would you like to work in a factory?",
        "Which country do you think has the most efficient factories?",
        "Have overseas companies built factories in your country?",
        "What do factories need to do to protect the environment?",
        "How have mass production techniques in factories changed our lives?",
        "How have working conditions in factories changed since the Industrial Revolution?",
        "What should be done about multinational companies employing children in sweat shops?",
        "Have you ever visited a factory and seen a production line?",
        "Should factories be full of workers or robots?",
        "Why do you think many countries copy Japanese factories?",
        "What do you think factories of the future will look like?",
        "What do you think the differences are working in a car factory and silicon chip factory?",
        "How did factories change societies?",
        "Do you think all factories need organized unions?",
        "What is your image of ‘fast food factories’?",
        "Do you think there were weapons factories in Iraq during Saddam Hussein’s rule?",
        "Would you like to visit Willie Wonka’s chocolate factory?"
    ],
    "Family": [
        "What comes to mind when you hear the word ‘family’?",
        "How important is your family to you?",
        "How important are you to your family?",
        "Would you like / Do you have your own family?",
        "Do you prefer spending time with your family or friends?",
        "Are there any strange people in your family?",
        "Are you jealous of any of your family members?",
        "Do you get on well with all of your family members?",
        "How often do you have big family get-togethers?",
        "How much of a family person are you?",
        "Do you have the ideal family?",
        "Is there a black sheep in your family?",
        "Is “blood thicker than water” regarding your family?",
        "Do you prefer the idea of extended or nuclear families?",
        "There is much talk recently of increased social problems due to family breakdown. Is this true in your country?",
        "When do you need your family most?",
        "What would the world be like without families?",
        "Are we all in one big happy family?",
        "Do you ever get tired of family duties?",
        "How far back do you know your family tree?"
    ],
    "Famine": [
        "What springs to mind when you hear the word “famine”?",
        "Why does famine happen?",
        "How many famines do you know of?",
        "Why is there famine today when the world is so rich?",
        "Will people dying in famines be a thing of the past one day?",
        "What does your country do to help famine victims?",
        "How do you feel when you see images of famine on television?",
        "How can we help cut the number of lives lost in a famine?",
        "Matthew Henry said: “They that die by famine die by inches.” What does this mean?",
        "A Zulu proverb says: “Abundance does not spread; famine does.” Can we reverse this?",
        "Would you pay a famine tax to help victims?",
        "How do people suffer in a famine?",
        "How can we ensure more charity donations actually helps victims?",
        "How much of a threat is famine to the world?",
        "Do you think famines are increasing or decreasing in number? Why?",
        "What can you do more to help famine victims?",
        "Why do people only give to famine victims when rock starts arrange aid concerts?",
        "“More than fifty percent of the total world population, live in poverty, with hunger as a constant companion and fear of famine a continual menace.” (Norman Borlaug)  Why is this so?",
        "Should countries relocate populations to areas where famine is less likely to happen?",
        "Does charity begin at home or should we help famine victims more?"
    ],
    "Farming": [
        "How important is farming in your country?",
        "Is farming in your country in a healthy condition?",
        "What crops are farmed in your country?",
        "What livestock is raised in your country?",
        "Do you think farming offers a good quality of life?",
        "How different is farming across the world?",
        "What do you think of farming GM crops?",
        "How can subsistence farming become more profitable?",
        "What do you think of the intensive farming methods used in rich countries?",
        "Do you think the farming of crops for biofuels is a good idea?",
        "What are the challenges the farming industry faces today?",
        "Does farming help or add to global warming?",
        "Would you like to be a farmer?",
        "Do you think we could save the world if we all went back to farming?",
        "Are you interested in farming news?",
        "Would you prefer to work in dairy farming or arable farming?",
        "What do you know about factory farming?",
        "Does farming help preserve the countryside?",
        "Do you think governments should encourage more organic farming?",
        "What do you understand by the term ‘urban farming’?"
    ],
    "Fashion": [
        "Do you like fashion?",
        "What do you think of the fashion industry?",
        "Are you a fashion victim / slave to fashion?",
        "Would you like to be a fashion model?",
        "How does fashion affect our lives?",
        "How important is fashion today compared with in the past?",
        "What do you think of the fact that what’s in fashion lasts just a short time, then we have to spend more money on the next “in” things?",
        "What are the bad things about fashion?",
        "Is fashion only for beautiful people?",
        "Do you have your own fashion or follow the crowds?",
        "What do you think of designer fashion?",
        "What do you think of street fashion?",
        "What area of fashion interests you most - clothes, hair, cosmetics, shoes, accessories, etc?",
        "Tell me about the most fashionable people you know?",
        "Could you date someone who has a terrible sense of fashion?",
        "Do you have a favourite fashion designer?",
        "What do you think of catwalk fashion? Can you wear the same clothes as the models",
        "What do you think of the fashion in other countries?",
        "What do you think is the best decade / era for fashion?",
        "How would you describe your fashion?"
    ],
    "Fathers": [
        "What images spring to mind when you hear the word ‘father’?",
        "Can you describe your father in one word? Why that word?",
        "Did your father spend a lot of time with you when you were a child?",
        "Do you always buy your father a present on Father’s Day?",
        "What are the differences between a father and a father-in-law?",
        "In what ways do you take after your father?",
        "What is your father’s biggest fault?",
        "Is your father more like a father or a best friend?",
        "What do/did your father and you argue about?",
        "What do you think of Father’s Day? Is it necessary?",
        "What are the biggest differences between fathers and grandfathers?",
        "Why and how did your mother fall in love with your father?",
        "Are you happy with the way your father raised you?",
        "Should father stay at home and look after the kids?",
        "What’s the best piece of advice your father has given you?",
        "Do you think father are the same all around the world?",
        "Do you think being a father is more difficult than being a mother?",
        "What do you think is the hardest thing about being a father?",
        "What’s the biggest lie you’ve ever told your father?",
        "What are the biggest roles of fathers?"
    ],
    "Fear": [
        "What is your biggest fear for yourself?",
        "What is your biggest fear for the world?",
        "Why do we feel fear?",
        "How often do you feel afraid?",
        "Why do people have different fears?",
        "How do you react to fear?",
        "How would you help someone to get over their fear?",
        "Have you ever panicked with fear?",
        "What happens to you physically and emotionally when fear takes hold of you / overcomes you?",
        "How often do you jump or start when something frightens you?",
        "Do you have any form of phobia or paranoia?",
        "What were you afraid of as a child?",
        "What things are people commonly afraid of and why?",
        "What facial expressions accompany fear?",
        "Do you like putting yourself in situations where you can feel fear?",
        "Are you ever afraid of other people?",
        "Do you think society lives in fear?",
        "“The fear of death is to be dreaded more than death itself.” What do you think about this quotation?",
        "What do you think having a fear of the 21st century would be like?",
        "If you ‘put the fear of God into someone,’ how do you think that person feels?"
    ],
    "February": [
        "What springs to mind when you hear the word ‘February'?",
        "What do you think of the month of February?",
        "What good things happen in February?",
        "What things do you usually do in February?",
        "What do you think of the word 'February'?",
        "What are people who are born in February like?",
        "What do you think of February weather?",
        "Where is February on the list of 'the best months'?",
        "Are there any bad things about the month of February?",
        "What plans do you have for next February?",
        "If you made a February festival, what would you it be like?",
        "Is there any delicious food you eat in February?",
        "How should people celebrate in February?",
        "What famous holidays are there in February?",
        "How do you feel when February arrives?",
        "If you made a video about February, what would you put in it?",
        "How do you feel when February is over?",
        "What three adjectives best describe February, and why?",
        "What good thing can you remember happening in February?",
        "What is a good symbol for February, and why?"
    ],
    "Feet": [
        "What do you know about feet?",
        "What English words do you know that describe the feet of animals or birds?",
        "What does it mean to ‘get your feet wet’ and when was the last time you got your feet wet?",
        "If you ‘have both feet on the ground,’ are you practical and sensible or the opposite. Do you have both feet on the ground?",
        "Do you think it’s OK to have cheesy (smelly) feet? Do you have cheesy feet?",
        "Do you ever get tired through being on your feet all day?",
        "Do you wish you had bigger or smaller feet?",
        "Are your feet ticklish?",
        "Have you ever injured your feet?",
        "What is reflexology? Do you think it works?",
        "Do you like your feet?",
        "Do you think feet are attractive?",
        "What’s the difference between ‘to have one’s foot in the door’ and ‘to have one foot in the grave’?",
        "Do you ever ‘walk your feet off’ going shopping or sightseeing?",
        "Can you easily get out of tricky situations by thinking on your feet?",
        "In romance, have you ever been swept off your feet or have you ever swept someone off her feet?",
        "Do you like walking in bare feet?",
        "Have you ever got cold feet and then regretted it later?",
        "Do you like foot massages?",
        "Do you ever do something feet first?"
    ],
    "Feminism": [
        "What is feminism?",
        "Why isn’t there something called ‘masculinism’?",
        "Is your country totally fair and equal to women and men?",
        "What do you know about the history of feminism?",
        "What have feminist movements achieved in your country?",
        "Do you think feminism sometimes has an unfair image?",
        "Why do you think relatively few women belong to feminist movements?",
        "Can men be feminists?",
        "What important things should men know about feminism?",
        "Why is there a stereotype of feminists hating men?",
        "Do you think feminist movements are needed in this century?",
        "How wide is the gender gap in your country?",
        "What do you think feminists mean by ‘reproductive freedom’?",
        "What is your opinion of ‘sexual objectification’ – portraying women (or men) as objects of sexual desire?",
        "What is the biggest worldwide problem facing women?",
        "What problems are there for women in other countries that do not exist in your country?",
        "What do you think of the view that marriage constitutes slavery for women, and that freedom for women cannot be won without the abolition of marriage?",
        "There is a site called “Ladies Against Feminism,” which “promotes beautiful womanhood.” What do you think this is all about?",
        "How would the world change if there was perfect sexual equality?",
        "Which woman has made the greatest progress for women?"
    ],
    "Finance": [
        "What comes to mind when you hear the word finance’?",
        "Do you think finance has different meanings to different people?",
        "Are you happy with the state of your finances?",
        "Do you think it’s important for children to learn about finance in school?",
        "Are you interested in reading news about the financial world?",
        "Are you good at saving and sticking to budgets?",
        "Do you have any interest in talking to a personal financial advisor?",
        "Have you ever risked money in financial markets?",
        "Does the finance minister/secretary in your country do a good job?",
        "Is it better to keep your money under your bed?",
        "What does the area of finance cover?",
        "What personal finance decisions have you had to make recently?",
        "What are the biggest personal finance decisions you’ll have to make?",
        "What kinds of decisions do executives have to make regarding finance?",
        "Would you like to work in finance?",
        "What did your parents tell you about finance?",
        "Do you have a head for finance?",
        "Do you spend too much time and energy sorting out your finances?",
        "Do people who always talk about money and finance bore you?",
        "Are you worried about your financial security in your old age?"
    ],
    "Finland": [
        "What images spring to mind when you hear the country Finland?",
        "What are the good things and bad things about Finland?",
        "What is Finland famous for?",
        "What do you know about Finnish history?",
        "What images of Finland do you have that are beautiful and high-tech?",
        "What do you think about Finland’s peoples?",
        "What has Finland given to the world?",
        "Would you like to visit Finland, or live there?",
        "What do you know about the geography of Finland?",
        "Who are the most famous Finnish people you know?",
        "How different is Finland from other Scandinavian or European countries?",
        "What do you know about Finnish culture?",
        "What do you think Finns think about their country?",
        "What do you think Finland will be like 50 years from now?",
        "Does your country have good relations with Finland?",
        "What do you think about Finland’s leaders?",
        "What is your idea of a typical Finn?",
        "What things about Finland do you think Finnish people are proud of?",
        "What do you know about Finnish politics?",
        "What would you like to ask a Finn about Finland?"
    ],
    "Fire": [
        "What comes to mind when you hear the word ‘fire’?",
        "What are your earliest memories of fire?",
        "Do you like looking at fire?",
        "How do you think the discovery of fire changed the life of humans?",
        "How have fires changed history?",
        "What problems do fires cause in today’s world?",
        "What do you know about the Ring of Fire?",
        "Why are some people fascinated with fire?",
        "What part does fire play in your customs, culture and traditions?",
        "Have you ever seen a building on fire?",
        "Are you good at making a fire?",
        "Do you worry about fire in your house, school, office, etc?",
        "What can we do to prevent fires?",
        "Do you think the job of a fire fighter is an interesting one?",
        "Can you see any fire hazards around you right now?",
        "What punishment do you think arsonists (people who set fires on purpose) get?",
        "Do you ever worry about electrical fires in your house?",
        "Is fire used to describe different human emotions in your language?",
        "“A child is not a vase to be filled but a fire to be lit.” What do you think of this quote?",
        "What kinds of things light your fire?"
    ],
    "Fish": [
        "Do you like fish?",
        "If you were a fish, what kind would you be?",
        "How important are fish?",
        "What part do fish play in the non-food culture of your country?",
        "How important are fish in the food culture of your country?",
        "Do you think fish make good pets?",
        "What is the grammatical difference between ‘fish’ and ‘fishes’?",
        "What do you think a school of fish is? Do you think this is a good term",
        "Do you have a favourite fish dish or seafood restaurant?",
        "Do you like going to fish markets?",
        "Do you prefer to look at or eat fish?",
        "What biological features make a fish a fish?",
        "Do you have a favourite book or movie about a fish or fish in general?",
        "Do you like eating raw fish?",
        "Why do you think eating fish is good for you?",
        "Have you tried the great British delicacy fish and chips?",
        "What do you think fish dream about?",
        "Do you think all fish are edible? Would you like to try every species",
        "Why are tropical fish so colourful?",
        "What questions would you like to ask a fish?"
    ],
    "Fishing": [
        "Are you interested in fishing?",
        "Is fishing an important industry in your country?",
        "Does fishing cause harm to other aquatic life?",
        "Do you know of any areas where over-fishing is taking place?",
        "Would you like to go big game fishing?",
        "Do you think there’s a big difference between fishing and whaling?",
        "Do fishing rights cause tensions between different countries?",
        "Are there any rules for fishing?",
        "Do you like looking at TV programmes about fishing?",
        "What dangers do commercial fishermen face?",
        "Is fishing a common hobby in your country?",
        "What do you know about the history of fishing in your country?",
        "Why do you think people like fishing as a hobby?",
        "What kinds of fishing do you know about?",
        "What equipment do you need to go fishing?",
        "Are there any dangers associated with fishing?",
        "What do you think are the differences between sea and river fishing?",
        "How much skill do you think is involved in fishing?",
        "Would you like to go on a fishing holiday?",
        "What will happen to fishing if too many species of fish become endangered?"
    ],
    "Flying": [
        "What springs to mind when you hear the word ‘flying’?",
        "What are the best things about flying?",
        "Can you remember the first time you flew?",
        "Do you think flying has got better or worse over the years?",
        "Do you prefer flying or taking the train?",
        "Do you have an ‘airplane routine’ or ‘in-flight habits’ when you fly?",
        "Do you think flight attendants like flying?",
        "Which airlines would you recommend (or not) and why?",
        "How safe do you think flying is?",
        "Do you think we’ll be flying to the Moon and Mars one day?",
        "Do you like flying?",
        "What are the worst things about flying?",
        "Do you think we’ll be using flying cars one day?",
        "Would you like to learn to fly?",
        "Which is better, flying in an airplane or helicopter?",
        "What does it mean if you’re flying in your dreams?",
        "Would you like to be able to fly like a bird?",
        "Do you think the skies of the future will have traffic jams?",
        "Do you ever think or worry about the plane crashing when you’re flying somewhere?",
        "Where would you like to fly to right now?"
    ],
    "Food": [
        "What comes to mind when you hear the word ‘food’?",
        "How often do you think about food?",
        "Can you eat anything?",
        "Can you go without food for a whole day?",
        "Do you have to watch what you eat?",
        "What is your favourite breakfast, lunch and dinner?",
        "Do you think your country’s food is the best?",
        "Do you think “you are what you eat”?",
        "What do you think about canned, frozen and processed food?",
        "What kinds of international cuisine do you like?",
        "Are you fussy or particular about the food you eat?",
        "Have your favourite kinds of food changed over the years?",
        "Do you like fast food and slow food?",
        "What do you think about food additives?",
        "Do you care where the food you eat comes from?",
        "What national dishes from your country would you recommend to the world?",
        "Do you worry about the rising cost of food?",
        "Do you think the world’s food will ever run out?",
        "What do you think of genetically-modified (GM) food?",
        "Is your food bill big?"
    ],
    "Food Safety": [
        "What springs to mind when you hear the word ‘food safety’?",
        "What food safety issues do hear or read about in the news?",
        "Do you think food is becoming more or less safe to eat?",
        "Do you worry about where the food you eat comes from?",
        "Do you understand what the chemicals and E numbers are on the ingredients of food labels?",
        "How sure are you your government is in control of the quality of food for sale in your supermarkets?",
        "Do you worry about how disease-free meat is?",
        "Do you think it is safer to eat out or at home?",
        "How safe do you think fast food is?",
        "Is there any food that scientists have not warned us about?",
        "Do you ever think that the food you eat is not safe?",
        "Is it safer to grow your own food?",
        "What should chefs and restaurant staff do to make sure food is safe to eat?",
        "Do you ever eat food that has gone past the eat-by / expiry date?",
        "Have you ever had food poisoning?",
        "Is food from your country the safest?",
        "Do people in your country put dangerous things in food on supermarket shelves?",
        "How safe is safe? Do you think we worry too much?",
        "Do you think genetically modified food is 100% safe to eat?",
        "Are you happy with the quality of the water that comes out of your taps?"
    ],
    "Football / Soccer": [
        "Why do you think football is the world’s most popular sport?",
        "Why does football attract hooligans?",
        "Is there anything else that joins the world in celebration like the football World Cup?",
        "In 30 seconds, can you explain what football is?",
        "Do you think women’s football is as exciting as men’s?",
        "“Some people believe football is a matter of life and death…I can assure you it is much, much more important than that.” What do you think of the thoughts of this famous football manager?",
        "How can football authorities change the rules to make the game more exciting?",
        "What do you know about the history of football?",
        "‘Football’ or ‘soccer’ - Which word is best?",
        "Pele or Maradona – Who was better?",
        "Do you think football is a sport and an art?",
        "Do you think professional footballers get paid too much?",
        "What do you like and dislike about football?",
        "Do you think the bosses of American sports like baseball and American football are jealous of the worldwide popularity of football?",
        "Where is the world’s best football played?",
        "What do you understand by the term ‘football widow’?",
        "Do you think football will one day become the number one sport in the USA?",
        "Is there a better feeling in life than to score the winning goal for your country in football’s World Cup final?",
        "Is it a problem that so few goals are scored in football?",
        "Do you think football will be different 50 or 100 years from now?"
    ],
    "Formula One": [
        "Do you like Formula 1?",
        "Have you ever watched a race from start to finish?",
        "What do you think of the driving skill of the drivers?",
        "Would you like to be able sit next to a driver (if there was a passenger seat) during a two-hour Formula 1 race?",
        "How important is teamwork in Formula 1?",
        "Do you think Formula 1 is only for very rich people?",
        "Would you like to train to be a Formula 1 driver?",
        "Which drivers do you know and what do you think of their personalities?",
        "What do you think of Formula 1 as a business and huge marketing success?",
        "What do you think it’s like to be a Formula 1 driver?",
        "What comes to mind when you hear the word ‘Formula 1’?",
        "Who do you think is the greatest driver ever?",
        "What other car racing championships do you know and why is Formula 1 more popular than them?",
        "What do you think of tobacco company sponsorship in Formula 1?",
        "How do you think Formula 1 survived before television?",
        "Do you like reading news about Formula 1?",
        "Why do you think there are so many scandals in Formula 1?",
        "Do you think Lewis Hamilton is the next big thing in Formula 1?",
        "Which of the world’s Formula 1 Grands Prix would you like to go to?",
        "What questions would you like to ask a Formula 1 driver?"
    ],
    "France": [
        "What images spring to mind when you hear the country France?",
        "What are the good things and bad things about France?",
        "What is France famous for?",
        "What do you know about French history?",
        "What images of France do you have that are romantic?",
        "What images of France do you have that are beautiful?",
        "What has France given to the world?",
        "What has the world given to France?",
        "Is France really the most fashionable country in the world?",
        "Who are the most famous French people you know?",
        "How different is France from other European countries?",
        "Do you think France is one of the world’s most important nations?",
        "Why is France one of the top tourist destinations in the world?",
        "What do you know about France’s colonial past?",
        "Does your country have good relations with France?",
        "What do you think about French food?",
        "What is your idea of a typical French person?",
        "What things about France do you think French people are proud of?",
        "What do you know about French politics?",
        "What would you like to ask a French person about France?"
    ],
    "Freedom": [
        "What comes to mind when you hear the word ‘freedom’?",
        "Do you have as much freedom as you want in your life?",
        "Do you have as much freedom as you want in your country?",
        "In what ways does your country take away your freedom?",
        "Was there a time in your life when you had a lack of freedom?",
        "Is everyone in your country equally free?",
        "What would it be like to live where there is little freedom of choice?",
        "Do men or women have more freedom in your country?",
        "Can freedom damage a country?",
        "Where in the world do you think is the greatest freedom?",
        "What is freedom?",
        "How important is freedom for you?",
        "Would you fight for your freedom?",
        "Is working 40 hours a week closer to freedom or slavery?",
        "What does freedom feel like?",
        "Do you agree we must be free to bear arms (have a gun)?",
        "How often do you think about freedom?",
        "What kind of stories do you hear in the news related to freedom?",
        "Do you think many people misunderstand the concept of freedom?",
        "The philosopher Rousseau said “Man is born free, and everywhere he is in chains\". What do you think of this?"
    ],
    "Freedom of Speech": [
        "What is freedom of speech?",
        "How does freedom of speech improve a society?",
        "Should there be some limits on what we are free to say?",
        "Should people be free to spread hatred, incite violence and ridicule others’ religions and nations?",
        "Is pure freedom of speech is undesirable in today’s world?",
        "Should you be free to tell an enemy your country’s national secrets?",
        "Some countries forbid school teachers from introducing subjects like homosexuality in their classes. Is this denying free speech?",
        "Does the Internet open up the possibilities of totally free speech and freedom of expression?",
        "Many countries censor websites to control what their citizens can and cannot see. Is this dangerous?",
        "When do you have to be careful what you say?",
        "Is freedom of speech important?",
        "Does freedom of speech include spreading lies about people?",
        "A Danish newspaper angered the world’s Muslims by publishing cartoons of the Prophet Mohamed. Is this freedom of speech?",
        "How important is freedom of the press?",
        "\"I disapprove of what you say, but I will defend to the death your right to say it.\" (Evelyn Beatrice Hall) Do you agree with this?",
        "Are there things you’d love to talk or write about that you daren’t?",
        "Has freedom of speech suffered with the war on terrorism?",
        "Do children and teenagers also have rights to freedom of speech?",
        "What do you think “gripe sites” are?",
        "Have you ever been told to be quiet?"
    ],
    "French Fries": [
        "Do you like French fries?",
        "What’s the best thing to eat French fries with?",
        "Do you think a capital “F” is necessary – Is it ‘French fries’ or ‘french fries’?",
        "Where can you buy the best fries?",
        "What’s the best thing/condiment to put on fries – ketchup, mayonnaise, salt, vinegar, or something else?",
        "What is the perfect size of fry – length and width?",
        "Do you think it’s sad that French fries are one of the most universally eaten foods in the world?",
        "After France voted against the US invasion of Iraq, French fries in some parts of the USA became known as ‘freedom fries’. What do you think about this?",
        "What would your life be like without French fries?",
        "Should French fries be banned from school meals?",
        "What is it about French fries that make them so popular?",
        "How do you cook French fries?",
        "What do you know about the history of French fries – are they really from France?",
        "Are French fries healthy and nutritious?",
        "What is the ideal alternative to French fries?",
        "Do you think French fries are good value for money?",
        "Are French fries the best junk/fast food?",
        "When would you start allowing your children to eat French fries?",
        "What do you think of the smell of freshly cooked French fries?",
        "British people eat ‘chip butties’ – French fries sandwiches. What do you think of this culinary delight?"
    ],
    "Frequently Asked Questions": [
        "What’s for dinner?",
        "Which came first, the chicken or the egg?",
        "Why does my computer keep freezing?",
        "Chicken or beef?",
        "What is the meaning of life?",
        "Where will I be in twenty years?",
        "How do the pictures arrive on the TV screen?",
        "Why do companies have to put silly music on their answering machines?",
        "How did he/she get elected?",
        "Do you worry about your weight?",
        "Why are we here?",
        "What will the weather be like tomorrow?",
        "Why do I have to go to work?",
        "Will you marry me?",
        "Why do I pay so much tax?",
        "Are we there yet?",
        "When I die, will I go to heaven?",
        "Is it really time to wake up?",
        "Why am I studying English?",
        "Done anything interesting recently?"
    ],
    "Friends": [
        "What do friends mean to you?",
        "What makes a friend a best friend?",
        "What makes you a good friend?",
        "Is it easy for you to make friends?",
        "Do you have any particularly close friends?",
        "Do you stay in touch with all of the friends you’ve made?",
        "Which long-lost friend would you like to see again?",
        "Is there a difference in friendship between your male friends and female friends?",
        "What would life be like without friends?",
        "Do you ever worry about losing your friends?",
        "Are friends sometimes more important than family?",
        "Do you agree with the expression “a friend in need is a friend in deed”?",
        "How similar are you to your friends?",
        "Do you think you have a special understanding with your friends?",
        "At which stages of life is it easier to make friends?",
        "Are your childhood friends those you have strongest bonds with?",
        "What’s the nicest thing you’ve ever done for your friends?",
        "How often do you fall out with your friends?",
        "If you could choose any friend in the world, who would it be?",
        "What is the most valuable thing you have to offer as a friend?"
    ],
    "The Future": [
        "How often do you think about the future?",
        "What do you hope for your own future?",
        "What comes to mind when you think about your future?",
        "What fears do you have for the future?",
        "Where do you see yourself in ten, twenty and fifty years from now?",
        "What futuristic things from science fiction movies do you want to happen in real life?",
        "Barack Obama said “The best is yet to come”. Do you agree?",
        "What will the world's biggest problem be in the future?",
        "Do you believe politicians who promise a great future? Why (not)?",
        "What does the past teach us about the future?",
        "How would you like to influence the future?",
        "Does the expression “the good old days” mean that the future will probably be worse?",
        "Are you optimistic or pessimistic about the future? Why?",
        "What do you think about the future of where where you live?",
        "What are your plans for the immediate, near and far future?",
        "What would you plan for your children’s future?",
        "When you were younger, what did you think about your future?",
        "What technology will we be using in the future?",
        "What are some major changes the world will see in the future?",
        "Would you like to live 100 years in the future or the past? Why?"
    ]
}
