export default {
    "GM Food": [
        "What does GM mean?",
        "Why are scientists trying to develop GM crops?",
        "Do you think GM food is safe to eat?",
        "How do you think scientists can be sure about the safety of GM food when they’ve had so few years to test it?",
        "How might growing GM crops damage the environment?",
        "What do you think of GM tomatoes that have a stronger tomato taste?",
        "Would you be happy buying GM apples the size of melons?",
        "Do you think GM food will solve the world's food shortages?",
        "If GM crops are resistant to pests and those pests become extinct, could this seriously harm the food chain?",
        "If GM crops mix with natural crops, they could form hybrid crops and damage wildlife. Is this OK?",
        "GM food has been called ‘Frankenfood’, after Frankenstein’s monster. What do you think of this name?",
        "Some say millions of bees in the US are dying because of the small changes GM crops make to nature. What do you think of this?",
        "What do you think of GM bananas that contain vaccines against diseases?",
        "Do you think countries like Britain are right to ban GM food?",
        "If “you are what you eat,” might we change with a GM food diet?",
        "Do you think it’s important to label food as containing GM crops?",
        "Some GM food has animal genes. What do you think of this?",
        "Do you think we’ll be eating 100% GM food one day?",
        "What do you think of calorie-free GM junk food?",
        "What more would you like to know about GM food?"
    ],
    "Gambling": [
        "What comes to mind when you hear the word ‘gambling’?",
        "Do you like gambling?",
        "Do you think gambling is good or bad for gamblers?",
        "What forms of gambling are legal and illegal in your country?",
        "What do different religions say about gambling?",
        "Why don’t governments make all forms of gambling illegal?",
        "What kind of criminal activities are associated with gambling?",
        "Do you think the life of a professional gambler is a glamorous one?",
        "Have you ever won or lost a lot of money through gambling?",
        "Do you think buying lottery tickets is a form of gambling?",
        "Why do you think so many people like gambling?",
        "What damage does gambling do to society?",
        "Have you ever been to a horse race or a casino?",
        "Do you think online gambling is dangerous?",
        "What makes people so addicted to gambling?",
        "Do you know anyone who is heavily into gambling?",
        "Which part of our character makes so many of us interested in gambling?",
        "How different do you think the world would be if there was no gambling?",
        "What question would you like to ask a gambling addict?",
        "What do you think his / her answer would be and why?"
    ],
    "Gandhi": [
        "What do you know about Gandhi?",
        "Why do you think Gandhi never won the Nobel Peace Prize?",
        "What did Gandhi teach the world?",
        "Do you think India is following Gandhi’s teaching today?",
        "What kind of world would we live in if we followed Gandhi’s teaching?",
        "How many battles have been won through non-violence?",
        "Why do you think Gandhi was assassinated?",
        "Gandhi said: \"An eye for an eye makes the whole world blind.\" Do you agree with this?",
        "Gandhi believed people should lead as simple a life as possible. Do you think people can do this today?",
        "What do you think Gandhi would say about today’s war on terror?",
        "What images come to mind when you hear the name ‘Gandhi’?",
        "Is Gandhi’s message and example of peaceful protest still important today?",
        "What do you think of Gandhi?",
        "What do you think Gandhi would dislike about today’s world?",
        "Do you think he would be happy with the economic success and nuclear weapons of India?",
        "Gandhi said: \"There are many causes that I am prepared to die for but no causes that I am prepared to kill for.\" What do you think?",
        "In what ways are you like Gandhi?",
        "Are there any criticisms of Gandhi that you know of?",
        "What is Gandhi’s legacy?",
        "What questions would you like to have asked Gandhi?"
    ],
    "Gangs": [
        "Have you ever belonged to a gang?",
        "Why do people join gangs?",
        "Don’t you think people should leave gangs behind when they leave school?",
        "Were there any bad gangs at your school?",
        "Were there any good gangs at your school?",
        "Is gang violence a problem in your society?",
        "What kinds of gangs are there in your country?",
        "What kind of organized crime are gangs involved in your country?",
        "Are you more worried about hooligan gangs or gangster gangs?",
        "Do gangs in your country form on the basis of colour, religion and race?",
        "What is a gang?",
        "Do different gangs in your country fight each other?",
        "Do you think gangs exist in all countries?",
        "Are the street gangs in your country armed?",
        "What do you do when you se a gang of young people on the street?",
        "How do Hollywood movies about gangs affect young children?",
        "Are there any famous gang feuds in your town/country?",
        "What do you think happens at the yearly National Gang Conference in the USA?",
        "How long do you think gang mentality has existed?",
        "How would you describe the profile of an average gang member?"
    ],
    "Gardening": [
        "Do you like gardening?",
        "What is it about gardening that makes many people love it?",
        "Is gardening a hobby for young or old people?",
        "Do you need a big garden to enjoy gardening, or can someone living in an apartment also do a bit of gardening?",
        "Do you think gardening is an expensive hobby?",
        "What do you think of the idea of everyone having a vegetable and herb garden to help the world’s food problems?",
        "Do you like looking at gardening shows on TV and reading gardening magazines?",
        "Do you know anyone who is crazy about gardening?",
        "What kind of equipment do you need to have gardening as a hobby?",
        "Do you think gardening is the same all over the world?",
        "What springs to mind when you hear the word ‘gardening’?",
        "Would you like a job as a gardener, or as a landscape architect?",
        "What do you think market gardening is?",
        "Do you like walking around gardens?",
        "Do you think the ‘English country garden’ is the best?",
        "Are gardens good for the environment?",
        "What do you know / think about Japanese Zen gardens?",
        "Do you have green fingers (UK) green thumbs (USA)?",
        "Do you think all schools should have a classroom garden and a kitchen garden?",
        "What dangers are involved with gardening?"
    ],
    "Garlic": [
        "Why do vampires, especially Dracula, hate garlic?",
        "Do you know the names for the different parts of garlic?",
        "Do you know of any potential side effects of garlic?",
        "How do you like garlic – crushed, sliced, diced or whole?",
        "What food / dishes do you know that have ‘garlic’ in the title?",
        "Cervantes wrote in ‘Don Quixote’: \"Do not eat garlic or onions; for their smell will reveal that you are a peasant.\" What do you think of this quote?",
        "What do you think of the smell of garlic being cooked in the kitchen?",
        "Which countries do you think value garlic the most?",
        "What products do you have at home with garlic in them?",
        "What is the best way to avoid having garlic breath?",
        "What comes to mind when you hear the word ‘garlic’?",
        "How important is garlic in your country’s cooking / cuisine?",
        "Do you like garlic?",
        "What is your favourite food that has garlic in it?",
        "What do you know about the health / medicinal benefits of garlic?",
        "Do you like the smell of garlic?",
        "Is garlic used for any customs or rituals in your country?",
        "What do you know about how to grow garlic or how garlic grows?",
        "How would you describe the taste of garlic to someone who had never eaten it?",
        "What are your thoughts on another person’s (or your own) garlic breath?"
    ],
    "Gay Rights": [
        "What do you understand by the term ‘gay rights’?",
        "Are there gay rights movements in your country?",
        "Do you think ‘gay rights’ refers more to men or women?",
        "Do you think the term ‘LGBT rights’ (lesbian, gay, bisexual and transgender people) is a better description?",
        "Do people freely talk about gay rights in your country without feeling afraid?",
        "Are there laws in your country that discriminate against LGBT people?",
        "Do you think gay people should be able to hold high positions in religions?",
        "What issues that gays have to deal with are different from those lesbians have to deal with?",
        "What do you think of same-sex relations and the raising of children?",
        "Is marriage a relationship between only a man and a woman?",
        "Do you think the issue of gay rights will disappear in the next few decades?",
        "Which nationalities do you think are most homophobic?",
        "In English, to ‘come out of the closet’ means to let people know you are gay. What do you say in your language for this?",
        "Is or was homosexuality a taboo subject in your country?",
        "What does the leader of your country say about gay rights?",
        "What do you think is the number one issue for gay rights groups?",
        "Why do you think some people are afraid of gay people?",
        "What jobs do you think discriminate most against gays?",
        "Do you always read articles about gay rights in newspapers?",
        "What law about gay rights would you like your government to pass?"
    ],
    "Gender": [
        "Are you happy being the gender you are?",
        "What would you like to do that you can’t do now if you changed gender?",
        "What do you think people study in gender studies classes?",
        "Are men and women very different?",
        "How are the words ‘gender’ and ‘sex’ used differently in English?",
        "Do you think men and women have different brains?",
        "Are there different laws in your country depending on your gender?",
        "Can people in your country change their gender under the law?",
        "Why do you think some people want to change their legal gender?",
        "Why are Gods generally seen as being men?",
        "Do men and women live in different cultures?",
        "Is it OK for boys to play with girls’ toys and vice versa?",
        "Are men or women bigger risk takers? Why do you think so",
        "Why do you think men are more aggressive than women?",
        "Are there differences in the ways men and women communicate?",
        "Do you think men or women are happier?",
        "Are their different barriers for men and women at work?",
        "Are gender roles changing in your country?",
        "Some feminists believe the ‘man’ in ‘human’ or the ‘he’ in ‘she’, ‘them’ and ‘they’ are sexist. What do you think?",
        "Should jobs have ‘-ess’ attached to the name so people know they are done by women (e.g. actress, authoress, hostess…)?"
    ],
    "Genetic Engineering": [
        "What is genetic engineering?",
        "Do you think genetic engineering is a good thing?",
        "What are people worried about who oppose genetic engineering?",
        "Do you worry about eating GM (genetically modified) food?",
        "Do you think genetically modified food could harm the ecosystems of the areas in which they grow?",
        "What do you know / think about the Oncomouse – the mouse specially modified to help in cancer research?",
        "Do you think it’s essential to modify genes to create new medicines?",
        "Scientists can genetically engineer fruit to contain vaccines at a very low cost – Is this a good idea?",
        "What do you think about cloning?",
        "Would you like to see a cloned version of yourself?",
        "What do you know about genes?",
        "Do you think genetic engineering is playing God and that we should leave life as it was created?",
        "What do you think of the idea of genetically engineering new bodily organs to replace yours when you are old?",
        "What do you think would happen if a GM crop or animal started causing major harm to the environment / us?",
        "Genetic engineering might allow parents to ‘design’ their children before their birth – What do you think of this?",
        "Should genetic engineering go ahead to eliminate human flaws, such as violence, jealousy, hate, etc?",
        "What if scientists create a monster human?",
        "What do you understand by the term ‘genetic aristocracy’?",
        "If someone’s genes are changed a lot, are they the same person?",
        "Does the government have the right to limit how far we modify ourselves?"
    ],
    "Genocide": [
        "What images spring to mind when you hear the word ‘genocide’?",
        "What does genocide mean? – Do you know how the word is made?",
        "How can genocide happen?",
        "What genocides do you know of in the past century?",
        "Why is genocide still happening in the world?",
        "What are the differences between genocide and crimes against humanity?",
        "What is the most appropriate punishment for someone involved in genocide?",
        "Is there anything in your country’s history that was genocide, or could be describes as genocide?",
        "What do you think of the term ‘ethnic cleansing’?",
        "What do you think of countries that deny their violent history and avoid putting terrible massacres in school history books?",
        "What do you think of those who deny the Holocaust ever happened?",
        "Do you think the destruction of Hiroshima and Nagasaki was genocide?",
        "Why is African slavery rarely regarded as genocide?",
        "It seems the world doesn’t act when genocide happens in Africa. Do you agree?",
        "Do you think genocide will ever stop?",
        "The International Criminal Court was set up to prosecute war criminals. The USA and China are among a few countries who refuse to allow their citizens to be tried in it. What do you think of this?",
        "What are the signs that genocide might happen in the future?",
        "After Rwanda, politicians swore genocide would never happen again. We had Bosnia and now have Darfur. What went wrong?",
        "Do you think there should be an International Genocide Day?",
        "What does genocide do to a country once it has finished?"
    ],
    "Geography": [
        "Do you like geography?",
        "Do you know a lot about the geography of your country?",
        "What were your geography teachers like?",
        "What do you think the difference is between physical geography and human geography?",
        "Is your general knowledge of geography good?",
        "What do you think it would be like to be a geographer?",
        "Do you like looking at maps and atlases?",
        "How has the world’s geography changed over the years?",
        "Which of these areas of geography would you choose to study – climatology, oceanography or demography?",
        "What does the word geography mean?",
        "Were you good at geography at school?",
        "What do you study in geography?",
        "Which part of the world do you think has the most interesting geography?",
        "How important is it to study geography at school?",
        "What are the most important things about geography that children need to know?",
        "What jobs can you do if you have a geography degree?",
        "What’s the difference between a city and a town?",
        "Do you like reading geography books and watching geography shows on TV?",
        "What is the most interesting area of geography for you?",
        "How well do you know your local geography – the area near your house?"
    ],
    "George W Bush": [
        "What do you think of George W Bush?",
        "What do you think the rest of the world thinks of him?",
        "What are George W Bush’s strong points?",
        "What are his weak points?",
        "Do you think George W Bush is a good speaker?",
        "What do you think when you see him on TV?",
        "Do you think George W Bush has been good for the world?",
        "Some think George W Bush is a war criminal. What do you think?",
        "Do you think he was right to invade Afghanistan and Iraq?",
        "What image of George W Bush sticks in your mind most? Why?",
        "Is George W Bush a good US President?",
        "What adjectives would you use to describe George W Bush?",
        "What do you know about George W Bush’s life before he became President?",
        "What mistakes do you think he has made?",
        "If he weren’t President, what job would he be best suited to?",
        "Do you know what ‘Bushisms’ are and do you know any?",
        "Bush said: \"I know the human being and fish can coexist peacefully.” What do you think he meant by this?",
        "What do you think George W Bush thinks of other world leaders?",
        "What are Bush’s biggest successes?",
        "What questions would you like to ask George W Bush?"
    ],
    "Georgia": [
        "What images spring to mind when you hear the country Georgia?",
        "What are the good things and bad things about Georgia?",
        "What is Georgia most famous for?",
        "What do you know about Georgian history?",
        "What are the differences between Georgia and your country?",
        "What do you think about Georgian people?",
        "What has Georgia given to the world?",
        "Would you like to visit Georgia, or live there?",
        "What do you know about the geography of Georgia?",
        "Who are the most famous Georgian people you know?",
        "How different is Georgia from the other former Soviet Union countries?",
        "What was the last news story you heard about Georgia?",
        "What do you think Georgia’s neighbours think of it?",
        "What do you think Georgia will be like 50 years from now?",
        "Does your country have good relations with Georgia?",
        "What could you do on a holiday in Georgia?",
        "What is your idea of a typical Georgian person?",
        "What things about Georgia do you think Georgian people are proud of?",
        "What do you know about Georgia’s culture?",
        "What would you like to ask a Georgian person about Georgia?"
    ],
    "Germany": [
        "What images spring to mind when you hear the country Germany?",
        "What are the good things and bad things about Germany?",
        "What is Germany famous for?",
        "What do you know about German history?",
        "What images of Germany do you have that are beautiful?",
        "What do you think of German cars?",
        "What has Germany given to the world?",
        "Would you like to visit Germany, or live there?",
        "Is German an important language?",
        "Who are the most famous German people you know?",
        "How different is Germany from other European countries?",
        "Do you think Germany is one of the world’s most important nations?",
        "Why is Germany one of the top tourist destinations in the world?",
        "What do you know about Germany’s past?",
        "Does your country have good relations with Germany?",
        "What do you think about German food and beer?",
        "What is your idea of a typical German person?",
        "What things about Germany do you think German people are proud of?",
        "What do you know about Germany politics?",
        "What would you like to ask a German person about Germany?"
    ],
    "Global Warming": [
        "What comes to mind when you think of global warming?",
        "Do you think human activity is responsible for global warming?",
        "When did you first become aware of global warming?",
        "Do you think all countries are taking global warming seriously?",
        "What most concerns you about global warming?",
        "Do you think you have already experienced the effects of global warming?",
        "How will global warming change our lives?",
        "Do you think global warming could destroy us all?",
        "Is your government doing enough to combat global warming?",
        "What single action should the world take to reduce the dangers of global warming?",
        "What’s the difference between global warming and climate change?",
        "What do you do in your daily life that might increase global warming?",
        "Have you made changes to your life to reduce global warming?",
        "What do you know about the science behind global warming?",
        "How do you think global warming will change the world over the next century?",
        "Do you know more about global warming than younger/older people?",
        "Does your government provide enough education on the effects of global warming?",
        "Which country makes you angriest when you think about global warming?",
        "Do you think China and India should slow their growth down?",
        "How did global warming happen without us noticing sooner?"
    ],
    "Globalization": [
        "What images spring to mind when you hear the word ‘globalization’?",
        "What are the good things and bad things about globalization?",
        "How long has the term ‘globalization’ been around?",
        "Do you think it’s possible to ignore globalization?",
        "How has globalization affected your life?",
        "Is globalization good for the world?",
        "What will globalization look like fifty years from now?",
        "Do you think globalization will make us all the same in the future?",
        "Which countries do you think like or hate globalization most?",
        "What concept do you think will come after globalization?",
        "What is globalization?",
        "Could globalization have happened without the Internet?",
        "How would your life be different if globalization hadn’t happened?",
        "What do you think of the concept of a global village?",
        "Has globalization improved people’s lives?",
        "Do you think globalization could end in a world with just one giant country?",
        "What do you think indigenous tribes think about globalization?",
        "Can you measure globalization?",
        "Do you think globalization will reduce or increase the poverty gap?",
        "How has popular culture added to globalization?"
    ],
    "God": [
        "Do you believe in God?",
        "Why do different religions have different gods?",
        "What do you think God thinks of the way we live?",
        "Is God the creator and ruler of the whole universe?",
        "What does God look like?",
        "Why are there so many people who do not believe in God?",
        "Why is God always seen as a white man in paintings and drawings?",
        "Is there a difference in how Christians, Muslims and Jews see God?",
        "Why do people who believe in God fight in wars?",
        " \"I believe in God, only I spell it 'Nature'.\" What do you think of this quote by Frank Lloyd Wright?",
        "If Christians, Muslims and Jews all believe in the same God, why is there so much fighting among them?",
        "Is there any proof that God exists?",
        "\"No God, no peace. Know God, know peace.\"  What do you think of this quote?",
        "Why did God create a huge universe when all that is important is here on Earth?",
        "Why did God create us?",
        "Why does God let innocent people suffer and evil people prosper?",
        "Does God love everyone the same?",
        "Why doesn’t God answer everyone’s prayers?",
        "What question would you like to ask God?",
        "If a person believes that God can protect them from natural disasters, do you think they also believe that God caused those disasters in the first place?"
    ],
    "Gold": [
        "Where does gold come from?",
        "Did you like the metal?",
        "What makes the metal so special and sought after?",
        "Do you have a lot of gold jewelry (USA) / jewellery (UK)?",
        "Would you consider buying gold as an investment instead of things like shares or property?",
        "Do you like wearing lots of gold jewelry (USA) / jewellery (UK)?",
        "Does gold have a special place in your country’s culture or customs?",
        "What do you own that is made of gold?",
        "Would you like to go panning for gold?",
        "Do you know what gold leaf is and what it is used for?",
        "What comes to mind when you hear the word ‘gold’?",
        "How do you think gold is made into things?",
        "Does your country win lots of gold medals at the Olympics or other sporting competitions?",
        "What does ‘gold plated’ mean and why are some things plated with gold?",
        "Do you ever check gold prices?",
        "Have you ever been to a gold market?",
        "What would you do with a gold ingot if you won one in a competition?",
        "What do you know about the gold carat system?",
        "What do you think it’s like working in a gold mine?",
        "What do you know about black gold?"
    ],
    "Google": [
        "What do you know about the history of Google?",
        "How often do you use Google?",
        "How do you think Google compares with other search engines?",
        "Do you have any complaints about Google?",
        "What other services do you think Google should provide?",
        "What would life be like without Google (or other search engines)?",
        "Would you like to work for Google?",
        "How did Google come to be one of the biggest companies in the world in such a short space of time?",
        "How do you think Google’s owners feel about their success?",
        "What does the verb ‘Google’ mean?",
        "What do you think of the name Google as a company name?",
        "What do you know about the different products and services Google has?",
        "Are you always happy with the searches you make on Google?",
        "What do you use Google (or other search engines) for?",
        "What do you think of Google’s mission statement to “organize the world's information and make it universally accessible and useful\"?",
        "Have you ever used Google Earth?",
        "What do you think of Google’s slogan: “Don’t Be Evil”?",
        "Google employees are encouraged to spend 20% of their work time on projects that interest them. Is this a good idea?",
        "What do you know about these companies that Google bought – Blogger, YouTube and DoubleClick?",
        "Do you use Google Alerts or Google’s Desktop Toolbar?"
    ],
    "Gossip": [
        "What is gossip?",
        "Have you ever been the victim of gossip?",
        "Are you a gossip?",
        "How often do you hear gossip?",
        "Are you interested in celebrity gossip?",
        "Do you like to know all the gossip about your friends and neighbours?",
        "Who is the biggest gossip you know?",
        "How quickly does gossip spread in your school / workplace?",
        "What are the most common subjects of gossip?",
        "Is there any gossip about your teacher?",
        "Why do people gossip or like gossip?",
        "Have you ever started any gossip?",
        "Do you read gossip columns in magazines? Why are these so popular",
        "Do you think it’s right that gossip columnists can make a lot of money writing bad things about people that may not be true?",
        "What is the most malicious piece of gossip you’ve ever heard?",
        "How do you feel if people gossip about you?",
        "What’s the difference between gossip and a rumour?",
        "Eleanor Roosevelt said: “Great minds discuss ideas; average minds discuss events; small minds discuss people.” Is this true?",
        "Why do you think gossip is sometimes ‘hot’ and sometimes ‘juicy’?",
        "Do you think people who gossip lead sad lives?"
    ],
    "Government": [
        "What images spring to mind when you hear the word ‘government’?",
        "What does a government actually do and what should it do?",
        "Are you happy with the government of your country?",
        "What do you think of the governments in America and China?",
        "Would you like to work for the government?",
        "Do you think there is a world government that is not corrupt?",
        "Would you prefer to work in local or national government?",
        "Why is there so much corruption in many governments?",
        "Should government leaders be paid more company CEOs?",
        "Ronald Regan said: “Government is not the solution to our problem. Government is the problem.” Do you agree with him?",
        "What successes has your government made?",
        "Do you follow the ins and outs of your government’s workings?",
        "If you wrote a letter to your government, what would you write about?",
        "Do you think there should be a world government?",
        "Do you think a government is essential in a democracy?",
        "What are the alternatives to governments?",
        "What would your first step be if you were head of your government?",
        "What would you like to change about your government?",
        "Do you think a government can ever make everyone happy?",
        "What do you think of this line from the 2006 movie ‘V for Vendetta’? “People should not be afraid of their government. Governments should be afraid of their people.”"
    ],
    "Grammar": [
        "Do you like studying grammar?",
        "Do you think grammar is the most important thing to learn in English?",
        "What is the most difficult part of English grammar?",
        "Which is more difficult, English grammar or your own language’s grammar?",
        "What is the best way to learn grammar?",
        "Do you have a favorite grammar book?",
        "How do you like to learn grammar in class?",
        "What are your grammar successes?",
        "Do you think playing grammar games is an effective way to learn?",
        "Do you think students should keep a special grammar notebook?",
        "What grammar websites would you recommend to other students?",
        "How do you think many people can learn a language without learning grammar?",
        "What grammar question would you really like answering now?",
        "Do you think you are good at explaining English grammar rules to other learners?",
        "Is the grammar of speech different from the grammar of writing?",
        "Have you ever met a native English speaker with poor grammar?",
        "Have all your English teachers been good at teaching grammar?",
        "What area of English grammar do you think is easiest to learn?",
        "How often have you said you hate grammar?",
        "Do you think that one day you’ll be able to download grammar from your computer into your brain and have no grammar homework?"
    ],
    "Great Britain": [
        "Is Britain great?",
        "What is the difference between Great Britain, England and the United Kingdom?",
        "What do you know about British food and weather?",
        "What would you like to do and see in Britain on a three-week holiday?",
        "How do you think British people would describe their country?",
        "Do you think Britain has too much political power in the world?",
        "Would you like to live in Great Britain?",
        "What parts of British culture are popular in your country?",
        "Does your country have good relations with Britain?",
        "What do you think of when you see the Union Jack flag?",
        "What do you know about Great Britain?",
        "How important is Britain in the world?",
        "How did Britain lose its empire?",
        "What has Great Britain contributed to the world?",
        "Would you like to speak with a British accent?",
        "Who is the most famous British person ever?",
        "What is Britain most famous for?",
        "What mistakes has Great Britain made?",
        "Do you like British fashion and music?",
        "What do you think of the British Queen?"
    ],
    "Greece": [
        "What images spring to mind when you hear the country Greece?",
        "What are the good things and bad things about Greece?",
        "What is Greece famous for?",
        "What do you know about Greek history?",
        "What images of Greece do you have that are romantic?",
        "What importance has Greece played in world history?",
        "What has Greece given to the world?",
        "Would you like to visit Greece or live there?",
        "Is Greece the most historic country in the world?",
        "Who are the most famous Greek people you know?",
        "How different is Greece from other European countries?",
        "Do you think Greece is one of the world’s most important nations?",
        "Why is Greece one of the top tourist destinations in the world?",
        "What do you know about the ancient Greek gods and mythology?",
        "Does your country have good relations with Greece?",
        "What do you think about Greek food?",
        "What is your idea of a typical Greek person?",
        "What things about Greece do you think Greek people are proud of?",
        "What do you know about Greek politics?",
        "What would you like to ask a Greek person about Greece?"
    ],
    "Gun Control": [
        "Do you think people need guns?",
        "How many guns are there in your society?",
        "Is there a lot of gun crime in your country?",
        "Switzerland has a higher rate of gun ownership than the USA, but hardly any gun crime. Why do you think this is?",
        "Do you think it’s a person’s right to own a gun?",
        "Is it easy or difficult to get a gun in your country?",
        "What checks should there be made before someone can buy a gun?",
        "In Japan there are strict gun control laws and so there is very little gun crime. Should all countries follow Japan to lower gun crime?",
        "Do you think people should be allowed to have guns to defend themselves in their home?",
        "Martin Luther King said: \"By our readiness to allow arms to be purchased at will and fired at whim...we have created an atmosphere in which violence and hatred have become popular pastimes.\" Do you agree with him?",
        "Do you think violent movies encourage the use of guns?",
        "People don’t need guns because the police will protect you. Do you agree with this statement?",
        "Do you think chemical sprays can replace guns for self defence?",
        "Guns don’t kill people, people do. What do you think of this?",
        "Do you think airline pilots should be allowed to carry guns?",
        "Do you think everyone will have access to a gun one day?",
        "Don’t you think guns should be banned to stop school shootings?",
        "Do you think making people have gun licenses would reduce crime?",
        "How can people have a gun in the house when they have children?",
        "Would you have a gun if you had the choice?"
    ]
}
