export default {
    "Taiwan": [
        "What images spring to mind when you hear the name “Taiwan’?",
        "What are the good things and bad things about Taiwan?",
        "What is Taiwan most famous for?",
        "What do you know about Taiwanese history?",
        "What are the differences between Taiwan and your country?",
        "What do you think about Taiwanese people?",
        "What has Taiwan given to the world?",
        "Would you like to visit Taiwan, or live there?",
        "What do you know about the geography of Taiwan?",
        "Who are the most famous Taiwanese people you know?",
        "How different is Taiwan from other Asian countries?",
        "What was the last news story you heard about Taiwan?",
        "What do you think Taiwan’s neighbours think of it?",
        "What do you think Taiwan will be like 50 years from now?",
        "Does your country have good relations with Taiwan?",
        "What could you do on a holiday in Taiwan?",
        "What is your idea of a typical Taiwanese person?",
        "What things about Taiwan do you think Taiwanese are proud of?",
        "What do you know about Taiwan’s culture?",
        "What would you like to ask a Taiwanese person about Taiwan?"
    ],
    "Tax": [
        "What images spring to mind when you hear the word ‘tax’?",
        "Do you think paying tax is a good or bad thing?",
        "What would happen in your country if everyone stopped paying tax?",
        "Do you know what taxes are spent on in your country?",
        "Would you like to move to a country where there are no taxes?",
        "Is tax an important issue at election time?",
        "What do you think of sales / consumption tax put on the things you buy?",
        "Would you like to be able to choose how your taxes are spent?",
        "Would you look for ways to avoid paying tax?",
        "How do the tax rates in your country compare with those in neighbouring countries?",
        "Is everything taxed in your country?",
        "Do you agree with the 10-20% tax hotels and restaurants put on bills?",
        "What do you think of having to pay inheritance tax on the money left to you by people who have died?",
        "Would you pay higher taxes if you knew the tax revenue would go towards climate change projects or reducing world poverty, etc?",
        "What changes would you like to see in your country’s tax system?",
        "Is tax evasion a big problem in your country?",
        "Should poor people be exempt from paying tax (i.e. they don’t have to pay)?",
        "What goods or services do you think should be taxed more heavily, and which should not be taxed at all?",
        "Do you think taxes will be different in the future?",
        "What taxes do you think are the most unfair?"
    ],
    "Taxi": [
        "What comes to mind when you hear the word ‘taxi’?",
        "How often do you take a taxi?",
        "Do you have any ‘taxi stories’?",
        "Are there enough taxi cabs in your town?",
        "What do you think of taxis in other countries?",
        "Do you think it’s always safe to use a taxi?",
        "Are taxis good value for money?",
        "Which do you like better, New York’s yellow cabs or London’s black cabs?",
        "How do you flag (U.S.) or hail (U.K.) a taxi in your country?",
        "What would happen in your town if all the taxis disappeared?",
        "Do you like taxis?",
        "Do you think taxi drivers should know every road?",
        "What’s the worst taxi drive you’ve ever had?",
        "Do you think a taxi driver’s job is dangerous?",
        "Why do taxi driver’s always talk about the weather?",
        "Do you always make sure the meter is on in the taxi?",
        "Have you ever taken a taxi that took the long way round?",
        "What kind of license do you think taxi drivers should have?",
        "Do you think taxis should have ‘in-taxi’ entertainment?",
        "Is it better to sit in the back of the taxi or in the passenger seat?"
    ],
    "Teaching": [
        "What images spring to mind when you hear the word ‘teaching’?",
        "Do you think teaching is easy?",
        "What are you good at teaching people?",
        "What skills do teachers need?",
        "Are all your teachers good at teaching their subject?",
        "Do you think teachers know everything about their subject?",
        "What do you think are the good and bad things about teaching?",
        "Is teaching dangerous in schools in your country?",
        "What is the best way of teaching English?",
        "John Sculley said: \"We expect teachers to handle teenage pregnancy, substance abuse, and the failings of the family.  Then we expect them to educate our children.\" Is this true for your country?",
        "Who is/was your favourite teacher and why?",
        "Is teaching or learning the most important activity in the classroom?",
        "Do you prefer mayonnaise or salad dressing on salads?",
        "Do you think a career in teaching will make you rich?",
        "Do you think teaching at elementary school, high school, or university would be best?",
        "Do you think technology is a good teaching tool?",
        "What teaching materials do you want your teachers to use?",
        "How will teaching change in the future?",
        "Do you think schools do a good job of teaching children?",
        "Gail Godwin said: \"Good teaching is one-quarter preparation and three-quarters theatre.\" Do you agree with her?"
    ],
    "Tears": [
        "What images spring to mind when you hear the word ‘tears’?",
        "Are tears different for men and women?",
        "What are the functions of tears?",
        "Have you ever burst into tears in public?",
        "When do tears well up in your eyes?",
        "Have you ever had tears of laughter and tears of joy?",
        "What childhood activities always ended in tears?",
        "When was the last time you bit your lip and fought back the tears?",
        "Antoine de Saint-Exupery said: \"It is such a secret place, the land of tears.\" Do you agree?",
        "Someone once said: \"Tears are words the heart can't express.\" Do you agree?",
        "When was the last time you cried?",
        "Do you like children’s tears?",
        "Are there different kinds of tears?",
        "Have you ever run out of tears?",
        "Can you easily hold back your tears?",
        "What images, situations or people can always reduce you to tears?",
        "Have you ever been bored to tears? Is this the beginning of being bored silly, then bored senseless, then being bored to death?",
        "Has a book or movie ever moved you to tears?",
        "Someone once said: \"A woman wears her tears like jewelry.\" What does this mean? Do you agree with?",
        "Someone once said: \"Our eyes need to be washed by our tears once in a while, so that we can see life with a clearer view again.\" Do you agree?"
    ],
    "Technology": [
        "What springs to mind when you hear the word ‘technology’?",
        "Is technology a good or a bad thing?",
        "What new technology could you not live without?",
        "Do you like reading about technology?",
        "Do you like using technology to learn?",
        "What do you think very old people think of modern technology?",
        "How has technology changed society?",
        "Has technology made us more impatient?",
        "Max Frisch said: \"Technology is the knack of arranging the world so that we don't have to experience it.\" Do you agree with him?",
        "Mark Kennedy said: \"All of the biggest technological inventions created by man - the airplane, the automobile, the computer - say little about his intelligence, but speak volumes about his laziness.\" Do you agree?",
        "What do you think of today’s technology?",
        "What do you think of tomorrow’s technology?",
        "Do you think we’ve become obsessed with technology?",
        "Do you always trust technology?",
        "Does technology ever let you down?",
        "What things would you never let technology replace?",
        "Has technology made our lives better than our grandparents’ lives?",
        "What technology is dangerous?",
        "Frank Lloyd Wright said: \"If it [technology] keeps up, man will waste away all his limbs but the push-button finger.\" What does this mean? Do you like this quote?",
        "Alan M. Eddison said: \"Modern technology... Owes ecology... An apology.\" What does this mean? Do you agree?"
    ],
    "Teddy Bears": [
        "What images spring to mind when you hear the word ‘teddy bear’?",
        "How important are teddy bears?",
        "Why do children love teddy bears?",
        "Do teddy bears make good Valentine gifts?",
        "What do you know about the history of teddy bears?",
        "Did your teddy bear have a name?",
        "How old is too old to sleep with a teddy bear?",
        "Would children be different without teddy bears?",
        "Can you name any famous teddy bears?",
        "Woody Allen said: \"I don't think my parents liked me. They put a live teddy bear in my crib.\" What do you think of this quote?",
        "Do you like teddy bears?",
        "What was your favourite teddy bear when you were a child?",
        "What do you think of Disney teddy bears?",
        "Do you think it’s strange that shops are so full of teddy bears?",
        "What would the world be like without teddy bears?",
        "What would teddy bears tell us if they could speak?",
        "Do you think a teddy bear in the rubbish is a sad sight?",
        "Can you be cruel to a teddy bear?",
        "Do you think teddy bears will be with us forever?",
        "Someone once said: \"Everything in life I share, except of course my teddy bear!\" Can you relate to this quote?"
    ],
    "Teenagers": [
        "What images spring to mind when you hear the word ‘teenager’?",
        "Do / Did you like being a teenager?",
        "Do you like teenagers?",
        "What useful things do teenagers do?",
        "Are teenagers the same all over the world?",
        "Would you like your children to do the same things you did when you were a teenager?",
        "Are teenage years difficult?",
        "What do adults dislike about teenagers?",
        "An Italian proverb says: \"Little children, headache; big children, heartache.\" Do you think this is true?",
        "Fran Lebowitz said: \"As a teenager you are at the last stage in your life when you will be happy to hear that the phone is for you.\" What does this mean? Do you think it's true?",
        "What would the world be like if it was run by teenagers?",
        "What stages do teenagers go through in each of their teen years?",
        "Do you think parents look forward to their cute little children becoming teenagers?",
        "Why is it that teenagers want to rebel so much?",
        "What are the best and worst things about being a teenager?",
        "Do parents really understand teenagers?",
        "Do you think today’s teens are the same as teenagers 50 years ago?",
        "What impact do teenagers have on society?",
        "Someone once said: \"It's difficult to decide whether growing pains are something teenagers have - or are.\" What do you think?",
        "William Galvin said: \"Mother Nature is kind. She gives us twelve years to develop a love for our children before turning them into teenagers.\" Do you like this quote?"
    ],
    "Teeth": [
        "What images spring to mind when you hear the word ‘teeth’?",
        "What do you do to you look after your teeth?",
        "Is it important to have straight white teeth?",
        "How would you feel about having false teeth (dentures)?",
        "Why are wisdom teeth called wisdom teeth?",
        "Have you ever had a really bad toothache?",
        "When was the last time you gritted your teeth?",
        "Have you ever felt like someone kicked you in the teeth?",
        "Do you go through a ritual every time you brush your teeth?",
        "Someone once said: \"Too many of today's children have straight teeth and crooked morals.\" What does this mean? Do you think it's true?",
        "Do you like your teeth?",
        "When you were a child, what did you do with your milk teeth after they fell out?",
        "Do you worry about tooth decay?",
        "Do you have a sweet tooth?",
        "What do you think when you lose a tooth or have to have one pulled out at the dentist?",
        "What is a tooth fairy and how much money do they leave?",
        "Do you have many fillings?",
        "Do you think people in the future will have very healthy teeth?",
        "What do you think of the idea of painted teeth?",
        "What do you do when you get food stuck between your teeth?"
    ],
    "Telephones": [
        "What comes to mind when you hear the word ‘telephone’?",
        "How important is the telephone to you?",
        "What would life be like with no telephone?",
        "Do you ever talk in English on the phone?",
        "How many calls do you make every day? How many of these are necessary?",
        "Who comes to your mind first when your telephone rings?",
        "Have you ever received any prank calls?",
        "Do you think Internet telephone will replace the current telephone system one day?",
        "What’s the best and worst news you’ve received over the phone?",
        "Chuck Palahniuk said: \"People use a telephone because they hate being close together and they are scared of being alone.\" Do you agree?",
        "Do you like using the telephone?",
        "What was your longest telephone call?",
        "What is the most annoying thing about using the phone?",
        "Do you worry about your telephone bill?",
        "Can you remember life before the mobile phone?",
        "Do you think you use the telephone too much?",
        "Do you like listening to other people’s telephone conversations?",
        "Have you ever got really angry with someone over the telephone?",
        "Do men or women talk more on the phone? Why?",
        "Ogden Nash said: \"Middle age is when you're sitting at home on a Saturday night and the telephone rings and you hope it isn't for you.\" Do you agree?"
    ],
    "Television": [
        "What images spring to mind when you hear the word ‘television’?",
        "What are the good things and bad things about television?",
        "What would life be like without television?",
        "How much television do you watch every day?",
        "Are you happy with the programmes on TV?",
        "Does television kill conversation in your family?",
        "Does violence on television make young people more violent?",
        "How will television change over the next few decades?",
        "Someone said: \"If it weren't for the fact that the TV set and the refrigerator are so far apart, some of us wouldn't get any exercise at all.\" Do you think this is true",
        "Someone once said: \"I wish there were a knob on the TV to turn up the intelligence.\" Do you think so too?",
        "What are your earliest memories of television?",
        "Is television important?",
        "How would society be different if TV had never been invented?",
        "What could you do for three hours without watching television?",
        "What is there too much of on television?",
        "How long can you sit watching TV?",
        "What do you think of television shows from other countries?",
        "Would you like a television in every room of your house?",
        "Frank Lloyd Wright said: \"Television is chewing gum for the eyes.\" What did he mean. Do you think so too?",
        "Donna Gephart said: \"Today, watching television often means fighting, violence and foul language - and that's just deciding who gets to hold the remote control.\" Do you think so too?"
    ],
    "Temperature": [
        "What springs to mind when you hear the word ‘temperature’?",
        "What is the perfect weather temperature for you?",
        "Do you like to experience extreme temperatures?",
        "What do you think of the temperatures in your country?",
        "How does a change in temperature affect your feelings?",
        "What do you think of today’s temperature?",
        "Do you worry about a change in temperature because of global warming?",
        "What is the hottest temperature you’ve ever experienced?",
        "Do you always use the temperature control in your house / office / car…?",
        "Do you know your average body temperature?",
        "Do you take an interest in what the temperature will be like in the days ahead?",
        "Do you ever check the temperature in your house?",
        "Have you ever had a very high temperature?",
        "What are the record temperatures reached in your country?",
        "Are you a cold, cool, warm or hot temperature person?",
        "What do you think will happen to the world’s temperature over the next few decades?",
        "Do you know people who turn on the air-con or heater when you think the temperature is great?",
        "What do you do when you have a high temperature?",
        "What makes your blood boil?",
        "What food or drink do you insist must be at the perfect temperature before eating or drinking?"
    ],
    "Tennis": [
        "What comes to mind when you hear the word ‘tennis’?",
        "Do you like watching tennis?",
        "Do you think men’s or women’s tennis is best?",
        "What do you think of the clothes tennis stars wear on court?",
        "Why do you think ‘zero’ in tennis is ‘love’?",
        "Which do you like better – singles or doubles?",
        "What is the world’s greatest tennis tournament?",
        "Do you think tennis stars get paid too much?",
        "Does your country have a strong tradition of playing tennis?",
        "Who is the greatest ever men’s and ladies’ tennis player?",
        "Are you good at tennis?",
        "Is tennis usually only for rich people?",
        "Why do you think tennis balls are yellow?",
        "Do you think the rules of tennis are easy of difficult?",
        "Would you prefer to watch a tennis game on TV or at the court?",
        "Should players be banned from grunting in tennis?",
        "What don’t British players do so well, seeing they invented the game?",
        "Do you think the top women’s player could ever beat a men’s player ranked towards the bottom of the world rankings?",
        "Is tennis the world’s most polite game?",
        "Do you think tennis will be different 100 years from now?"
    ],
    "Terrorism": [
        "What images spring to mind when you hear the word ‘terrorism’?",
        "Has your life changed in any way due to terrorism?",
        "Is the name “war on terror” a correct name?",
        "If a country repeatedly kills innocent civilians while trying to kill terrorists, does that country take part in terrorism?",
        "Do you think news stations are neutral when they report on terrorism?",
        "Do you think terrorism is here to stay?",
        "What three adjectives would you choose to describe terrorism?",
        "Which is worse, terrorism or climate change?",
        "What do you think of the fact that trillions of dollars are spent fighting in Iraq and Afghanistan, but only millions are spent on killer diseases like malaria and AIDs?",
        "What do governments learn from terrorism?",
        "What is terrorism?",
        "Do you worry about terrorism?",
        "When did terrorism first start in the world?",
        "What countries around the world have terrorist attacks within their borders?",
        "Is there a difference between a freedom fighter and a terrorist?",
        "Is there a difference between a country’s national hero, who may have killed innocents for his country’s independence, and a terrorist?",
        "Do you think terror groups will one day get hold of nuclear and chemical weapons?",
        "What is state sponsored terrorism?",
        "Is it better (and cheaper) to tackle the roots of terrorism rather than fight unbelievable expensive wars?",
        "What do you understand by the term ‘cyber-terrorism’? How dangerous is it?"
    ],
    "Tests": [
        "What images spring to mind when you hear the word ‘test’?",
        "Do you get nervous when you take tests?",
        "Are there any kinds of tests that you love?",
        "Do you have any special routines you follow before you take a test?",
        "What test has made you most nervous?",
        "What do you think about while you wait for the result of a test?",
        "Have you ever cheated on a test?",
        "Have you ever taken an IQ test?",
        "Do you think testing is useful or a waste of time?",
        "Do you think your test scores reflect your true ability and intelligence?",
        "Do you like taking tests?",
        "Are you good at taking tests?",
        "What was the last English test that you took like?",
        "Have you ever had a blood test?",
        "Would you be more nervous before your driving test, a blood test or an English test?",
        "What’s the best way to prepare for a test?",
        "What medical tests have you had?",
        "What was the worst test you ever took?",
        "Are there too many tests in school?",
        "How do you feel when you fail a test?"
    ],
    "Thailand": [
        "What images spring to mind when you hear the country Thailand?",
        "What are the good things and bad things about Thailand?",
        "What is Thailand most famous for?",
        "What do you know about Thailand’s history?",
        "What are the differences between Thailand and your country?",
        "What do you think about Thai people?",
        "What has Thailand given to the world?",
        "Would you like to visit Thailand, or live there?",
        "What do you know about the geography of Thailand?",
        "Who are the most famous Thai people you know?",
        "How different is Thailand from other Southeast Asian countries?",
        "What was the last news story you heard about Thailand?",
        "What do you think Thailand’s neighbours think of it?",
        "What do you think Thailand will be like 50 years from now?",
        "Does your country have good relations with Thailand?",
        "What could you do on a holiday in Thailand?",
        "What is your idea of a typical Thai person?",
        "What things about Thailand do you think Thais are proud of?",
        "What do you know about Thai culture?",
        "What would you like to ask a Thai person about Thailand?"
    ],
    "Theatre": [
        "What springs to mind when you hear the word ‘theatre’?",
        "Do you use the British spelling ‘theatre’ or the American spelling ‘theater’? Does it matter which one you use?",
        "How often do you go to the theatre?",
        "Is the theatre only for rich people?",
        "What do you like and dislike about the theatre?",
        "What’s the best thing you’ve ever seen at the theatre?",
        "Would you like to work as a theatre critic?",
        "Are theatre tickets easy to get in your country?",
        "How do you feel when you sit in a theatre before the performance begins?",
        "What’s the nicest theatre you’ve ever been to?",
        "Why is the theatre important?",
        "What kind of theatre history does your country have?",
        "Do you prefer watching a play at the theatre or a movie at the movie theatre (cinema)?",
        "Do you think theatre tickets are reasonably priced?",
        "Have you ever been to the theatre in another country?",
        "Do you think people will always be interested in the theatre?",
        "What questions would you like to ask a theatre actor?",
        "Would you like to perform or act on stage at the theatre?",
        "Would you like to see a theatre play in English?",
        "What’s are the differences between movies and plays?"
    ],
    "Thinking": [
        "What springs to mind when you hear the word ‘thinking’?",
        "Why do we think?",
        "Do you always think about what you must do next/later?",
        "What is a thinker? Are you one?",
        "Can too much thinking affect your health?",
        "How can we stop people from thinking too much?",
        "Is thinking a positive or negative thing? Why?",
        "What would happen if we stopped thinking?",
        "What do you do when thinking keeps you awake at night?",
        "When was the last time thinking about something solved a problem?",
        "How would the world change if we could read each other's thoughts?",
        "What are you thinking right now?",
        "What do you do when you find yourself thinking bad thoughts?",
        "What do you think other people think of you?",
        "How much do you care about what others think of you?",
        "What things change the way you think?",
        "Why do different people think in different ways?",
        "What do you spend your day thinking about most? Why?",
        "What are the differences between the way men and women think?",
        "What do children think about most? Why?"
    ],
    "Tigers": [
        "What comes to mind when you hear the word ‘tiger’?",
        "What do you think of tigers?",
        "Can you be a tiger?",
        "What three adjectives would you use to describe tigers?",
        "Do you think tiger products have all the medicinal properties Chinese medicine says they have?",
        "What does a tiger do all day?",
        "What is a paper tiger?",
        "Do you think tigers make good pets?",
        "How does a tiger compare with a lion?",
        "Madonna said: \"Better to live one year as a tiger, than a hundred as a sheep.\" Do you agree?",
        "Do you like tigers?",
        "What do you know about tigers?",
        "What would the world be like without tigers?",
        "What do you think of tiger hunters and those who trade in tiger skins?",
        "What do you think tigers think of humans?",
        "Which is more beautiful – the striped tiger of the white tiger?",
        "How are tigers different from the other big cats?",
        "What kind of people are those born in the year of the tiger?",
        "If ten tigers escaped from your local zoo, would you leave the house?",
        "A doctor said: \"You handle depression in much the same way you handle a tiger.\" Do you agree?"
    ],
    "Time": [
        "What comes to mind when you hear the word ‘time’?",
        "How often do you think about time?",
        "Do you ever waste your time?",
        "Do you have enough time to do the things you want to do?",
        "Does time fly when you’re having fun?",
        "Do you ever think life is a race against time?",
        "What stage(s) in our life do we have all the time in the world?",
        "Do you agree that time will tell?",
        "Douglas Adams said: \"Time is an illusion. Lunchtime doubly so.\" Do you agree?",
        "Einstein said: \"The only reason for time is so that everything doesn't happen at once.\" What do you think of this quote?",
        "How do you like to spend time?",
        "Does it annoy you when people take their time doing things?",
        "How much spare time do you have every day?",
        "What is the most time-consuming thing you do in your life?",
        "What do you do to kill time?",
        "Is time on your side?",
        "Have you ever been in the right place at the right time?",
        "Do you agree that there’s no time like the present?",
        "Alice Bloch said: \"We say we waste time, but that is impossible. We waste ourselves.\" Do you agree?",
        "Seneca said: \"Time discovers truth.\" Do you agree?"
    ],
    "Tourism": [
        "What images spring to mind when you hear the word ‘tourism’?",
        "How important is tourism to your country?",
        "Would you like to work in tourism?",
        "What are the good and bad things about tourism?",
        "What do you think tourism will be like in the future?",
        "What are the major tourist attractions in your country?",
        "What do you think of the idea of space tourism?",
        "How does tourism change lives?",
        "What is eco-tourism? Do you think it’s a good idea?",
        "Is there a difference between a tourist and a backpacker ?",
        "Do you think tourism helps people in the world understand each other?",
        "Is tourism something that only rich people take part in?",
        "What do you think of sex tourism? Do you think it’ll ever disappear?",
        "What factors affect tourism?",
        "Do tourists really get to see the real countries they visit?",
        "Do you think tourism is bad for the planet?",
        "Are tourists in your country funny?",
        "How has tourism changed over the past few decades?",
        "Are you a good ambassador for your country’s tourism industry?",
        "What is tourism?"
    ],
    "Toys": [
        "What comes to mind when you hear the word ‘toy’?",
        "What are your favourite toys?",
        "Do you still play with toys?",
        "How are today’s toys compared with those you played with as a child?",
        "Are toys too expensive?",
        "Did children today have too many toys?",
        "What’s the greatest toy ever invented?",
        "What’s the greatest toy yet to be invented?",
        "Sam Levenson said \"The simplest toy, one which even the youngest child can operate, is called a grandparent.\" Do you agree?",
        "Tom Robbins said \"the brain is an educational toy”. What does this mean? Do you agree?",
        "Are toys good or bad?",
        "What percentage of toys a child has should be educational toys?",
        "Would you buy a child a toy or a book?",
        "What’s the best toy shop you know of?",
        "Would you like a job making, designing and testing toys?",
        "Why do kids like toys?",
        "If you could be a toy, what would you be?",
        "What toys are there for adults?",
        "Bill Gates said about the Internet: \"Nice toy, but what a waste of time.\" What do you think he meant? Do you agree?",
        "Desmond Morris said \"Life is like a very short visit to a toyshop between birth and death.\" Do you agree?"
    ],
    "Traditional Medicine": [
        "What springs to mind when you hear the term ‘traditional medicine’?",
        "What is ‘traditional’ about traditional medicine?",
        "What traditional medicine do you know about?",
        "Have you tried any traditional medicine?",
        "Do you think traditional medicine is just a trend that goes in and out of fashion?",
        "Do you think traditional medicine works?",
        "What kind of people use traditional medicine?",
        "Do you think traditional medicines work better than modern drugs?",
        "Do you trust traditional medicine?",
        "Do you think doctors should study about and be experts in traditional medicine?",
        "Do you think traditional medicines are tried, tested and safe?",
        "Why do you think so little is known about the health benefits of traditional medicine?",
        "Which countries in the world have the best medicines?",
        "Do you think we can find all the medicines we need from the natural world, instead of making drugs?",
        "Would you like to try acupuncture? Cupping?  Massage?",
        "What are your thoughts on traditional Chinese medicine?",
        "Do you think the medicine in Western hospitals is traditional medicine in other countries?",
        "What do you think of things like art therapy, music therapy, healing with animals, etc?",
        "What would you like to know about traditional medicine?",
        "Do you know anyone who uses traditional medicine?"
    ],
    "Trains": [
        "What comes to mind when you hear the word ‘trains’?",
        "Is the train system in your country good?",
        "How important are trains in your country?",
        "Do you like over ground or underground trains?",
        "Which country has the best train network?",
        "Which city has the best subway system?",
        "Do you like long-distance train journeys?",
        "What do you usually do on a train?",
        "Do you have any ‘train stories’?",
        "Which is better – the train or the car?",
        "What do you like and dislike about trains?",
        "Why do you think people like looking at trains as a hobby - train spotting?",
        "Do you ever worry about train safety?",
        "What do you think would be the most romantic and beautiful train journey in the world?",
        "What will trains be like in the future?",
        "Do you think you’ll ever be on the gravy train?",
        "Do you like train stations?",
        "Would you like to go on a long journey on a steam train?",
        "What strange people have you come across on a train?",
        "How could trains be made better?"
    ],
    "Translation": [
        "What comes to mind when you hear the word ‘translation’?",
        "Are there words in your language that you think are almost impossible to translate?",
        "What problems have you had with translating English idioms?",
        "Have you ever had great fun using an online translation service?",
        "Would you like to work as a translator?",
        "Do you think someone will invent an instant speech translation machine one day so we can always understand what people are saying in other languages?",
        "Have you made any funny mistakes because of translation?",
        "Do you think a country’s slang is difficult to translate?",
        "Jonathan Miller said: \"What makes literature interesting is that it does not survive its translation.\" Do you agree?",
        "Umberto Eco said: \"Translation is the art of failure.\" Do you agree?",
        "How important is translation in learning a language?",
        "Are you always satisfied with how easily words can be translated?",
        "Do you use translation tools to learn English?",
        "If two speakers of different languages fell in love, could they ever make each other understand exactly how they feel – is love lost in translation?",
        "Why is it that translated jokes are rarely funny?",
        "Do you need an in-depth knowledge of the other culture to be able to do a good translation?",
        "How well do you think a term like “democracy” is translated and understood in countries that have no democracy?",
        "Are movies in English always translated well into your language?",
        "The poet Robert Frost said: \"Poetry is what gets lost in translation.\" Do you agree?",
        "George Borrow said: \"Translation is at best an echo.\" Do you agree?"
    ],
    "Transplants": [
        "What comes to mind when you hear the word ‘transplant’?",
        "What would you think if you needed a transplant?",
        "Would you ever consider having a face transplant?",
        "Will you donate your organs to medicine so they can be transplanted after you die?",
        "Do you think people are different after a heart transplant?",
        "Do you think people would be less human if they had the organ of an animal transplanted into their body?",
        "Do you think scientists will be able to transplant any human organ in the future?",
        "How would someone change after a brain transplant?",
        "If you needed a brain transplant, whose brain would you like?",
        "Barry Switzer joked about his son: \"It was like a heart transplant. We tried to implant college in him but his head rejected it.\" What does this mean? Do you think it’s funny?",
        "Do you think there’ll ever be such things as personality transplants?",
        "Why do you think hair transplants rarely work?",
        "Do you think transplants are a bit like playing Frankenstein?",
        "Would you ever say no to an organ transplant?",
        "Would you agree to hospitals using your DNA to grow spare organs for later use in your life?",
        "Would you accept a transplant organ from someone you hated?",
        "Is donating an organ for transplant the greatest gift you can give?",
        "What do you think of the idea of skill, talent and ability transplants?",
        "Could transplants one day change humans and make a new species?",
        "Pioneering heart surgeon Dr. Christian Barnard said: \"It is infinitely better to transplant a heart than to bury it so it can be devoured by worms.\" Do you agree?"
    ],
    "Transportation": [
        "What comes to mind when you hear the word ‘transportation’?",
        "What's you favourite method of transportation?",
        "What transportation problems are there in your country?",
        "What will the transportation of the future be like?",
        "What would life be like if all public transportation in your country stopped?",
        "Are you happy with transportation services in your country?",
        "What do you think of the transportation in other countries?",
        "How many different kinds of transportation have you been on?",
        "Will the quality of transportation in your country get better or worse?",
        "What was transportation like when you were a kid?",
        "If life is a highway, what mode of transportation are you using?",
        "What do you think is the most dangerous form of transportation and why?",
        "Which transportation do you prefer – air, sea or road?",
        "If you were a mode of transportation, what would you be?",
        "What form of transport is worst for the environment?",
        "What mode of transportation would you like someone to invent?",
        "How has international transportation changed in the past few decades?",
        "What are the transportation needs of your country?",
        "Do you think we are spoilt for choice these days with all the different transportation options?",
        "What do you think will be the next big breakthrough in transportation?"
    ],
    "Travel": [
        "Do you like travelling?",
        "What is travel for you?",
        "What different kinds of travelling are there?",
        "What’s the best place you’ve ever been to?",
        "Would you like to go travelling for a few years non-stop?",
        "What are the good and bad things about travelling?",
        "Where do you want to travel to before you die?",
        "Is it better to travel or to arrive?",
        "Lin Yutang said: \"No one realizes how beautiful it is to travel until he comes home and rests his head on his old, familiar pillow.\" Do you agree?",
        "Elizabeth Drew said: \"Too often travel, instead of broadening the mind, merely lengthens the conversation.\" What does this mean? Do you agree?",
        "What springs to mind when you hear the word ‘travel’?",
        "Are you a traveller?",
        "Is travel an education?",
        "Would you like to travel in space or to the moon?",
        "Would you like to work in the travel industry?",
        "What are the pros and cons of traveling first class and backpacking?",
        "Is travel helping the world?",
        "What would make you wiser – travelling around the world for ten years or reading 10,000 books?",
        "Mason Cooley said: \"Travelers never think that they are the foreigners.\" Do you agree?",
        "St. Augustine said: \"The World is a book, and those who do not travel read only a page.\" What does this mean? Do you agree?"
    ],
    "Turkey": [
        "What images spring to mind when you hear the country Turkey?",
        "What are the good things and bad things about Turkey?",
        "What is Turkey most famous for?",
        "What do you know about Turkey’s history?",
        "What are the differences between Turkey and your country?",
        "What do you think about Turkish people?",
        "What has Turkey given to the world?",
        "Would you like to visit Turkey, or live there?",
        "What do you know about the geography of Turkey?",
        "Who are the most famous Turkish people you know?",
        "How different is Turkey from other Mediterranean countries?",
        "What was the last news story you heard about Turkey?",
        "What do you think Turkey’s neighbours think of it?",
        "What do you think Turkey will be like 50 years from now?",
        "Does your country have good relations with Turkey?",
        "What could you do on a holiday in Turkey?",
        "What is your idea of a typical Turkish person?",
        "What things about Turkey do you think Turks are proud of?",
        "What do you know about Turkish culture?",
        "What would you like to ask a Turkish person about Turkey?"
    ],
    "Twitter": [
        "What springs to mind when you hear the word ‘Twitter’?",
        "What do you think of the name Twitter for a website?",
        "What did you think when you first heard of / used Twitter?",
        "Do you think 140 characters are enough for the Twitter updates?",
        "Why do you think Twitter is so successful?",
        "How does Twitter compare with other social networking sites?",
        "How do you think Twitter makes money?",
        "How could Twitter make more money?",
        "Why do you think Twitter chose a small bird as its logo?",
        "What would you like Twitter to do differently?",
        "What do you think of Twitter?",
        "What do you think of Twitter’s slogan, “What are you doing”?",
        "What Twitter sites do you follow / like?",
        "How many people would you like to follow your Twitter site?",
        "What do you think of the word ‘tweet’ (meaning a message posted on Twitter)?",
        "Who do you think Twitter is most useful for?",
        "Is your life interesting enough to tweet about?",
        "Which famous person would you like to follow on Twitter and why?",
        "What questions would you like to ask Twitter’s owners?",
        "Did you like this discussion?"
    ]
}
