export default {
    "Canada": [
        "What do you think of Canada?",
        "What kind of country is Canada?",
        "How important is Canada on the world stage?",
        "How different are Canadians from Americans?",
        "What do you know about Canadian history?",
        "What images spring to mind when you hear the country Canada?",
        "What do you think are the advantages of being Canadian?",
        "What do you think of when you hear the word \"Canada\"?",
        "What do you know about Canada’s indigenous peoples?",
        "What would you like to do if you spent six months in Canada?",
        "What are some differences between Canada and the USA?",
        "What is Canada famous for?",
        "Is Canada the kind of country you’d like to live in?",
        "What has Canada given the world?",
        "What is there to see and do in Canada?",
        "Do you have any negative images of Canada?",
        "What does a typical Canadian look like?",
        "What things are made in Canada?",
        "What do you know about the geography of Canada?",
        "What would you like to know about Canada?"
    ],
    "Cannabis / Marijuana": [
        "Have you ever consumed cannabis?",
        "What are the different ways of consuming cannabis?",
        "Why do people use cannabis?",
        "What does your country think about cannabis?",
        "What should happen to people who drive under its influence?",
        "Is driving high on cannabis as dangerous as drunk driving?",
        "How can society discourage people from using drugs?",
        "Do you think education alone is enough to stop drug use?",
        "Are fines a sufficient penalty for drugged driving?",
        "How can police tell if someone is under the influence of cannabis?",
        "What other names do you know for cannabis?",
        "What do you think of cannabis?",
        "Why is cannabis legal in some countries and illegal in others?",
        "What are the effects of cannabis?",
        "Have your parents discussed marijuana with you?",
        "People say cannabis leads to harder drugs. What do you think?",
        "Which is worse - cannabis or alcohol?",
        "Do you think marijuana is a hallucinogen?",
        "Should cannabis be legal?",
        "Would you ever come to class stoned/high? (Be honest!)"
    ],
    "Capital Punishment": [
        "What is the difference between capital punishment and corporal punishment?",
        "Do you agree with capital punishment?",
        "What is the history of capital punishment in your country?",
        "What does the government do about people wrongly executed?",
        "Is the death penalty a deterrent to violent crime?",
        "What different methods are there of applying the death penalty?",
        "What do you think of the argument “an eye for an eye, a tooth for a tooth”?",
        "Do you think victims’ families get a sense of closure knowing a killer has been executed?",
        "Should the death penalty be applied to mentally disabled people?",
        "What do you think the executioner feels?",
        "Do you think capital punishment is murder?",
        "Which is worse, life imprisonment or the death penalty?",
        "Why do many Christian countries have the death penalty when the Bible says, “Thou shalt not kill”?",
        "What do you think is the most humane way to put someone to death?",
        "Do you think the victim’s family should be able to choose the method of execution?",
        "If execution is unacceptable, what is the alternative?",
        "What does the \"capital\" mean in \"capital punishment\"?",
        "Should the general public be allowed to look at executions?",
        "In Britain, you can receive the death penalty for killing the Queen but not your neighbor. What do you think?",
        "Do you think the death penalty can be applied to thieves?"
    ],
    "Capitalism": [
        "What is capitalism?",
        "Is capitalism the best economic system for the world?",
        "Who likes capitalism?",
        "Who suffers from capitalism?",
        "Will the whole world be capitalist one day?",
        "What are the advantages of capitalism over communism?",
        "What is the free market?",
        "What is the difference between capitalism and greed?",
        "What happens to the less intelligent or able under capitalism?",
        "If capitalism is so great, why are there many people living below the poverty line in capitalist countries?",
        "Is capitalism a nice word?",
        "Are there better alternatives to capitalism?",
        "Does capitalism make the rich richer and the poor poorer?",
        "Is it ethical for CEOs to get giant salaries?",
        "Aren’t capitalists people who exploit workers?",
        "Does capitalism destroy the environment?",
        "Are giant, multinational corporations good for the world?",
        "What are the objectives of anti-capitalism activists?",
        "Bill Gates has billions of dollars. Many people in New Orleans live below the poverty line. Is that capitalism?",
        "Are you a supporter of capitalism?"
    ],
    "Cars": [
        "Are you into cars?",
        "Do you think cars are good value for money?",
        "Do you think the world would be a better place without cars?",
        "Have you ever been in a car accident?",
        "How different do you think cars of the future will be?",
        "Should governments restrict engine sizes to protect the environment?",
        "What do you think of drivers who decorate their cars with soft toys?",
        "Which country produces the best cars?",
        "Do you like sitting in a car, either as a driver or a passenger?",
        "Why do so many people care so much about their cars?",
        "What’s your favourite car?",
        "Do you need a car?",
        "Do people need cars that go way above national speed limits?",
        "Have you seen the Pixar/Disney movie Cars?",
        "If you were a car, what car would you like to be?",
        "What features and functions of a car do you need most?",
        "Do you prefer driving gas guzzlers or fuel efficient cars?",
        "Do you think it is fair to call a car a dangerous weapon?",
        "Do you think the car a person drives is an extension of his/her personality?",
        "Where do cars rank in the list of most important inventions?"
    ],
    "Celebrities": [
        "What is a celebrity?",
        "Do you think anyone can become a celebrity?",
        "Do you think celebrities like Oprah Winfrey deserve the millions of dollars they get paid?",
        "Why are so many people obsessed with celebrities?",
        "What do you think are the downsides to being a celebrity?",
        "Are there any celebrities you hate the sight of?",
        "Would you like to be interviewed by celebrity magazines?",
        "Do you think there are different levels of celebrity?",
        "Which celebrities would you invite to your birthday party and why?",
        "Are there differences between a ‘celebrity’ and a ‘famous person’?",
        "Do you think all celebrities are talented?",
        "Do you have a favourite celebrity?",
        "Do you like reading about celebrities in magazines, online etc.?",
        "Would you like to be a celebrity?",
        "Do you think celebrities like being celebrities?",
        "Would you see your friends often if you became a world celebrity?",
        "What aspects of your present life would you miss if you became a celebrity?",
        "Have you ever met any celebrities?",
        "Which two celebrities would you like to see interview one another?",
        "Which celebrity would you like to swap places with?"
    ],
    "Cellular Telephones": [
        "What was life like before cell phones?",
        "What cell phone functions are important for you?",
        "Are there any features on your cell phone you don’t need?",
        "Can people use their cell phones while they are driving in your country?",
        "What does the ‘cellular’ mean in cellular phone?",
        "Do you think cell phones are liberating?",
        "Would it be a big problem for you if your cell phone was lost or stolen?",
        "How often do you turn your cell phone off?",
        "Which cell phone maker is best?",
        "Do you think cell phones really interfere with equipment in hospitals and on airplanes?",
        "What are the best things about cell phones?",
        "Do you get annoyed with other cell phone users?",
        "What do you do when you annoy other people with your cell phone?",
        "Do you think people should be fined for using their cell phone in a no cell phone area?",
        "Are you worried about brain damage from using cell phones?",
        "How do you feel if you leave the house without your cell phone?",
        "Do you think the call and rental charges for cell phones are reasonable?",
        "Have you ever slept with your cell phone?",
        "Do you have any complaints about cell phone batteries?",
        "Have you heard that using a cell phone near a gasoline stand can cause an explosion?"
    ],
    "Censorship": [
        "How would you explain censorship to someone unfamiliar with it?",
        "Do you think the Internet should be censored?",
        "Is it up to the government or other agencies to censor things?",
        "What things should never be censored?",
        "Does censorship result in reduced chances of education for society?",
        "Would you like to be a movie censor?",
        "What do you think censors are more afraid of: print, songs, movies or the Internet?",
        "Are history books in your country censored to hide your nation’s historical wrongdoing?",
        "Many world governments have asked Google Earth to censor parts of its maps that show sensitive areas. Do you agree with this?",
        "The European Union is considering censoring racism and hate propaganda on the Internet – is this good censorship?",
        "Do you agree there should be censorship in societies?",
        "Do you think censorship violates freedom of speech?",
        "Do you think heavy censorship harms or protects societies?",
        "Do you think musical lyrics need censoring?",
        "What kind of interview, qualifications and experience do you think government censors should have?",
        "Do you think the website MySpace needs to be censored?",
        "Is it necessary to censor nudity on television and in movies?",
        "What would the world be like if there was no censorship at all?",
        "What or who would you most like to censor?",
        "What is worst - moral, political, military or religious censorship?"
    ],
    "Change": [
        "Do you like change?",
        "What's the biggest change you've made in your life? Was it good / bad?",
        "Are you good at dealing with change?",
        "Do you think change is important?",
        "What is the biggest change this world needs?",
        "What things in your life would you hate to change?",
        "What three things about your past would you like to change?",
        "What advice would you give to someone who hates change?",
        "What happens to people who find it difficult to change?",
        "Can you teach someone to accept and like change?",
        "Is the world changing faster than before?",
        "How do old and young people cope with change?",
        "What is the biggest change you'd like to make to your life?",
        "Why are some people better than others at dealing with change?",
        "What has changed in your life compared to ten years ago?",
        "Is change always good?",
        "What has been your biggest life-changing event?",
        "What would you like to change about yourself?",
        "How has your society changed in the past decade?",
        "What will change in the future?"
    ],
    "Charity and Charities": [
        "Do you have a favourite charity?",
        "Are you satisfied with the work charities do?",
        "Do you think governments should do more to help charities?",
        "How often do you give money to charities?",
        "Have you ever received charity from others?",
        "Would you like to work for a charity?",
        "Do you worry about where the money you donate to charity goes?",
        "Do you think that one day there will be no need for charities?",
        "Do you agree with the expression “charity begins at home”?",
        "How much suffering would disappear if more people donated money to charity?",
        "Do you think charities should only help people and not animals, buildings, etc.?",
        "What do you think of people who stand outside stores or railway stations holding charity donation boxes?",
        "What is the largest amount of money you have donated?",
        "Do you think we should all donate some of our salary to charity?",
        "What was the last cause you donated money to?",
        "Do you ever buy used goods from charity shops?",
        "What do you think of Bill Gates’ charity?",
        "Do you think the people you know are very charitable?",
        "Do you think it is immoral for people to spend lots of money on themselves when people are starving and dying?",
        "Do you take part in fund raising events for charity?"
    ],
    "Child Soldiers": [
        "What comes to mind when you hear the word ‘child soldiers’?",
        "Where do you think child soldiers fight in the world?",
        "What do you think of the people who force children to take up arms and fight?",
        "What do you think the children feel about fighting in wars?",
        "How do you think a child changes once he or she is given a gun and told to kill people?",
        "Do you think the emotional scars child soldiers suffer ever heal?",
        "What should the global community do to reduce the number of children fighting in conflicts across the world?",
        "Can you imagine fighting in a war at the age of nine or ten?",
        "Do you think child soldiers are happy?",
        "In what ways do you think child soldiers can be more dangerous than adult soldiers?",
        "What is the youngest at which people can join your country’s army?",
        "What do you think the average child soldier does every day?",
        "Do you think your country has ever used child soldiers?",
        "Do you think it’s OK to give children guns if they were the only and last chance to protect your country?",
        "Do you think there are enough global campaigns to highlight the plight of child soldiers?",
        "The United Nations says it is ok for fifteen-year-olds to fight. What do you think about this?",
        "The UN says using children under 15 is a war crime. Do you agree?",
        "Countries still celebrate the bravery of child soldiers during World War II. Do you think it’s OK for them to do this?",
        "Do you know about the Coalition to Stop the Use of Child Soldiers?",
        "What is the worst case of the use of child soldiers you know about?"
    ],
    "Children": [
        "Are you good with children?",
        "Do you agree with the expression “children should be seen and not heard”?",
        "How many children should a couple have?",
        "When does a child become an adult?",
        "What’s the most irritating thing about children?",
        "Do you like other people’s children?",
        "Do you think children are spoilt nowadays?",
        "Would you like your children to be like you?",
        "How expensive is raising children?",
        "What do you think children worry about most?",
        "Do you like children?",
        "Are children becoming more dangerous and violent?",
        "Do you think children are hard work?",
        "Do you think children are becoming more and more like adults?",
        "What advice would you give to children today?",
        "What do you think children would like to change about their world?",
        "What time should children go to bed?",
        "Are you a child at heart?",
        "Is it more fun to spend time with children or adults?",
        "From what age should children be allowed to work?"
    ],
    "China": [
        "How do you feel about China?",
        "What do you think China is most famous for?",
        "Would you like to go to China?",
        "What do you think of products with the “Made in China” label?",
        "Do you think China will become the strongest country in the world?",
        "Does the power of China make you worried in any way?",
        "What do you most admire about China?",
        "What do you consider to be China’s biggest problems?",
        "Do you think that one day the world will be learning Chinese rather than English?",
        "What are relations like between China and your country?",
        "Do you like Chinese food?",
        "How is China perceived by the media in your country?",
        "What do you know about China’s leaders and politics?",
        "What is your image of life in China?",
        "What springs to mind when you hear the country China?",
        "What aspects of Chinese culture are there in your country?",
        "Do you think China should get more involved in resolving problems in the world’s trouble spots?",
        "What can other countries learn from China?",
        "What are your views on China and its policies towards Tibet and Taiwan?",
        "What do you know about China’s history?"
    ],
    "Chocolate": [
        "Do you like chocolate?",
        "Which country do you think makes the most delicious chocolate?",
        "Do you like getting chocolate as a present?",
        "Do you know how chocolate is made?",
        "How much chocolate should children eat?",
        "Is chocolate part of any celebrations in your country?",
        "Do you think chocolate is healthy?",
        "Who do you think are the world’s biggest chocolate eaters?",
        "Why is chocolate so often associated with romance?",
        "What would the world be like without chocolate?",
        "What do you know about the history of chocolate?",
        "Did you eat a lot of chocolate when you were a child?",
        "Why do you think so many people are addicted to chocolate?",
        "What is your favourite brand / bar / kind of chocolate?",
        "Would you like to eat some chocolate right now?",
        "Do you have a favourite chocolate TV commercial?",
        "How can the word ‘chocolate’ be a countable and uncountable noun?",
        "Have you read the book ‘Charlie and the Chocolate Factory’?",
        "Does eating chocolate change our feelings?",
        "What are your earliest memories of chocolate?"
    ],
    "Christmas": [
        "What is Christmas?",
        "Is Christmas the same today as it was 100 years ago?",
        "What’s the best Christmas you’ve ever had?",
        "Is there anything stressful about Christmas?",
        "Is Christmas better in the cold Northern Hemisphere or on a beach in the Southern Hemisphere?",
        "Have your feelings towards Christmas changed since you were a child?",
        "What do you usually do on Christmas Eve and Christmas Day?",
        "What is your favourite Christmas song?",
        "What do you know about Santa Claus?",
        "How do you feel when Christmas is over for another year?",
        "What does Christmas mean to you?",
        "Is Christmas too commercial nowadays?",
        "Should people go to church at Christmas?",
        "Is it important to buy presents at Christmas?",
        "What do you usually eat at Christmas?",
        "Do you think Christmas is the best holiday of the year?",
        "How should a very traditional Christmas be spent?",
        "What do you want for Christmas?",
        "What do you dislike about Christmas?",
        "Would you like to spend Christmas in another country?"
    ],
    "Cities": [
        "Are cities good things?",
        "What is your favorite city?",
        "How are city people and country people different?",
        "What are the biggest problems with living in cities?",
        "What damage do cities do to the countryside?",
        "When does a town become a city?",
        "Which world city do you think would be the best to live in?",
        "How will cities in the future be different from those today?",
        "If you were city mayor, what changes would you make to your city?",
        "Which city would you choose as capital of the world and why?",
        "Do you prefer city or country life?",
        "What do you like and dislike about the capital city of your country?",
        "What do you think are the world’s three greatest cities and why?",
        "Is the capital city of a country always that country’s best city?",
        "Is it better to grow up in the city?",
        "How are the cities in your country different?",
        "Do you think there’ll be more and more cities in the world?",
        "What’s the best way to deal with traffic problems in a city?",
        "Are cities beautiful?",
        "Is it possible for a city to escape social problems?"
    ],
    "Climate Change": [
        "How do you feel about climate change?",
        "Are you more worried about climate change or the war on terror?",
        "Has climate change affected the country in which you live?",
        "Do you believe everything scientists say about climate change?",
        "Do you believe everything politicians say about climate change?",
        "What do you think the world’s climate will be like 50 years from now?",
        "What do you do to try to limit the effects of climate change?",
        "What is your country doing to limit the effects of climate change?",
        "Do you think the USA and China are doing enough?",
        "How often do you think about climate change?",
        "How would you explain climate change to someone who knew nothing about it?",
        "What can the world do to reverse climate change?",
        "Are “eco-friendly” cars and electrical appliances really eco-friendly?",
        "What will our grandchildren think of us using so much carbon?",
        "What do you know about carbon footprints?",
        "Which industries need to become cleaner and greener?",
        "Do you think there’ll be climate change refugees in the future?",
        "What are you most worried about with climate change?",
        "Are there any positives to come from climate change?",
        "Is climate change the worst thing ever to happen to humankind?"
    ],
    "Clothes": [
        "Why do we need clothes?",
        "Why do people spend lots of money on clothes?",
        "Who decides which clothes are fashionable?",
        "Do you think clothes are a waste of money?",
        "How long does it take you to decide which clothes to wear?",
        "Is shopping for clothes your favourite kind of shopping?",
        "Do you buy clothes magazines?",
        "Do you ever think other people look good in their clothes but you don’t look good in your clothes?",
        "Were you embarrassed to wear the clothes you wore as a kid?",
        "Why are you wearing the clothes you have on now?",
        "What do clothes tell people about our personalities?",
        "Do you have clothes in your closet that you’ve never worn?",
        "Do you ever buy used clothes?",
        "Do you have a favourite clothes shop?",
        "What new clothes would you like to buy if you had lots of money?",
        "Are men’s clothes or women’s clothes best?",
        "Do you always recycle your old clothes or give them to charity?",
        "What do you think of my clothes?",
        "What’s your favourite item of clothing?",
        "If you were an item of clothing, what would you be and why?"
    ],
    "Coffee": [
        "Are you a ‘coffeeholic’?",
        "Do you care if you have instant or blend coffee?",
        "Do you need coffee to wake you up in the morning?",
        "Is coffee bad for you?",
        "Does coffee affect your appetite?",
        "What do you think of Starbucks?",
        "Do you think caffeine is a dangerous drug?",
        "What do you think of the new trend of flavored coffee?",
        "Do you like the smell of coffee?",
        "What would you like to know about coffee?",
        "Are there any health benefits to drinking coffee?",
        "What do you know about coffee production and who gets the big profits?",
        "Would you drink less coffee if you knew it stained your teeth?",
        "What is the difference between blend, cappuccino and espresso?",
        "Does coffee grown in different parts of the world taste differently?",
        "What role does coffee (or tea) play in your life?",
        "What’s the difference between Irish coffee and Turkish coffee?",
        "Do you know what fair trade coffee is?",
        "Do you like coffee sold in cans?",
        "What do you think happens when you overdose on coffee?"
    ],
    "Companies": [
        "What springs to mind when you hear the word ‘company’?",
        "What are your favourite companies?",
        "Which company would you love to work for and why?",
        "Which companies do you dislike most?",
        "Have you ever written a letter of complaint to a company?",
        "Which companies do you think provide the best customer service and best products?",
        "Do you prefer bricks-and-mortar companies or Internet companies?",
        "Amazon.com founder and boss Jeff Bezos said: \"A brand for a company is like a reputation for a person.\" What do you think of this?",
        "Mary Kay Ash said: \"People are definitely a company’s greatest asset.\" Do you think this is true all over the world?",
        "Andrew Grove said: \"In the future, all companies will be Internet companies.\" Do you agree? Would this be good?",
        "Do you think companies really care about the environment?",
        "Do you think multinational companies have become too big and have too much power?",
        "Why do you think big companies pay their CEOs lots of money, even if they lose the company money or get involved in scandals?",
        "Do you think oil companies are good for the world?",
        "How could companies in your country be more successful?",
        "Which company makes the best adverts and commercials?",
        "Do you think most companies look after their staff?",
        "How will companies be different in the future?",
        "Google co-founder Larry Page said: \"You don't need to have a 100-person company to develop that idea.\" Is he right?",
        "Ross Perot said: \"You'd be amazed how many companies don't listen to their customers.\" Do you think you'd be amazed?"
    ],
    "Competition": [
        "What images spring to mind when you hear the word ‘competition’?",
        "Are you a competitive person? Why/why not?",
        "Why are some people very competitive?",
        "Is competition good for us?",
        "Do you like competitive people?",
        "In what way is education a competition in your country?",
        "Do you think life is a competition?",
        "Do we learn to be competitive or are we born competitive?",
        "David Sarnoff said: \"Competition brings out the best in products and the worst in people.\" What does this mean? Do you agree?",
        "Dr T.P.Chia said: \"A competitive person is always a winner. An uncompetitive person is always a loser.\" What do you think?",
        "What’s your favourite competition?",
        "Do you compete with other students in your English class?",
        "Do you compete with yourself?",
        "How did competition begin?",
        "Which country is in \"competition\" with your country?",
        "What would the world be like without competition?",
        "Are men more competitive than women?",
        "How can you learn to be more competitive?",
        "Do drivers in your country drive as if they are in a competition?",
        "Do you care if you lose when you are in a competition?"
    ],
    "Complaining": [
        "What springs to mind when you hear the word ‘complain’?",
        "Are you a complainer?",
        "Who do you usually complain to?",
        "What complaints do you have at the moment?",
        "Have you ever complained in a restaurant, hotel, airplane or train?",
        "How often do people complain to you?",
        "How often do people complain about you?",
        "Do you have any complaints about English?",
        "What are your biggest complaints about your friends?",
        "Do men or women complain more?",
        "What kinds of things do you complain about?",
        "When was the last time you complained about something?",
        "Have you ever written a letter or e-mail of complaint?",
        "Do you like complaining?",
        "What is your complaining style – polite or aggressive?",
        "How often do you complain to yourself in public?",
        "Do you think complaining relieves stress?",
        "Do you like watching other people complain?",
        "Have you ever got a better service after you’ve complained?",
        "Why might people complain about you?"
    ],
    "Computers": [
        "What is a computer?",
        "When did you use a computer for the first time?",
        "How useful are computers to you?",
        "What is the best thing about a computer?",
        "What is your favorite piece of software?",
        "What would life be like without your computer?",
        "Can you keep up to date with the latest computer technology?",
        "Do you control computers or do they control you?",
        "Would you like to spend more time with your computer?",
        "What would happen if all of the world’s computers suddenly stopped forever?",
        "Do you like computers?",
        "Do you have your own computer?",
        "Do computers ever make you want to pull your hair out (i.e. become very frustrated)?",
        "What is the worst thing about computers?",
        "Do you know a lot about computers?",
        "Do you think computers will always look similar to the way they do now (a screen with a keyboard)?",
        "What would you miss most if your computer was taken away?",
        "Would you like to take a course in computer science?",
        "Do you think it’s cool to be a nerd or computer geek?",
        "What would you like computers to do that they can’t do now?"
    ],
    "Conservation": [
        "What is conservation?",
        "Would you like to work as a conservationist?",
        "When and why do you think conservation became a high profile issue?",
        "Do you think conservationists are winning or losing their battles?",
        "Is enough attention given to conservation in your country’s schools and media?",
        "Which countries have the best and worst records on conservation?",
        "Do you think your grandchildren will be happy with our attempts at conservation?",
        "What do you think the world would be like today without the efforts of conservationists?",
        "Which countries in the world are most in need of conservation projects?",
        "Which conservation charity or organization would you support?",
        "Why is conservation important?",
        "What are the most important areas regarding conservation in your country?",
        "Is globalization making conservation efforts more difficult?",
        "Do you agree with the illegal actions some conservationists use?",
        "How can we reverse the effects of deforestation and desertification?",
        "What do you think of the fact that much of Earth’s biodiversity has already been lost?",
        "What do you know about sustainable development and renewable resources?",
        "Is it our duty to keep the Earth as it was created?",
        "What does the current condition of Earth say about the human race?",
        "Do you think our children will look after the Earth better than we have?"
    ],
    "Consumerism": [
        "Which (social) facts influence consumerism?",
        "Are there any benefits in consumerism?",
        "What is the role of product labels (like food or clothing brands) in consumerism?",
        "Do you believe special occasions like Christmas or Easter have become too consumeristic?",
        "Is there a way to escape the culture of consumerism?",
        "Do you think there are more consumerist women than men? Why?",
        "Are teenagers and children becoming consumerists earlier?",
        "Does mass media and society affect teenage consumerism?",
        "In your opinion, are consumerist people less creative?",
        "What is ethical consumerism?",
        "Is consumerism a pathology?",
        "What is “green consumerism”? Is it a contradiction?",
        "How does consumerism affect the environment and nature?",
        "Do you agree with extreme anti-consumerism philosophies and attitudes?",
        "Do you believe that changing your spending habits can make a big difference in your life?",
        "Is consumerism spoiling our culture?",
        "Our world economy is based on consumerism. Will consumerism always be predominant?",
        "Has consumerism changed over the years?",
        "What is medical consumerism?",
        "Which jobs are strictly related to consumerism?"
    ],
    "Conversation Questions": [
        "Are you good at small talk and making conversation?",
        "When was the last time you had a really, really interesting conversation?",
        "Do you like intelligent conversation?",
        "What do you think of your English conversation classes and study books?",
        "How do you feel when people interrupt you in the middle of an important conversation?",
        "If you were a fly on the wall, which conversation in history would you like to listen to?",
        "What do you do when you hear your name pop up in other people’s conversations?",
        "Are you OK at everyday conversation in English?",
        "Someone once said: \"Conversation is an exercise of the mind; gossip is merely an exercise of the tongue.\" What does this mean? Do you agree?",
        "Robert C. Gallagher said: \"Anyone who thinks the art of conversation is dead ought to tell a child to go to bed.\" What does this mean? Do you agree?",
        "What springs to mind when you hear the word ‘conversation’?",
        "People say conversation is an art. Do you think so?",
        "What topics of conversation do you enjoy most?",
        "Do you like listening to other people’s conversations?",
        "Have you ever overheard a conversation you wish you hadn’t?",
        "Who in life do you find it difficult to strike up a conversation with?",
        "What common conversation starters do you use?",
        "How long are your phone conversations?",
        "Oscar Wilde said: \"Conversation about the weather is the last refuge of the unimaginative.\" What does this mean? Do you agree with him?",
        "A Chinese proverb says: \"A single conversation across the table with a wise person is worth a month's study of books.\" Do you agree?"
    ],
    "Corporate Responsibility": [
        "What springs to mind when you hear the term ‘corporate responsibility’?",
        "When and why do you think people first started talking about corporate responsibility?",
        "What do companies need to do to show they exercise good corporate responsibility?",
        "Which companies do you think are leaders in corporate responsibility?",
        "Which industries show poor corporate responsibility?",
        "Do you think there should be a corporate responsibility law?",
        "Do you think making huge profits means companies can never be responsible?",
        "What are the most irresponsible companies on Earth?",
        "Are there different responsibilities for small companies and multinationals?",
        "Jeff Mackey said: \"Business social responsibility should not be coerced; it is a voluntary decision that the entrepreneurial leadership of every company must make on its own.\" Do you agree?",
        "What is corporate responsibility?",
        "Do you think corporate responsibility is important?",
        "What responsibilities do oil and cigarette companies have?",
        "What is the most important corporate responsibility?",
        "Are American companies the most responsible in the world?",
        "What responsibilities do companies have when it comes to child labour?",
        "What responsibilities do companies have concerning their customers?",
        "Has the Internet changed corporate responsibility in any way?",
        "Which business leader is a good example of corporate responsibility?",
        "Can a company survive if it shows no corporate responsibility?"
    ],
    "Correction Activities": [
        "What comes to mind when you hear the word ‘correction’?",
        "What do you think when your teacher says you’re going to do some correction?",
        "What kind of correction do you like most?",
        "Do you like the correction activities your teacher gives you?",
        "Do you have an example of how a mistake your teacher corrected stuck with you and you never forgot it?",
        "What do you think when you see your paper and it’s full of red ink and corrections?",
        "How important do you think correction activities are in class?",
        "Do you always understand the reasons why the teacher asks you to do a particular correction activity?",
        "Do you keep a special corrections notebook?",
        "How important are correction activities compared with learning new things?",
        "Do you like doing correction activities in class?",
        "Do you ever think correction activities are a waste of time?",
        "Do you prefer self correction, peer correction or teacher correction?",
        "How do you feel when a teacher corrects your mistakes in front of the class?",
        "What things are important for a correction activity to be successful?",
        "What advice would you give to a student who says they hate being corrected?",
        "Would you like the teacher to correct all of your mistakes as soon as you make them?",
        "Are there mistakes you make again and again, even though the teacher corrects you again and again?",
        "Do you think you need a correction activity in every class?",
        "What questions would you like to ask your teacher about correction?"
    ],
    "Cosmetic Surgery": [
        "What do you think of cosmetic surgery?",
        "Do you think there’s a difference between cosmetic and plastic surgery?",
        "Would you consider having cosmetic surgery?",
        "Do you think cosmetic surgery is more popular with women or men?",
        "What do you think are the dangers of cosmetic surgery?",
        "What parts of your face / body would you like to change?",
        "Would you like to be a cosmetic surgeon?",
        "Why is cosmetic surgery so popular in some countries but not at all in others?",
        "What do you think of people who have cosmetic surgery?",
        "Do you think there should be an age limit for people to have cosmetic surgery?",
        "Would you have cosmetic surgery if it was free?",
        "What would you think if one of your parents came home with a new face / body?",
        "Do you think cosmetic surgery should be banned for children?",
        "Who would you like to look like?",
        "Do you think people who have cosmetic surgery are always happy with the results?",
        "What advice would you give to a friend who wants cosmetic surgery?",
        "Does cosmetic surgery always make people look better?",
        "Is cosmetic surgery playing with the way God made us?",
        "Do you know anyone who has had cosmetic surgery?",
        "Do you think a cosmetic surgeon is happy in their job?"
    ],
    "Cosmetics": [
        "What do you think of cosmetics?",
        "Is there anything strange about people using cosmetics?",
        "How much more beautiful do you / do people look with cosmetics?",
        "Do you think cosmetics are reasonably priced?",
        "What do you think of men wearing lipstick, mascara and foundation?",
        "Why is most lipstick red or pink? What’s wrong with black or green?",
        "Do you think people look better without make-up and cosmetics?",
        "Don’t you think cosmetics are a waste of money?",
        "Do people use cosmetics because they lack confidence?",
        "Do you think we’ll always use cosmetics?",
        "How important are cosmetics?",
        "Do you think cosmetics are good for the skin?",
        "From what age is it OK to start using cosmetics?",
        "Do you believe cosmetics companies’ ads that say their products erase wrinkles and slow down the aging process?",
        "Do you know anyone who uses too much make-up?",
        "Do people use cosmetics differently in different countries?",
        "Which cosmetics and cosmetics companies are best?",
        "Do you think cosmetics companies should advertise their products using ‘normal’ women, instead of supermodels?",
        "How long do you think people spend each day applying and removing cosmetics?",
        "What new type of cosmetics would you like to see on the market?"
    ],
    "Countries": [
        "What are countries?",
        "Do we need so many countries in the world?",
        "What is the most beautiful country in the world?",
        "Which will be the next country to be created?",
        "What things are necessary for a country to be a country?",
        "What country would you love to live in?",
        "What is the most dangerous country in the world?",
        "Would the world be better with more or fewer countries?",
        "What is the most successful country in the world?",
        "Which country produces the most delicious food?",
        "Do you like your country?",
        "How many countries have you been to?",
        "Are there any countries you don’t like?",
        "Why do neighbouring countries go to war with each other?",
        "What changes would you like to make to your country?",
        "How has your country made you the person you are today?",
        "Do you think everyone should live in their own country?",
        "What positive things can the world learn from your country?",
        "Which country in the world do you most admire and why?",
        "If you were a country, what would you be and why?"
    ],
    "Credit Cards": [
        "How many credit cards do you have?",
        "What do you like most about credit cards?",
        "What do you like least about credit cards?",
        "In what ways are credit cards better than cash?",
        "Do credit cards make you buy more things?",
        "Do you think credit cards will replace cash one day?",
        "What do you think of the interest charges on credit cards?",
        "Why do you think credit card companies charge such high interest?",
        "Do you pay all of your credit card off every month?",
        "What are your feelings when you receive the envelope containing your credit card bill?",
        "Who would you trust with your credit card details?",
        "Have you ever lost your credit card?",
        "Do you worry about using your credit card to buy things online?",
        "Are you interested in the air miles and free gifts you can get by using your credit card?",
        "What do you usually use your credit card for?",
        "What is the biggest purchase you’ve made with your card?",
        "Do you think we’ll still be using credit cards twenty years from now?",
        "What do you think of American Express?",
        "Would people be in a better financial situation without credit cards?",
        "When did you last use your credit card?"
    ],
    "Crime": [
        "Have you ever been a victim of crime?",
        "Are you afraid of becoming a victim of crime?",
        "Is crime a problem where you live?",
        "Does your government talk a lot about combating crime?",
        "Do you worry about Internet crime?",
        "Is anyone capable of turning to crime?",
        "Who are the world’s biggest war criminals?",
        "Have you ever thought of fighting crime by becoming a police officer?",
        "Do you think the punishment always fits the crime?",
        "Do you have any crime prevention tips?",
        "Have you ever committed a petty crime?",
        "Have you ever witnessed a serious crime?",
        "How can governments reduce crime?",
        "Is violent crime a big problem in your country?",
        "Do you think crime pays?",
        "Is juvenile crime on the increase in your country?",
        "Is organized crime a big problem in your country?",
        "What is hate crime?",
        "When can you say, “It’s a crime to do nothing”?",
        "Have you ever reported a crime?"
    ],
    "Current Events and News": [
        "Are you interested in current events and news?",
        "Is there a difference between news and current events?",
        "What stories have you been following recently?",
        "How many hours a day do you spend reading about, watching or listening to news?",
        "What is the latest news about your country?",
        "Are you interested in news from other countries?",
        "When did you first become interested in current events?",
        "Do you ever read or listen to the news in English?",
        "Would you prefer to study English using news materials or textbooks?",
        "Which area of current events would you like to be more knowledgeable about?",
        "Do you want to study current events in your English class?",
        "What kind of current events stories do you like?",
        "What sections of a newspaper or website do you check for current events (health, technology, business, etc.)?",
        "How current is current?",
        "How much time do you spend discussing current events with friends?",
        "What recent events are you fed up hearing about?",
        "How do you feel when you haven’t heard the news for a few days?",
        "How often does the news greatly affect your feelings?",
        "Which person in the news do you most like hearing or reading about?",
        "What is your favorite news source?"
    ],
    "Cyber-Bullying": [
        "What springs to mind when you hear the word ‘cyber-bullying’?",
        "How can someone be bullied in cyber-space?",
        "Do you think online bullying is worse than or not as bad as physical bullying?",
        "When did you first hear about cyber-bullying?",
        "What would you do if you were cyber-bullied?",
        "Why do cyber-bullies bully other people online?",
        "How much of a problem do you think cyber-bullying is?",
        "What can people do to stop cyber-bullying?",
        "Do Internet companies and mobile phone companies have a duty to stop cyber-bullying?",
        "Do you think there should be a punishment for cyber-bullying?",
        "What examples of cyber-bullying can you think of?",
        "Do you know anyone, or have you heard about anyone who has been cyber-bullied?",
        "How do you think cyber-bullying affects the life of those bullied?",
        "Isn’t it best simply not to visit the sites on which nasty comments or pictures are posted if you are being cyber-bullied?",
        "Don’t you think it would be easy for police to trace where nasty posts of text messages came from?",
        "What responsibilities do social networking sites have in stopping cyber-bullying?",
        "Do you think cyber-bullies and school or office bullies are different?",
        "Should someone who is being cyber-bullied go to the police?",
        "What questions would you like to ask a cyber-bully?",
        "How can governments educate people, especially children, about the harm cyber-bullying does?"
    ]
}
