export default {
    "Kangaroos": [
        "What comes to mind when you hear the word ‘kangaroo’?",
        "What do you know about kangaroos?",
        "Do you think kangaroos lead good lives?",
        "What three adjectives would you choose to describe kangaroos and why?",
        "What do kangaroos do during their days?",
        "What things do kangaroos worry about?",
        "Do you think kangaroos have skipping and jumping races?",
        "In Australia, kangaroos are pests and farmers shoot them. What do you think of this?",
        "Do you think a kangaroo would be a good pet?",
        "Do you think Australian people are proud to have kangaroos as wild animals in their country?",
        "Have you ever eaten or would you ever eat kangaroo meat?",
        "In what way is a kangaroo like Australia itself?",
        "What do you think kangaroos think of humans?",
        "What will kangaroos evolve into in 100 million years from now?",
        "Would you like to work with kangaroos – studying them, photographing them, helping protect them etc?",
        "Would you like to be a kangaroo?",
        "What similarities are there between kangaroos and humans?",
        "How would life be different if we could skip, hop and bounce as far as kangaroos can?",
        "What questions would you like to ask a kangaroo?",
        "What do you think its answers might be?"
    ],
    "Karate": [
        "What comes to mind when you hear the word ‘karate’?",
        "What do you know about karate?",
        "Do you think being a karate expert would be helpful in your life?",
        "How many people could a karate black belt fight off at one time?",
        "Do you think the karate you see in movies is the same as the karate you learn?",
        "What are the differences between karate, kung fu and tae kwon doe?",
        "What does the word ‘karate’ mean? Is it a good description?",
        "Do you think karate is the best form of self defense?",
        "Do you think karate should be an Olympic sport?",
        "Would you like to take karate lessons?",
        "Do you think karate should be taught at elementary schools?",
        "How would your life be different if you had a black belt in karate?",
        "What do you think karate teaches people about themselves?",
        "Bruce Lee once said: \"Karate is like an iron bar; Kung Fu is like an iron bar with a chain attached.\" What does this mean?",
        "What do you think karate training is like?",
        "Do you think actors get paid too much money?",
        "Who are the top actors in your country?",
        "How long do you think it takes to get a black belt in karate?",
        "What questions would you like to ask a karate expert?",
        "What do you think his/her answers might be?"
    ],
    "Kazakhstan": [
        "What images spring to mind when you hear the country Kazakhstan?",
        "What are the good things and bad things about Kazakhstan?",
        "What is Kazakhstan most famous for?",
        "What do you know about Kazakhstan’s history?",
        "What are the differences between Kazakhstan and your country?",
        "What do you think about Kazakh people?",
        "What has Kazakhstan given to the world?",
        "Would you like to visit Kazakhstan, or live there?",
        "What do you know about the geography of Kazakhstan?",
        "Who are the most famous Kazakh people you know?",
        "How different is Kazakhstan from other European/Asian countries?",
        "What was the last news story you heard about Kazakhstan?",
        "What do you think Kazakhstan’s neighbours think of it?",
        "What do you think Kazakhstan will be like 50 years from now?",
        "Does your country have good relations with Kazakhstan?",
        "What could you do on a holiday in Kazakhstan?",
        "What is your idea of a typical Kazakh person?",
        "What things about Kazakhstan do you think Kazakhs are proud of?",
        "What do you know about Kazakh culture?",
        "What would you like to ask a Kazakh person about Kazakhstan?"
    ],
    "Kenya": [
        "What images spring to mind when you hear the country Kenya?",
        "What are the good things and bad things about Kenya?",
        "What is Kenya famous for?",
        "What do you know about Kenyan history?",
        "What images of Kenya do you have that are beautiful and adventurous?",
        "What do you think about Kenya’s peoples?",
        "What has Kenya given to the world?",
        "Would you like to visit Kenya, or live there?",
        "What do you know about the geography of Kenya?",
        "Who are the most famous Kenyan people you know?",
        "How different is Kenya from other African countries?",
        "What do you know about Kenyan cultures?",
        "Why isn’t Kenya one of the richest countries in Africa?",
        "What do you think Kenya will be like 50 years from now?",
        "Does your country have good relations with Kenya?",
        "What do you think about Kenya’s wildlife?",
        "What is your idea of a typical Kenyan person?",
        "What things about Kenya do you think Kenyan people are proud of?",
        "What do you know about Kenyan politics?",
        "What would you like to ask a Kenyan person about Kenya?"
    ],
    "King Kong": [
        "What do you know about King Kong?",
        "What images of King Kong have you seen in your life?",
        "Have you seen any King Kong movies?",
        "What do you think the world thought of the original black and white movie of King Kong made in 1933?",
        "What kind of personality do you think King Kong has?",
        "What would happen to King Kong if he suddenly appeared on New York’s streets today?",
        "Did you ever want Godzilla to beat King Kong?",
        "It is said Godzilla represented Japan after WWII and King Kong represented America. What do you think of this?",
        "Is King Kong still one of the greatest screen monsters / heroes?",
        "What is the 21st Century screen monster that is as good as King Kong?",
        "What springs to mind when you hear the words ‘King Kong’?",
        "Do you often see King Kong in adverts in your country?",
        "What happened after King Kong fell to the ground after being killed on top of the Empire State Building?",
        "What do you think King Kong’s early life was like?",
        "Which King Kong movie is best, the 1933 original or the sequels that came after it?",
        "What would you do if you saw King Kong walking down your street?",
        "If you were King Kong, what would you do on the loose in New York?",
        "What do you think Queen Kong is like?",
        "What questions would you like to ask King Kong?",
        "What do you think his answers might be?"
    ],
    "Kissing": [
        "What springs to mind when you hear the word ‘kissing’?",
        "What do you think about kissing?",
        "When and why do you think kissing first started?",
        "What do you think an alien visiting our planet would think of people kissing?",
        "Do you think every nationality kisses?",
        "Is there anything unhealthy about kissing?",
        "What instructions would you give to someone who wanted to know how to kiss?",
        "If Mommy really kissed Santa Claus, was she cheating?",
        "What would you do if you saw your partner kissing someone else?",
        "Would you buy a “how to kiss” video?",
        "Do you think the French really invented the French Kiss?",
        "At what age is it OK for people to start kissing?",
        "Can you remember what your first real kiss was like?",
        "Do you think kissing on a crowded train is OK?",
        "Are you good at kissing?",
        "Is it OK for people in their seventies to French kiss in public?",
        "Do you think people will always kiss or will we grow out of it?",
        "What is the best movie kiss of all time?",
        "What’s kissing like with really bad breath?",
        "Are there, or should there be, any rules to kissing?"
    ],
    "Knowledge": [
        "What comes to mind when you hear the word ‘knowledge’?",
        "What’s the best way to increase your knowledge?",
        "Do you have more knowledge about life than your other family members?",
        "What important knowledge do you want to pass on to your children?",
        "Do you think people with a lot of knowledge are wise?",
        "What’s better to have, great imagination or lots of knowledge?",
        "Are people born with a better ability to learn knowledge than others?",
        "Have you ever been frustrated because of a lack of knowledge?",
        "Do you ever impress people with your knowledge?",
        "What’s the difference between knowledge and education?",
        "Is knowledge important?",
        "What subject are you most knowledgeable about?",
        "What subject would you like to be most knowledgeable about?",
        "People say knowledge is power – is this true?",
        "Is all knowledge useful?",
        "How is your general knowledge? Are you good at quizzes?",
        "What is the tree of knowledge and what would you like to take from it?",
        "What’s the biggest threat to society, knowledge or ignorance?",
        "What is more important, knowledge or common sense?",
        "Are you angry when people do things without your knowledge?"
    ],
    "Korea": [
        "What images spring to mind when you hear the country Korea?",
        "What are the good things and bad things about North and South Korea?",
        "What are North and South Korea famous for?",
        "What do you know about North and South Korean history?",
        "What images of North and South Korea do you have that are sad?",
        "What do you think about the fact that North and South Korean families cannot write to, telephone or see each other?",
        "What has North and South Korea given to the world?",
        "Would you like to visit North and South Korea, or live there?",
        "What do you know about the geography of North and South Korea?",
        "Who are the most famous North and South Korean people you know?",
        "How different are North and South Korea from each other and from other Asian countries?",
        "What do you know about the Korean War?",
        "Why isn’t North Korea as rich and as advanced as South Korea?",
        "What do you think North and South Korea will be like 50 years from now?",
        "Does your country have good relations with the two Koreas?",
        "What do you think about North Korea’s leader Kim Jong Il?",
        "What is your idea of a typical Korean person?",
        "What things about Korea do you think Korean people are proud of?",
        "What do you know about North and South Korean politics?",
        "What would you like to ask a North and South Korean person about North and South Korea?"
    ],
    "Kuwait": [
        "What images spring to mind when you hear the country Kuwait?",
        "What are the good things and bad things about Kuwait?",
        "What is Kuwait famous for?",
        "What do you know about Kuwaiti history?",
        "What images of Kuwait do you have that are exotic?",
        "What do you think about Kuwait?",
        "What has Kuwait given to the world?",
        "Would you like to visit Kuwait, or live there?",
        "What do you know about the economy of Kuwait?",
        "Who are the most famous Kuwaiti people you know?",
        "How different is Kuwait from other Middle Eastern countries?",
        "What do you know about Kenyan cultures?",
        "How would the world be different today if Saddam Hussein hadn’t invaded Kuwait?",
        "What do you think Kuwait will be like 50 years from now?",
        "Does your country have good relations with Kuwait?",
        "What do you think about Kuwait’s oil?",
        "What is your idea of a typical Kuwaiti person?",
        "What things about Kuwait do you think Kuwaiti people are proud of?",
        "What do you know about Kuwaiti culture politics?",
        "What would you like to ask a Kuwaiti person about Kuwait?"
    ]
}
