// this doesn't include Russia, which the website has in PDF form.

export default {
    "Racial Profiling": [
        "What images spring to mind when you hear the term ‘racial profiling’?",
        "What exactly is racial profiling?",
        "Is racial profiling OK if it leads to a reduction in terrorist attacks?",
        "In what ways are motorcycles better than cars?",
        "Do you agree with racial profiling in regards to airport security?",
        "Is racial profiling simply a form of government-sponsored racism?",
        "Does racial profiling lead to the harmful stereotyping of different races as criminals and/or terrorists?",
        "Do you think racial profiling will alienate those profiled and thus lead to greater social problems?",
        "What is an alternative to racial profiling?",
        "How would you feel if you were suspected of wrongdoing because of your colour or race?",
        "Does your government take part in racial profiling?",
        "Is racial profiling a good or a bad thing?",
        "What are governments’ arguments for carrying out racial profiling?",
        "Which races are targeted most under racial profiling? Is this fair?",
        "Do you think any government targets white people under racial profiling?",
        "Is it racial profiling or religion profiling? Which would be worse?",
        "Are you guilty of subconsciously (or otherwise) racial profiling?",
        "Is racial profiling the same as the law of probability?",
        "What do you know about the history of racial profiling?",
        "How do you think airport staff are trained in racial profiling?"
    ],
    "Racism": [
        "What images spring to mind when you hear the word ‘racism’?",
        "How much racism is there in your country?",
        "Have you ever been the victim of racism?",
        "What do you do when you see racism against others?",
        "Have you ever done anything to help stamp out racism?",
        "In which country do you think racism is worst?",
        "Why are people racist?",
        "Who is the biggest racist you know?",
        "Is racism getting worse or disappearing in your country?",
        "What kind of world would it be if there was no racism?",
        "Do you ever have racist thoughts?",
        "Do you think racism will ever disappear from this world?",
        "How do you explain racism to a child?",
        "What races do people in your country discriminate against?",
        "What punishments should there be for those guilty of racism?",
        "What’s the best way to stamp out racism?",
        "What’s the worst example of racism you’ve witnessed or experienced?",
        "Do you think racism feels differently to black, white, Asian, Indian, Arab… people?",
        "What adjectives would you use to describe racism?",
        "What is worse, racism, sexism or homophobia?"
    ],
    "Radio": [
        "What comes to mind when you hear the word ‘radio’?",
        "How important is the radio in your life?",
        "When is radio better than television?",
        "What kind of radio programmes do you prefer to listen to?",
        "Do you think radio is making a comeback with the Internet?",
        "Where do you usually listen to the radio?",
        "Do you think listening to the radio is a good way to improve your English?",
        "Which country makes the best movies?",
        "Who is your favourite movie star?",
        "Do you like listening to top-40 music radio shows?",
        "How often do you listen to the radio?",
        "Do you have a favourite radio show host?",
        "Did video kill the radio star?",
        "What’s the difference between FM and AM radio?",
        "Have you ever listened to a radio show from another country? What did you think?",
        "Would you like to work in radio?",
        "Would you buy an adaptor to add radio to your iPod?",
        "Do you think most radio stations play the same old boring music?",
        "When is the best time to listen to the radio?",
        "Do you think we’ll always have radio stations?"
    ],
    "Rain": [
        "What comes to mind when you hear the word ‘rain’?",
        "Do you like rain?",
        "How does rain change your feelings?",
        "Do you wish it rain more or rain less where you live?",
        "What kind of rain do you like?",
        "What do you like to do in the rain?",
        "Have you ever done a rain dance?",
        "Can you think of a time when it rained and you really wished it would stop?",
        "Do you think rain means the same thing to people in different countries?",
        "What do you think of the sound and smell of rain?",
        "Why does it rain cats and dogs in England?",
        "Do you think acid rain is still a problem?",
        "Do you think it’s OK to drink rainwater?",
        "Where does rain come from? How is it formed?",
        "Has anyone ever “rained on your parade”?",
        "When was the last time you got soaked in the rain?",
        "When can rain be dangerous?",
        "What’s the difference between drizzle, a shower, a downpour, the heavens opening, and heavy rain?",
        "Are there any poems or songs about rain in your language?",
        "What do you think of raindrops and rainbows?"
    ],
    "Ramadan": [
        "How do people celebrate Ramadan in your country?",
        "How do you feel the week and the day before Ramadan starts?",
        "What do you like most about Ramadan?",
        "Are you sad when Ramadan is over?",
        "What’s your best Ramadan memory?",
        "Do you think each Ramadan changes you as a person?",
        "What would you like non-Muslims to understand about Ramadan?",
        "Do you think Ramadan is hard on your body?",
        "What’s your favourite Ramadan food?",
        "Who do you think enjoys Ramadan more, children or adults?",
        "What springs to mind when you hear the word ‘Ramadan’?",
        "Do you say special prayers during Ramadan?",
        "Are there medical benefits to Ramadan?",
        "Do people in different countries celebrate Ramadan differently?",
        "Do you think all countries with Muslim population should have special national holidays to celebrate Ramadan?",
        "How would you explain what Ramadan is to someone who didn’t know?",
        "Do you ever feel Ramadan interrupts your daily schedule?",
        "Do you think the way people celebrate Ramadan today is different to how they celebrated it in the past?",
        "Would you like to go to another country to celebrate Ramadan?",
        "Would you prefer Ramadan to be at the same time every year or do you like the Ramadan period moving forward each year?"
    ],
    "Rap Music": [
        "What springs to mind when you hear the word ‘rap’?",
        "Do you like rap music?",
        "What’s the difference between rap and hip-hop?",
        "Do you think rap is as important a musical genre as jazz, soul and funk etc?",
        "What do you like or dislike about rap?",
        "Why do many rappers sing about violence?",
        "Do you think rappers get a bad rap from the press?",
        "How is rap different from other musical styles?",
        "Which rappers have been the most important?",
        "What do you think of non-American rappers?",
        "Do you think rap music has replaced rock music?",
        "Are good rappers poets?",
        "Is it necessary to wear the clothes and follow rap fashions to truly appreciate rap music?",
        "What topics do you like rappers to rap about?",
        "Do you think rap is misunderstood?",
        "Do old people like rap?",
        "Do you think rap artists are good role models for kids?",
        "What would you say to someone who said rap isn’t music?",
        "Would you like to learn English through rap songs?",
        "What’s the difference between rap and rock?"
    ],
    "Reading": [
        "What images spring to mind when you hear the word ‘reading’?",
        "What are your earliest memories of reading?",
        "What do you get out of reading?",
        "Would you like to read more?",
        "How important is reading?",
        "What do you enjoy reading most?",
        "How could you get someone who hates reading to like reading?",
        "Do you prefer reading books, newspapers, magazines or things on the Internet?",
        "Have you ever cried while reading a book?",
        "What books do you think should be required reading?",
        "How varied are your reading/literary tastes?",
        "Do you like reading in English?",
        "Are you better in English at reading or listening?",
        "Is reading the book better than watching the movie?",
        "Are you good at speed reading? Are you a fast reader?",
        "What are reading skills? Which ones are you good at and which ones do you need to work on?",
        "What new books have you read recently?",
        "Do you have a favourite reading teacher?",
        "Do you like reading stories to children?",
        "How different do you think reading will be in the future?"
    ],
    "Reading Activities": [
        "What comes to mind when you hear the term ‘reading activity’?",
        "What do you think when your teacher says you’re going to do some reading?",
        "What kind of reading practice do you need most? Which reading skills do you need to improve?",
        "Do you like the reading activities your teacher gives you?",
        "Do you have an example of how a reading lesson really improved your reading?",
        "Do you know of any websites that have good reading activities?",
        "How different is reading in English to reading in your own language?",
        "Do you always understand the reasons why the teacher asks you to do a particular reading activity?",
        "What are your biggest problems with reading?",
        "How important are reading activities compared with writing, speaking and listening activities?",
        "Do you like doing reading activities in class?",
        "Do you ever think reading activities are a waste of time?",
        "Do you prefer reading things in books and magazines or reading things on the Internet?",
        "Is the topic important when you do a reading activity?",
        "What things are important for a reading activity to be successful?",
        "What advice would you give to a student who says he/she is no good at reading or hates reading?",
        "How does the ability to read in English improve your life?",
        "Are there some things you like reading in English more than you do in your own language?",
        "Do you think you need reading practice in every class?",
        "What questions would you like to ask your teacher about reading?"
    ],
    "Recycling": [
        "What comes to mind when you hear the word ‘recycling’?",
        "How does recycling benefit the planet?",
        "Are you good at recycling things?",
        "Does your town do enough recycling?",
        "What would the world be like without recycling?",
        "Do you think recycling is here to stay or will we go back to a disposable goods lifestyle?",
        "What would you think if your neighbours never recycled anything?",
        "How much good do you think you’re doing when you recycle things?",
        "What things do you throw away that you think should be recycled?",
        "What do you think of the idea of water recycled from sewage?",
        "Should recycling be mandatory?",
        "What fines should people have to pay if they do not recycle?",
        "Do you think only ‘educated’ people recycle?",
        "Have you been to other countries where recycling is much better or worse than in your country?",
        "What should schools teach children about recycling?",
        "What kinds of things do you think cannot be recycled?",
        "What are your feelings towards the recycling of nuclear waste?",
        "Should there be a reward system for people who recycle things?",
        "What do you think of the idea of having a special minister for recycling in the government?",
        "Which is better, recycling or buying only the things we really need?"
    ],
    "Red": [
        "What comes to mind when you hear the word ‘red’?",
        "What would the world be like without the colour red?",
        "Is the colour red important in your country’s culture?",
        "What things look good in red and what things do not?",
        "How would you feel if you lived in a red house with everything red inside?",
        "What human characteristics does the colour red represent?",
        "When was the last time you “saw red”?",
        "Have you ever been “in the red” with the bank?",
        "If a person’s favourite colour is red, what kind of person are they?",
        "Why aren’t red wine, red meat and red hair really red?",
        "Have you ever been caught red-handed doing something you shouldn’t?",
        "What red objects do you like most?",
        "Why do the Red Cross and Red Crescent organizations use the colour red?",
        "Do you like the word ‘red’?",
        "Do you ever get fed up of the red tape in local and national governments?",
        "What idioms or expressions are there in your language using the word ‘red’?",
        "What feelings does the colour red express?",
        "When was the last time you painted the town red?",
        "Do you think brands like Ferrari and Coca Cola are better red?",
        "Do you get a lot of red writing on your paper when your teacher returns your homework?"
    ],
    "Refugees": [
        "What comes to mind when you hear the word ‘refugee’?",
        "What makes a refugee a refugee?",
        "Are there many refugees in your country?",
        "What rights do and don’t refugees have?",
        "Do you think the image of refugees has changed over the years?",
        "What’s the difference between political refugees and economic refugees?",
        "What do you think it’s like to suddenly lose your home and way of life and end up on a refugee camp?",
        "What problems do refugees bring to the countries they go to?",
        "What benefits are there to countries who accept refugees?",
        "When do you think the concept of refugees first started?",
        "How do you think countries decide who is a refugee and who isn’t?",
        "Can you be a refugee in your own country?",
        "What rights and benefits should a country give to those who give refugee status to immigrants?",
        "If a refugee camp turns into a bustling town with businesses, roads and communities, is it still a refugee camp?",
        "What should people do on World Refugee Day (June 20)?",
        "What do you know about the UN’s refugee agency, the UNHCR (United Nations High Commission for Refugees)?",
        "What’s the difference between a refugee, a migrant and an internally displaced person?",
        "Where do you think today’s refugees from Darfur, Iraq, Burma and Palestine will be twenty years from now?",
        "Would you give money to refugee charities?",
        "What questions would you ask a refugee?"
    ],
    "Religion": [
        "What comes to mind when you hear the word ‘religion’?",
        "What does religion mean to you?",
        "Is religion always a good thing?",
        "With all the religions in the world, how do we know which one is best or true?",
        "Do people choose their religion or do people’s parents choose it?",
        "If religion is all about love and peace, why are many of the world’s conflicts and wars caused by religion?",
        "If religion teaches us that all men and women are equal and we must love everyone the same, why is there so much racism?",
        "Do you like talking about religion?",
        "What do you think of the argument that religion is really modern-day superstition?",
        "What would the world be like without religion?",
        "Why do you practice your religion (or why don’t you have a religion)?",
        "How does religion give hope to so many people?",
        "Do you think people will eventually stop believing in religion?",
        "What do you think of new religions?",
        "Do people who follow a religion have a better time than those who don’t?",
        "Do you think religion always fits our modern-day world?",
        "What would Jesus, Mohamed and Buddha think of our world today?",
        "Do you think there’ll ever be a single world religion?",
        "Money is more important than religion and shopping malls are more popular than places of worship. What do you think about this?",
        "How did religion start?"
    ],
    "Rent": [
        "What comes to mind when you hear the word ‘rent’?",
        "Do you think landlords charge too much for rent?",
        "Is it better to rent or buy property?",
        "Should kids with jobs pay rent to their parents?",
        "What do you need to think about before renting a place to live?",
        "How important are rent agreements?",
        "How do you find rented accommodation in your town?",
        "Would you rent out a room in your house to a lodger?",
        "What are the advantages and disadvantages of renting rather than buying?",
        "How often should a landlord put the rent up?",
        "What experiences do you have of paying rent?",
        "Would you rather rent an apartment or a house?",
        "Would you rather rent somewhere just for yourself or with friends?",
        "What would you worry about if you rented your house or apartment to someone?",
        "Would you feel like it’s your real home if you rented?",
        "If you rented your property, would you keep visiting it to keep an eye on it?",
        "What’s the most you would pay in rent?",
        "How should rent be divided between four people in a 3-bedroom house, when 2 people share one bedroom?",
        "What is a good landlord and a bad landlord?",
        "Would you spend money on wallpaper, paint, the garden, etc. if you lived in rented accommodation?"
    ],
    "Research": [
        "What comes to mind when you hear the word ‘research’?",
        "What would you like to research?",
        "How important is research?",
        "What are a few things you have researched recently?",
        "Would you like to work as a researcher?",
        "What would you like your government to spend more money on researching?",
        "What things do you think humans first started researching?",
        "How many answers are there still to find and how many things still to research?",
        "What are the biggest breakthroughs researchers have made recently?",
        "Does research always lead to positive things?",
        "What is market research? Do you like being surveyed by market researchers?",
        "What are your views on stem cell research?",
        "What do you think a medical researcher does on an average day?",
        "What do you think about using animals for research?",
        "Do you think that some research your government pays for is totally useless?",
        "Have you ever had to write a research paper?",
        "Do you like online research?",
        "A research project found out that teenagers were moody. What do you think of people getting paid to find this out?",
        "What piece of research would you like to do on your class/family/friends today?",
        "Would you volunteer to be a guinea pig in laboratory research of new medicines or medical treatments?"
    ],
    "Restaurants": [
        "What comes to mind when you hear the word ‘restaurant’?",
        "What is your favourite restaurant and why?",
        "Do you like expensive restaurants?",
        "How often do you go to restaurants?",
        "Do you think the ambience is important in restaurants?",
        "What kind of restaurant would you like to open?",
        "What’s the best restaurant name you’ve heard of?",
        "Are you happy with the restaurants in your town?",
        "Is restaurant food the best?",
        "Have you ever complained about the food or service in a restaurant?",
        "If you could have your own restaurant, what would you call it?",
        "What do you think of fast food restaurants?",
        "Would you go to a romantic restaurant with a friend?",
        "What do you think people study on a restaurant management course?",
        "Do you prefer restaurants that are cheap and cheerful or very fancy?",
        "Do you think you should tip the staff in restaurants?",
        "Would you like to work as a restaurant critic?",
        "What’s the longest you’d wait for a restaurant table?",
        "What’s the most expensive meal you’ve had at a restaurant?",
        "Would you like to eat at a different restaurant every night for the rest of your life?"
    ],
    "Retirement": [
        "What comes to mind when you hear the word ‘retirement’?",
        "Are you looking forward to your retirement?",
        "What do you think you’ll do in your retirement?",
        "Do you think people who retire miss working?",
        "What’s the best age for retirement?",
        "What do you think of famous people who come out of retirement?",
        "Would you like to aim for an early retirement?",
        "What do you think of the idea of living on a retirement home?",
        "“A retired husband is often a wife's full-time job.” (Ella Harris) What do you think?",
        "Do you think the challenge of retirement is how to spend time without spending money?",
        "In what ways do you think retirement might be stressful?",
        "Would you move if you lived in a country where natural disasters were common?",
        "What do you think you’ll do more of in your retirement?",
        "Does retirement scare you?",
        "Do you think retirement might be the best years of your life?",
        "What problems does a country have if too many of its citizens are in retirement?",
        "Are you putting money away for your retirement?",
        "Is retirement the end of useful life or a new beginning?",
        "Do you think retirement is when you stop living at work and begin working at living?",
        "“Retirement is wonderful. It's doing nothing without worrying about getting caught at it.” (Gene Perret) Do you agree?"
    ],
    "Rice": [
        "What comes to mind when you hear the word ‘rice’?",
        "What rice dishes do you like?",
        "Which is better, rice or potatoes?",
        "What can you do with rice?",
        "Do you like creamy rice pudding?",
        "Japanese people mix tea with rice. What do you think of this?",
        "Which country grows the world’s tastiest rice?",
        "Do you prefer white rice or brown rice?",
        "What’s your favourite way to prepare rice?",
        "Why do people throw rice at weddings?",
        "What part does rice play in your culture?",
        "Is using a rice cooker the best way to cook rice?",
        "What images do you have of rice paddies?",
        "What things can you do with rice paper?",
        "Are Chinese rice dishes, Indian rice dishes, Thai rice dishes, Japanese rice dishes… best?",
        "What seasonings and spices go best with rice?",
        "What do you know about how rice grows?",
        "What do you know about the nutritional value of rice?",
        "What would you tell someone about rice who knew nothing about it?",
        "What would the world do if rice suddenly disappeared?"
    ],
    "Risk": [
        "What images spring to mind when you hear the word ‘risk’?",
        "Do you take a lot of risks in life or are you risk averse?",
        "What’s the biggest risk you’ve ever taken?",
        "What risks are there in your normal daily life?",
        "What health risks do you worry about?",
        "What is something you would risk your life to get?",
        "What are the risks of using the Internet?",
        "What are the risks of not taking risks?",
        "Would you do a job that was full of risks?",
        "“Only a person who risks is free.” (Unknown) Do you think this is true?",
        "Would life be boring without risk?",
        "Are risk-takers more successful in life?",
        "Do you think life is riskier today than it was 50 years ago?",
        "What is risk management? Have you ever applied it in your life?",
        "What risks have you taken that have gone wrong, and which have worked?",
        "Have you ever taken a risk with money and it paid off?",
        "If you invested money, would you be cautious and spread your risks, or be adventurous and invest in high-risk investments?",
        "How do the risks in our life change as we move through childhood to old age?",
        "Do you live in a town that is risky to live in?",
        "Do you need to take risks to be better at English?"
    ],
    "Road Rage": [
        "What images spring to mind when you hear the term ‘road rage’?",
        "Is there a lot of road rage in your country?",
        "What causes road rage?",
        "Do people’s personalities change once they are behind the wheel of a car?",
        "What kind of people are more likely to commit acts of road rage?",
        "What’s the worst incident of road rage you’ve ever witnessed?",
        "Have you ever been a victim of road rage?",
        "Do you get angry with other drivers?",
        "Is road rage worse in your country or in other countries?",
        "Do the police do enough to prevent road rage?",
        "What would / do you do if someone hoots and flashes you from behind?",
        "What kinds of driving makes people angry?",
        "What bad driving habits from other drivers make you really angry?",
        "Do you ever think it’s dangerous to hoot (sound your horn at) another car out of anger?",
        "Why do you think some people get so angry at the wheel that they physically attack and sometimes kill other drivers?",
        "How should governments deal with road rage?",
        "How would you deal with an extremely angry motorist who was ranting and raving at you?",
        "Why do a lot of people’s manners and courtesy go out the window when they get behind the wheel?",
        "Do you think road rage will become more or less common?",
        "Do you think it’s possible for someone to never get angry while driving?"
    ],
    "Robots": [
        "What images spring to mind when you hear the word 'robot'?",
        "Will robots take over the world one day?",
        "The West sees robots as evil and dangerous, Japan sees them as helpful and cute. What do you think?",
        "Which is your favourite movie about robots?",
        "If you had a robot, what would you like it to do?",
        "What role will robots play in our society later this century?",
        "Will robots ever like identical to humans?",
        "Do you think robots will ever have emotions or be able to love?",
        "What would happen if you programmed a robot to hate and to build other robots that hated?",
        "What name would you give to your robot?",
        "Will robots have rights? What will robot rights be?",
        "When do you think robots will replace McDonalds workers?",
        "Have you ever felt as though you were a robot?",
        "Do you think people will have robots as companions, instead of a pet?",
        "What would society be like if robots took over our jobs?",
        "Could a robot football team ever beat a human football team?",
        "Would you rather deal with a robot or a human in a store or government department?",
        "Would you cry if your robot of ten years died?",
        "How much of the human body will be replaced by machines? Will we be androids in the future?",
        "Would a robot be a better leader than the leader of your country?"
    ],
    "Rock and Roll": [
        "What images spring to mind when you hear the term ‘rock and roll’?",
        "Do you like rock and roll?",
        "What do you know about the history of rock and roll?",
        "How is today’s rock and roll different from that in the 1950s?",
        "What impact has rock and roll had on society?",
        "John Lennon famously said the Beatles were more popular than Jesus and questioned: “I don't know which will go first, rock 'n' roll or Christianity” What do you think?",
        "Who are the greatest rock and roll stars?",
        "“Sex and drugs and rock and roll.” Is this your ideal lifestyle?",
        "What kind of rock and roll star would you like to be?",
        "Keith Richards of the Rolling Stones said rock and roll is “music for the neck downwards.” Do you agree with him?",
        "What exactly is rock and roll?",
        "Is rock and roll America’s greatest cultural export?",
        "Why is rock and roll called rock and roll?",
        "What do you think of Elvis Presley?",
        "Salman Rushdie said rock and roll is the music of freedom and that frightens people. Do you agree with him?",
        "Muddy Waters said: “The blues had a baby and they called it rock and roll.” What do you think of this?",
        "Is American rock and roll the best?",
        "Which rock and roll artists would you love to meet and go to a karaoke bar with?",
        "Is rock and roll as exciting today as it was in the 50s and 60s?",
        "Is hip hop and rap taking over from rock and roll?"
    ],
    "Romania": [
        "What images spring to mind when you hear the country Romania?",
        "What are the good things and bad things about Romania?",
        "What is Romania most famous for?",
        "What do you know about Romanian history?",
        "What images of Romania do you have that are beautiful and mysterious?",
        "What do you think about Romanians?",
        "What has Romania given to Europe and the world?",
        "Would you like to visit Romania, or live there?",
        "What do you know about the geography of Romania?",
        "Who are the most famous Romanian people you know?",
        "How different is Romania from other European countries?",
        "What do you know about the different Romanian cultures?",
        "What do you think Romania’s neighbours think about Romania?",
        "What do you think Romania will be like 50 years from now?",
        "Does your country have good relations with Romania?",
        "What do you think about Romania’s leaders?",
        "What is your idea of a typical Romanian?",
        "What things about Romania do you think Romanians are proud of?",
        "What do you know about Romanian politics?",
        "What would you like to ask a Romanian about Romania?"
    ],
    "Roses": [
        "What comes to mind when you hear the word ‘rose’?",
        "Is the rose the most beautiful flower in the world?",
        "Why are roses associated with romance?",
        "What colour roses do you like best?",
        "Has you ever given someone a rose or a bunch of roses?",
        "Can you name all of the parts of the rose?",
        "Do you think roses are most commonly associated with England?",
        "If a red rose is for love, what are white, yellow and pink roses for?",
        "What do you think of the name ‘Rose’ for a newborn baby (girl)?",
        "“Life is a rose; beware of the thorns.” What do you think of this?",
        "Is it more romantic to give a single rose or a dozen?",
        "Do you like the smell of roses?",
        "Why do you think people put rose petals in their bath?",
        "What does the expression “like a rose between two thorns” mean?",
        "If a rose were human, what kind of personality would it have?",
        "Does a rose have any meaning or importance in your culture?",
        "Why are rose tattoos so popular?",
        "In what way is love like a rose?",
        "Do men like receiving roses too?",
        "Do you think roses are good for your health?"
    ],
    "Rubbish": [
        "What images spring to mind when you hear the word ‘rubbish’?",
        "Do you create a lot of rubbish?",
        "Do you always put your rubbish in rubbish bins?",
        "Do you think your country produces too much rubbish?",
        "Have you ever bought something and then thought it was rubbish when you got home?",
        "Is there a lot of rubbish in the streets in your town?",
        "Do you prefer the word ‘rubbish’, ‘trash’ or ‘garbage’?",
        "Have you ever said “That’s rubbish!” in English when you disagreed with what someone said?",
        "Why is there so much rubbish on TV?",
        "What will happen when we run out of land to use as rubbish dumps?",
        "What are the laws in your town concerning the recycling of rubbish?",
        "What music do you think is total rubbish?",
        "Which person in the world do you think usually talks absolute rubbish?",
        "What’s the difference between rubbish and litter?",
        "What does “to rubbish” someone (or their ideas) mean? Have you ever rubbished someone or have you ever been rubbished?",
        "Are there newspapers in your country that often print a load of rubbish?",
        "Have you ever thought “He’s/She’s a rubbish actor / football player / singer”?",
        "What’s the solution to the world’s rubbish problem?",
        "How often should rubbish collection take place?",
        "What city have you been to where the streets were full of rubbish?"
    ],
    "Rudeness": [
        "Are you sometimes rude?",
        "What do you think about rudeness?",
        "What acts of rudeness bother you most?",
        "Is rudeness a problem in your country?",
        "What did your parents tell you about being rude?",
        "Blowing your nose in public is OK in England but rude in Japan. Slurping noodles is OK in Japan but rude in England. Who decides what’s rude and what’s not?",
        "Who is the rudest person you know?",
        "What rude behaviour do you see in public every day?",
        "What do you do when sales staff in shops or waiting staff in restaurants are very rude?",
        "If someone is rude to you, are you generally rude back?",
        "What springs to mind when you hear the word ‘rudeness’?",
        "Is your society becoming ruder or more polite?",
        "Which nationalities do you think are overly rude?",
        "Do cars make people rude?",
        "Are there many rude words in your language?",
        "How do you deal with someone who is very rude to you?",
        "Do you think it’s rude to correct someone’s grammar mistakes in a conversation?",
        "Should being rude be made a crime?",
        "Do you like watching one person being very rude to another person?",
        "Why is it rude to ask someone’s age?"
    ],
    "Rwanda": [
        "What images spring to mind when you hear the country Rwanda?",
        "What are the good things and bad things about Rwanda?",
        "What is Rwanda most famous for?",
        "What do you know about Rwandan history?",
        "Do you think Rwandans will live together in peace from now?",
        "What do you think about Rwandans?",
        "What has Rwanda given to Africa and the world?",
        "Would you like to visit Rwanda, or live there?",
        "What do you know about the geography of Rwanda?",
        "Who are the most famous Rwandan people you know?",
        "How different is Rwanda from other African countries?",
        "What do you know about the different Rwandan cultures?",
        "What do you think Rwanda’s neighbours think about Rwanda?",
        "What do you think Rwanda will be like 50 years from now?",
        "Does your country have good relations with Rwanda?",
        "What do you think about Rwanda’s leaders?",
        "What is your idea of a typical Rwandan?",
        "What things about Rwanda do you think Rwandans are proud of?",
        "What do you know about Rwandan politics?",
        "What would you like to ask a Rwandan about Rwanda?"
    ]
}
