export default {
    "OK": [
        "What comes to mind when you hear the abbreviation ‘OK’?",
        "How many meanings of ‘OK’ do you know?",
        "How does different pronunciation change the meaning of ‘OK’?",
        "Do you prefer the spelling ‘OK’ or ‘okay’?",
        "‘OK’ (or ‘okay’) is a verb, a noun, an adverb and an adjective. Can you think of examples of each in a sentence?",
        "Is the word ‘OK’ used in your language?",
        "Do you think there’s a more recognized or more useful word than ‘OK’ on our planet?",
        "What is the difference between ‘OK’ and ‘AOK’?",
        "Can you complete this question and then answer it? “Is it OK If I ____”?",
        "Do I look OK?",
        "Do you think ‘OK’ is a word or abbreviation?",
        "Do you think ‘OK’ is a useful abbreviation?",
        "What do you think the ‘O’ and ‘K’ might stand for?",
        "Can you complete this question and then answer it? “Is it OK to ____”?",
        "Would you be OK with having English as your country’s official language?",
        "Name something you’re just OK at doing. Why are you just OK at this?",
        "Are you okay?",
        "In English, a longer form of ‘OK’ is ‘okie dokie’ (meaning yes, sure). What do you think of this?",
        "What things are not OK to do in your house?",
        "If someone described you as being OK, would you be happy or unhappy with the description?"
    ],
    "Obesity": [
        "What comes to mind when you hear the word ‘obesity’?",
        "What do you know about obesity?",
        "How much of a problem is obesity in your country?",
        "Which people in your country are obese?",
        "Why is obesity bad for your health?",
        "Why is obesity increasing?",
        "What should governments do to combat obesity?",
        "Do you think obese people should pay higher medical charges?",
        "Why don’t parents do enough to stop their children from becoming obese?",
        "Is obesity immoral when so many people in the world are starving?",
        "Which is worse, obesity or anorexia?",
        "Should schools ban junk food to fight obesity?",
        "Do you think obesity will be more of a problem in the future?",
        "Do you think there are any drugs that can reduce obesity?",
        "Do you think children should be taken into care if their parents let them become obese?",
        "Do you see nay relationship between obesity and video games?",
        "Should there be a “fat tax” on food that is very high in calories?",
        "What do you think of the “big is beautiful” phenomena in the USA?",
        "Is obesity a disease or a choice?",
        "Do you think obese people should have special seats in airplanes and pay more money?"
    ],
    "Oceans": [
        "What comes to mind when you hear the word ‘ocean’?",
        "Are you an ocean or a mountain person?",
        "What adjectives would you use to describe oceans?",
        "What experiences have you had in your life with oceans?",
        "How important are oceans?",
        "Would you like a job as an oceanographer?",
        "What’s the scariest thing about oceans?",
        "In what ways are you like an ocean?",
        "What are the most beautiful creatures living in the oceans?",
        "How do the oceans affect the weather?",
        "What is an ocean?",
        "What’s the difference between an ocean and a sea?",
        "What fun things can you do in the ocean?",
        "Do you have different images of the different oceans in the world?",
        "What would you like to know about oceans?",
        "What would you do if you owned a whole ocean?",
        "What do you know about the El Nino effect?",
        "Do you think there should be more ocean than land or more land than ocean?",
        "Are the world’s oceans in danger? How can we protect them?",
        "What scary monsters live at the very, very bottom of the ocean?"
    ],
    "October": [
        "What springs to mind when you hear the word ‘October'?",
        "What do you think of the month of October?",
        "What good things happen in October?",
        "What things do you usually do in October?",
        "What do you think of the word 'October'?",
        "What are people who are born in October like?",
        "What do you think of October weather?",
        "Where is October on the list of 'the best months'?",
        "Are there any bad things about the month of October?",
        "What plans do you have for next October?",
        "If you made a October festival, what would you it be like?",
        "Is there any delicious food you eat in October?",
        "How should people celebrate in October?",
        "What famous holidays are there in October?",
        "How do you feel when October arrives?",
        "If you made a video about October, what would you put in it?",
        "How do you feel when October is over?",
        "What three adjectives best describe October, and why?",
        "What good thing can you remember happening in October?",
        "What is a good symbol for October, and why?"
    ],
    "Oil": [
        "Why is oil so important?",
        "What do you think of oil companies?",
        "What will happen when the oil runs out?",
        "Do you think taking all of the oil from under the earth and oceans is dangerous?",
        "How will oil-producing companies survive financially when their oil has all run out?",
        "Are you interested in what happens to oil prices?",
        "What do you know about oil crises?",
        "Do you think Iraq was really invaded because of oil?",
        "What do you know about OPEC?",
        "What environmental impact does oil production have?",
        "What springs to mind when you hear the word ‘oil’?",
        "Why do you think oil money isn’t used to reduce poverty?",
        "How can oil be owned by a company or country when it’s part of the Earth’s natural resources?",
        "Do you think oil companies are ethical?",
        "What would you like to change about oil companies?",
        "Why aren’t the citizens of oil producing companies very rich?",
        "Do you think oil companies do enough to protect the environment, especially after oil spills in the ocean?",
        "What is oil used for?",
        "Should oil companies all be owned by governments, who would then share oil profits with their citizens?",
        "What would the world be like if the world’s oil ran out tomorrow?"
    ],
    "Old Age": [
        "What comes to mind when you hear the term ‘old age’?",
        "Do you worry about your old age?",
        "What do you think old age is like?",
        "How will your life be different when you reach your old age?",
        "When does old age start?",
        "Is it important to prepare financially for old age?",
        "How and why do people die of old age?",
        "How many people do you know who are enjoying their old age?",
        "What new hobbies will you take up in your old age?",
        "How is old age different from being middle aged?",
        "Are you looking forward to your old age?",
        "Do you think life in your old age will be better or worse than now?",
        "What things are there to look forward to about old age?",
        "What can people in old age teach younger people?",
        "What social problems are associated with old age?",
        "Would you consider living in an old age home when you’re older?",
        "How would the world be different if life-prolonging drugs meant old age stared at the age of 105?",
        "Does your government care for people in old age?",
        "Would you like to live to an old age? How old?",
        "Do you think people in old age look at the world differently?"
    ],
    "Olympics": [
        "What comes into your mind when you hear the word 'Olympics'?",
        "Are you a big fan of the Olympics?",
        "Which Olympic Games can you remember well?",
        "Would your town be good at hosting the Olympics?",
        "How does a country benefit from hosting an Olympics?",
        "Do your country’s athletes do well in the Olympics?",
        "What is your favourite event at the Olympics and why?",
        "What do you know about the Olympics rings and flag?",
        "What do you think it’s like to win Olympic gold and stand on the podium with your national anthem playing?",
        "Which is best - the opening ceremony or the closing ceremony?",
        "Is the Olympics the best sports event in the world?",
        "Would you like to carry the Olympics torch?",
        "Do you think the Olympics should only be for amateur athletes and not professional athletes?",
        "Do you think sumo should be in the Olympics?",
        "Which is better, the winter or summer Olympics?",
        "Who do you think is the greatest ever Olympian (Olympic athlete)?",
        "Do you think the 2020 Tokyo Olympics will be super successful?",
        "Which Olympic record would you like to break?",
        "Why are the Olympics always held in rich cities? Should they be held in a poor country for once?",
        "What do you know about the history of the Olympics?"
    ],
    "Oman": [
        "What images spring to mind when you hear the country Oman?",
        "What are the good things and bad things about Oman?",
        "What is Oman famous for?",
        "What do you know about Omani history?",
        "What images of Oman do you have that are exotic?",
        "What do you think about Oman?",
        "What has Oman given to the world?",
        "Would you like to visit Oman, or live there?",
        "What do you know about the economy of Oman?",
        "Who are the most famous Omani people you know?",
        "How different is Oman from other Middle Eastern countries?",
        "What do you know about Oman’s culture?",
        "Do you think Oman is a good tourist destination?",
        "What do you think Oman will be like 50 years from now?",
        "Does your country have good relations with Oman?",
        "What does your country have in common with Oman?",
        "What is your idea of a typical Omani person?",
        "What things about Oman do you think Omani people are proud of?",
        "What do you know about Oman’s geography?",
        "What would you like to ask an Omani person about Oman?"
    ],
    "One": [
        "In what ways is the number one better than the number one hundred?",
        "Which of your loved ones are you closest to?",
        "Have you ever been number one?",
        "Can you describe one member of your family in one word?",
        "Do you read books one by one or can you read them simultaneously?",
        "Would you prefer language lessons one-to-one or do you like having other students around?",
        "Have you ever done something that was a one-off – never to be repeated?",
        "How do you know when you’ve met ‘the one’ – your perfect partner?",
        "Do you like to compete with people and get one up on them?",
        "What do you think the expressions “one love” and “one world” mean?",
        "What are your feelings towards the number one?",
        "Who is number one in this world and in your world?",
        "If you could have just one more of something, what would it be?",
        "Do you know anyone who is a one in a million?",
        "Are you at one with the world?",
        "If you had one wish, what would it be?",
        "If someone asked to be excused to go and do a number one, where would he or she be going? What do you think of this expression?",
        "The song “One” by U2 was voted the best song ever? What do you think of this?",
        "How would your friends describe you using this pattern – “S/he’s the one who……”?",
        "Do you think “One” would be a good name to give your child?"
    ],
    "Operations": [
        "What comes to mind when you hear the word ‘operation’?",
        "Have you ever had an operation?",
        "Would you like to see an operation?",
        "Would you rather be conscious or unconscious if you had an operation?",
        "What do you think goes through people’s mind the night before an operation?",
        "Do you think there are any operations that are risk free?",
        "Have you ever heard any stories about people being given the wrong operation?",
        "What would be the scariest operation for you?",
        "How do you think operations have changed over the decades?",
        "Do you prefer the British English noun ‘operation’ or the American English ‘surgery’?",
        "Would you try cosmetic surgery? Which part of your face or body would you change?",
        "What’s the difference between cosmetic and plastic surgery?",
        "Do you think surgery in the future will be performed without cutting the body open?",
        "What would your reaction be if your doctor said you needed open heart or brain surgery?",
        "Do you think keyhole surgery is picking a lock or operating on someone by only making a tiny hole in their body?",
        "How much dental surgery have you had?",
        "If it were possible, would you prefer to have surgery at home?",
        "Would you trust having surgery in other countries?",
        "Would you let student doctors to perform surgery on you for a fee?",
        "How will surgery be different fifty years from now?"
    ],
    "Opinions": [
        "What comes to mind when you hear the word ‘opinion’?",
        "Do people usually agree or disagree with your opinions?",
        "What do you have strong opinions on?",
        "What’s your opinion of yourself?",
        "In your opinion, what is an opinion?",
        "Is there anyone whose opinions you strongly disagree with?",
        "Do you always consider other people’s opinions before making decisions?",
        "Whose opinion do you value most?",
        "What do you usually ask people’s opinions on?",
        "Do you have an opinion on everything?",
        "Are opinions important?",
        "Is it better to talk about and share opinions or keep them to yourself?",
        "Have you ever upset anyone with your opinions?",
        "Have you ever been afraid to give your opinion?",
        "Has anyone ever given you an opinion that you didn’t want?",
        "What’s your opinion on life?",
        "What’s your opinion of me?",
        "Do you like looking at opinion polls?",
        "Do you always have healthy or unhealthy differences of opinion with people?",
        "Do always give your honest opinion when asked for it or do you sometimes bend the truth?"
    ],
    "Organ Transplants": [
        "What comes to mind when you hear the phrase ‘organ transplants’?",
        "What organs can be transplanted?",
        "What do you think of organ transplants?",
        "What do you think of people who refuse organ transplants?",
        "Do you think organ transplants will become much more common in the future?",
        "Do you think body parts from animals will be used in organ transplants in the future?",
        "Do you think brain transplants will be possible in the future?",
        "Would you like to be a doctor who performs organ transplants?",
        "Would you give up one of your kidneys or half of your liver to save the life of a friend?",
        "What do you think of face transplants?",
        "What do you know about organ transplants?",
        "Would you allow the organs of a loved one to be transplanted?",
        "Would you accept to have an animal’s heart if it could save your life?",
        "What would you think if your government paid for a serial killer in prison to have an organ transplant?",
        "Which of your organs would you want for organ transplants after you die?",
        "Are you a different person if you have a heart transplant?",
        "Would you like to see an organ transplant?",
        "How worried would you be if your doctor said you needed an organ transplant?",
        "What are the dangers of organ transplants?",
        "If you could clone yourself to have a stock of body parts for future organ transplants, would you?"
    ],
    "Over": [
        "Do you know anyone who always overacts? Does this annoy you?",
        "When was the last time something or someone overawed you?",
        "Have you ever been overcharged for something? Did you get your money back?",
        "Have you ever been overcome with emotion?",
        "What places do you know that are overcrowded?",
        "Have you ever overdone something and ruined it?",
        "What do you think of bank overdrafts?",
        "Do you ever take books back to the library that are overdue?",
        "When was the last time you were overjoyed?",
        "Do you often go on overnight trips?",
        "What do you think about our overpopulated world?",
        "What strong smells do you think are overpowering?",
        "Do you think sex is overrated?",
        "How often do you go overseas?",
        "When was the last time you overslept? Did you get into trouble for it?",
        "Have you ever overstayed your welcome?",
        "Have you ever overstepped the mark and made people angry?",
        "Do you think there should be a ban on cars overtaking each other?",
        "What do you think of overtime? Do you do it?",
        "What’s your advice for people who are overweight?"
    ],
    "Overpopulation": [
        "What springs to  mind when you hear the word ‘overpopulation’?",
        "What are the causes of overpopulation?",
        "What problems does overpopulation create?",
        "What can governments do to deal with overpopulation?",
        "Is there a single action the world can take to reduce overpopulation?",
        "When did overpopulation start to be a problem?",
        "Is underpopulation a problem?",
        "Who does overpopulation affect most?",
        "Do you think the problem of overpopulation will become bigger or smaller?",
        "Are there any positive things about overpopulation?",
        "Is overpopulation a problem in your town or country?",
        "Do natural disasters reduce overpopulation?",
        "Are the problems of overpopulation different in the developed and developing worlds?",
        "How big a threat to the planet is overpopulation?",
        "Does religion have a part to play in reducing overpopulation?",
        "Do you think the Earth might be so overpopulated one day that there’ll be no more space for us?",
        "Do you think there should be a limit on the number of children couples can have in countries with overpopulation?",
        "Do you think scientists should stop inventing new medicines to stop overpopulation?",
        "Should infertility research and treatments — including surrogacy — be continued?",
        "Is overpopulation a problem for poor or rich people?"
    ],
    "Ozone Layer": [
        "What springs to mind when you hear the words ‘ozone layer’",
        "What is ozone and what does it do?",
        "When did you first become aware of the ozone layer?",
        "What has been happening to the ozone layer?",
        "What destroys the ozone layer most?",
        "Do you think the ozone layer will ever repair itself?",
        "Where in the world is suffering most from the holes in the ozone layer?",
        "What is the relationship between the ozone layer and sunlight?",
        "What’s the relationship between the ozone layer and greenhouse gases?",
        "What would you like to know about the ozone layer?",
        "What will happen to the world if the ozone layer disappears?",
        "What should we do to help protect the ozone layer?",
        "What do you think the ozone layer looks like?",
        "How do you think scientists first knew there was an ozone layer?",
        "How long do you think it would take for the ozone layer to repair itself?",
        "Are there any good things about the ozone layer depletion?",
        "Why do you think scientists pump more ozone into the atmosphere?",
        "Has the thinning ozone layer had an effect on your country?",
        "Does the ozone layer affect our health?",
        "What is your government’s policy on the ozone layer?"
    ]
}
